### ISSUE TITLE
panic on entry conflict with committed entry

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#1811]
I start the 3-node cluster, and one of them panic:

```
nohup: ignoring input and appending output to ‘nohup.out’
2014/11/27 05:19:13 no data-dir provided, using default data-dir ./infra2.etcd
2014/11/27 05:19:13 etcd: listening for peers on http://172.31.39.92:7002
2014/11/27 05:19:13 etcd: listening for client requests on http://172.31.39.92:4002
2014/11/27 05:19:13 etcdserver: name = infra2
2014/11/27 05:19:13 etcdserver: data dir = infra2.etcd
2014/11/27 05:19:13 etcdserver: snapshot count = 10000
2014/11/27 05:19:13 etcdserver: advertise client URLs = http://172.31.39.92:4002
2014/11/27 05:19:13 etcdserver: initial advertise peer URLs = http://172.31.39.92:7002
2014/11/27 05:19:13 etcdserver: initial cluster = infra1=http://172.31.39.94:7001,infra2=http://172.31.39.92:7002,infra3=http://172.31.39.93:7003
2014/11/27 05:19:13 etcdserver: start member ddcc6eb479e9a80b in cluster 58f252774325f61f
2014/11/27 05:19:13 etcdserver: added member e7333b0ad35b3e9 [http://172.31.39.94:7001] to cluster 58f252774325f61f
2014/11/27 05:19:13 etcdserver: added member 86f39d83c80c2df5 [http://172.31.39.93:7003] to cluster 58f252774325f61f
2014/11/27 05:19:13 etcdserver: added local member ddcc6eb479e9a80b [http://172.31.39.92:7002] to cluster 58f252774325f61f
2014/11/27 05:19:13 raft: elected leader e7333b0ad35b3e9 at term 3
2014/11/27 05:19:13 rafthttp: stream client to e7333b0ad35b3e9 at term 3 starts
2014/11/27 05:19:14 etcdserver: published {Name:infra2 ClientURLs:[http://172.31.39.92:4002]} to cluster 58f252774325f61f
...
2014/11/27 05:48:23 sender: reach the maximal serving to http://172.31.39.94:7001/raft
2014/11/27 06:25:14 raft: lost leader e7333b0ad35b3e9 at term 4
2014/11/27 06:25:16 rafthttp: read ents error: read tcp 172.31.39.94:7001: use of closed network connection
2014/11/27 06:25:16 rafthttp: stream client to e7333b0ad35b3e9 at term 3 is closed
2014/11/27 06:25:17 raft: elected leader 86f39d83c80c2df5 at term 5
2014/11/27 06:25:17 rafthttp: stream client to 86f39d83c80c2df5 at term 5 starts
2014/11/27 06:25:24 raft: lost leader 86f39d83c80c2df5 at term 6
2014/11/27 06:25:24 rafthttp: read ents error: read tcp 172.31.39.93:7003: use of closed network connection
2014/11/27 06:25:24 rafthttp: stream client to 86f39d83c80c2df5 at term 5 is closed
2014/11/27 06:25:28 raft: elected leader ddcc6eb479e9a80b at term 8
2014/11/27 06:25:29 rafthttp: stream server to 86f39d83c80c2df5 at term 8 starts
2014/11/27 06:25:29 rafthttp: stream server to e7333b0ad35b3e9 at term 8 starts
2014/11/27 06:46:49 raft: lost leader ddcc6eb479e9a80b at term 9
2014/11/27 06:46:49 raft: elected leader 86f39d83c80c2df5 at term 9
2014/11/27 06:46:49 entry 6320117 conflict with committed entry [committed(6320119)]
panic: entry 6320117 conflict with committed entry [committed(6320119)]

goroutine 25 [running]:
runtime.panic(0x6ecf40, 0xc208314c10)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
log.Panicf(0x875bf0, 0x36, 0xc208786870, 0x2, 0x2)
        /usr/local/go/src/pkg/log/log.go:314 +0xcd
github.com/coreos/etcd/raft.(*raftLog).maybeAppend(0xc208018d20, 0x606ff4, 0x8, 0x606ff7, 0xc208003e60, 0x4, 0x4, 0x606ff8, 0x1)
        /home/ubuntu/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/log.go:83 +0x1b9
github.com/coreos/etcd/raft.(*raft).handleAppendEntries(0xc20803c840, 0x3, 0xddcc6eb479e9a80b, 0x86f39d83c80c2df5, 0x9, 0x8, 0x606ff4, 0xc208003e60, 0x4, 0x4, ...)
        /home/ubuntu/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:425 +0x78
github.com/coreos/etcd/raft.stepFollower(0xc20803c840, 0x3, 0xddcc6eb479e9a80b, 0x86f39d83c80c2df5, 0x9, 0x8, 0x606ff4, 0xc208003e60, 0x4, 0x4, ...)
        /home/ubuntu/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:532 +0x256
github.com/coreos/etcd/raft.(*raft).Step(0xc20803c840, 0x3, 0xddcc6eb479e9a80b, 0x86f39d83c80c2df5, 0x9, 0x8, 0x606ff4, 0xc208003e60, 0x4, 0x4, ...)
        /home/ubuntu/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:420 +0xe8
github.com/coreos/etcd/raft.(*node).run(0xc208018cd0, 0xc20803c840)
        /home/ubuntu/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:255 +0x43e
created by github.com/coreos/etcd/raft.StartNode
        /home/ubuntu/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:154 +0x541
```
The other two are still running.

**Comment by xiang90** [comment]
@yichengq Added cannot reproduce label to this issue. will revisit if it reoccurs.
