### ISSUE TITLE
Setting ETCD_TRACE=* causes panic: reflect: reflect.Value.SetString using value obtained using unexported field

### ISSUE THREAD

**Issue by carmstrong** [coreos/etcd#1970]
I'm trying to use the `/debug/metrics` endpoint to troubleshoot an etcd cluster. Following the [debugging etcd](https://github.com/coreos/etcd/blob/master/Documentation/debugging.md) instructions, I set this in my cloud-config:

```
coreos:
  etcd:
    trace: '*'
```

On the machine, this successfully translates to `ETCD_TRACE`, which the [configuration documentation](https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#environment-variables) says is a valid environment variable. However, etcd panics on start, with the following logs:

```
-- Logs begin at Fri 2014-12-19 03:35:36 UTC, end at Fri 2014-12-19 03:58:44 UTC. --
Dec 19 03:35:45 deis-2 systemd[1]: Starting etcd...
Dec 19 03:35:45 deis-2 systemd[1]: Started etcd.
Dec 19 03:35:45 deis-2 etcd[904]: panic: reflect: reflect.Value.SetString using value obtained using unexported field
Dec 19 03:35:45 deis-2 etcd[904]: goroutine 16 [running]:
Dec 19 03:35:45 deis-2 etcd[904]: runtime.panic(0x7ab6c0, 0xc208000ae0)
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
Dec 19 03:35:45 deis-2 etcd[904]: reflect.flag.mustBeAssignable(0x187)
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/reflect/value.go:331 +0x124
Dec 19 03:35:45 deis-2 etcd[904]: reflect.Value.SetString(0x7ab6c0, 0xc20807c188, 0x0, 0x187, 0x7fffce0a2fe8, 0x1)
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/reflect/value.go:1690 +0x27
Dec 19 03:35:45 deis-2 etcd[904]: github.com/coreos/etcd/config.(*Config).loadEnv(0xc20807c000, 0x8d0520, 0xc20807c000, 0x0, 0x0)
Dec 19 03:35:45 deis-2 etcd[904]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6-r2/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/config/config.go:212 +0xab9
Dec 19 03:35:45 deis-2 etcd[904]: github.com/coreos/etcd/config.(*Config).LoadEnv(0xc20807c000, 0x0, 0x0)
Dec 19 03:35:45 deis-2 etcd[904]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6-r2/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/config/config.go:177 +0x5b
Dec 19 03:35:45 deis-2 etcd[904]: github.com/coreos/etcd/config.(*Config).Load(0xc20807c000, 0xc208000010, 0x0, 0x0, 0x0, 0x0)
Dec 19 03:35:45 deis-2 etcd[904]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6-r2/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/config/config.go:144 +0x222
Dec 19 03:35:45 deis-2 etcd[904]: main.main()
Dec 19 03:35:45 deis-2 etcd[904]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6-r2/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/main.go:30 +0x91
Dec 19 03:35:45 deis-2 etcd[904]: goroutine 19 [finalizer wait]:
Dec 19 03:35:45 deis-2 etcd[904]: runtime.park(0x413a00, 0xcb9310, 0xcb6d89)
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
Dec 19 03:35:45 deis-2 etcd[904]: runtime.parkunlock(0xcb9310, 0xcb6d89)
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
Dec 19 03:35:45 deis-2 etcd[904]: runfinq()
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
Dec 19 03:35:45 deis-2 etcd[904]: runtime.goexit()
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/runtime/proc.c:1445
Dec 19 03:35:45 deis-2 etcd[904]: goroutine 20 [runnable]:
Dec 19 03:35:45 deis-2 etcd[904]: text/template/parse.lexText(0xc20805c200, 0x9fb688)
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/text/template/parse/lex.go:228 +0x381
Dec 19 03:35:45 deis-2 etcd[904]: text/template/parse.(*lexer).run(0xc20805c200)
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/text/template/parse/lex.go:198 +0x40
Dec 19 03:35:45 deis-2 etcd[904]: created by text/template/parse.lex
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/text/template/parse/lex.go:191 +0x112
Dec 19 03:35:45 deis-2 etcd[904]: goroutine 21 [runnable]:
Dec 19 03:35:45 deis-2 etcd[904]: os/signal.loop()
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/os/signal/signal_unix.go:19
Dec 19 03:35:45 deis-2 etcd[904]: created by os/signal.init·1
Dec 19 03:35:45 deis-2 etcd[904]: /usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x32
Dec 19 03:35:45 deis-2 systemd[1]: etcd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 19 03:35:45 deis-2 systemd[1]: Unit etcd.service entered failed state.
Dec 19 03:35:55 deis-2 systemd[1]: etcd.service holdoff time over, scheduling restart.
Dec 19 03:35:55 deis-2 systemd[1]: Stopping etcd...
Dec 19 03:35:55 deis-2 systemd[1]: Starting etcd...
```

The etcd definition looks fine:
```
core@deis-2 ~ $ systemctl cat etcd
# /usr/lib64/systemd/system/etcd.service
[Unit]
Description=etcd

[Service]
User=etcd
PermissionsStartOnly=true
Environment=ETCD_DATA_DIR=/var/lib/etcd
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd
Restart=always
RestartSec=10s

# /run/systemd/system/etcd.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADDR=172.17.8.101:4001"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/..."
Environment="ETCD_NAME=2c4b6ed408b64802bdea1361f0890a81"
Environment="ETCD_PEER_ADDR=172.17.8.101:7001"
Environment="ETCD_PEER_ELECTION_TIMEOUT=2000"
Environment="ETCD_PEER_HEARTBEAT_INTERVAL=500"
Environment="ETCD_TRACE=*"
```

Am I doing something wrong here?

**Comment by yichengq** [comment]
This has been fixed. Thanks to @aeneby
