### ISSUE TITLE
etcd 0.4.6 panics on new members when data directory is on a different mount

### ISSUE THREAD

**Issue by carmstrong** [coreos/etcd#2050]
We wanted to move the etcd data directory to EC2's ephemeral disk. I formatted the volume as ext4, mounted it, and configured etcd to use it. However, when a node joins the cluster, etcd panics. I tried both ext3 and ext4 (and btrfs) with the same result.

```
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: [etcd] Jan  7 01:11:19.169 INFO      | 66239884f41d4adeb0ea4a106c38e9fb: peer added: '79aa20eea1db4e469770c2698a55c03d'
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: [signal 0xb code=0x1 addr=0x0 pc=0x56e1cf]
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: goroutine 10813 [running]:
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: runtime.panic(0x897820, 0xcb21f3)
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: github.com/coreos/etcd/third_party/github.com/goraft/raft.(*Peer).flush(0xc208ce9c00)
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6-r2/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/peer.go:180 +0x2af
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: github.com/coreos/etcd/third_party/github.com/goraft/raft.(*Peer).heartbeat(0xc208ce9c00, 0xc20a278660)
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6-r2/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/peer.go:163 +0x48a
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: github.com/coreos/etcd/third_party/github.com/goraft/raft.funcÂ·005()
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6-r2/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/peer.go:97 +0x76
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: created by github.com/coreos/etcd/third_party/github.com/goraft/raft.(*Peer).startHeartbeat
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6-r2/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/peer.go:98 +0x13d
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: goroutine 16 [select, 41 minutes]:
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: github.com/coreos/etcd/etcd.(*Etcd).runServer(0xc208060300)
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6-r2/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/etcd/etcd.go:327 +0xa4a
Jan 07 01:11:19 ip-10-21-2-54.ec2.internal etcd[609]: github.com/coreos/etcd/etcd.(*Etcd).Run(0xc208060300)
<< snipped >>
Jan 07 01:11:29 ip-10-21-2-54.ec2.internal systemd[1]: etcd.service holdoff time over, scheduling restart.
Jan 07 01:11:30 ip-10-21-2-54.ec2.internal systemd[1]: Stopping etcd...
```

For the full stacktrace: https://gist.githubusercontent.com/carmstrong/fd274a839234b63b8d6f/raw/1c067f9fbdd23e51df27e451ea725ea6dd085589/gistfile1.txt

Note that etcd then gets confused:
```
Jan 07 01:11:30 ip-10-21-2-54.ec2.internal systemd[1]: Starting etcd...
Jan 07 01:11:30 ip-10-21-2-54.ec2.internal systemd[1]: Started etcd.
Jan 07 01:11:30 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:30.740 INFO      | 66239884f41d4adeb0ea4a106c38e9fb: peer added: '79aa20eea1db4e469770c2698a55c03d'
Jan 07 01:11:30 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:30.741 INFO      | Peer URLs in log:  / 66239884f41d4adeb0ea4a106c38e9fb (http://10.21.1.245:7001)
Jan 07 01:11:30 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:30.741 INFO      | Discovery via https://discovery.etcd.io using prefix /ccf1ce2060eefa4c1919ab1b132fe38a.
Jan 07 01:11:31 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:31.351 INFO      | Discovery found peers [http://10.21.1.83:7001 http://10.21.1.82:7001 http://10.21.1.245:7001]
Jan 07 01:11:31 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:31.351 INFO      | Discovery fetched back peer list: [10.21.1.83:7001 10.21.1.82:7001 10.21.1.245:7001]
Jan 07 01:11:31 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:31.356 INFO      | Send Join Request to http://10.21.1.245:7001/join
Jan 07 01:11:31 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:31.361 INFO      | 66239884f41d4adeb0ea4a106c38e9fb attempted to join via 10.21.1.245:7001 failed: fail on join request: Raft Internal Error ()
Jan 07 01:11:35 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:35.862 INFO      | 66239884f41d4adeb0ea4a106c38e9fb attempted to join via 10.21.1.83:7001 failed: fail checking join version: Client Internal Error (Get http://10.21.1.83:7001/version: dial tcp 10.21.1.83:7001: i/o timeout)
Jan 07 01:11:35 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:35.867 INFO      | Send Join Request to http://10.21.1.82:7001/join
Jan 07 01:11:35 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:35.869 INFO      | 66239884f41d4adeb0ea4a106c38e9fb attempted to join via 10.21.1.82:7001 failed: fail on join request: Raft Internal Error ()
Jan 07 01:11:35 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:35.875 INFO      | Send Join Request to http://10.21.1.245:7001/join
Jan 07 01:11:35 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:35.877 INFO      | 66239884f41d4adeb0ea4a106c38e9fb attempted to join via 10.21.1.245:7001 failed: fail on join request: Raft Internal Error ()
Jan 07 01:11:35 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:35.877 WARNING   | 66239884f41d4adeb0ea4a106c38e9fb cannot connect to previous cluster [10.21.1.245:7001 10.21.1.83:7001 10.21.1.82:7001 10.21.1.245:7001]: fail joining the cluster via given peers after 1 retries
Jan 07 01:11:35 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:35.879 INFO      | etcd server [name 66239884f41d4adeb0ea4a106c38e9fb, listen on :4001, advertised url http://10.21.2.54:4001]
Jan 07 01:11:35 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:35.879 INFO      | peer server [name 66239884f41d4adeb0ea4a106c38e9fb, listen on :7001, advertised url http://10.21.2.54:7001]
Jan 07 01:11:35 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:35.879 INFO      | 66239884f41d4adeb0ea4a106c38e9fb starting in peer mode
Jan 07 01:11:35 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:35.879 INFO      | 66239884f41d4adeb0ea4a106c38e9fb: state changed from 'initialized' to 'follower'.
Jan 07 01:11:38 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:38.320 INFO      | 66239884f41d4adeb0ea4a106c38e9fb: state changed from 'follower' to 'candidate'.
Jan 07 01:11:38 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:38.322 INFO      | removed during cluster re-configuration
Jan 07 01:11:38 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:38.322 INFO      | 66239884f41d4adeb0ea4a106c38e9fb: state changed from 'candidate' to 'follower'.
Jan 07 01:11:38 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:38.322 INFO      | 66239884f41d4adeb0ea4a106c38e9fb: term #18446744073709551615 started.
Jan 07 01:11:38 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:38.322 INFO      | 66239884f41d4adeb0ea4a106c38e9fb: state changed from 'follower' to 'stopped'.
Jan 07 01:11:38 ip-10-21-2-54.ec2.internal etcd[9261]: [etcd] Jan  7 01:11:38.323 INFO      | 66239884f41d4adeb0ea4a106c38e9fb: state changed from 'stopped' to 'stopped'.
```

Does anyone have any ideas?

**Comment by carmstrong** [comment]
Also seeing this with btrfs.

**Comment by xiang90** [comment]
@carmstrong It seems like the node was not using the data directory from the full log you shared.

**Comment by carmstrong** [comment]
@xiang90 Is there a configuration setting other than `ETCD_DATA_DIR` that I should be setting? I also tried mounting at `/var/lib/etcd` and got the same error...

**Comment by carmstrong** [comment]
We also tried specifying a data directory location on the same mount as the root filesystem, and **this worked**. This suggests that etcd doesn't like having its data directory on a separate mount/filesystem, but that doesn't really make any sense.

Has anyone tried this? It's pretty easy to reproduce with a moderate amount of etcd traffic.

**Comment by carmstrong** [comment]
Just to confirm, it has nothing to do with the data directory directive itself -- when mounting `/var/lib/etcd` on a machine, etcd has this same panic even though we never configured the data directory in the etcd config.

**Comment by bacongobbler** [comment]
Can confirm here as well. I've mounted a drive on EC2 as ext4, mounted it to /var/lib/etcd, and as soon as it flushed to disk, etcd panicked: https://gist.github.com/bacongobbler/2fe711c368b9f0cdded0

mount config: https://gist.github.com/bacongobbler/1b2754ed5ef5072a8d53

**Comment by mboersma** [comment]
I had the same results as @bacongobbler, but using `btrfs`.

**Comment by mboersma** [comment]
Here is a log with `verbose=true` for `etcd` crashing when a new node joins when `/var/lib/etcd` is on a separate mount: https://gist.github.com/mboersma/4292e502e60fa473ed58

**Comment by bacongobbler** [comment]
from looking at our stacktraces, I think the panic came from somewhere in here (which would make sense considering that this is a disk flush operation): https://github.com/coreos/etcd/blob/v0.4.6/server/peer_server.go#L772-L790

**Comment by carmstrong** [comment]
I am unable to replicate this panic using etcd 2.0 rc1 with the same repro steps.

**Comment by xiang90** [comment]
@carmstrong We cannot reproduce this problem. Here is what we did.

1. Starts a ec2 m3.large MachineA. And starts an 0.4.6 etcd process on the local filesystem (/dev/xdva1).
2. push some traffic to the etcd cluster to make it save a snapshot. 
3. stop the etcd process.
4. attach a 8Gi SSD volume to Machine A. 
5. mkfs -t ext4 on the new volume
6. mount the volume onto /media/ephemeral
7. copy the previous data dir to /media/ephemeral
8. change the ownership of the data dir to the current user.
9. restart etcd using the moved data dir.
(10) push some traffic to etcd to make it save a snapshot (we also tried to skip this step)  
11. Starts a ec2 m3.large Machine B. And let Machine B join Machine A. 

It works fine. Did we miss anything?

**Comment by carmstrong** [comment]
@xiang90 I can replicate this reliably by deploying deis.

If it helps, I can spin up a cluster, get this panic to occur, and then give you SSH access to investigate?

**Comment by xiang90** [comment]
@carmstrong Can you please set up simple evn to reproduce this problem? And let me know your steps?

**Comment by polvi** [comment]
just commenting that this is a high priority issue for us to figure out. thanks @xiang90 for stepping and helping the Deis team figure it out..

**Comment by yichengq** [comment]
@carmstrong You are welcome to either give access of the cluster in problem or give the steps to reproduce it. Let us do the bests to find it out and fix it.

**Comment by carmstrong** [comment]
I'm happy to give you guys access to a cluster that just hit the panic. @yichengq I don't see you on IRC, but ping me with your pubkey.

**Comment by carmstrong** [comment]
This ended up being user error which I should have caught - see https://github.com/deis/deis/pull/2872

Thanks so much to @yichengq for jumping on this!

**Comment by yichengq** [comment]
1. etcd 2.0 will not panic in this case because it won't have the snapshot to use until the snapshot is fully ready.
2. etcd 2.0 will fatal if the snapshot directory fails to create or read, instead of panics later when sending snapshot.
3. This issue happens because underlying data directory is mounted while etcd is running. We can check the fds status that etcd is using to confirm it.
