### ISSUE TITLE
panic: interface conversion: net.Conn is *tls.Conn, not *net.TCPConn

### ISSUE THREAD

**Issue by cinience** [coreos/etcd#2184]
```
#./etcd -listen-client-urls=https://192.168.0.11:4002,http://127.0.0.1:4001 -listen-peer-urls=http://127.0.0.1:4003 -ca-file=/opt/my/ca.crt -cert-file=/opt/my/server.crt -key-file=/opt/my/server.key.insecure -advertise-client-urls=https://192.168.0.11:4002,http://127.0.0.1:4001 
2015/01/29 15:11:28 no data-dir provided, using default data-dir ./default.etcd
2015/01/29 15:11:28 etcd: listening for peers on http://127.0.0.1:4003
2015/01/29 15:11:28 etcd: clientTLS: cert = /opt/my/server.crt, key = /opt/my/server.key.insecure, ca = /opt/my/ca.crt
2015/01/29 15:11:28 etcd: listening for client requests on http://127.0.0.1:4001
2015/01/29 15:11:29 etcd: listening for client requests on https://192.168.0.11:4002
2015/01/29 15:11:29 etcdserver: name = default
2015/01/29 15:11:29 etcdserver: data dir = default.etcd
2015/01/29 15:11:29 etcdserver: heartbeat = 100ms
2015/01/29 15:11:29 etcdserver: election = 1000ms
2015/01/29 15:11:29 etcdserver: snapshot count = 10000
2015/01/29 15:11:29 etcdserver: advertise client URLs = http://127.0.0.1:4001,https://192.168.0.11:4002
2015/01/29 15:11:29 etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2015/01/29 15:11:29 etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
2015/01/29 15:11:29 etcdserver: start member ce2a822cea30bfca in cluster 7e27652122e8b2ae
2015/01/29 15:11:29 raft: ce2a822cea30bfca became follower at term 0
2015/01/29 15:11:29 raft: newRaft ce2a822cea30bfca [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/01/29 15:11:29 raft: ce2a822cea30bfca became follower at term 1
panic: interface conversion: net.Conn is *tls.Conn, not *net.TCPConn

goroutine 12 [running]:
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc208031f90, 0x0, 0x0, 0x0, 0x0)
	/Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:43 +0xe3
net/http.(*Server).Serve(0xc208062c00, 0x7fec19529510, 0xc208031f90, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x7fec19529510, 0xc208031f90, 0x7fec1952a7e0, 0xc20801cfc0, 0x0, 0x0, 0x0)
	/Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·006(0x7fec19529510, 0xc208031f90)
	/Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:186 +0x80
created by github.com/coreos/etcd/etcdmain.startEtcd
	/Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:187 +0x1e60
```

**Comment by xiang90** [comment]
fix via https://github.com/coreos/etcd/pull/2185
