### ISSUE TITLE
proxy: panic when proxy starts before the cluster

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2206]
1. goreman start
2. add new member
3. proxy panic in 1min:
```
23:16:42 proxy | Starting proxy on port 5003
23:16:42 etcd1 | Starting etcd1 on port 5000
23:16:42 etcd2 | Starting etcd2 on port 5001
23:16:42 etcd3 | Starting etcd3 on port 5002
23:16:42 proxy | 2015/02/01 23:16:42 no proxy data-dir provided, using default proxy data-dir ./default.etcdproxy
23:16:42 proxy | 2015/02/01 23:16:42 proxy: using peer urls [http://localhost:7001 http://localhost:7002 http://localhost:7003]
23:16:42 proxy | 2015/02/01 23:16:42 etcdserver: could not get cluster response from http://localhost:7001: Get http://localhost:7001/members: dial tcp 127.0.0.1:7001: connection refused
23:16:42 proxy | 2015/02/01 23:16:42 etcdserver: could not get cluster response from http://localhost:7002: Get http://localhost:7002/members: dial tcp 127.0.0.1:7002: connection refused
23:16:42 proxy | 2015/02/01 23:16:42 etcdserver: could not get cluster response from http://localhost:7003: Get http://localhost:7003/members: dial tcp 127.0.0.1:7003: connection refused
23:16:42 proxy | 2015/02/01 23:16:42 proxy: etcdserver: could not retrieve cluster information from the given urls
23:16:42 proxy | 2015/02/01 23:16:42 proxy: listening for client requests on 127.0.0.1:8080
23:16:42 etcd1 | 2015/02/01 23:16:42 no data-dir provided, using default data-dir ./infra1.etcd
23:16:42 etcd1 | 2015/02/01 23:16:42 etcd: listening for peers on http://localhost:7001
23:16:42 etcd1 | 2015/02/01 23:16:42 etcd: listening for client requests on http://localhost:4001
23:16:42 etcd3 | 2015/02/01 23:16:42 no data-dir provided, using default data-dir ./infra3.etcd
23:16:42 etcd2 | 2015/02/01 23:16:42 no data-dir provided, using default data-dir ./infra2.etcd
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: name = infra1
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: data dir = infra1.etcd
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: heartbeat = 100ms
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: election = 1000ms
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: snapshot count = 10000
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: advertise client URLs = http://localhost:4001
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: initial advertise peer URLs = http://localhost:7001
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: initial cluster = infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003
23:16:42 etcd3 | 2015/02/01 23:16:42 etcd: listening for peers on http://localhost:7003
23:16:42 etcd3 | 2015/02/01 23:16:42 etcd: listening for client requests on http://localhost:4003
23:16:42 etcd2 | 2015/02/01 23:16:42 etcd: listening for peers on http://localhost:7002
23:16:42 etcd2 | 2015/02/01 23:16:42 etcd: listening for client requests on http://localhost:4002
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: start member a8266ecf031671f3 in cluster e9c7614f68f35fb2
23:16:42 etcd1 | 2015/02/01 23:16:42 raft: a8266ecf031671f3 became follower at term 0
23:16:42 etcd1 | 2015/02/01 23:16:42 raft: newRaft a8266ecf031671f3 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
23:16:42 etcd1 | 2015/02/01 23:16:42 raft: a8266ecf031671f3 became follower at term 1
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: name = infra2
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: data dir = infra2.etcd
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: heartbeat = 100ms
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: election = 1000ms
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: snapshot count = 10000
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: advertise client URLs = http://localhost:4002
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: initial advertise peer URLs = http://localhost:7002
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: initial cluster = infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: added member 6e3bd23ae5f1eae0 [http://localhost:7002] to cluster e9c7614f68f35fb2
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: added member 924e2e83e93f2560 [http://localhost:7003] to cluster e9c7614f68f35fb2
23:16:42 etcd1 | 2015/02/01 23:16:42 etcdserver: added local member a8266ecf031671f3 [http://localhost:7001] to cluster e9c7614f68f35fb2
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: name = infra3
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: data dir = infra3.etcd
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: heartbeat = 100ms
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: election = 1000ms
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: snapshot count = 10000
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: advertise client URLs = http://localhost:4003
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: initial advertise peer URLs = http://localhost:7003
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: initial cluster = infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: start member 924e2e83e93f2560 in cluster e9c7614f68f35fb2
23:16:42 etcd3 | 2015/02/01 23:16:42 raft: 924e2e83e93f2560 became follower at term 0
23:16:42 etcd3 | 2015/02/01 23:16:42 raft: newRaft 924e2e83e93f2560 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
23:16:42 etcd3 | 2015/02/01 23:16:42 raft: 924e2e83e93f2560 became follower at term 1
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: start member 6e3bd23ae5f1eae0 in cluster e9c7614f68f35fb2
23:16:42 etcd2 | 2015/02/01 23:16:42 raft: 6e3bd23ae5f1eae0 became follower at term 0
23:16:42 etcd2 | 2015/02/01 23:16:42 raft: newRaft 6e3bd23ae5f1eae0 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
23:16:42 etcd2 | 2015/02/01 23:16:42 raft: 6e3bd23ae5f1eae0 became follower at term 1
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: added local member 6e3bd23ae5f1eae0 [http://localhost:7002] to cluster e9c7614f68f35fb2
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: added member 924e2e83e93f2560 [http://localhost:7003] to cluster e9c7614f68f35fb2
23:16:42 etcd2 | 2015/02/01 23:16:42 etcdserver: added member a8266ecf031671f3 [http://localhost:7001] to cluster e9c7614f68f35fb2
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: added member 6e3bd23ae5f1eae0 [http://localhost:7002] to cluster e9c7614f68f35fb2
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: added local member 924e2e83e93f2560 [http://localhost:7003] to cluster e9c7614f68f35fb2
23:16:42 etcd3 | 2015/02/01 23:16:42 etcdserver: added member a8266ecf031671f3 [http://localhost:7001] to cluster e9c7614f68f35fb2
23:16:43 etcd3 | 2015/02/01 23:16:43 raft: 924e2e83e93f2560 is starting a new election at term 1
23:16:43 etcd3 | 2015/02/01 23:16:43 raft: 924e2e83e93f2560 became candidate at term 2
23:16:43 etcd3 | 2015/02/01 23:16:43 raft: 924e2e83e93f2560 received vote from 924e2e83e93f2560 at term 2
23:16:43 etcd3 | 2015/02/01 23:16:43 raft: 924e2e83e93f2560 [logterm: 1, index: 3] sent vote request to 6e3bd23ae5f1eae0 at term 2
23:16:43 etcd3 | 2015/02/01 23:16:43 raft: 924e2e83e93f2560 [logterm: 1, index: 3] sent vote request to a8266ecf031671f3 at term 2
23:16:43 etcd1 | 2015/02/01 23:16:43 raft: a8266ecf031671f3 [term: 1] received a MsgVote message with higher term from 924e2e83e93f2560 [term: 2]
23:16:43 etcd1 | 2015/02/01 23:16:43 raft: a8266ecf031671f3 became follower at term 2
23:16:43 etcd1 | 2015/02/01 23:16:43 raft: a8266ecf031671f3 [logterm: 1, index: 3, vote: 0] voted for 924e2e83e93f2560 [logterm: 1, index: 3] at term 2
23:16:43 etcd2 | 2015/02/01 23:16:43 raft: 6e3bd23ae5f1eae0 [term: 1] received a MsgVote message with higher term from 924e2e83e93f2560 [term: 2]
23:16:43 etcd2 | 2015/02/01 23:16:43 raft: 6e3bd23ae5f1eae0 became follower at term 2
23:16:43 etcd2 | 2015/02/01 23:16:43 raft: 6e3bd23ae5f1eae0 [logterm: 1, index: 3, vote: 0] voted for 924e2e83e93f2560 [logterm: 1, index: 3] at term 2
23:16:43 etcd3 | 2015/02/01 23:16:43 raft: 924e2e83e93f2560 received vote from a8266ecf031671f3 at term 2
23:16:43 etcd3 | 2015/02/01 23:16:43 raft: 924e2e83e93f2560 [q:2] has received 2 votes and 0 vote rejections
23:16:43 etcd3 | 2015/02/01 23:16:43 raft: 924e2e83e93f2560 became leader at term 2
23:16:43 etcd3 | 2015/02/01 23:16:43 raft.node: 924e2e83e93f2560 elected leader 924e2e83e93f2560 at term 2
23:16:43 etcd2 | 2015/02/01 23:16:43 raft.node: 6e3bd23ae5f1eae0 elected leader 924e2e83e93f2560 at term 2
23:16:43 etcd1 | 2015/02/01 23:16:43 raft.node: a8266ecf031671f3 elected leader 924e2e83e93f2560 at term 2
23:16:43 etcd2 | 2015/02/01 23:16:43 rafthttp: starting client stream to 924e2e83e93f2560 at term 2
23:16:43 etcd1 | 2015/02/01 23:16:43 rafthttp: starting client stream to 924e2e83e93f2560 at term 2
23:16:44 etcd3 | 2015/02/01 23:16:44 etcdserver: published {Name:infra3 ClientURLs:[http://localhost:4003]} to cluster e9c7614f68f35fb2
23:16:44 etcd2 | 2015/02/01 23:16:44 etcdserver: published {Name:infra2 ClientURLs:[http://localhost:4002]} to cluster e9c7614f68f35fb2
23:16:44 etcd1 | 2015/02/01 23:16:44 etcdserver: published {Name:infra1 ClientURLs:[http://localhost:4001]} to cluster e9c7614f68f35fb2
23:16:50 etcd3 | 2015/02/01 23:16:50 etcdserver: added member 4dd8628e0da2f78b [http://127.0.0.1:7004] to cluster e9c7614f68f35fb2
23:16:50 etcd3 | 2015/02/01 23:16:50 sender: error posting to 4dd8628e0da2f78b: dial tcp 127.0.0.1:7004: connection refused
23:16:50 etcd3 | 2015/02/01 23:16:50 sender: the connection with 4dd8628e0da2f78b becomes inactive
23:16:50 etcd3 | 2015/02/01 23:16:50 sender: failed to send message in 266.365us
23:16:50 etcd3 | 2015/02/01 23:16:50 sender: failed to send message in 786.008us
23:16:50 etcd2 | 2015/02/01 23:16:50 etcdserver: added member 4dd8628e0da2f78b [http://127.0.0.1:7004] to cluster e9c7614f68f35fb2
23:16:50 etcd1 | 2015/02/01 23:16:50 etcdserver: added member 4dd8628e0da2f78b [http://127.0.0.1:7004] to cluster e9c7614f68f35fb2
23:17:12 proxy | panic: runtime error: invalid memory address or nil pointer dereference
23:17:12 proxy | [signal 0xb code=
23:17:12 proxy | 0x1 addr=0x0 pc=0xa2b61]
23:17:12 proxy | goroutine 27 [running]:
23:17:12 proxy | runtime.panic(0x3e5260, 0x6772a4)
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/runtime/panic.c:279 +0xf5
23:17:12 proxy | github.com/coreos/etcd/etcdserver.(*Cluster).PeerURLs(0x0, 0x0, 0x0, 0x0)
23:17:12 proxy | 	/Users/unihorn/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:178 +0x371
23:17:12 proxy | github.com/coreos/etcd/etcdmain.func·007(0x0, 0x0
23:17:12 proxy | , 0x0)
23:17:12 proxy | 	/Users/unihorn/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:253 +0x81
23:17:12 proxy | github.com/coreos/etcd/proxy.(*director).refresh(0x208737530)
23:17:12 proxy | 	/Users/unihorn/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/proxy/director.go:56 +0x35
23:17:12 proxy | github.com/coreos/etcd/proxy.func·001()
23:17:12 proxy | 	/Users/unihorn/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/proxy/director.go:42 +0x75
23:17:12 proxy | created by github.com/coreos/etcd/proxy.newDirector
23:17:12 proxy | 	/Users/unihorn/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/proxy/director.go:45 +0x9a
23:17:12 proxy | goroutine 16 [chan receive (nil chan)]:
23:17:12 proxy | github.com/coreos/etcd/etcdmain.Main()
23:17:12 proxy | 	/Users/unihorn/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:77 +0x56b
23:17:12 proxy | main.main()
23:17:12 proxy | 	/Users/unihorn/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/main.go:48 +0x1ab
23:17:12 proxy | goroutine 19 [finalizer wait]:
23:17:12 proxy | runtime.park(0x14510,
23:17:12 proxy | 0x67a8d0, 0x679369)
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/runtime/proc.c:1369 +0x89
23:17:12 proxy | runtime.parkunlock(0x67a8d0, 0x679369)
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/runtime/proc.c:1385 +0x3b
23:17:12 proxy | runfinq()
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/runtime/mgc0.c:2644 +0xcf
23:17:12 proxy | runtime.goexit()
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/runtime/proc.c:1445
23:17:12 proxy | goroutine 28 [IO wait]:
23:17:12 proxy | net.runtime_pollWait(0x2208726d10, 0x72, 0x0)
23:17:12 proxy | 	/private/tmp/go-eKWUV2/go/src/pkg/runtime/netpoll.goc:146 +0x66
23:17:12 proxy | net.(*pollDesc).Wait(0x2087945a0, 0x72, 0x0, 0x0)
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/net/fd_poll_runtime.go:84 +0x46
23:17:12 proxy | net.(*pollDesc).WaitRead(0x2087945a0, 0x0, 0x0)
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/net/fd_poll_runtime.go:89 +0x42
23:17:12 proxy | net.(*netFD).accept(0x208794540, 0x507ac8, 0x0, 0x22087253c8, 0x23)
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/net/fd_unix.go:419 +0x343
23:17:12 proxy | net.(*TCPListener).AcceptTCP(0x20874e0c8, 0x208750ea8, 0x0, 0x0)
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/net/tcpsock_posix.go:234 +0x5d
23:17:12 proxy | net.(*TCPListener).Accept(0x20874e0c8, 0x0, 0x0, 0x0, 0x0)
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/net/tcpsock_posix.go:244 +0x4b
23:17:12 proxy | net/http.(*Server).Serve(0x208718a20, 0x2208726eb0, 0x20874e0c8, 0x0, 0x0)
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/net/http/server.go:1698 +0x91
23:17:12 proxy | net/http.Serve(0x2208726eb0, 0x20874e0c8, 0x2208726e88, 0x2087a4220, 0x0, 0x0)
23:17:12 proxy | 	/usr/local/opt/go/libexec/src/pkg/net/http/server.go:1576 +0x7c
23:17:12 proxy | github.com/coreos/etcd/etcdmain.func·008()
23:17:12 proxy | 	/Users/unihorn/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:303 +0x14b
23:17:12 proxy | created by github.com/coreos/etcd/etcdmain.startProxy
23:17:12 proxy | 	/Users/unihorn/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:304 +0xc28
23:17:12 proxy | Terminating proxy
```

**Comment by xiang90** [comment]
@yichengq I cannot reproduce this on master. Also I found there is a bug that might cause this, but it is not caused by adding a member.

**Comment by yichengq** [comment]
More reliable way to reproduce:
1. apply patch
```
diff --git a/Procfile b/Procfile
index 7e6f4f7..b1e8458 100644
--- a/Procfile
+++ b/Procfile
@@ -1,5 +1,5 @@
 # Use goreman to run `go get github.com/mattn/goreman`
-etcd1: bin/etcd -name infra1 -listen-client-urls http://localhost:4001 -advertise-client-urls http://localhost:4001 -listen-peer-urls http://localhost:7001 -initial-advertise-peer-urls http://localhost:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new
-etcd2: bin/etcd -name infra2 -listen-client-urls http://localhost:4002 -advertise-client-urls http://localhost:4002 -listen-peer-urls http://localhost:7002 -initial-advertise-peer-urls http://localhost:7002 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new
-etcd3: bin/etcd -name infra3 -listen-client-urls http://localhost:4003 -advertise-client-urls http://localhost:4003 -listen-peer-urls http://localhost:7003 -initial-advertise-peer-urls http://localhost:7003 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new
+etcd1: sleep 1 && bin/etcd -name infra1 -listen-client-urls http://localhost:4001 -advertise-client-urls http://localhost:4001 -listen-peer-urls http://localhost:7001 -initial-advertise-peer-urls http://localhost:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new
+etcd2: sleep 1 && bin/etcd -name infra2 -listen-client-urls http://localhost:4002 -advertise-client-urls http://localhost:4002 -listen-peer-urls http://localhost:7002 -initial-advertise-peer-urls http://localhost:7002 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new
+etcd3: sleep 1 && bin/etcd -name infra3 -listen-client-urls http://localhost:4003 -advertise-client-urls http://localhost:4003 -listen-peer-urls http://localhost:7003 -initial-advertise-peer-urls http://localhost:7003 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003' -initial-cluster-state new
 proxy: bin/etcd -proxy=on -bind-addr 127.0.0.1:8080 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003'
```
2. goreman start
3. wait 1 min
