### ISSUE TITLE
tocommit(27) is out of range [lastIndex(0)]

### ISSUE THREAD

**Issue by marvell** [coreos/etcd#2215]
Run `node-1`:
```
etcd \
  --name="node-1" \
  --listen-client-urls="http://127.0.0.1:4001" \
  --listen-peer-urls="http://127.0.0.1:7001" \
  --advertise-client-urls="http://127.0.0.1:4001" \
  --initial-advertise-peer-urls="http://127.0.0.1:7001" \
  --initial-cluster="node-1=http://127.0.0.1:7001" \
  --initial-cluster-state="new"
```

Then, run `node-2`:
```
etcdctl --peers="http://127.0.0.1:4001" member add "node-2" "http://127.0.0.1:7002"
etcd \
  --name="node-2" \
  --listen-client-urls="http://127.0.0.1:4002" \
  --listen-peer-urls="http://127.0.0.1:7002" \
  --advertise-client-urls="http://127.0.0.1:4002" \
  --initial-advertise-peer-urls="http://127.0.0.1:7002" \
  --initial-cluster="node-1=http://127.0.0.1:7001,node-2=http://127.0.0.1:7002" \
  --initial-cluster-state="existing"
```

Stop `node-2` and delete data directory `rm -rf ./node-2.etcd`. Then, try again run `node-2`...
```
etcd \
>   --name="node-2" \
>   --listen-client-urls="http://127.0.0.1:4002" \
>   --listen-peer-urls="http://127.0.0.1:7002" \
>   --advertise-client-urls="http://127.0.0.1:4002" \
>   --initial-advertise-peer-urls="http://127.0.0.1:7002" \
>   --initial-cluster="node-1=http://127.0.0.1:7001,node-2=http://127.0.0.1:7002" \
>   --initial-cluster-state="existing"
2015/02/03 18:44:15 no data-dir provided, using default data-dir ./node-2.etcd
2015/02/03 18:44:15 etcd: listening for peers on http://127.0.0.1:7002
2015/02/03 18:44:15 etcd: listening for client requests on http://127.0.0.1:4002
2015/02/03 18:44:15 etcdserver: name = node-2
2015/02/03 18:44:15 etcdserver: data dir = node-2.etcd
2015/02/03 18:44:15 etcdserver: heartbeat = 100ms
2015/02/03 18:44:15 etcdserver: election = 1000ms
2015/02/03 18:44:15 etcdserver: snapshot count = 10000
2015/02/03 18:44:15 etcdserver: advertise client URLs = http://127.0.0.1:4002
2015/02/03 18:44:15 etcdserver: start member adc75cbdb4a31959 in cluster a9efa5de7f8fc772
2015/02/03 18:44:15 raft: adc75cbdb4a31959 became follower at term 0
2015/02/03 18:44:15 raft: newRaft adc75cbdb4a31959 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/02/03 18:44:15 raft: adc75cbdb4a31959 became follower at term 1
2015/02/03 18:44:16 raft: adc75cbdb4a31959 [term: 1] received a MsgHeartbeat message with higher term from e52ada62956ff923 [term: 2]
2015/02/03 18:44:16 raft: adc75cbdb4a31959 became follower at term 2
2015/02/03 18:44:16 tocommit(27) is out of range [lastIndex(0)]
panic: tocommit(27) is out of range [lastIndex(0)]

goroutine 9 [running]:
log.Panicf(0x4c5d70, 0x2c, 0xc2080c4510, 0x2, 0x2)
  /usr/local/go/src/log/log.go:314 +0xd0
github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc20802c7d0, 0x1b)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/log.go:177 +0x179
github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc208032580, 0x8, 0xadc75cbdb4a31959, 0xe52ada62956ff923, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:591 +0x47
github.com/coreos/etcd/raft.stepFollower(0xc208032580, 0x8, 0xadc75cbdb4a31959, 0xe52ada62956ff923, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:561 +0xfdd
github.com/coreos/etcd/raft.(*raft).Step(0xc208032580, 0x8, 0xadc75cbdb4a31959, 0xe52ada62956ff923, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:459 +0x23f
github.com/coreos/etcd/raft.(*node).run(0xc20802c780, 0xc208032580)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:275 +0x689
created by github.com/coreos/etcd/raft.StartNode
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:168 +0x50a

goroutine 1 [chan receive]:
github.com/coreos/etcd/etcdmain.Main()
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:73 +0x648
main.main()
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/main.go:31 +0x1b

goroutine 7 [IO wait]:
net.(*pollDesc).Wait(0xc208086920, 0x72, 0x0, 0x0)
  /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208086920, 0x0, 0x0)
  /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080868c0, 0xc208096000, 0x1000, 0x1000, 0x0, 0x727bb0, 0xc20802b188)
  /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208038088, 0xc208096000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  /usr/local/go/src/net/net.go:121 +0xdc
github.com/coreos/etcd/pkg/transport.timeoutConn.Read(0x729658, 0xc208038088, 0x12a05f200, 0x12a05f200, 0xc208096000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_conn.go:43 +0x165
github.com/coreos/etcd/pkg/transport.(*timeoutConn).Read(0xc20801fb40, 0xc208096000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  <autogenerated>:17 +0xd6
net/http.noteEOFReader.Read(0x729718, 0xc20801fb40, 0xc208032478, 0xc208096000, 0x1000, 0x1000, 0x376180, 0x0, 0x0)
  /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20801fb60, 0xc208096000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
  <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2080545a0)
  /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2080545a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208032420)
  /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
  /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 8 [select]:
net/http.(*persistConn).writeLoop(0xc208032420)
  /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
  /usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 10 [chan receive]:
github.com/coreos/etcd/rafthttp.(*peer).handle(0xc208032630)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/rafthttp/peer.go:187 +0x99
created by github.com/coreos/etcd/rafthttp.NewPeer
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/rafthttp/peer.go:94 +0x2cc

goroutine 11 [chan receive]:
github.com/coreos/etcd/rafthttp.(*peer).handle(0xc208032630)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/rafthttp/peer.go:187 +0x99
created by github.com/coreos/etcd/rafthttp.NewPeer
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/rafthttp/peer.go:94 +0x2cc

goroutine 12 [chan receive]:
github.com/coreos/etcd/rafthttp.(*peer).handle(0xc208032630)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/rafthttp/peer.go:187 +0x99
created by github.com/coreos/etcd/rafthttp.NewPeer
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/rafthttp/peer.go:94 +0x2cc

goroutine 13 [chan receive]:
github.com/coreos/etcd/rafthttp.(*peer).handle(0xc208032630)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/rafthttp/peer.go:187 +0x99
created by github.com/coreos/etcd/rafthttp.NewPeer
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/rafthttp/peer.go:94 +0x2cc

goroutine 14 [select]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc20806c200)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:348 +0x1330
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:288 +0x294

goroutine 15 [select]:
github.com/coreos/etcd/raft.(*node).step(0xc20802c780, 0x72a198, 0xc208054c00, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc20802c910, ...)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:383 +0x1ed
github.com/coreos/etcd/raft.(*node).Propose(0xc20802c780, 0x72a198, 0xc208054c00, 0xc208052750, 0x88, 0x88, 0x0, 0x0)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:355 +0x141
github.com/coreos/etcd/etcdserver.(*EtcdServer).Do(0xc20806c200, 0x72a198, 0xc208054c00, 0x594b501d0c4c0001, 0x439c00, 0x3, 0xc20803dda0, 0x26, 0xc208047900, 0x38, ...)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:470 +0x2ee
github.com/coreos/etcd/etcdserver.(*EtcdServer).publish(0xc20806c200, 0x12a05f200)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:633 +0x30b
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:269 +0x4f

goroutine 16 [select]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0xc20806c200)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:299 +0x48c
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:270 +0x69

goroutine 17 [IO wait]:
net.(*pollDesc).Wait(0xc208086610, 0x72, 0x0, 0x0)
  /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208086610, 0x0, 0x0)
  /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080865b0, 0x0, 0x727bb0, 0xc20802b7a0)
  /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208038040, 0x72a2d8, 0x0, 0x0)
  /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208038040, 0x0, 0x0, 0x0, 0x0)
  /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc20801f8c0, 0x0, 0x0, 0x0, 0x0)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x7a
net/http.(*Server).Serve(0xc208054d80, 0x729430, 0xc20801f8c0, 0x0, 0x0)
  /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x729430, 0xc20801f8c0, 0x72a088, 0xc20803dbc0, 0x45d964b800, 0x0, 0x0)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·005(0x729430, 0xc20801f8c0)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:178 +0x5a
created by github.com/coreos/etcd/etcdmain.startEtcd
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:179 +0x1d1e

goroutine 18 [IO wait]:
net.(*pollDesc).Wait(0xc2080866f0, 0x72, 0x0, 0x0)
  /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080866f0, 0x0, 0x0)
  /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208086690, 0x0, 0x727bb0, 0xc20802b668)
  /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208038048, 0x0, 0x0, 0x0)
  /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208038048, 0x0, 0x0, 0x0, 0x0)
  /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc20802b730, 0x0, 0x0, 0x0, 0x0)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:39 +0x71
net/http.(*Server).Serve(0xc208054de0, 0x729468, 0xc20802b730, 0x0, 0x0)
  /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x729468, 0xc20802b730, 0x72a1d8, 0xc20801eba0, 0x0, 0x0, 0x0)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·006(0x729468, 0xc20802b730)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:186 +0x80
created by github.com/coreos/etcd/etcdmain.startEtcd
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:187 +0x1e60

goroutine 19 [select]:
github.com/coreos/etcd/pkg/fileutil.func·001()
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x658
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x231

goroutine 20 [select]:
github.com/coreos/etcd/pkg/fileutil.func·001()
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x658
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x231

goroutine 21 [IO wait]:
net.(*pollDesc).Wait(0xc208086ed0, 0x72, 0x0, 0x0)
  /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208086ed0, 0x0, 0x0)
  /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208086e70, 0xc2080b2000, 0x1000, 0x1000, 0x0, 0x727bb0, 0xc20802b7f8)
  /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208038118, 0xc2080b2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
  /usr/local/go/src/net/net.go:121 +0xdc
github.com/coreos/etcd/pkg/transport.timeoutConn.Read(0x729658, 0xc208038118, 0x12a05f200, 0x12a05f200, 0xc2080b2000, 0x1000, 0x1000, 0x100000000, 0x0, 0x0)
  /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_conn.go:43 +0x165
github.com/coreos/etcd/pkg/transport.(*timeoutConn).Read(0xc20801ef40, 0xc2080b2000, 0x1000, 0x1000, 0x3, 0x0, 0x0)
  <autogenerated>:17 +0xd6
net/http.(*liveSwitchReader).Read(0xc20805e408, 0xc2080b2000, 0x1000, 0x1000, 0xe661, 0x0, 0x0)
  /usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc20801ef60, 0xc2080b2000, 0x1000, 0x1000, 0x40, 0x0, 0x0)
  /usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc208054f00)
  /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208054f00, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc208054f00, 0x0, 0x0, 0x0, 0xc208086e00, 0x0, 0x0)
  /usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20803df20, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20803df20, 0x0, 0x0, 0x0, 0x0)
  /usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc208054f00, 0xc2080355f0, 0x0, 0x0)
  /usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20805e3c0, 0x0, 0x0, 0x0)
  /usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20805e3c0)
  /usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
  /usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by xiang90** [comment]
@marvell Stop node-2 and delete data directory rm -rf ./node-2.etcd. Then, try again run node-2...

You should never do that. If the data dir is lost, remove the node from the cluster. If you want to add the node back, add it again via runtime configuration.

**Comment by xiang90** [comment]
@marvell More detail here: https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#lifecycle
