### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dmitryint** [coreos/etcd#2295]
etcd v2.0.2 in docker
bootstrap 5 nodes cluster
after 30 minutes all nodes crashes with same error:

```
2015/02/13 12:58:15 etcd: peerTLS: cert = /data/etcd/ssl/server.crt, key = /data/etcd/ssl/server.key, ca = /data/etcd/ssl/ca.crt
2015/02/13 12:58:16 etcd: listening for peers on https://0.0.0.0:7001
2015/02/13 12:58:16 etcd: clientTLS: cert = /data/etcd/ssl/server.crt, key = /data/etcd/ssl/server.key, ca = /data/etcd/ssl/ca.crt
2015/02/13 12:58:16 etcd: listening for client requests on http://0.0.0.0:2379
2015/02/13 12:58:17 etcd: listening for client requests on https://0.0.0.0:4001
2015/02/13 12:58:17 datadir is valid for the 2.0.1 format
2015/02/13 12:58:17 etcdserver: name = node1.coreos.intersoftlab.ru
2015/02/13 12:58:17 etcdserver: data dir = /etcd_data
2015/02/13 12:58:17 etcdserver: member dir = /etcd_data/member
2015/02/13 12:58:17 etcdserver: heartbeat = 100ms
2015/02/13 12:58:17 etcdserver: election = 1000ms
2015/02/13 12:58:17 etcdserver: snapshot count = 10000
2015/02/13 12:58:17 etcdserver: advertise client URLs = http://172.17.42.1:2379,https://172.16.20.10:4001
2015/02/13 12:58:18 etcdserver: restart member 11b1d81545a7c53c in cluster dde4e50beb5dd8b9 at commit index 10004
2015/02/13 12:58:18 raft: 11b1d81545a7c53c became follower at term 88
2015/02/13 12:58:18 raft: newRaft 11b1d81545a7c53c [peers: [], term: 88, commit: 10004, applied: 0, lastindex: 10007, lastterm: 88]
2015/02/13 12:58:18 etcdserver: added local member 11b1d81545a7c53c [https://172.16.20.10:7001] to cluster dde4e50beb5dd8b9
2015/02/13 12:58:18 etcdserver: added member 140ee9c4a341523f [https://172.16.20.50:7001] to cluster dde4e50beb5dd8b9
2015/02/13 12:58:18 etcdserver: added member 2c6cf380a42df16b [https://172.16.20.20:7001] to cluster dde4e50beb5dd8b9
2015/02/13 12:58:18 etcdserver: added member 37864afe3ad250b0 [https://172.16.20.40:7001] to cluster dde4e50beb5dd8b9
2015/02/13 12:58:18 etcdserver: added member 454a97fdc352f27c [https://172.16.20.30:7001] to cluster dde4e50beb5dd8b9
2015/02/13 12:58:18 etcdserver: start to snapshot (applied: 10004, lastsnap: 0)
2015/02/13 12:58:18 etcdserver: compacted log at index 10004
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6111f5]

goroutine 22 [running]:
runtime.panic(0x7d8a80, 0xa5d433)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/coreos/etcd/snap.(*Snapshotter).save(0x0, 0xc2080c0bd0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/snap/snapshotter.go:71 +0x3b5
github.com/coreos/etcd/snap.(*Snapshotter).SaveSnap(0x0, 0xc20871c000, 0xb1f4b, 0x128583, 0xc20817cab0, 0x5, 0x5, 0x0, 0x0, 0x0, ...)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/snap/snapshotter.go:59 +0xbc
github.com/coreos/etcd/etcdserver.(*storage).SaveSnap(0xc208250110, 0xc20871c000, 0xb1f4b, 0x128583, 0xc20817cab0, 0x5, 0x5, 0x0, 0x0, 0x0, ...)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/storage.go:59 +0x65
github.com/coreos/etcd/etcdserver.(*EtcdServer).snapshot(0xc2080b6500, 0x2714, 0xc2080ac420)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:822 +0x586
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc2080b6500)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:423 +0xd3d
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:295 +0x1d2

goroutine 16 [runnable]:
github.com/coreos/etcd/etcdmain.Main()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:76 +0x56b
main.main()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/main.go:48 +0x1ab

goroutine 19 [finalizer wait]:
runtime.park(0x4131d0, 0xa61f78, 0xa601a9)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xa61f78, 0xa601a9)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 23 [runnable]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).Do(0xc2080b6500, 0x7f3d67a7b268, 0xc2080e48a0, 0x3c4b8304b2310001, 0x826d10, 0x3, 0xc2080ac630, 0x26, 0xc2080bc9a0, 0x6c, ...)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:479 +0x5cf
github.com/coreos/etcd/etcdserver.(*EtcdServer).publish(0xc2080b6500, 0x12a05f200)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:641 +0x2c9
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:276 +0x4c

goroutine 24 [runnable]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0xc2080b6500)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:306 +0x3f5
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:277 +0x64

goroutine 25 [IO wait]:
net.runtime_pollWait(0x7f3d67a6fe10, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208080370, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208080370, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc208080310, 0x8f59f0, 0x0, 0x7f3d67a6d4f0, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a028, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc20803a028, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
crypto/tls.(*listener).Accept(0xc2080a2f20, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/crypto/tls/tls.go:46 +0x6a
github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc2080a2f40, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x79
net/http.(*Server).Serve(0xc2080e4900, 0x7f3d67a708d0, 0xc2080a2f40, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1698 +0x91
github.com/coreos/etcd/etcdmain.serveHTTP(0x7f3d67a708d0, 0xc2080a2f40, 0x7f3d67a7b0e8, 0xc2080ac3c0, 0x45d964b800, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x136
github.com/coreos/etcd/etcdmain.func·005(0x7f3d67a708d0, 0xc2080a2f40)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:175 +0x56
created by github.com/coreos/etcd/etcdmain.startEtcd
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:176 +0x1351

goroutine 26 [IO wait]:
net.runtime_pollWait(0x7f3d67a6fd60, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20807a680, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20807a680, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20807a620, 0x8f59f0, 0x0, 0x7f3d67a6d4f0, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a040, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc20803a040, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc208084730, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x70
net/http.(*Server).Serve(0xc2080e4960, 0x7f3d67a70908, 0xc208084730, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1698 +0x91
github.com/coreos/etcd/etcdmain.serveHTTP(0x7f3d67a70908, 0xc208084730, 0x7f3d67a7b2a8, 0xc208083a40, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x136
github.com/coreos/etcd/etcdmain.func·006(0x7f3d67a70908, 0xc208084730)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:183 +0x81
created by github.com/coreos/etcd/etcdmain.startEtcd
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:184 +0x1475

goroutine 27 [IO wait]:
net.runtime_pollWait(0x7f3d67a6fcb0, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20807a760, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20807a760, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20807a700, 0x8f59f0, 0x0, 0x7f3d67a6d4f0, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a048, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc20803a048, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/coreos/etcd/pkg/transport.(*tlsKeepaliveListener).Accept(0xc208082820, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:70 +0x6d
net/http.(*Server).Serve(0xc2080e49c0, 0x7f3d67a71438, 0xc208082820, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1698 +0x91
github.com/coreos/etcd/etcdmain.serveHTTP(0x7f3d67a71438, 0xc208082820, 0x7f3d67a7b2a8, 0xc208083a40, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x136
github.com/coreos/etcd/etcdmain.func·006(0x7f3d67a71438, 0xc208082820)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:183 +0x81
created by github.com/coreos/etcd/etcdmain.startEtcd
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:184 +0x1475

goroutine 28 [runnable]:
github.com/coreos/etcd/pkg/fileutil.func·001()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x5e5
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x157

goroutine 29 [runnable]:
github.com/coreos/etcd/pkg/fileutil.func·001()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x5e5
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x157
```

**Comment by ghristov** [comment]
Actually I experienced that very same issues a couple of minutes ago. I was running standalone server though. Also I fixed it by recreating data directory.

**Comment by atombox** [comment]
In case somebody needs a 32bit working version for development/testing purposes, I can confirm that etcd 0.5 works on 32bit.
