### ISSUE TITLE
Cannot recover from this error. Had to delete the data dir to run it again.

### ISSUE THREAD

**Issue by ghristov** [coreos/etcd#2296]
> ./etcd --data-dir standalone/ --listen-client-urls http://127.0.0.1:4001
2015/02/13 15:22:56 netutil: Resolving localhost:4001 to 127.0.0.1:4001
2015/02/13 15:22:56 etcd: listening for peers on http://localhost:2380
2015/02/13 15:22:56 etcd: listening for peers on http://localhost:7001
2015/02/13 15:22:56 etcd: listening for client requests on http://127.0.0.10:4001
2015/02/13 15:22:56 datadir is valid for the 2.0.1 format
2015/02/13 15:22:56 etcdserver: name = default
2015/02/13 15:22:56 etcdserver: data dir = standalone/
2015/02/13 15:22:56 etcdserver: member dir = standalone/member
2015/02/13 15:22:56 etcdserver: heartbeat = 100ms
2015/02/13 15:22:56 etcdserver: election = 1000ms
2015/02/13 15:22:56 etcdserver: snapshot count = 10000
2015/02/13 15:22:56 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/02/13 15:22:56 etcdserver: restart member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit index 10001
2015/02/13 15:22:56 raft: ce2a822cea30bfca became follower at term 2
2015/02/13 15:22:56 raft: newRaft ce2a822cea30bfca [peers: [], term: 2, commit: 10001, applied: 0, lastindex: 10001, lastterm: 2]
2015/02/13 15:22:56 etcdserver: added local member ce2a822cea30bfca [http://localhost:2380 http://localhost:7001] to cluster 7e27652122e8b2ae
2015/02/13 15:22:56 etcdserver: start to snapshot (applied: 10001, lastsnap: 0)
2015/02/13 15:22:56 etcdserver: compacted log at index 10001
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6111f5]

>goroutine 23 [running]:
runtime.panic(0x7d8a80, 0xa5d433)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/coreos/etcd/snap.(*Snapshotter).save(0x0, 0xc208070ab0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/snap/snapshotter.go:71 +0x3b5
github.com/coreos/etcd/snap.(*Snapshotter).SaveSnap(0x0, 0xc2084c4000, 0xa938, 0x126b9, 0xc2081c6418, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/snap/snapshotter.go:59 +0xbc
github.com/coreos/etcd/etcdserver.(*storage).SaveSnap(0xc2081c6050, 0xc2084c4000, 0xa938, 0x126b9, 0xc2081c6418, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/storage.go:59 +0x65
github.com/coreos/etcd/etcdserver.(*EtcdServer).snapshot(0xc20808e100, 0x2711, 0xc2081a2270)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:822 +0x586
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc20808e100)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:423 +0xd3d
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:295 +0x1d2

>goroutine 16 [runnable]:
github.com/coreos/etcd/etcdmain.Main()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:76 +0x56b
main.main()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/main.go:48 +0x1ab

>goroutine 19 [finalizer wait]:
runtime.park(0x4131d0, 0xa61f78, 0xa601a9)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xa61f78, 0xa601a9)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

>goroutine 20 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/pkg/runtime/time.goc:39 +0x31
net.func·019()
	/usr/local/go/src/pkg/net/dnsclient_unix.go:183 +0x56
created by net.loadConfig
	/usr/local/go/src/pkg/net/dnsclient_unix.go:212 +0x153

>goroutine 24 [runnable]:
github.com/coreos/etcd/raft.(*node).step(0xc20800e0a0, 0x7fa7f4f9cd78, 0xc2080a3e60, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc20800e7d0, ...)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:383 +0x1cc
github.com/coreos/etcd/raft.(*node).Propose(0xc20800e0a0, 0x7fa7f4f9cd78, 0xc2080a3e60, 0xc208116580, 0xa2, 0xa2, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:355 +0x12f
github.com/coreos/etcd/etcdserver.(*EtcdServer).Do(0xc20808e100, 0x7fa7f4f9cd78, 0xc2080a3e60, 0xca4b831b405a0001, 0x826d10, 0x3, 0xc2081a2690, 0x26, 0xc2080a3da0, 0x51, ...)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:478 +0x30b
github.com/coreos/etcd/etcdserver.(*EtcdServer).publish(0xc20808e100, 0x12a05f200)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:641 +0x2c9
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:276 +0x4c

>goroutine 25 [runnable]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0xc20808e100)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:306 +0x3f5
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:277 +0x64

>goroutine 26 [IO wait]:
net.runtime_pollWait(0x7fa7f4f96d20, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20808c1b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20808c1b0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20808c150, 0x8f59f0, 0x0, 0x7fa7f4f954e8, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a060, 0xc2081cc3c0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc20803a060, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc2080888c0, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x79
net/http.(*Server).Serve(0xc2080a3ec0, 0x7fa7f4f970b8, 0xc2080888c0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1698 +0x91
github.com/coreos/etcd/etcdmain.serveHTTP(0x7fa7f4f970b8, 0xc2080888c0, 0x7fa7f4f9cb30, 0xc2081a2210, 0x45d964b800, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x136
github.com/coreos/etcd/etcdmain.func·005(0x7fa7f4f970b8, 0xc2080888c0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:175 +0x56
created by github.com/coreos/etcd/etcdmain.startEtcd
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:176 +0x1351

>goroutine 27 [IO wait]:
net.runtime_pollWait(0x7fa7f4f96c70, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20808c290, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20808c290, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20808c230, 0x8f59f0, 0x0, 0x7fa7f4f954e8, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a068, 0xc2081cc440, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc20803a068, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc2080889e0, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x79
net/http.(*Server).Serve(0xc2080a3f20, 0x7fa7f4f970b8, 0xc2080889e0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1698 +0x91
github.com/coreos/etcd/etcdmain.serveHTTP(0x7fa7f4f970b8, 0xc2080889e0, 0x7fa7f4f9cb30, 0xc2081a2210, 0x45d964b800, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x136
github.com/coreos/etcd/etcdmain.func·005(0x7fa7f4f970b8, 0xc2080889e0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:175 +0x56
created by github.com/coreos/etcd/etcdmain.startEtcd
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:176 +0x1351

>goroutine 28 [IO wait]:
net.runtime_pollWait(0x7fa7f4f96bc0, 0x72, 0x0)
	/usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20808c370, 0x72, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc20808c370, 0x0, 0x0)
	/usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc20808c310, 0x8f59f0, 0x0, 0x7fa7f4f954e8, 0xb)
	/usr/local/go/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a070, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x5d
net.(*TCPListener).Accept(0xc20803a070, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x4b
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc208037d10, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x70
net/http.(*Server).Serve(0xc2080a3f80, 0x7fa7f4f970f0, 0xc208037d10, 0x0, 0x0)
	/usr/local/go/src/pkg/net/http/server.go:1698 +0x91
github.com/coreos/etcd/etcdmain.serveHTTP(0x7fa7f4f970f0, 0xc208037d10, 0x7fa7f4f9cdb8, 0xc2081ce120, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x136
github.com/coreos/etcd/etcdmain.func·006(0x7fa7f4f970f0, 0xc208037d10)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:183 +0x81
created by github.com/coreos/etcd/etcdmain.startEtcd
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:184 +0x1475

>goroutine 29 [runnable]:
github.com/coreos/etcd/pkg/fileutil.func·001()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x5e5
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x157

>goroutine 30 [runnable]:
github.com/coreos/etcd/pkg/fileutil.func·001()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x5e5
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x157

127.0.0.1 is used to hide the real IP. I was not listening to localhost.

I was running a standalone server and testing some waitForChange situations with the library etcd4j.

><dependency>
      <groupId>org.mousio</groupId>
      <artifactId>etcd4j</artifactId>
      <version>2.1.1</version>
    </dependency>

While testing I noticed that responses from the server stopped. 
I checked what happened with the process and  there was this stacktrace and the daemon was stopped.

Tried to run it again but this appeared again. So i tried like that  around 5 times. Then decided to remove the data dir and recreate it. It worked like a charm.

Version of the etcd : etcd version 2.0.2

**Comment by ghristov** [comment]
Duplicated with #2295
