### ISSUE TITLE
raftAttributes key doesn't exist

### ISSUE THREAD

**Issue by colebrumley** [coreos/etcd#2297]
I have a 3 node cluster set up for testing and was attempting some load tests yesterday (thousands of writes per second with key watchers going too), when I got an error I haven't seen before:

```
2015/02/13 08:18:11 etcd: listening for peers on http://10.126.75.72:7001
2015/02/13 08:18:11 etcd: listening for peers on http://127.0.0.1:7001
2015/02/13 08:18:11 etcd: listening for client requests on http://10.126.75.72:4001
2015/02/13 08:18:11 etcd: listening for client requests on http://127.0.0.1:4001
2015/02/13 08:18:11 etcdserver: discovery token ignored since a cluster has already been initialized. Valid log found at "/var/lib/etcd/mvp01.etcd/wal"
2015/02/13 08:18:12 etcdserver: recovered store from snapshot at index 172422
2015/02/13 08:18:12 nodeToMember should never fail: raftAttributes key doesn't exist
panic: nodeToMember should never fail: raftAttributes key doesn't exist

goroutine 1 [running]:
log.Panicf(0x8b0090, 0x22, 0xc20a049040, 0x1, 0x1)
        /usr/local/go/src/log/log.go:314 +0xd0
github.com/coreos/etcd/etcdserver.membersFromStore(0x7f4f9f68a578, 0xc2080621e0, 0xc2080621e0, 0xc208cae140)
        /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:362 +0x398
github.com/coreos/etcd/etcdserver.NewClusterFromStore(0x7fff6667578d, 0x3a, 0x7f4f9f68a578, 0xc2080621e0, 0x1)
        /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:101 +0x179
github.com/coreos/etcd/etcdserver.NewServer(0xc20803a210, 0xc208058480, 0x0, 0x0)
        /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:213 +0x20b6
github.com/coreos/etcd/etcdmain.startEtcd(0xc208082000, 0x0, 0x0, 0x0)
        /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:161 +0x18cc
github.com/coreos/etcd/etcdmain.Main()
        /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:54 +0x1fc
main.main()
        /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/main.go:31 +0x1b
```

Possibly pertinent info:
 - etcd 2.0
 - using public discovery service
 - all 3 nodes error like this when restarted
 - one node is running in a docker container

EDIT: Wrapping ugliness

UPDATE:  I was able to get the cluster back up by deleting the data-dirs on all nodes.

**Comment by xiang90** [comment]
@colebrumley Are you running etcd 2.0.2 or 2.0?

**Comment by yichengq** [comment]
@colebrumley Do you have the backup of data-dir? Or the way to reproduce it?

**Comment by colebrumley** [comment]
@xiang90 : This is 2.0.0
@yichengq: I foolishly did not save the data-dir, I am trying to recreate it now and will update if I am successful

**Comment by colebrumley** [comment]
OK, after digging more I believe this could be an extension of https://github.com/coreos/etcd/issues/1959.  When I recreated this issue, I got "too many open files" on a snapshot attempt, then the node began to display this behavior:

```
Feb 13 10:37:11 VA1ACHMVP01 etcd[21562]: 2015/02/13 10:37:11 etcdserver: start to snapshot (applied: 220200, lastsnap: 210189)
Feb 13 10:37:11 VA1ACHMVP01 etcd[21562]: 2015/02/13 10:37:11 etcdserver: compacted log at index 220200
Feb 13 10:37:11 VA1ACHMVP01 etcd[21562]: 2015/02/13 10:37:11 etcdserver: save snapshot error: open mvp01.etcd/snap/0000000000000002-0000000000035c28.snap: too many open files
Feb 13 10:37:12 VA1ACHMVP01 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Feb 13 10:37:12 VA1ACHMVP01 systemd[1]: Unit etcd.service entered failed state.
Feb 13 10:46:32 VA1ACHMVP01 systemd[1]: Starting Etcd Server...
Feb 13 10:46:32 VA1ACHMVP01 systemd[1]: Started Etcd Server.
Feb 13 10:46:32 VA1ACHMVP01 etcd[21814]: 2015/02/13 10:46:32 no data-dir provided, using default data-dir ./mvp01.etcd
Feb 13 10:46:32 VA1ACHMVP01 etcd[21814]: 2015/02/13 10:46:32 etcd: listening for peers on http://10.126.75.72:7001
Feb 13 10:46:32 VA1ACHMVP01 etcd[21814]: 2015/02/13 10:46:32 etcd: listening for peers on http://127.0.0.1:7001
Feb 13 10:46:32 VA1ACHMVP01 etcd[21814]: 2015/02/13 10:46:32 etcd: listening for client requests on http://10.126.75.72:4001
Feb 13 10:46:32 VA1ACHMVP01 etcd[21814]: 2015/02/13 10:46:32 etcd: listening for client requests on http://127.0.0.1:4001
Feb 13 10:46:32 VA1ACHMVP01 etcd[21814]: 2015/02/13 10:46:32 etcdserver: discovery token ignored since a cluster has already been initialized. Valid log found at "mvp01.etcd/wal"
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: 2015/02/13 10:46:33 etcdserver: recovered store from snapshot at index 210189
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: 2015/02/13 10:46:33 nodeToMember should never fail: raftAttributes key doesn't exist
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: panic: nodeToMember should never fail: raftAttributes key doesn't exist
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: goroutine 1 [running]:
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: log.Panicf(0x8b0090, 0x22, 0xc20a4a7040, 0x1, 0x1)
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: /usr/local/go/src/log/log.go:314 +0xd0
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: github.com/coreos/etcd/etcdserver.membersFromStore(0x7f321a41f578, 0xc208066420, 0xc208066420, 0xc208dd3b80)
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:362 +0x398
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: github.com/coreos/etcd/etcdserver.NewClusterFromStore(0x7fff5a4daefa, 0x3a, 0x7f321a41f578, 0xc208066420, 0x1)
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:101 +0x179
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: github.com/coreos/etcd/etcdserver.NewServer(0xc208036210, 0xc208070480, 0x0, 0x0)
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:213 +0x20b6
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: github.com/coreos/etcd/etcdmain.startEtcd(0xc208080000, 0x0, 0x0, 0x0)
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:161 +0x18cc
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: github.com/coreos/etcd/etcdmain.Main()
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:54 +0x1fc
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: main.main()
Feb 13 10:46:33 VA1ACHMVP01 etcd[21814]: /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/main.go:31 +0x1b
Feb 13 10:46:33 VA1ACHMVP01 systemd[1]: etcd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 13 10:46:33 VA1ACHMVP01 systemd[1]: Unit etcd.service entered failed state.
```

I did save the data-dir if it would be helpful, but it's around 8.5MB so it's not uploaded anywhere yet.

**Comment by yichengq** [comment]
@colebrumley It could help a lot if you could send it to my email address yicheng.qin@coreos.com

**Comment by colebrumley** [comment]
OK, sent!

**Comment by yichengq** [comment]
@colebrumley 
Cheers for @xiang90 ! :light_rail: 
The original add node entries are applied into raft but not store because store has a more strict checking. so its info cannot be recovered from store any more.
