### ISSUE TITLE
etcd panic when using etcdctl remove a member

### ISSUE THREAD

**Issue by holmes86** [coreos/etcd#2651]
I try removing a member of etcd cluster, then I found etcd panic. "journalctl -u etcd" as follow:

```
Apr 10 15:07:01 machine2 systemd[1]: Unit etcd.service entered failed state.
Apr 10 15:07:01 machine2 systemd[1]: etcd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/net/http/server.go:1721 +0x313
Apr 10 15:07:01 machine2 etcd[13510]: created by net/http.(*Server).Serve
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/net/http/server.go:1174 +0xa7e
Apr 10 15:07:01 machine2 etcd[13510]: net/http.(*conn).serve(0xc208314000)
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/net/http/server.go:1673 +0x19f
Apr 10 15:07:01 machine2 etcd[13510]: net/http.serverHandler.ServeHTTP(0xc2081e3e60, 0x7f48a0634d30, 0xc208436aa0, 0xc20807fc70)
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/pkg/cors/cors.go:86 +0x20f
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/pkg/cors.(*CORSHandler).ServeHTTP(0xc20833c7e0, 0x7f48a0634d30, 0xc208436aa0, 0xc20807fc70)
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/net/http/server.go:1511 +0x1a3
Apr 10 15:07:01 machine2 etcd[13510]: net/http.(*ServeMux).ServeHTTP(0xc208021dd0, 0x7f48a0634d30, 0xc208436aa0, 0xc20807fc70)
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/etcdserver/etcdhttp/client.go:116 +0x38f
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/etcdserver/etcdhttp.(*keysHandler).ServeHTTP(0xc2084ff740, 0x7f48a0634d30, 0xc208436aa0, 0xc20807fc70)
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/etcdserver/server.go:491 +0x5cf
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/etcdserver.(*EtcdServer).Do(0xc208088100, 0x7f48a0634b70, 0xc20818e0c0, 0xb94ca227363d0002, 0xc2083cf8f0, 0x3, 0xc2083d3e50, 0x45, 0xc2080a1b00, 0x8c, ...)
Apr 10 15:07:01 machine2 etcd[13510]: goroutine 36 [runnable]:
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x157
Apr 10 15:07:01 machine2 etcd[13510]: created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x5e5
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/pkg/fileutil.func·001()
Apr 10 15:07:01 machine2 etcd[13510]: goroutine 35 [runnable]:
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/pkg/osutil/osutil.go:82 +0x147
Apr 10 15:07:01 machine2 etcd[13510]: created by github.com/coreos/etcd/pkg/osutil.HandleInterrupts
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/pkg/osutil/osutil.go:66 +0x5e
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/pkg/osutil.func·001()
Apr 10 15:07:01 machine2 etcd[13510]: goroutine 34 [chan receive]:
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/etcdmain/etcd.go:189 +0x14a4
Apr 10 15:07:01 machine2 etcd[13510]: created by github.com/coreos/etcd/etcdmain.startEtcd
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/etcdmain/etcd.go:188 +0x81
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/etcdmain.func·006(0x7f48a0625c38, 0xc208001230)
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x136
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/etcdmain.serveHTTP(0x7f48a0625c38, 0xc208001230, 0x7f48a0634bb0, 0xc20833c7e0, 0x0, 0x0, 0x0)
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/net/http/server.go:1698 +0x91
Apr 10 15:07:01 machine2 etcd[13510]: net/http.(*Server).Serve(0xc2081e3e60, 0x7f48a0625c38, 0xc208001230, 0x0, 0x0)
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x70
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc208001230, 0x0, 0x0, 0x0, 0x0)
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/net/tcpsock_posix.go:244 +0x4b
Apr 10 15:07:01 machine2 etcd[13510]: net.(*TCPListener).Accept(0xc208048030, 0x0, 0x0, 0x0, 0x0)
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/net/tcpsock_posix.go:234 +0x5d
Apr 10 15:07:01 machine2 etcd[13510]: net.(*TCPListener).AcceptTCP(0xc208048030, 0x1d, 0x0, 0x0)
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/net/fd_unix.go:419 +0x343
Apr 10 15:07:01 machine2 etcd[13510]: net.(*netFD).accept(0xc20808c850, 0x8f6fa8, 0x0, 0x7f48a06243f0, 0xb)
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/net/fd_poll_runtime.go:89 +0x42
Apr 10 15:07:01 machine2 etcd[13510]: net.(*pollDesc).WaitRead(0xc20808c8b0, 0x0, 0x0)
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/net/fd_poll_runtime.go:84 +0x46
Apr 10 15:07:01 machine2 etcd[13510]: net.(*pollDesc).Wait(0xc20808c8b0, 0x72, 0x0, 0x0)
Apr 10 15:07:01 machine2 etcd[13510]: /builddir/build/BUILD/go/src/pkg/runtime/netpoll.goc:146 +0x66
Apr 10 15:07:01 machine2 etcd[13510]: net.runtime_pollWait(0x7f48a0625940, 0x72, 0x0)
Apr 10 15:07:01 machine2 etcd[13510]: goroutine 33 [IO wait]:
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/etcdmain/etcd.go:189 +0x14a4
Apr 10 15:07:01 machine2 etcd[13510]: created by github.com/coreos/etcd/etcdmain.startEtcd
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/etcdmain/etcd.go:188 +0x81
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/etcdmain.func·006(0x7f48a0625c38, 0xc2080011c0)
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x136
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/etcdmain.serveHTTP(0x7f48a0625c38, 0xc2080011c0, 0x7f48a0634bb0, 0xc20833c7e0, 0x0, 0x0, 0x0)
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/etcdserver/server.go:733 +0x9ba
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/etcdserver.(*EtcdServer).applyRequest(0xc208088100, 0x964ca225fa210001, 0xc2084e7cd0, 0x3, 0xc2084f1c50, 0x25, 0xc2084f3b60, 0x51, 0x0, 0x0, ...)
Apr 10 15:07:01 machine2 etcd[13510]: /root/rpmbuild/BUILD/etcd-2.0.3/src/github.com/coreos/etcd/etcdserver/cluster.go:331 +0xb1
Apr 10 15:07:01 machine2 etcd[13510]: github.com/coreos/etcd/etcdserver.(*Cluster).UpdateAttributes(0xc208352140, 0x6fafd2d770d2396, 0xc2084e7cf0, 0xb, 0xc2084345c0, 0x2, 0x4)
Apr 10 15:07:01 machine2 etcd[13510]: /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
Apr 10 15:07:01 machine2 etcd[13510]: runtime.panic(0x7d9900, 0xa5c5d3)
Apr 10 15:07:01 machine2 etcd[13510]: goroutine 27 [running]:
Apr 10 15:07:01 machine2 etcd[13510]: [signal 0xb code=0x1 addr=0x0 pc=0x4a11b1]
Apr 10 15:07:01 machine2 etcd[13510]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 10 15:07:01 machine2 etcd[13510]: 2015/04/10 15:07:01 etcdserver: removed member 6fafd2d770d2396 from cluster 5a21426bca2d472c
Apr 10 15:07:01 machine2 etcd[13510]: 2015/04/10 15:07:01 raft: newRaft f2882b486b73afb9 [peers: [6fafd2d770d2396,f2882b486b73afb9], term: 6113, commit: 12823270, applied: 12819995, lastindex: 12823270, lastterm: 6113]
Apr 10 15:07:01 machine2 etcd[13510]: 2015/04/10 15:07:01 raft: f2882b486b73afb9 became follower at term 6113
Apr 10 15:07:01 machine2 etcd[13510]: 2015/04/10 15:07:01 etcdserver: restart member f2882b486b73afb9 in cluster 5a21426bca2d472c at commit index 12823270


```

**Comment by xiang90** [comment]
@holmes86 Are you running on current master? Or 2.0.9?

**Comment by holmes86** [comment]
@xiang90 yes, I am running on current master. my etcd version is 2.0.3,thanks

**Comment by xiang90** [comment]
@holmes86 Hrm... I guess I do not quite understand. Are you running 2.0.3 or current master? I think we have fixed a related issue after 2.0.3 release.

**Comment by holmes86** [comment]
@xiang90 sorry, I got it wrong. I am running etcd 2.0.3. I will try the current master.

**Comment by xiang90** [comment]
@holmes86 Any update?

**Comment by xiang90** [comment]
@holmes86 Closing due to low activity. Feel free to reopen if the problem still exists after your update.
