### ISSUE TITLE
Question: `etcdctl backup` documentation is outdated?

### ISSUE THREAD

**Issue by sorah** [coreos/etcd#2664]
Referring https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#backing-up-the-datastore , I expect this to succeed, but fail:

```
$ etcdctl backup -data-dir path/to/existing/etcd -backup-dir /tmp/etcd
2015/04/13 13:38:20 open path/to/existing/etcd/snap: no such file or directory
```

specifying `path/to/existing/etcd/member` to `data-dir` success, with the following output, when `etcd` server process is running:

```
2015/04/13 13:45:52 wal: opened all the files until 0000000000000004-000000000021f93f.wal, since it is still in use by an etcd server
Failed to find the match snapshot record {Index:2350235 Term:10 XXX_unrecognized:[]} in wal .../etcd/member/wal.etcdctl will add it back. Start auto fixing...
```

Then placed backup-dir to `/tmp/etcd2/member` and started `etcd` server process with it -- but failed:

```
2015/04/13 13:44:50 etcd: already initialized as member before, starting as etcd member...
2015/04/13 13:44:50 etcd: listening for peers on http://127.0.0.1:3380
2015/04/13 13:44:50 etcd: listening for client requests on http://127.0.0.1:3379
2015/04/13 13:44:50 etcdserver: datadir is valid for the 2.0.1 format
2015/04/13 13:44:50 etcdserver: recovered store from snapshot at index 2350235
2015/04/13 13:44:50 etcdserver: name = default
2015/04/13 13:44:50 etcdserver: force new cluster
2015/04/13 13:44:50 etcdserver: data dir = /tmp/etcd
2015/04/13 13:44:50 etcdserver: member dir = /tmp/etcd/member
2015/04/13 13:44:50 etcdserver: heartbeat = 100ms
2015/04/13 13:44:50 etcdserver: election = 1000ms
2015/04/13 13:44:50 etcdserver: snapshot count = 10000
2015/04/13 13:44:50 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/04/13 13:44:50 etcdserver: loaded cluster information from store: default=http://localhost:2380,default=http://localhost:7001
2015/04/13 13:44:50 etcdserver: forcing restart of member 4cb113a1740001 in cluster 4cb113a1740002 at commit index 2
2015/04/13 13:44:50 raft: 4cb113a1740001 state.commit 2 is out of range [2350235, 2350235]
panic: raft: 4cb113a1740001 state.commit 2 is out of range [2350235, 2350235]

goroutine 1 [running]:
log.(*Logger).Panicf(0x2088a4190, 0x5b6990, 0x31, 0x20897a100, 0x4, 0x4)
        /usr/local/Cellar/go/1.4/libexec/src/log/log.go:200 +0xd1
github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0x77fd70, 0x5b6990, 0x31, 0x20897a100, 0x4, 0x4)
        /Users/sorah/git/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/logger.go:121 +0x5d
github.com/coreos/etcd/raft.(*raft).loadState(0x2089780c0, 0x0, 0x0, 0x2, 0x0, 0x0, 0x0)
        /Users/sorah/git/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:754 +0x27b
github.com/coreos/etcd/raft.newRaft(0x208972480, 0xb4c3)
        /Users/sorah/git/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:194 +0x707
github.com/coreos/etcd/raft.RestartNode(0x208972480, 0x0, 0x0)
        /Users/sorah/git/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:187 +0x4b
github.com/coreos/etcd/etcdserver.restartAsStandaloneNode(0x2088a6630, 0x2088b6870, 0x20896d320, 0x0, 0x0, 0x0, 0x0)
        /Users/sorah/git/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:307 +0xaab
github.com/coreos/etcd/etcdserver.NewServer(0x2088a6630, 0x2088b65a0, 0x0, 0x0)
        /Users/sorah/git/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:241 +0x2455
github.com/coreos/etcd/etcdmain.startEtcd(0x2088b81e0, 0x0, 0x0, 0x0)
        /Users/sorah/git/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:180 +0x13c8
github.com/coreos/etcd/etcdmain.Main()
        /Users/sorah/git/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:81 +0x594
main.main()
        /Users/sorah/git/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x1b

goroutine 9 [syscall]:
os/signal.loop()
        /usr/local/Cellar/go/1.4/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/Cellar/go/1.4/libexec/src/os/signal/signal_unix.go:27 +0x35
```

Running `etcdctl backup` when etcd process isn't running for `member` directory, succeeds and can start new etcd server process on it.

**Comment by barakmich** [comment]
Interesting that we have the note for it requiring shutdown for Windows servers but not Linux...

This strikes me more as a bug, perhaps related to/introduced by auto-cutting WALs, which is what's happened in that code lately. Though that's just a guess.

So two resolution options here:
1) Update the docs and require `backup` work on a stopped data-dir, as well as having the message "still in use" stop trying to backup.
2) Fix `backup` to work correctly on a running data-dir.

**Comment by xiang90** [comment]
@barakmich The problem is introduced by `snapMark`. The user now might copy a snapshot that is more up-to-date than any of the not-in-use wal files. But, when restarting, it still looks for the mark in the wal.

**Comment by sorah** [comment]
so we have 2 problems, right?

1. backup command doesn't see `#{data dir}/member`
2. a bug caused by `snapMark` ? (note: I don't know the detail of it)
