### ISSUE TITLE
etcd 0.4.x: etcd fails to start (panic: runtime error: index out of range) CoreOS 653.0.0

### ISSUE THREAD

**Issue by lordelph** [coreos/etcd#2737]
I updated a 3-node Vagrant-based cluster to CoreOS 653 from a previous alpha. Now etcd will not start, recording a "panic: runtime error: index out of range" message in the journal. Here's a section of the journal with the details of the etcd startup and subsequent failure

The user-data did not change, and was using the same etcd configuration as before the upgrade.
~~~~~~~~~
Apr 23 13:50:10 core-01 systemd[1]: etcd.service holdoff time over, scheduling restart.
Apr 23 13:50:10 core-01 systemd[1]: Starting etcd...
Apr 23 13:50:10 core-01 systemd[1]: Started etcd.
Apr 23 13:50:10 core-01 etcd[1176]: [etcd] Apr 23 13:50:10.301 INFO      | Peer URLs in log:  / 6b7ec6df5efb4a8e960a0b6d1d21c38b ()
Apr 23 13:50:10 core-01 etcd[1176]: [etcd] Apr 23 13:50:10.302 INFO      | Discovery via https://discovery.etcd.io using prefix /abcdef-my-prefix-was-here-0123456
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.498 INFO      | Discovery found peers [http://172.17.8.102:7001 http://172.17.8.103:7001]
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.499 INFO      | Discovery fetched back peer list: [172.17.8.102:7001 172.17.8.103:7001]
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.503 INFO      | Send Join Request to http://172.17.8.102:7001/join
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.505 INFO      | 6b7ec6df5efb4a8e960a0b6d1d21c38b attempted to join via 172.17.8.102:7001 failed: fail on join request: Raft Internal Error ()
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.509 INFO      | Send Join Request to http://172.17.8.103:7001/join
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.511 INFO      | 6b7ec6df5efb4a8e960a0b6d1d21c38b attempted to join via 172.17.8.103:7001 failed: fail on join request: Raft Internal Error ()
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.511 WARNING   | 6b7ec6df5efb4a8e960a0b6d1d21c38b cannot connect to previous cluster [172.17.8.102:7001 172.17.8.103:7001]: fail joining the cluster via given peers after 1 retries
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.516 INFO      | etcd server [name 6b7ec6df5efb4a8e960a0b6d1d21c38b, listen on :4001, advertised url http://172.17.8.101:4001]
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.517 INFO      | peer server [name 6b7ec6df5efb4a8e960a0b6d1d21c38b, listen on :7001, advertised url http://172.17.8.101:7001]
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.518 INFO      | 6b7ec6df5efb4a8e960a0b6d1d21c38b starting in peer mode
Apr 23 13:50:11 core-01 etcd[1176]: [etcd] Apr 23 13:50:11.518 INFO      | 6b7ec6df5efb4a8e960a0b6d1d21c38b: state changed from 'initialized' to 'follower'.
Apr 23 13:50:12 core-01 etcd[1176]: [etcd] Apr 23 13:50:12.456 INFO      | 6b7ec6df5efb4a8e960a0b6d1d21c38b: state changed from 'follower' to 'candidate'.
Apr 23 13:50:12 core-01 etcd[1176]: [etcd] Apr 23 13:50:12.457 INFO      | 6b7ec6df5efb4a8e960a0b6d1d21c38b: state changed from 'candidate' to 'leader'.
Apr 23 13:50:12 core-01 etcd[1176]: [etcd] Apr 23 13:50:12.457 INFO      | 6b7ec6df5efb4a8e960a0b6d1d21c38b: leader changed from '' to '6b7ec6df5efb4a8e960a0b6d1d21c38b'.
Apr 23 13:50:14 core-01 etcd[1176]: panic: runtime error: index out of range
Apr 23 13:50:14 core-01 etcd[1176]: goroutine 43 [running]:
Apr 23 13:50:14 core-01 etcd[1176]: runtime.panic(0x897820, 0xcb2cbc)
Apr 23 13:50:14 core-01 etcd[1176]: /usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
Apr 23 13:50:14 core-01 etcd[1176]: github.com/coreos/etcd/third_party/github.com/goraft/raft.(*Log).commitInfo(0xc20802a700, 0x0, 0x0)
Apr 23 13:50:14 core-01 etcd[1176]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.9-r1/work/etcd-0.4.9/gopath/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/log.go:301 +0x33a
Apr 23 13:50:14 core-01 etcd[1176]: github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).TakeSnapshot(0xc208074120, 0x0, 0x0)
Apr 23 13:50:14 core-01 etcd[1176]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.9-r1/work/etcd-0.4.9/gopath/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:1203 +0x2aa
Apr 23 13:50:14 core-01 etcd[1176]: github.com/coreos/etcd/server.(*PeerServer).monitorSnapshot(0xc2080bc000)
Apr 23 13:50:14 core-01 etcd[1176]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.9-r1/work/etcd-0.4.9/gopath/src/github.com/coreos/etcd/server/peer_server.go:785 +0x15c
Apr 23 13:50:14 core-01 etcd[1176]: github.com/coreos/etcd/server.*PeerServer.(github.com/coreos/etcd/server.monitorSnapshot)·fm()
Apr 23 13:50:14 core-01 etcd[1176]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.9-r1/work/etcd-0.4.9/gopath/src/github.com/coreos/etcd/server/peer_server.go:298 +0x26
Apr 23 13:50:14 core-01 etcd[1176]: github.com/coreos/etcd/server.func·002()
Apr 23 13:50:14 core-01 etcd[1176]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.9-r1/work/etcd-0.4.9/gopath/src/github.com/coreos/etcd/server/peer_server.go:768 +0x5d
Apr 23 13:50:14 core-01 etcd[1176]: created by github.com/coreos/etcd/server.(*PeerServer).startRoutine
Apr 23 13:50:14 core-01 etcd[1176]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.9-r1/work/etcd-0.4.9/gopath/src/github.com/coreos/etcd/server/peer_server.go:769 +0xb4
Apr 23 13:50:14 core-01 etcd[1176]: goroutine 16 [select]:
Apr 23 13:50:14 core-01 etcd[1176]: github.com/coreos/etcd/etcd.(*Etcd).runServer(0xc208050300)
Apr 23 13:50:14 core-01 etcd[1176]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.9-r1/work/etcd-0.4.9/gopath/src/github.com/coreos/etcd/etcd/etcd.go:327 +0xa4a
Apr 23 13:50:14 core-01 etcd[1176]: github.com/coreos/etcd/etcd.(*Etcd).Run(0xc208050300)
Apr 23 13:50:14 core-01 etcd[1176]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.9-r1/work/etcd-0.4.9/gopath/src/github.com/coreos/etcd/etcd/etcd.go:298 +0x3352
Apr 23 13:50:14 core-01 etcd[1176]: main.main()
Apr 23 13:50:14 core-01 etcd[1176]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.9-r1/work/etcd-0.4.9/gopath/src/github.com/coreos/etcd/main.go:43 +0x2b8
Apr 23 13:50:14 core-01 etcd[1176]: goroutine 19 [finalizer wait]:
Apr 23 13:50:14 core-01 systemd[1]: etcd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 23 13:50:14 core-01 systemd[1]: Unit etcd.service entered failed state.
Apr 23 13:50:14 core-01 systemd[1]: etcd.service failed.
~~~~~~~~~

**Comment by philips** [comment]
Is this happening on one machine or all three? WAL safety is one of the major features of etcd 2.0 which is now available in the alpha channel: https://coreos.com/blog/coreos-alpha-with-etcd-2/

So, if you are willing to upgrade to etcd 2.0 that would be the best path. Otherwise, you will need to delete the information in the /var/lib/etcd directory for this machine and re-add it to the cluster.

**Comment by xiang90** [comment]
@lordelph 
There is a known issue in go-raft. go-raft is unmaintained now. So it is not going to be fixed. We have moved to etcd/raft in 2.0, which is a more robust raft with full test coverage. And we are actively supporting/testing it.

**Comment by lordelph** [comment]
As this was just for development, I trashed the cluster and started a new one using etcd 2.0. I logged the issue as it would seem that after an automatic update this would stop a cluster from working.

**Comment by xiang90** [comment]
@lordelph Yes. It is a known issue for go-raft. Thanks for your reporting. If you find any issue in etcd 2.0, please report back too. We are happy to help/support your more than this time!
