### ISSUE TITLE
Panic adding a node back in the cluster after purging node data dir

### ISSUE THREAD

**Issue by ilmerovingio** [coreos/etcd#2907]
I have a local cluster of 3 VMs running on Vagrant

```
vagrant@etcd2:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

vagrant@etcd2:~$ uname -a
Linux etcd1 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

vagrant@etcd2:~$ etcd --version
etcd Version: 2.0.11
Git SHA: 0678329
Go Version: go1.4.2
Go OS/Arch: linux/amd64

vagrant@etcd2:~$ etcdctl member list
48066a2a6d457e78: name=etcd2 peerURLs=http://172.17.1.101:2380 clientURLs=http://172.17.1.101:2379
5f3fc4d39f11e43a: name=etcd1 peerURLs=http://172.17.1.100:2380 clientURLs=http://172.17.1.100:2379
7c095ed337acf4ee: name=etcd3 peerURLs=http://172.17.1.102:2380 clientURLs=http://172.17.1.102:2379
```
After doing some benchmark tuning the "-snapshot-count" param I had the node 'etcd1' not able to rejoin the cluster due to https://github.com/coreos/etcd/issues/2515. I checked with lsof and there were not open files for any etcd WAL files.

Trying to add back the node to the cluster I cleaned its data dir and specified -initial-cluster-state to 'existing' but without success. Here's the log:

```
2015/06/02 15:56:11 etcd: already initialized as member before, starting as etcd member...
2015/06/02 15:56:11 etcd: listening for peers on http://172.17.1.100:2380
2015/06/02 15:56:11 etcd: listening for client requests on http://127.0.0.1:2379
2015/06/02 15:56:11 etcd: listening for client requests on http://172.17.1.100:2379
2015/06/02 15:56:11 etcdserver: datadir is valid for the 2.0.1 format
2015/06/02 15:56:11 etcdserver: name = etcd1
2015/06/02 15:56:11 etcdserver: data dir = /vagrant/etcd/etcd1
2015/06/02 15:56:11 etcdserver: member dir = /vagrant/etcd/etcd1/member
2015/06/02 15:56:11 etcdserver: heartbeat = 100ms
2015/06/02 15:56:11 etcdserver: election = 1000ms
2015/06/02 15:56:11 etcdserver: snapshot count = 1000
2015/06/02 15:56:11 etcdserver: advertise client URLs = http://172.17.1.100:2379
2015/06/02 15:56:11 etcdserver: restart member 5f3fc4d39f11e43a in cluster fb20059ee7960f89 at commit index 0
2015/06/02 15:56:11 raft: 5f3fc4d39f11e43a became follower at term 0
2015/06/02 15:56:11 raft: newRaft 5f3fc4d39f11e43a [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/06/02 15:56:11 raft: 5f3fc4d39f11e43a [term: 0] received a MsgHeartbeat message with higher term from 7c095ed337acf4ee [term: 59]
2015/06/02 15:56:11 raft: 5f3fc4d39f11e43a became follower at term 59
2015/06/02 15:56:11 tocommit(20721) is out of range [lastIndex(0)]
panic: tocommit(20721) is out of range [lastIndex(0)]

goroutine 6 [running]:
log.Panicf(0x8ccbb0, 0x2c, 0xc2080e6510, 0x2, 0x2)
        /usr/local/go/src/log/log.go:314 +0xd0
github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc208038780, 0x50f1)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/log.go:177 +0x179
github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc20803a4d0, 0x8, 0x5f3fc4d39f11e43a, 0x7c095ed337acf4ee, 0x3b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:593 +0x47
github.com/coreos/etcd/raft.stepFollower(0xc20803a4d0, 0x8, 0x5f3fc4d39f11e43a, 0x7c095ed337acf4ee, 0x3b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:563 +0xfdd
github.com/coreos/etcd/raft.(*raft).Step(0xc20803a4d0, 0x8, 0x5f3fc4d39f11e43a, 0x7c095ed337acf4ee, 0x3b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:461 +0x23f
github.com/coreos/etcd/raft.(*node).run(0xc208038730, 0xc20803a4d0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:275 +0x689
created by github.com/coreos/etcd/raft.RestartNode
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:180 +0x121

goroutine 1 [chan receive]:
github.com/coreos/etcd/etcdmain.Main()
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:108 +0xb81
main.main()
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x1b

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [select]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc20804a200)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:365 +0x14b0
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:305 +0x27c

goroutine 9 [select]:
github.com/coreos/etcd/raft.(*node).step(0xc208038730, 0x7fe69a336180, 0xc20806a9c0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc2080387d0, ...)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:383 +0x1ed
github.com/coreos/etcd/raft.(*node).Propose(0xc208038730, 0x7fe69a336180, 0xc20806a9c0, 0xc2080721b0, 0x8a, 0x8a, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:355 +0x141
github.com/coreos/etcd/etcdserver.(*EtcdServer).Do(0xc20804a200, 0x7fe69a336180, 0xc20806a9c0, 0x3a4db4fcb9cb0001, 0x840140, 0x3, 0xc20803de90, 0x26, 0xc2080352c0, 0x3a, ...)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:498 +0x2ee
github.com/coreos/etcd/etcdserver.(*EtcdServer).publish(0xc20804a200, 0x12a05f200)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:661 +0x30b
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:287 +0x4f

goroutine 10 [select]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0xc20804a200)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:316 +0x48c
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:288 +0x69

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc2080845a0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080845a0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208084540, 0x0, 0x7fe69a333c18, 0xc2080336d8)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036040, 0x7fe69a336348, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208036040, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc20801f9a0, 0x0, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x7a
net/http.(*Server).Serve(0xc20806ab40, 0x7fe69a335558, 0xc20801f9a0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x7fe69a335558, 0xc20801f9a0, 0x7fe69a336000, 0xc20803dc50, 0x45d964b800, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·005(0x7fe69a335558, 0xc20801f9a0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:204 +0x5a
created by github.com/coreos/etcd/etcdmain.startEtcd
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:205 +0x1850

goroutine 12 [IO wait]:
net.(*pollDesc).Wait(0xc208084680, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208084680, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208084620, 0x0, 0x7fe69a333c18, 0xc208033620)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036048, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208036048, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc208033520, 0x0, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x71
net/http.(*Server).Serve(0xc20806aba0, 0x7fe69a335590, 0xc208033520, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x7fe69a335590, 0xc208033520, 0x7fe69a3361c0, 0xc20801ea80, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·006(0x7fe69a335590, 0xc208033520)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:212 +0x80
created by github.com/coreos/etcd/etcdmain.startEtcd
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:213 +0x1992

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0xc208084760, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208084760, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208084700, 0x0, 0x7fe69a333c18, 0xc208033650)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036050, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208036050, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc2080335a0, 0x0, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x71
net/http.(*Server).Serve(0xc20806ac00, 0x7fe69a335590, 0xc2080335a0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x7fe69a335590, 0xc2080335a0, 0x7fe69a3361c0, 0xc20801ea80, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·006(0x7fe69a335590, 0xc2080335a0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:212 +0x80
created by github.com/coreos/etcd/etcdmain.startEtcd
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:213 +0x1992

goroutine 14 [chan receive]:
github.com/coreos/etcd/pkg/osutil.func·001()
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:53 +0x68
created by github.com/coreos/etcd/pkg/osutil.HandleInterrupts
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:74 +0x1f6

goroutine 15 [select]:
github.com/coreos/etcd/pkg/fileutil.func·001()
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x658
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x231

goroutine 16 [select]:
github.com/coreos/etcd/pkg/fileutil.func·001()
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:69 +0x658
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:75 +0x231
```

**Comment by xiang90** [comment]
@ilmerovingio If you lost the previous data, etcd member should be considered as dead. You have to remove it rather than restarting it.

**Comment by xiang90** [comment]
@ilmerovingio More details: https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#lifecycle

**Comment by ilmerovingio** [comment]
@xiang90: sorry, I forgot to do a proper node cleanup. When I saw the exceptions I thought that it was a an app issue. To avoid that could be useful to have an error message for that. 

Regarding https://github.com/coreos/etcd/issues/2515 I'll try to reproduce it. 

Thanks a lot again!

**Comment by ilmerovingio** [comment]
I was able to reproduce https://github.com/coreos/etcd/issues/2515
```
2015/06/02 16:46:56 etcdserver: failed to purge wal file remove /vagrant/etcd/etcd1/member/wal/0000000000000000-0000000000000000.wal: text file busy
vagrant@etcd1:~$ echo $?
1
vagrant@etcd1:~$ lsof | grep /vagrant/etcd
vagrant@etcd1:~$ echo $?
1
```
but I think that it could be related to the virtualbox mount point that I'm using for the data-dir
```
vagrant@etcd1:~$ mount
/dev/sda1 on / type ext4 (rw)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
none on /sys/kernel/security type securityfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
none on /sys/fs/pstore type pstore (rw)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
vagrant on /vagrant type vboxsf (uid=1000,gid=1000,rw)
```

I posted this comment because maybe it can be helpful to debug https://github.com/coreos/etcd/issues/2515, maybe not... :) thanks again!
