### ISSUE TITLE
raft panic when sending MsgApp

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2918]
```
2015/06/01 15:43:11 INFO: raft: 7e1d7e3cd441ab75 failed to send message to 217e5298f6dfdb33 because it is unreachable [next = 107931036, match = 107931035, state = ProgressStateProbe, waiting = true, pendingSnapshot = 0]
2015/06/01 15:43:11 INFO: raft: 7e1d7e3cd441ab75 failed to send message to 217e5298f6dfdb33 because it is unreachable [next = 107931036, match = 107931035, state = ProgressStateProbe, waiting = true, pendingSnapshot = 0]
2015/06/1 15:43:11 etcdserver: saved snapshot at index 107937203
2015/06/1 15:43:11 etcdserver: compacted raft log at 107932203
2015/06/01 15:43:11 raft: slice[107931036,107939749) out of bound [107932204,107939748]
panic: raft: slice[107931036,107939749) out of bound [107932204,107939748]

goroutine 11 [running]:
log.(*Logger).Panicf(0xc20804e190, 0x99be10, 0x27, 0xc20df4d140, 0x4, 0x4)
        /usr/local/go/src/log/log.go:200 +0xd1
github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0xb875b0, 0x99be10, 0x27, 0xc20df4d140, 0x4, 0x4)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/raft/logger.go:121 +0x5d
github.com/coreos/etcd/raft.(*raftLog).mustCheckOutOfBounds(0xc20d110000, 0x66ee59c, 0x66f07a5)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/raft/log.go:300 +0x3fc
github.com/coreos/etcd/raft.(*raftLog).slice(0xc20d110000, 0x66ee59c, 0x66f07a5, 0x100000, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/raft/log.go:258 +0x74
github.com/coreos/etcd/raft.(*raftLog).entries(0xc20d110000, 0x66ee59c, 0x100000, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/raft/log.go:224 +0xb2
github.com/coreos/etcd/raft.(*raft).sendAppend(0xc20cf3b440, 0x217e5298f6dfdb33)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/raft/raft.go:265 +0x994
github.com/coreos/etcd/raft.(*raft).bcastAppend(0xc20cf3b440)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/raft/raft.go:308 +0xa2
github.com/coreos/etcd/raft.stepLeader(0xc20cf3b440, 0x2, 0x0, 0x7e1d7e3cd441ab75, 0x0, 0x0, 0x0, 0xc215291d60, 0x1, 0x1, ...)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/raft/raft.go:513 +0x2b7
github.com/coreos/etcd/raft.(*raft).Step(0xc20cf3b440, 0x2, 0x0, 0x7e1d7e3cd441ab75, 0x0, 0x0, 0x0, 0xc215291d60, 0x1, 0x1, ...)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/raft/raft.go:487 +0x259
github.com/coreos/etcd/raft.(*node).run(0xc20d1100a0, 0xc20cf3b440)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/raft/node.go:281 +0x4d4
created by github.com/coreos/etcd/raft.RestartNode
        /Users/unihorn/gopath/src/github.com/coreos/etcd/raft/node.go:190 +0xce
```

The process seems to be:
1. leader is ready to send MsgApp
2. leader checks that it doesn't need to send MsgSnapshot and gets start index 107931036
3. leader compacts the log at 107937203
4. leader panic because it cannot find the log entries to send

**Comment by xiang90** [comment]
@yichengq I have got a fix. But this seems to be a very low probability issue and can recover from a simple restart. This involves a raft change and needs more testing. So defer to 2.2.
