### ISSUE TITLE
travis failed on TestSimpleHTTPClientDoCancelContextResponseBodyClosed

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2933]
```
panic: test timed out after 3m0s
goroutine 17 [running]:
testing.func·008()
	/usr/local/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x59
goroutine 1 [chan receive]:
testing.RunTests(0x9182f0, 0x13c7e60, 0x36, 0x36, 0xc208086101)
	/usr/local/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc20805e0f0, 0x13d22c0)
	/usr/local/go/src/testing/testing.go:485 +0xe1
main.main()
	github.com/coreos/etcd/client/_test/_testmain.go:216 +0x382
goroutine 13 [chan receive]:
github.com/coreos/etcd/client.(*simpleHTTPClient).Do(0xc208064180, 0x7f1fd3ca71c0, 0xc20805c680, 0x7f1fd3ca7140, 0x13d2cd8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/coreos/etcd/client/_test/_obj_test/client.go:297 +0xe98
github.com/coreos/etcd/client.TestSimpleHTTPClientDoCancelContextResponseBodyClosed(0xc208084360)
	/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/client/client_test.go:214 +0x762
testing.tRunner(0xc208084360, 0x13c7ea8)
	/usr/local/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xd4e
goroutine 14 [chan receive]:
github.com/coreos/etcd/client.func·008()
	/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/client/client_test.go:208 +0x83
created by github.com/coreos/etcd/client.TestSimpleHTTPClientDoCancelContextResponseBodyClosed
	/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/client/client_test.go:212 +0x6ed
goroutine 15 [chan receive]:
github.com/coreos/etcd/client.(*fakeTransport).RoundTrip(0xc20800a660, 0xc20801ec30, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/client/client_test.go:118 +0x247
github.com/coreos/etcd/client.func·003()
	github.com/coreos/etcd/client/_test/_obj_test/client.go:280 +0xca
created by github.com/coreos/etcd/client.(*simpleHTTPClient).Do
	github.com/coreos/etcd/client/_test/_obj_test/client.go:283 +0x3f6
```

**Comment by yichengq** [comment]
duplicated with #2449
