### ISSUE TITLE
etcd2 panic - "rafthttp: unexpected removal of unknown peer"

### ISSUE THREAD

**Issue by seanmcgary** [coreos/etcd#3106]
Ran across this yesterday as I was testing a new etcd2 cluster. It panicked, but seems to have recovered itself after restarting. If you guys need any additional information, just let me know and I can try to pull it for you.

- CoreOS beta version 717.1.0
- etcd v2.0.12

```
Jul 07 05:58:09 10.0.0.10 systemd[1]: Starting etcd2...
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcd: listening for peers on http://10.0.0.10:2380
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcd: listening for peers on http://10.0.0.10:7001
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcd: listening for client requests on http://0.0.0.0:2379
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcd: listening for client requests on http://0.0.0.0:4001
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: datadir is valid for the 2.0.1 format
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: name = replacement
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: data dir = /var/lib/etcd2
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: member dir = /var/lib/etcd2/member
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: heartbeat = 100ms
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: election = 1200ms
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: snapshot count = 10000
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: advertise client URLs = http://54.0.0.87:2379
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: start member a4763e447530a34c in cluster 13801021d3b5070a
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c became follower at term 0
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: newRaft a4763e447530a34c [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c became follower at term 1
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c [term: 1] received a MsgHeartbeat message with higher term from f97375ba307d2a72 [term: 111]
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c became follower at term 111
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft.node: a4763e447530a34c elected leader f97375ba307d2a72 at term 111
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c [logterm: 0, index: 42916] rejected msgApp [logterm: 111, index: 42916] from f97375ba307d2a72
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c [commit: 0, lastindex: 0, lastterm: 0] starts to restore snapshot [index: 40005, term: 111]
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raftlog: log [committed=1, applied=0, unstable.offset=0, len(unstable.Entries)=0] starts to restore snapshot [index: 40005, term: 111]
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c restored progress of 3ab7e7180c8048e [next = 40006, match = 0, wait = 0]
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c restored progress of 5b0b9473a49ec5b1 [next = 40006, match = 0, wait = 0]
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c restored progress of ca4106e8dd9184c0 [next = 40006, match = 0, wait = 0]
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c restored progress of d72eefae0aaea811 [next = 40006, match = 0, wait = 0]
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c restored progress of f97375ba307d2a72 [next = 40006, match = 0, wait = 0]
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 raft: a4763e447530a34c [commit: 0] restored snapshot [index: 40005, term: 111]
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: saved incoming snapshot at index 40005
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 rafthttp: starting client stream to f97375ba307d2a72 at term 111
Jul 07 05:58:09 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:09 etcdserver: recovered from incoming snapshot at index 40005
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:10 raft: a4763e447530a34c [commit: 40005] ignored snapshot [index: 40005, term: 111]
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:10 rafthttp: unexpected removal of unknown peer '14573937466367116480'
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:10 rafthttp: encountered error reading the client log stream: read tcp 54.151.9.49:2380: use of closed network connection
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: 2015/07/07 05:58:10 rafthttp: client streaming to f97375ba307d2a72 at term 111 has been stopped
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: panic: rafthttp: unexpected removal of unknown peer '14573937466367116480'
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: goroutine 27 [running]:
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: log.Panicf(0x8db2f0, 0x31, 0xc20822b4f8, 0x1, 0x1)
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: /usr/lib/go/src/log/log.go:314 +0xd0
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: github.com/coreos/etcd/rafthttp.(*transport).removePeer(0xc208089960, 0xca4106e8dd9184c0)
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.0.10/work/gopath/src/github.com/coreos/etcd/rafthttp/transport.go:152 +0x1c3
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: github.com/coreos/etcd/rafthttp.(*transport).RemovePeer(0xc208089960, 0xca4106e8dd9184c0)
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.0.10/work/gopath/src/github.com/coreos/etcd/rafthttp/transport.go:136 +0x77
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: github.com/coreos/etcd/etcdserver.(*EtcdServer).applyConfChange(0xc208068200, 0x8e4e6618b063c0eb, 0x1, 0xca4106e8dd9184c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.0.10/work/gopath/src/github.com/coreos/etcd/etcdserver/server.go:795 +0x81e
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0xc208068200, 0xc20819c048, 0x1a35, 0x1a37, 0xc2080ae060, 0x0, 0x0)
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.0.10/work/gopath/src/github.com/coreos/etcd/etcdserver/server.go:699 +0x399
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc208068200)
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.0.10/work/gopath/src/github.com/coreos/etcd/etcdserver/server.go:430 +0xf4c
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.0.10/work/gopath/src/github.com/coreos/etcd/etcdserver/server.go:298 +0x294
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: goroutine 1 [runnable]:
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: github.com/coreos/etcd/etcdmain.Main()
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.0.10/work/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:102 +0x9f7
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: main.main()
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.0.10/work/gopath/src/github.com/coreos/etcd/main.go:29 +0x1b
Jul 07 05:58:10 10.0.0.10 etcd2[3099]: goroutine 5 [syscall]:
Jul 07 05:58:10 10.0.0.10 systemd[1]: etcd2.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 07 05:58:10 10.0.0.10 systemd[1]: etcd2.service: Unit entered failed state.
Jul 07 05:58:10 10.0.0.10 systemd[1]: etcd2.service: Failed with result 'exit-code'.
Jul 07 05:58:20 10.0.0.10 systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Jul 07 05:58:20 10.0.0.10 systemd[1]: Started etcd2.
Jul 07 05:58:20 10.0.0.10 systemd[1]: Starting etcd2...
Jul 07 05:58:20 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:20 etcd: already initialized as member before, starting as etcd member...
Jul 07 05:58:20 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:20 etcd: listening for peers on http://10.0.0.10:2380
Jul 07 05:58:20 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:20 etcd: listening for peers on http://10.0.0.10:7001
Jul 07 05:58:20 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:20 etcd: listening for client requests on http://0.0.0.0:2379
Jul 07 05:58:20 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:20 etcd: listening for client requests on http://0.0.0.0:4001
Jul 07 05:58:20 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:20 etcdserver: datadir is valid for the 2.0.1 format
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: recovered store from snapshot at index 40005
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: name = replacement
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: data dir = /var/lib/etcd2
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: member dir = /var/lib/etcd2/member
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: heartbeat = 100ms
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: election = 1200ms
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: snapshot count = 10000
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: advertise client URLs = http://54.0.0.87:2379
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: loaded cluster information from store: 1c2bf88cf8ba413593ebca7d2986f739=http://54.176.252.131:2380,828ef046b2054630a7fade8645fbab49=http://54.176.217.150:2380,=http://54.0.0.87:2380,c18ba4b5d4224e9189b99d898e17e57f=http://54.151.9.49:2380,f1e5e033166a43b4ad9ae729e2beea88=http://54.219.49.11:2380
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: restart member a4763e447530a34c in cluster 13801021d3b5070a at commit index 46714
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 raft: a4763e447530a34c became follower at term 111
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 raft: newRaft a4763e447530a34c [peers: [3ab7e7180c8048e,5b0b9473a49ec5b1,ca4106e8dd9184c0,d72eefae0aaea811,f97375ba307d2a72], term: 111, commit: 46714, applied: 40005, lastindex: 46714, lastterm: 111]
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 raft.node: a4763e447530a34c elected leader f97375ba307d2a72 at term 111
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: removed member ca4106e8dd9184c0 from cluster 13801021d3b5070a
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: added local member a4763e447530a34c [http://54.0.0.87:2380] to cluster 13801021d3b5070a
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 raft: a4763e447530a34c [logterm: 0, index: 46740] rejected msgApp [logterm: 111, index: 46740] from f97375ba307d2a72
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 raft: a4763e447530a34c [logterm: 0, index: 46741] rejected msgApp [logterm: 111, index: 46741] from f97375ba307d2a72
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 raft: a4763e447530a34c [logterm: 0, index: 46741] rejected msgApp [logterm: 111, index: 46741] from f97375ba307d2a72
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 raft: a4763e447530a34c [logterm: 0, index: 46741] rejected msgApp [logterm: 111, index: 46741] from f97375ba307d2a72
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 raft: a4763e447530a34c [logterm: 0, index: 46741] rejected msgApp [logterm: 111, index: 46741] from f97375ba307d2a72
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 rafthttp: starting client stream to f97375ba307d2a72 at term 111
Jul 07 05:58:21 10.0.0.10 etcd2[3107]: 2015/07/07 05:58:21 etcdserver: published {Name:replacement ClientURLs:[http://54.0.0.87:2379]} to cluster 13801021d3b5070a
Jul 07 06:13:23 10.0.0.10 etcd2[3107]: 2015/07/07 06:13:23 rafthttp: client streaming to f97375ba307d2a72 at term 111 has been stopped
```

**Comment by yichengq** [comment]
Actually you are running etcd 2.0.10 from the panic log. This is an known bug that has been fixed in 2.0.11(https://github.com/coreos/etcd/releases/tag/v2.0.11). If you upgrade to the latest etcd, it will not have this problem.

Thanks for reporting!
