### ISSUE TITLE
unexpected output for "etcdctl -h | grep --"

### ISSUE THREAD

**Issue by gouyang** [coreos/etcd#3140]
```
$ ./etcdctl -h | grep --peers
grep: unrecognized option '--peers'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
panic: template: help:1:0: executing "help" at <NAME:
   >: write /dev/stdout: broken pipe

goroutine 1 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.printHelp(0xdd5a90, 0x1e7, 0xb77660, 0xc2080d0240)
	/home/guohua/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/help.go:167 +0x358
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.ShowAppHelp(0xc20815c4d0)
	/home/guohua/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/help.go:103 +0x59
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.checkHelp(0xc20815c4d0, 0xc20815c400)
	/home/guohua/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/help.go:183 +0x89
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc2080d0240, 0xc20800a380, 0x2, 0x2, 0x0, 0x0)
	/home/guohua/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:105 +0x842
main.main()
	/home/guohua/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdctl/main.go:62 +0x18c8

goroutine 5 [chan receive]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0x106bc80)
	/home/guohua/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.init.1
	/home/guohua/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 12 [syscall]:
os/signal.loop()
	/home/guohua/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/guohua/go1.5/src/os/signal/signal_unix.go:28 +0x37
```
```
$ ./etcdctl -v
etcdctl version 2.1.0-rc.0+git
```

test with other program, docker for example, no such issue
```
$ docker -h | grep --peers
grep: unrecognized option '--peers'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```

**Comment by gouyang** [comment]
etcd works well too.
```
$ etcd -h | grep --peers
grep: unrecognized option '--peers'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```

**Comment by yichengq** [comment]
This happens because our codegangsta/cli dependency panics if write fails. will fix.

**Comment by gouyang** [comment]
is it okay just to print the error?

**Comment by xiang90** [comment]
@yichengq If this is a dependency issue, can you please open an issue in the dependency repo and refer it here? Thanks!

**Comment by yichengq** [comment]
Close this because we have submitted the upstream issue and will track this problem in that issue.
