### ISSUE TITLE
Cannot repair EOF wal created under 2.0.11

### ISSUE THREAD

**Issue by sdodson** [coreos/etcd#3186]
I'm not certain this is expected to work or not, however I have a number of corrupt wal files due to various crashes and no space on device issues, all of which were created by etcd 2.0.11. I was hoping to repair them by running etcd 2.1 against them however that fails with the following.

Is WAL repair only expected to work on files created under etcd 2.1?
Here's an archive of the data directory if you'd like to look at it http://sdodson.fedorapeople.org/wal-eof.tar.gz

```
$ etcd-v2.1.1-linux-amd64/etcd --data-dir var/lib/openshift/openshift.local.etcd/member                                                                                                                                                         
2015/07/27 16:25:18 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
2015/07/27 16:25:18 etcdmain: found invalid file/dir snap under data dir var/lib/openshift/openshift.local.etcd/member (Ignore this if you are upgrading etcd)
2015/07/27 16:25:18 etcdmain: found invalid file/dir wal under data dir var/lib/openshift/openshift.local.etcd/member (Ignore this if you are upgrading etcd)
2015/07/27 16:25:18 etcdmain: listening for peers on http://localhost:2380
2015/07/27 16:25:18 etcdmain: listening for peers on http://localhost:7001
2015/07/27 16:25:18 etcdmain: listening for client requests on http://localhost:2379
2015/07/27 16:25:18 etcdmain: listening for client requests on http://localhost:4001
2015/07/27 16:25:18 etcdserver: recovered store from snapshot at index 30003
2015/07/27 16:25:18 etcdserver: name = default
2015/07/27 16:25:18 etcdserver: data dir = var/lib/openshift/openshift.local.etcd/member
2015/07/27 16:25:18 etcdserver: member dir = var/lib/openshift/openshift.local.etcd/member/member
2015/07/27 16:25:18 etcdserver: heartbeat = 100ms
2015/07/27 16:25:18 etcdserver: election = 1000ms
2015/07/27 16:25:18 etcdserver: snapshot count = 10000
2015/07/27 16:25:18 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/07/27 16:25:18 etcdserver: loaded cluster information from store: <nil>
2015/07/27 16:25:18 wal: repairing var/lib/openshift/openshift.local.etcd/member/member/wal/0000000000000003-0000000000007534.wal
2015/07/27 16:25:18 etcdserver: repaired WAL error (unexpected EOF)
2015/07/27 16:25:18 wal: ignored file 0000000000000003-0000000000007534.wal.broken in wal
2015/07/27 16:25:18 etcdserver: restarting member 2d2799920762340b in cluster 9167b744a00ddfe7 at commit index 34642
2015/07/27 16:25:18 raft: 2d2799920762340b state.commit 34642 is out of range [30003, 34641]
panic: 2d2799920762340b state.commit 34642 is out of range [30003, 34641]

goroutine 1 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc2080cb4c0, 0xa28810, 0x2b, 0xc208b93000, 0x4, 0x4)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x185
github.com/coreos/etcd/raft.(*raft).loadState(0xc20811c000, 0x6, 0x2d2799920762340b, 0x8752, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:759 +0x27b
github.com/coreos/etcd/raft.newRaft(0xc20971ec00, 0x40a1d3)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:194 +0x707
github.com/coreos/etcd/raft.RestartNode(0xc20971ec00, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:187 +0x4b
github.com/coreos/etcd/etcdserver.restartNode(0xc20811c0c0, 0xc2080621b0, 0x29, 0xc20918f210, 0x0, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:261 +0x6ca
github.com/coreos/etcd/etcdserver.NewServer(0xc20811c0c0, 0xc2080623f0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:278 +0x297d
github.com/coreos/etcd/etcdmain.startEtcd(0xc20806ad80, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:203 +0x1446
github.com/coreos/etcd/etcdmain.Main()
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:100 +0x8b2
main.main()
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x1b

goroutine 13 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 19 [chan receive]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0xc4aee0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.init·1
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7
```

**Comment by yichengq** [comment]
etcd2.1 includes both repair code and the patch to generate WAL that could be repaired by this repair code. So this is not a problem/bug in etcd2.1.

If the data is important, I could help to generate loadable WAL that has the same data in your data dir. Sorry for the inconvenience.

> a number of corrupt wal files due to various crashes and no space on device issues, all of which were created by etcd 2.0.11.

I suppose 2.0.11 will fatal when there is one corrupt wal file. Are these corrupt wal files from different members?

**Comment by sdodson** [comment]
Its across a few different failure scenarios. Out of disk space, panics,
etc.

The tarball is just from a test environment, no need to try to recover it.

**Comment by yichengq** [comment]
@sdodson That makes sense.

You could expect that 2.1 will repair corrupt wal files in all these situations.

Thanks for reporting.
