### ISSUE TITLE
etcd v2.1.1 panic on etcdctl exec-watch and node reboot

### ISSUE THREAD

**Issue by kayrus** [coreos/etcd#3213]
OS: fresh install, three nodes in cluster CoreOS alpha (758.1.0)
etcd:

```
etcd2 --version
etcd Version: 2.1.1
Git SHA: 6335fdc
Go Version: go1.4.2
Go OS/Arch: linux/amd64
```

steps to reproduce:

```sh
coreos1: etcdctl exec-watch --recursive /foo-service -- sh -c 'echo "\"$ETCD_WATCH_KEY\" key was updated to \"$ETCD_WATCH_VALUE\" value by \"$ETCD_WATCH_ACTION\" action"'
coreos2: etcdctl mkdir /foo-service && while true; do etcdctl set /foo-service/123 'dfsdfdsfdsfdsf'; sleep 1; done
coreos3: sudo reboot
```

As a result you will see the following output:

```sh
etcd output:


core@coreos1 ~ $ etcdctl exec-watch --recursive /foo-service -- sh -c 'echo "\"$ETCD_WATCH_KEY\" key was updated to \"$ETCD_WATCH_VALUE\" value by \"$ETCD_WATCH_ACTION\" action"'
"/foo-service" key was updated to "" value by "create" action
"/foo-service/123" key was updated to "dfsdfdsfdsfdsf" value by "set" action
"/foo-service/123" key was updated to "dfsdfdsfdsfdsf" value by "set" action
"/foo-service/123" key was updated to "dfsdfdsfdsfdsf" value by "set" action
"/foo-service/123" key was updated to "dfsdfdsfdsfdsf" value by "set" action
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x459023]

goroutine 1 [running]:
github.com/coreos/etcd/etcdctl/command.environResponse(0x0, 0xc2081909a0, 0x16, 0x16, 0x0, 0x0, 0x0)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/etcdctl/command/exec_watch_command.go:111 +0x643
github.com/coreos/etcd/etcdctl/command.execWatchCommandFunc(0xc2080cd810, 0xc2080685a0, 0x5, 0x0, 0x0)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/etcdctl/command/exec_watch_command.go:87 +0x6cb
github.com/coreos/etcd/etcdctl/command.rawhandle(0xc2080cd810, 0xd38388, 0x4, 0x0, 0x0)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:105 +0x65d
github.com/coreos/etcd/etcdctl/command.handlePrint(0xc2080cd810, 0xd38388, 0xd38438)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:111 +0x32
github.com/coreos/etcd/etcdctl/command.handleKey(0xc2080cd810, 0xd38388)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:144 +0x3e
github.com/coreos/etcd/etcdctl/command.func·001(0xc2080cd810)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/etcdctl/command/exec_watch_command.go:39 +0x34
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0xbda310, 0xa, 0x0, 0x0, 0xca4610, 0x2e, 0x0, 0x0, 0x0, 0x0, ...)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:101 +0xe42
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc2080c6000, 0xc20800a000, 0x8, 0x8, 0x0, 0x0)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:125 +0xb70
main.main()
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/etcdctl/main.go:62 +0xf13

goroutine 12 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [chan receive]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0xfad720)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.init·1
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 33 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 22 [chan receive]:
github.com/coreos/etcd/etcdctl/command.func·002()
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/etcdctl/command/exec_watch_command.go:76 +0x48
created by github.com/coreos/etcd/etcdctl/command.execWatchCommandFunc
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.1/work/gopath/src/github.com/coreos/etcd/etcdctl/command/exec_watch_command.go:79 +0x536

goroutine 20 [IO wait]:
net.(*pollDesc).Wait(0xc208010c30, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010c30, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010bd0, 0xc2080ff000, 0x1000, 0x1000, 0x0, 0x7f535ba38e08, 0xc20802bfe0)
        /usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802e080, 0xc2080ff000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f535ba3b118, 0xc20802e080, 0xc2080cd918, 0xc2080ff000, 0x1000, 0x1000, 0x9f19e0, 0x0, 0x0)
        /usr/lib/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080b3560, 0xc2080ff000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208052780)
        /usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208052780, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2080cd8c0)
        /usr/lib/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:660 +0xc9f

goroutine 21 [select]:
net/http.(*persistConn).writeLoop(0xc2080cd8c0)
        /usr/lib/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:661 +0xcbc

goroutine 28 [runnable]:
net/http.(*persistConn).writeLoop(0xc2080cdad0)
        /usr/lib/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by kayrus** [comment]
Same issue from another user: https://gist.github.com/cornelius-keller/00f9bf4b4669fd066f45

**Comment by yichengq** [comment]
@kayrus We just refactor to use etcd/client after release 2.1. I reproduced it on the 2.1 successfully, and also found that the problem has been fixed in the master. Could you give it another test?

**Comment by xiang90** [comment]
@kayrus Can you give current master a try?

**Comment by kayrus** [comment]
will try on monday

**Comment by kayrus** [comment]
Fixed. But every host reboot adds ~10 sec timeout:

```sh
$ while true; do ./etcdctl set /foo-service/123 "`date`"; sleep 1; done
Mon Aug 10 14:25:50 UTC 2015
Mon Aug 10 14:25:51 UTC 2015
Mon Aug 10 14:25:53 UTC 2015 - reboot has been started
Mon Aug 10 14:26:00 UTC 2015
Mon Aug 10 14:26:01 UTC 2015
Mon Aug 10 14:26:03 UTC 2015
```

**Comment by xiang90** [comment]
@kayrus I am closing this one. You can create another issue with detailed information for the new problem you met.
