### ISSUE TITLE
etcdctl backup can't be restored from (v2.0.12)

### ISSUE THREAD

**Issue by a-robinson** [coreos/etcd#3298]
I'm trying to test out backup and restore on release version 2.0.12, which is what Kubernetes currently uses. As best I can tell, I'm completely unable to restore data that was backed up using `etcdctl backup` from a running etcd container on a Kubernetes master.

Here's one way to reproduce, running as root on a running Kubernetes master:
```shell
etcdctl backup --data-dir /mnt/master-pd/var/etcd/data --backup-dir /var/tmp/backup
docker run -it -v /var/tmp/backup:/var/etcd/data gcr.io/google_containers/etcd:2.0.12 /bin/sh -c "/usr/local/bin/etcd --addr 127.0.0.1:4001 --bind-addr 127.0.0.1:4001 --data-dir /var/etcd/data --force-new-cluster"
```

The flags are the same used to run etcd in Kubernetes normally, with the `--force-new-cluster` flag added. When I do this, I get the following stack trace:

```console
# docker run -it -v /var/tmp/backup:/var/etcd/data gcr.io/google_containers/etcd:2.0.12 /bin/sh -c "/usr/local/bin/etcd --addr 127.0.0.1:4001 --bind-addr 127.0.0.1:4001 --data-dir /var/etcd/data --force-new-cluster"
2015/08/14 16:59:44 etcd: already initialized as member before, starting as etcd member...
2015/08/14 16:59:44 etcd: listening for peers on http://localhost:2380
2015/08/14 16:59:44 etcd: listening for peers on http://localhost:7001
2015/08/14 16:59:44 etcd: listening for client requests on http://127.0.0.1:4001
2015/08/14 16:59:44 etcdserver: datadir is valid for the 2.0.1 format
2015/08/14 16:59:44 etcdserver: recovered store from snapshot at index 180018
2015/08/14 16:59:44 etcdserver: name = default
2015/08/14 16:59:44 etcdserver: force new cluster
2015/08/14 16:59:44 etcdserver: data dir = /var/etcd/data
2015/08/14 16:59:44 etcdserver: member dir = /var/etcd/data/member
2015/08/14 16:59:44 etcdserver: heartbeat = 100ms
2015/08/14 16:59:44 etcdserver: election = 1000ms
2015/08/14 16:59:44 etcdserver: snapshot count = 10000
2015/08/14 16:59:44 etcdserver: advertise client URLs = http://127.0.0.1:4001
2015/08/14 16:59:44 etcdserver: loaded cluster information from store: default=http://localhost:2380,default=http://localhost:7001
2015/08/14 16:59:44 etcdserver: forcing restart of member 4f2d2716140001 in cluster 4f2d2716140002 at commit index 2
2015/08/14 16:59:44 raft: 4f2d2716140001 state.commit 2 is out of range [180018, 180018]
panic: raft: 4f2d2716140001 state.commit 2 is out of range [180018, 180018]

goroutine 1 [running]:
log.Panicf(0x8d9990, 0x31, 0xc2088ae8d8, 0x4, 0x4)
	/usr/local/go/src/log/log.go:314 +0xd0
github.com/coreos/etcd/raft.(*raft).loadState(0xc20803ae70, 0x0, 0x0, 0x2, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:680 +0x283
github.com/coreos/etcd/raft.newRaft(0x4f2d2716140001, 0xc208032ad0, 0x1, 0x1, 0xa, 0x1, 0x7f3727dcdb00, 0xc2088c62a0, 0x0, 0xc208b66300)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:172 +0x552
github.com/coreos/etcd/raft.RestartNode(0x4f2d2716140001, 0xa, 0x1, 0x7f3727dcdb00, 0xc2088c62a0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:178 +0xff
github.com/coreos/etcd/etcdserver.restartAsStandaloneNode(0xc20803a210, 0xc208072120, 0xc2088af3e8, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:158 +0xa51
github.com/coreos/etcd/etcdserver.NewServer(0xc20803a210, 0xc2080723f0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:232 +0x2731
github.com/coreos/etcd/etcdmain.startEtcd(0xc208082000, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:186 +0x13b9
github.com/coreos/etcd/etcdmain.Main()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:85 +0x626
main.main()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x1b

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35
```

@xiang90

**Comment by a-robinson** [comment]
Interestingly, if I just do a raw directory copy instead of an etcdctl backup, things actually work properly:
```console
$ cp -r /mnt/master-pd/var/etcd/data /var/tmp/backup
$ docker run -it -v /var/tmp/backup:/var/etcd/data gcr.io/google_containers/etcd:2.0.12 /bin/sh -c "/usr/local/bin/etcd --addr 127.0.0.1:4001 --bind-addr 127.0.0.1:4001 --data-dir /var/etcd/data --force-new-cluster"
2015/08/14 17:03:42 etcd: already initialized as member before, starting as etcd member...
2015/08/14 17:03:42 etcd: listening for peers on http://localhost:2380
2015/08/14 17:03:42 etcd: listening for peers on http://localhost:7001
2015/08/14 17:03:42 etcd: listening for client requests on http://127.0.0.1:4001
2015/08/14 17:03:42 etcdserver: datadir is valid for the 2.0.1 format
2015/08/14 17:03:42 etcdserver: recovered store from snapshot at index 180018
2015/08/14 17:03:42 etcdserver: name = default
2015/08/14 17:03:42 etcdserver: force new cluster
2015/08/14 17:03:42 etcdserver: data dir = /var/etcd/data
2015/08/14 17:03:42 etcdserver: member dir = /var/etcd/data/member
2015/08/14 17:03:42 etcdserver: heartbeat = 100ms
2015/08/14 17:03:42 etcdserver: election = 1000ms
2015/08/14 17:03:42 etcdserver: snapshot count = 10000
2015/08/14 17:03:42 etcdserver: advertise client URLs = http://127.0.0.1:4001
2015/08/14 17:03:42 etcdserver: loaded cluster information from store: default=http://localhost:2380,default=http://localhost:7001
2015/08/14 17:03:42 etcdserver: forcing restart of member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit index 182802
2015/08/14 17:03:42 raft: ce2a822cea30bfca became follower at term 4
2015/08/14 17:03:42 raft: newRaft ce2a822cea30bfca [peers: [ce2a822cea30bfca], term: 4, commit: 182802, applied: 180018, lastindex: 182802, lastterm: 4]
2015/08/14 17:03:44 raft: ce2a822cea30bfca is starting a new election at term 4
2015/08/14 17:03:44 raft: ce2a822cea30bfca became candidate at term 5
2015/08/14 17:03:44 raft: ce2a822cea30bfca received vote from ce2a822cea30bfca at term 5
2015/08/14 17:03:44 raft: ce2a822cea30bfca became leader at term 5
2015/08/14 17:03:44 raft.node: ce2a822cea30bfca elected leader ce2a822cea30bfca at term 5
2015/08/14 17:03:44 etcdserver: published {Name:default ClientURLs:[http://127.0.0.1:4001]} to cluster 7e27652122e8b2ae
```

**Comment by a-robinson** [comment]
And so you don't have to look it up, the gcr.io/google_containers/etcd image is simply the etcd and etcdctl binaries copied from the official release tar into a busybox image: https://github.com/kubernetes/kubernetes/tree/master/cluster/images/etcd

**Comment by yichengq** [comment]
@a-robinson We have fixed some related bugs in 2.1. I could reproduce the bug in 2.0, while etcd 2.1 works well in this scenario. Could you give 2.1 a try?

**Comment by xiang90** [comment]
@yichengq Can you please point out which pr fixed the issue?

**Comment by yichengq** [comment]
@xiang90 This is the original issue: https://github.com/coreos/etcd/issues/2664

**Comment by a-robinson** [comment]
Thank you @yichengq!

I'd tried restoring the backup using the 2.1 and 2.2 versions of etcd, but hadn't tried doing the backup with a different version of etcdctl. Doing the backup with etcdctl v2.1.1 works, allowing etcd v2.0.12 to be started from the backup. Are you aware of any incompatibilities we may run into from backing up and restoring data from etcd 2.0.12, only using 2.1.1 for etcdctl?

**Comment by yichengq** [comment]
I would recommend to use etcd 2.1 too. We verified WAL functionality using functional testing in 2.1, and made some patches to let it support to repair last-entry-broken WAL, then fix backup command based on these changes.

**Comment by a-robinson** [comment]
The kubernetes 1.0 branch would need a *very* good justification for bumping the minor version of etcd that it's on due to expectations around the size and stability of patches, so production instances are going to be stuck on 2.0.12 (or at least a 2.0.x patch) until we cut kubernetes 1.1 (probably in October).

If you're able to check the incompatibilities a little more, that'd be very helpful to us!

**Comment by xiang90** [comment]
@yichengq Can you help to check? Thanks a lot.

**Comment by yichengq** [comment]
I have checked the patch for this issue and related codes. I think using etcdctl 2.1.1 could work as a good solution for it.

**Comment by xiang90** [comment]
@yichengq Thanks!

@a-robinson I think this issue is fully resolved. Thanks for reporting!

**Comment by a-robinson** [comment]
Thank you!
