### ISSUE TITLE
Can't simultaneously run github 2.1.1 tag with 2.2.0 tag

### ISSUE THREAD

**Issue by dannysauer** [coreos/etcd#3551]
Adding a 2.2.0 node to an existing 2.1.1 cluster caused all of the 2.1.1 nodes to immediately exit, which is inconvenient. :)

Steps to reproduce:

Start 2-node 2.1.1 cluster like this:
```shell
/srv/etcd/bin_2.1.1/etcd \
  --name one \
  --data-dir /tmp/etcd1 \
  --listen-peer-urls   "http://$(hostname -s):2380" \
  --listen-client-urls "http://localhost:2379,http://$(hostname -s):2379" \
  --advertise-client-urls "http://$(hostname -s):2379" \
  --initial-cluster "one=http://$(hostname -s):2380,two=http://$(hostname -s):2378" \
  --initial-advertise-peer-urls "http://$(hostname -s):2380"


/srv/etcd/bin_2.1.1/etcd \
  --name two \
  --data-dir /tmp/etcd2 \
  --listen-peer-urls   "http://$(hostname -s):2378" \
  --listen-client-urls "http://localhost:2377,http://$(hostname -s):2377" \
  --advertise-client-urls "http://$(hostname -s):2377" \
  --initial-cluster "one=http://$(hostname -s):2380,two=http://$(hostname -s):2378" \
  --initial-advertise-peer-urls "http://$(hostname -s):2378"
```

Shut down one of the nodes and restart with the two "initial" args removed, and it works fine.  As soon as I replace it with a 2.2.0 binary, though - like this:
```shell
    /srv/etcd/bin_2.2.0/etcd \
      --name one \
      --data-dir /tmp/etcd1 \
      --listen-peer-urls   "http://$(hostname -s):2380" \
      --listen-client-urls "http://localhost:2379,http://$(hostname -s):2379" \
      --advertise-client-urls "http://$(hostname -s):2379"
```

And the 2.1.1 node immediately fails.  Restarting the 2.1.1 node results in the same trace output, at the end of this message.  It should be noted that both binaries were compiled using a relatively older go from RHEL6:
```
$ go version
go version go1.4 linux/amd64
```

Here's the trace:

```
2015/09/17 08:15:30 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 8
2015/09/17 08:15:30 etcdmain: the server is already initialized as member before, starting as etcd member...
2015/09/17 08:15:30 etcdmain: listening for peers on http://redactedhostname:2378
2015/09/17 08:15:30 etcdmain: listening for client requests on http://localhost:2377
2015/09/17 08:15:30 etcdmain: listening for client requests on http://redactedhostname:2377
2015/09/17 08:15:30 etcdserver: name = two
2015/09/17 08:15:30 etcdserver: data dir = /tmp/etcd2
2015/09/17 08:15:30 etcdserver: member dir = /tmp/etcd2/member
2015/09/17 08:15:30 etcdserver: heartbeat = 100ms
2015/09/17 08:15:30 etcdserver: election = 1000ms
2015/09/17 08:15:30 etcdserver: snapshot count = 10000
2015/09/17 08:15:30 etcdserver: advertise client URLs = http://redactedhostname:2377
2015/09/17 08:15:30 etcdserver: restarting member 7bbbdb95dc1e9487 in cluster ad71625aeedbbe60 at commit index 753
2015/09/17 08:15:30 raft: 7bbbdb95dc1e9487 became follower at term 136
2015/09/17 08:15:30 raft: newRaft 7bbbdb95dc1e9487 [peers: [], term: 136, commit: 753, applied: 0, lastindex: 753, lastterm: 136]
2015/09/17 08:15:30 etcdserver: starting server... [version: 2.1.1, cluster version: to_be_decided]
2015/09/17 08:15:30 etcdserver: added member 4211eee9d7d937fd [http://redactedhostname:2380] to cluster ad71625aeedbbe60
2015/09/17 08:15:30 etcdserver: added local member 7bbbdb95dc1e9487 [http://redactedhostname:2378] to cluster ad71625aeedbbe60
2015/09/17 08:15:30 etcdserver: set the initial cluster version to 2.1.0
2015/09/17 08:15:30 flags: unmarshal should never fail (proto: wrong wireType = 2 for field ID)
2015/09/17 08:15:30 rafthttp: failed to dial 4211eee9d7d937fd on stream MsgApp v2 (net/http: request canceled while waiting for connection)
2015/09/17 08:15:30 rafthttp: failed to dial 4211eee9d7d937fd on stream Message (net/http: request canceled while waiting for connection)
panic: unmarshal should never fail (proto: wrong wireType = 2 for field ID)

goroutine 29 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc20801eb00, 0xa21190, 0x20, 0xc208177860, 0x1, 0x1)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x185
github.com/coreos/etcd/pkg/pbutil.MustUnmarshal(0x7fadf6b151a8, 0xc2086d1a20, 0xc208064c60, 0x88, 0x90)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/pbutil/pbutil.go:41 +0x134
github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0xc208001680, 0xc2082ac048, 0x2f1, 0x31b, 0xc208177c78, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:751 +0x246
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc208001680)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:469 +0xbaa
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:362 +0x3eb

goroutine 1 [runnable]:
github.com/coreos/etcd/etcdmain.Main()
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:124 +0xe47
main.main()
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/main.go:29 +0x1b

goroutine 13 [syscall]:
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 19 [chan receive]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0xc3fd60)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.init·1
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 30 [runnable]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).Do(0xc208001680, 0x7fadf6b14b80, 0xc20805b020, 0x874fdbdff1860001, 0x9825d0, 0x3, 0xc2081a0ed0, 0x26, 0xc2081aab80, 0x34, ...)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:544 +0x71e
github.com/coreos/etcd/etcdserver.(*EtcdServer).publish(0xc208001680, 0x12a05f200)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:706 +0x314
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:338 +0x4f

goroutine 31 [runnable]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0xc208001680)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:373 +0x49e
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:339 +0x69

goroutine 32 [runnable]:
github.com/coreos/etcd/etcdserver.monitorFileDescriptor(0xc20805ad80)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/metrics.go:80 +0x4d8
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:340 +0x8a

goroutine 33 [runnable]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).monitorVersions(0xc208001680)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:939 +0x3d9
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:341 +0xa4

goroutine 34 [runnable]:
github.com/coreos/etcd/etcdserver/etcdhttp.capabilityLoop(0xc208001680)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/etcdhttp/capability.go:52 +0x1ad
created by github.com/coreos/etcd/etcdserver/etcdhttp.NewClientHandler
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/etcdhttp/client.go:59 +0x58

goroutine 51 [runnable]:
net.(*pollDesc).Wait(0xc208116450, 0x77, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitWrite(0xc208116450, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:93 +0x43
net.(*netFD).connect(0xc2081163f0, 0x0, 0x0, 0x7fadf6b12ea8, 0xc2081a6ee0, 0xecd
8cd013, 0x317d505f, 0xc3fb40, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_unix.go:114 +0x24b
net.(*netFD).dial(0xc2081163f0, 0x7fadf6b12e58, 0x0, 0x7fadf6b12e58, 0xc2086cd71
0, 0xecd8cd013, 0x317d505f, 0xc3fb40, 0x0, 0x0)
        /usr/lib/golang/src/net/sock_posix.go:139 +0x37a
net.socket(0x98ee10, 0x3, 0x2, 0x1, 0x0, 0xc2086cd700, 0x7fadf6b12e58, 0x0, 0x7f
adf6b12e58, 0xc2086cd710, ...)
        /usr/lib/golang/src/net/sock_posix.go:91 +0x422
net.internetSocket(0x98ee10, 0x3, 0x7fadf6b12e58, 0x0, 0x7fadf6b12e58, 0xc2086cd
710, 0xecd8cd013, 0x317d505f, 0xc3fb40, 0x1, ...)
        /usr/lib/golang/src/net/ipsock_posix.go:137 +0x148
net.dialTCP(0x98ee10, 0x3, 0x0, 0xc2086cd710, 0xecd8cd013, 0x317d505f, 0xc3fb40,
 0xc2081896f8, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:156 +0x125
net.dialSingle(0x98ee10, 0x3, 0xc2081abc07, 0xd, 0x0, 0x0, 0x7fadf6b12df0, 0xc20
86cd710, 0xecd8cd013, 0x317d505f, ...)
        /usr/lib/golang/src/net/dial.go:235 +0x3f5
net.func·016(0xecd8cd013, 0xe317d505f, 0xc3fb40, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/dial.go:163 +0x12c
net.dial(0x98ee10, 0x3, 0x7fadf6b12df0, 0xc2086cd710, 0xc2080eda90, 0xecd8cd013,
 0xe317d505f, 0xc3fb40, 0x0, 0x0, ...)
        /usr/lib/golang/src/net/fd_unix.go:40 +0x6f
net.(*Dialer).Dial(0xc20804e4c0, 0x98ee10, 0x3, 0xc2081abc07, 0xd, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/dial.go:170 +0x4be
github.com/coreos/etcd/pkg/transport.(*rwTimeoutDialer).Dial(0xc20804e4b0, 0x98ee10, 0x3, 0xc2081abc07, 0xd, 0x0, 0x0, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_dialer.go:29 +0x9c
github.com/coreos/etcd/pkg/transport.*rwTimeoutDialer.Dial·fm(0x98ee10, 0x3, 0xc2081abc07, 0xd, 0x0, 0x0, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_transport.go:41 +0x79
net/http.(*Transport).dial(0xc2080643f0, 0x98ee10, 0x3, 0xc2081abc07, 0xd, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:479 +0x84
net/http.(*Transport).dialConn(0xc2080643f0, 0x0, 0xc2081abc00, 0x4, 0xc2081abc07, 0xd, 0xc208116380, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:564 +0x1678
net/http.func·019()
        /usr/lib/golang/src/net/http/transport.go:520 +0x42
created by net/http.(*Transport).getConn
        /usr/lib/golang/src/net/http/transport.go:522 +0x335

goroutine 37 [runnable]:
github.com/coreos/etcd/pkg/fileutil.func·001()
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:72 +0x658
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:78 +0x231

goroutine 38 [runnable]:
github.com/coreos/etcd/pkg/fileutil.func·001()
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:72 +0x658
created by github.com/coreos/etcd/pkg/fileutil.PurgeFile
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/fileutil/purge.go:78 +0x231

goroutine 59 [chan receive]:
net/http.func·016()
        /usr/lib/golang/src/net/http/transport.go:507 +0x65
created by net/http.func·017
        /usr/lib/golang/src/net/http/transport.go:513 +0xba

goroutine 60 [chan receive]:
net/http.func·016()
        /usr/lib/golang/src/net/http/transport.go:507 +0x65
created by net/http.func·017
        /usr/lib/golang/src/net/http/transport.go:513 +0xba

goroutine 52 [runnable]:
net.(*pollDesc).Wait(0xc2081165a0, 0x77, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitWrite(0xc2081165a0, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:93 +0x43
net.(*netFD).connect(0xc208116540, 0x0, 0x0, 0x7fadf6b12ea8, 0xc2081a6f20, 0xecd8cd013, 0x317f9f73, 0xc3fb40, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_unix.go:114 +0x24b
net.(*netFD).dial(0xc208116540, 0x7fadf6b12e58, 0x0, 0x7fadf6b12e58, 0xc2086cd740, 0xecd8cd013, 0x317f9f73, 0xc3fb40, 0x0, 0x0)
        /usr/lib/golang/src/net/sock_posix.go:139 +0x37a
net.socket(0x98ee10, 0x3, 0x2, 0x1, 0x0, 0xc2086cd700, 0x7fadf6b12e58, 0x0, 0x7fadf6b12e58, 0xc2086cd740, ...)
        /usr/lib/golang/src/net/sock_posix.go:91 +0x422
net.internetSocket(0x98ee10, 0x3, 0x7fadf6b12e58, 0x0, 0x7fadf6b12e58, 0xc2086cd740, 0xecd8cd013, 0xc2317f9f73, 0xc3fb40, 0x1, ...)
        /usr/lib/golang/src/net/ipsock_posix.go:137 +0x148
net.dialTCP(0x98ee10, 0x3, 0x0, 0xc2086cd740, 0xecd8cd013, 0x317f9f73, 0xc3fb40, 0xc20818a6f8, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:156 +0x125
net.dialSingle(0x98ee10, 0x3, 0xc2081abd07, 0xd, 0x0, 0x0, 0x7fadf6b12df0, 0xc2086cd740, 0xecd8cd013, 0x317f9f73, ...)
        /usr/lib/golang/src/net/dial.go:235 +0x3f5
net.func·016(0xecd8cd013, 0xe317f9f73, 0xc3fb40, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/dial.go:163 +0x12c
net.dial(0x98ee10, 0x3, 0x7fadf6b12df0, 0xc2086cd740, 0xc2086d9a90, 0xecd8cd013, 0xe317f9f73, 0xc3fb40, 0x0, 0x0, ...)
        /usr/lib/golang/src/net/fd_unix.go:40 +0x6f
net.(*Dialer).Dial(0xc20804e4c0, 0x98ee10, 0x3, 0xc2081abd07, 0xd, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/dial.go:170 +0x4be
github.com/coreos/etcd/pkg/transport.(*rwTimeoutDialer).Dial(0xc20804e4b0, 0x98ee10, 0x3, 0xc2081abd07, 0xd, 0x0, 0x0, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_dialer.go:29 +0x9c
github.com/coreos/etcd/pkg/transport.*rwTimeoutDialer.Dial·fm(0x98ee10, 0x3, 0xc2081abd07, 0xd, 0x0, 0x0, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_transport.go:41 +0x79
net/http.(*Transport).dial(0xc2080643f0, 0x98ee10, 0x3, 0xc2081abd07, 0xd, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:479 +0x84
net/http.(*Transport).dialConn(0xc2080643f0, 0x0, 0xc2081abd00, 0x4, 0xc2081abd07, 0xd, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/transport.go:564 +0x1678
net/http.func·019()
        /usr/lib/golang/src/net/http/transport.go:520 +0x42
created by net/http.(*Transport).getConn
        /usr/lib/golang/src/net/http/transport.go:522 +0x335

goroutine 56 [IO wait]:
net.(*pollDesc).Wait(0xc2081168b0, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081168b0, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208116850, 0x0, 0x7fadf6b10d10, 0xc20819fdd8)
        /usr/lib/golang/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20804c0f0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20804c0f0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:244 +0x4c
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc208031c30, 0x0, 0x0, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x71
net/http.(*Server).Serve(0xc2081a4f00, 0x7fadf6b13ec8, 0xc208031c30, 0x0, 0x0)
        /usr/lib/golang/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x7fadf6b13ec8, 0xc208031c30, 0x7fadf6b15418, 0xc2081a6e20, 0x0, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·006(0x7fadf6b13ec8, 0xc208031c30)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:229 +0x80
created by github.com/coreos/etcd/etcdmain.startEtcd
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:230 +0x1a79

goroutine 55 [IO wait]:
net.(*pollDesc).Wait(0xc2081167d0, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081167d0, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208116770, 0x0, 0x7fadf6b10d10, 0xc20819fda8)
        /usr/lib/golang/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20804c0c8, 0x1, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20804c0c8, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:244 +0x4c
github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc208124d60, 0x0, 0x0, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x7a
net/http.(*Server).Serve(0xc2081a4ea0, 0x7fadf6b13e90, 0xc208124d60, 0x0, 0x0)
        /usr/lib/golang/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x7fadf6b13e90, 0xc208124d60, 0x7fadf6b152f0, 0xc2086cd6b0, 0x45d964b800, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·005(0x7fadf6b13e90, 0xc208124d60)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:221 +0x5a
created by github.com/coreos/etcd/etcdmain.startEtcd
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:222 +0x1937

goroutine 57 [IO wait]:
net.(*pollDesc).Wait(0xc208116990, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208116990, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208116930, 0x0, 0x7fadf6b10d10, 0xc20819fe08)
        /usr/lib/golang/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20804c100, 0xc2081a6c07, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20804c100, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:244 +0x4c
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc208031d30, 0x0, 0x0, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x71
net/http.(*Server).Serve(0xc2081a4f60, 0x7fadf6b13ec8, 0xc208031d30, 0x0, 0x0)
        /usr/lib/golang/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x7fadf6b13ec8, 0xc208031d30, 0x7fadf6b15418, 0xc2081a6e20, 0x0, 0x0, 0x0)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x1be
github.com/coreos/etcd/etcdmain.func·006(0x7fadf6b13ec8, 0xc208031d30)
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:229 +0x80
created by github.com/coreos/etcd/etcdmain.startEtcd
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:230 +0x1a79

goroutine 58 [chan receive]:
github.com/coreos/etcd/pkg/osutil.func·001()
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:51 +0x68
created by github.com/coreos/etcd/pkg/osutil.HandleInterrupts
        /opt/security/src/danny/rpmbuild/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/pkg/osutil/interrupt_unix.go:72 +0x1f6
```

**Comment by yichengq** [comment]
Could you check your etcd 2.2.0 version through `etcd --version`? I think it is not the tagged version. For 2.2.0 log, it should print out version stuffs at the head:
```
2015-09-17 09:15:04.907222 I | etcdmain: etcd Version: 2.2.0
2015-09-17 09:15:04.907315 I | etcdmain: Git SHA: e4561dd
2015-09-17 09:15:04.907329 I | etcdmain: Go Version: go1.5
2015-09-17 09:15:04.907334 I | etcdmain: Go OS/Arch: darwin/amd64
```

**Comment by dannysauer** [comment]
Poop; you're right.
```
$ /srv/etcd/bin_2.2.0/etcd --version
etcd Version: 2.1.1+git
Git SHA: 668a8a8
Go Version: go1.4
Go OS/Arch: linux/amd64
```

I did this to build that...
```
$ git checkout v2.2.0
Note: checking out 'v2.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at e4561dd... *: bump to v2.2.0
```
Why would the revision tagged as v2.2.0 with a comment of "bump to v2.2.0" not result in a v2.2.0 binary? :)

**Comment by dannysauer** [comment]
...and why does the git sha in my binary not match the one git produced?  Hmm...

Ok, apparently the bin was already populated from the last time I build something in there, and the build script doesn't overwrite the old binaries there.  I guess that's a separate issue. :D

Removing bin/* and re-running ./build gave me this, which looks better.
```
$ /var/tmp/etcd-v2.2.0-linux-amd64/bin/etcd --version
etcd Version: 2.2.0
Git SHA: e4561dd
Go Version: go1.4
Go OS/Arch: linux/amd64
```

**Comment by xiang90** [comment]
@dannysauer Can you try to reproduce this issue with 2.2 version?

**Comment by dannysauer** [comment]
I'm making sure the rest of the git repo is clean (to avoid any other unexpected surprises) and rebuilding to do just that. :)

**Comment by xiang90** [comment]
@dannysauer Thanks a lot.

**Comment by dannysauer** [comment]
Once again, the issue was really my mistake. :)

Adding a 2.2.0 node to the cluster simply causes the existing (older) 2.1.1 node to emit the reasonable message:
```
2015/09/17 11:08:00 etcdserver: the etcd version 2.1.1 is not up-to-date
2015/09/17 11:08:00 etcdserver: member 7bbbdb95dc1e9487 has a higher version &{2.2.0 2.1.0}
2015/09/17 11:08:05 etcdserver: the etcd version 2.1.1 is not up-to-date
2015/09/17 11:08:05 etcdserver: member 7bbbdb95dc1e9487 has a higher version &{2.2.0 2.1.0}
```
and the cluster shows as healthy when checked with both the 2.2.0 and 2.1.1 etcdctl binaries.

It also works fine to inject the actual 2.2.0 into a cluster running that kinda broken 2.1.1 that I was using earlier.

Thanks for helping me identify a gap in my package build process. :D
