### ISSUE TITLE
Is the following wedged etcd data dir recoverable (2.0.11 ran out of disk, 2.1.1 can't load it)

### ISSUE THREAD

**Issue by smarterclayton** [coreos/etcd#3565]
A 2.0.11 etcd ran out of disk while writing.  In attempting to restart with etcd 2.1.1 (below) the panic is thrown.  Is the data directory recoverable via manual intervention?  Should 2.1 repair be able to open this file?

Can provide the dump on request.

```
$ etcd --data-dir /var/lib/openshift/openshift.local.etcd 
2015/09/21 14:03:44 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 2
2015/09/21 14:03:44 etcdmain: the server is already initialized as member before, starting as etcd member...
2015/09/21 14:03:44 etcdmain: listening for peers on http://localhost:2380
2015/09/21 14:03:44 etcdmain: listening for peers on http://localhost:7001
2015/09/21 14:03:44 etcdmain: listening for client requests on http://localhost:2379
2015/09/21 14:03:44 etcdmain: listening for client requests on http://localhost:4001
2015/09/21 14:03:45 etcdserver: recovered store from snapshot at index 7450763
2015/09/21 14:03:45 etcdserver: name = default
2015/09/21 14:03:45 etcdserver: data dir = /var/lib/openshift/openshift.local.etcd
2015/09/21 14:03:45 etcdserver: member dir = /var/lib/openshift/openshift.local.etcd/member
2015/09/21 14:03:45 etcdserver: heartbeat = 100ms
2015/09/21 14:03:45 etcdserver: election = 1000ms
2015/09/21 14:03:45 etcdserver: snapshot count = 10000
2015/09/21 14:03:45 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/09/21 14:03:45 etcdserver: loaded cluster information from store: <nil>
2015/09/21 14:03:45 etcdserver: restarting member 9b0323e8423efc26 in cluster ef68503b936e4155 at commit index 7453311
2015/09/21 14:03:45 raft: 9b0323e8423efc26 state.commit 7453311 is out of range [7450763, 7453310]
panic: 9b0323e8423efc26 state.commit 7453311 is out of range [7450763, 7453310]

goroutine 1 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc2080ab4e0, 0xa231b0, 0x2b, 0xc2081adb00, 0x4, 0x4)
	/builddir/build/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x185
github.com/coreos/etcd/raft.(*raft).loadState(0xc208034e40, 0xf, 0x9b0323e8423efc26, 0x71ba7f, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/raft/raft.go:759 +0x27b
github.com/coreos/etcd/raft.newRaft(0xc209a1f440, 0x40a433)
	/builddir/build/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/raft/raft.go:194 +0x707
github.com/coreos/etcd/raft.RestartNode(0xc209a1f440, 0x0, 0x0)
	/builddir/build/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/raft/node.go:187 +0x4b
github.com/coreos/etcd/etcdserver.restartNode(0xc208034000, 0xc20806e1b0, 0x29, 0xc20936d1d0, 0x0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:261 +0x6ca
github.com/coreos/etcd/etcdserver.NewServer(0xc208034000, 0xc20806e3f0, 0x0, 0x0)
	/builddir/build/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdserver/server.go:278 +0x297d
github.com/coreos/etcd/etcdmain.startEtcd(0xc208068d80, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:203 +0x1446
github.com/coreos/etcd/etcdmain.Main()
	/builddir/build/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:100 +0x8b2
main.main()
	/builddir/build/BUILD/etcd-2.1.1/gopath/src/github.com/coreos/etcd/main.go:37 +0xf9
```

**Comment by yichengq** [comment]
etcd2.1 includes both repair code and the patch to generate WAL that could be repaired by this repair code. So 2.0.11 corrupted log may not be recoverable by 2.1, and 2.1 log should always be recoverable.

We don't have official way to recover corrupted 2.0.11 data dir now.

**Comment by smarterclayton** [comment]
Ok, thanks.
