### ISSUE TITLE
Unable to retsart after disk-full

### ISSUE THREAD

**Issue by MikaelCluseau** [coreos/etcd#3591]
Hi,

I'm unable to restart a standalone etcd2 server after a disk full event on CoreOS stable 723.3.0. I upgraded CoreOS to the latest stable (766.3.0) as it has etcd 2.1 which should recovers from this. But it doesn't :(

```
etcdmain: etcd Version: 2.1.2
etcdmain: Git SHA: ff8d1ec
etcdmain: Go Version: go1.4.2
etcdmain: Go OS/Arch: linux/amd64
etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 8
etcdmain: the server is already initialized as member before, starting as etcd member...
etcdmain: listening for peers on http://10.100.0.1:2380
etcdmain: listening for peers on http://10.100.0.1:7001
etcdmain: listening for client requests on http://10.100.0.1:2379
etcdserver: recovered store from snapshot at index 18521854
etcdserver: name = ceph-1
etcdserver: data dir = /var/lib/etcd2
etcdserver: member dir = /var/lib/etcd2/member
etcdserver: heartbeat = 100ms
etcdserver: election = 1000ms
etcdserver: snapshot count = 10000
etcdserver: advertise client URLs = http://10.100.0.1:2379
etcdserver: loaded cluster information from store: <nil>
wal: ignored file 000000000000073c-00000000011a9eff.wal.broken in wal
etcdserver: restarting member d241f35f522492d6 in cluster c72546b08be501c5 at commit index 18523916
etcd2.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

The datadir is:
```
etcd2.bck/member/wal/000000000000073c-00000000011a9eff.wal
etcd2.bck/member/wal/000000000000073a-00000000011a50dd.wal
etcd2.bck/member/wal/0000000000000739-00000000011a29cc.wal
etcd2.bck/member/wal/0000000000000738-00000000011a02bb.wal
etcd2.bck/member/wal/000000000000073b-00000000011a77ee.wal
etcd2.bck/member/wal/000000000000073c-00000000011a9eff.wal.broken
etcd2.bck/member/snap/0000000000000004-00000000011a77ed.snap
etcd2.bck/member/snap/0000000000000004-00000000011a29cb.snap
etcd2.bck/member/snap/0000000000000004-00000000011a02ba.snap
etcd2.bck/member/snap/0000000000000004-00000000011a50dc.snap
etcd2.bck/member/snap/0000000000000004-00000000011a9efe.snap
```

I tried to backup the datadir which resulted in the following structure:
```
backup-etcd2/member/wal/0000000000000000-0000000000000000.wal
backup-etcd2/member/snap/0000000000000004-00000000011a9efe.snap
```

I then tried to start from this backup:
```
etcdmain: etcd Version: 2.1.2
etcdmain: Git SHA: ff8d1ec
etcdmain: Go Version: go1.4.2
etcdmain: Go OS/Arch: linux/amd64
etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 8
etcdmain: the server is already initialized as member before, starting as etcd member...
etcdmain: listening for peers on http://10.100.0.1:2380
etcdmain: listening for peers on http://10.100.0.1:7001
etcdmain: listening for client requests on http://10.100.0.1:2379
etcdserver: recovered store from snapshot at index 18521854
etcdserver: name = ceph-1
etcdserver: data dir = /var/lib/etcd2
etcdserver: member dir = /var/lib/etcd2/member
etcdserver: heartbeat = 100ms
etcdserver: election = 1000ms
etcdserver: snapshot count = 10000
etcdserver: advertise client URLs = http://10.100.0.1:2379
etcdserver: loaded cluster information from store: <nil>
etcdserver: restarting member 500168eda40001 in cluster 500168eda40002 at commit index 18523916
raft: 500168eda40001 state.commit 18523916 is out of range [18521854, 18523915]
etcd2.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

Is there a way to ignore this last raft log entry?

thanks.

**Comment by xiang90** [comment]
@MikaelCluseau You need to rename the wal file back to .wal. And restart etcd to see if it can be recovered or not.

**Comment by MikaelCluseau** [comment]
Thanks for the quick answer! Unfortunately, it didn't repair correctly:

```
wal: repairing /var/lib/etcd2/member/wal/000000000000073c-00000000011a9eff.wal
etcdserver: repaired WAL error (unexpected EOF)
wal: ignored file 000000000000073c-00000000011a9eff.wal.broken in wal
etcdserver: restarting member d241f35f522492d6 in cluster c72546b08be501c5 at commit index 18523916
```

**Comment by xiang90** [comment]
@MikaelCluseau Why do you think it is not repaired correctly. More logs after the restarting one?

**Comment by MikaelCluseau** [comment]
It crashed, I just tried debug mode, in fact systemd-journald seems to miss some output. Here the result of trying in a terminal instead of the service:

```
2015/09/24 22:39:33 wal: repairing etcd2.orig/member/wal/000000000000073c-00000000011a9eff.wal
2015/09/24 22:39:33 etcdserver: repaired WAL error (unexpected EOF)
2015/09/24 22:39:33 wal: ignored file 000000000000073c-00000000011a9eff.wal.broken in wal
2015/09/24 22:39:34 etcdserver: restarting member d241f35f522492d6 in cluster c72546b08be501c5 at commit index 18523916
2015/09/24 22:39:34 raft: d241f35f522492d6 state.commit 18523916 is out of range [18521854, 18523915]
panic: d241f35f522492d6 state.commit 18523916 is out of range [18521854, 18523915]

goroutine 1 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc2080a74c0, 0xa33070, 0x2b, 0xc2088fac00, 0x4, 0x4)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x185
github.com/coreos/etcd/raft.(*raft).loadState(0xc2088ad140, 0x4, 0xd241f35f522492d6, 0x11aa70c, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/raft/raft.go:759 +0x27b
github.com/coreos/etcd/raft.newRaft(0xc2087bb0e0, 0x40a5e3)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/raft/raft.go:194 +0x707
github.com/coreos/etcd/raft.RestartNode(0xc2087bb0e0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/raft/node.go:187 +0x4b
github.com/coreos/etcd/etcdserver.restartNode(0xc20811e000, 0xc2080681b0, 0x29, 0xc20862b138, 0x0, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:279 +0x6ca
github.com/coreos/etcd/etcdserver.NewServer(0xc20811e000, 0xc2080683f0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/etcdserver/server.go:280 +0x2974
github.com/coreos/etcd/etcdmain.startEtcd(0xc208062d80, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:224 +0x17e3
github.com/coreos/etcd/etcdmain.Main()
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:104 +0x157e
main.main()
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/main.go:29 +0x1b

goroutine 13 [syscall]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 19 [chan receive]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0xc58200)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.init·1
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 33 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by xiang90** [comment]
@MikaelCluseau Can you please paste in the full log from starting?

**Comment by MikaelCluseau** [comment]
Sure, I'm trying to get an extract of the last log entry with xxd too.
```
# etcd2 --data-dir=etcd2.orig --debug
2015/09/24 22:53:43 etcdmain: etcd Version: 2.1.2
2015/09/24 22:53:43 etcdmain: Git SHA: ff8d1ec
2015/09/24 22:53:43 etcdmain: Go Version: go1.4.2
2015/09/24 22:53:43 etcdmain: Go OS/Arch: linux/amd64
2015/09/24 22:53:43 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 8
2015/09/24 22:53:43 etcdmain: the server is already initialized as member before, starting as etcd member...
2015/09/24 22:53:43 etcdmain: listening for peers on http://localhost:2380
2015/09/24 22:53:43 etcdmain: listening for peers on http://localhost:7001
2015/09/24 22:53:43 etcdmain: listening for client requests on http://localhost:2379
2015/09/24 22:53:43 etcdmain: listening for client requests on http://localhost:4001
2015/09/24 22:53:43 etcdserver: recovered store from snapshot at index 18521854
2015/09/24 22:53:43 etcdserver: name = default
2015/09/24 22:53:43 etcdserver: data dir = etcd2.orig
2015/09/24 22:53:43 etcdserver: member dir = etcd2.orig/member
2015/09/24 22:53:43 etcdserver: heartbeat = 100ms
2015/09/24 22:53:43 etcdserver: election = 1000ms
2015/09/24 22:53:43 etcdserver: snapshot count = 10000
2015/09/24 22:53:43 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/09/24 22:53:43 etcdserver: loaded cluster information from store: <nil>
2015/09/24 22:53:43 wal: repairing etcd2.orig/member/wal/000000000000073c-00000000011a9eff.wal
2015/09/24 22:53:43 etcdserver: repaired WAL error (unexpected EOF)
2015/09/24 22:53:43 wal: ignored file 000000000000073c-00000000011a9eff.wal.broken in wal
2015/09/24 22:53:43 etcdserver: restarting member d241f35f522492d6 in cluster c72546b08be501c5 at commit index 18523916
2015/09/24 22:53:43 raft: d241f35f522492d6 state.commit 18523916 is out of range [18521854, 18523915]
panic: d241f35f522492d6 state.commit 18523916 is out of range [18521854, 18523915]

goroutine 1 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc2080a74c0, 0xa33070, 0x2b, 0xc208900b00, 0x4, 0x4)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x185
github.com/coreos/etcd/raft.(*raft).loadState(0xc2088e7140, 0x4, 0xd241f35f522492d6, 0x11aa70c, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/raft/raft.go:759 +0x27b
github.com/coreos/etcd/raft.newRaft(0xc2087bb0e0, 0x40a5e3)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/raft/raft.go:194 +0x707
github.com/coreos/etcd/raft.RestartNode(0xc2087bb0e0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/raft/node.go:187 +0x4b
github.com/coreos/etcd/etcdserver.restartNode(0xc20811e000, 0xc2080681b0, 0x29, 0xc20862b138, 0x0, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:279 +0x6ca
github.com/coreos/etcd/etcdserver.NewServer(0xc20811e000, 0xc2080683f0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/etcdserver/server.go:280 +0x2974
github.com/coreos/etcd/etcdmain.startEtcd(0xc208062d80, 0x0, 0x0, 0x0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:224 +0x17e3
github.com/coreos/etcd/etcdmain.Main()
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:104 +0x157e
main.main()
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/main.go:29 +0x1b

goroutine 13 [syscall]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 19 [chan receive]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0xc58200)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.init·1
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.1.2/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 33 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by MikaelCluseau** [comment]
What the last log entry looks like:
```
[end of previous entry's data]
0091bf0: 4d65 7461 6461 7461 223a 7b22 726f 6c65  Metadata":{"role
0091c00: 223a 226e 6f64 6522 7d2c 2256 6572 7369  ":"node"},"Versi
0091c10: 6f6e 223a 2230 2e31 302e 3222 7d28 0032  on":"0.10.2"}(.2
0091c20: 0038 0040 0148 f0db d0d3 b39a c283 1450  .8.@.H.........P
0091c30: 0058 0060 0068 0070 0078 0080 0100 1c00  .X.`.h.p.x......
0091c40: 0000 0000 0000 0803 109d 85a6 ac03 1a12  ................
0091c50: 0804 10d6 a592 91f5 ebfc a0d2 0118 8bce  ................
0091c60: ea08 4900 0000 0000 0000 0802 10bb eddd  ..I.............
0091c70: 8b0d 1a3f 0800 1004 188b ceea 0822 3408  ...?........."4.
0091c80: dd93 9ef7 cdc9 dda7 d601 1204 5359 4e43  ............SYNC
0091c90: 1a00 2200 2800 3200 3800 4800 5000 5800  ..".(.2.8.H.P.X.
0091ca0: 6000 6800 7000 78b9 a6cd fdc3 99c2 8314  `.h.p.x.........
0091cb0: 8001 001c 0000 0000 0000 0008 0310 94e1  ................
0091cc0: c4ce 071a 1208 0410 d6a5 9291 f5eb fca0  ................
0091cd0: d201 188c ceea 0805 0800 0000 0000 0008  ................
0091ce0: 0210 dbfa cbe1 081a fa0f 0800 1004 188c  ................
0091cf0: ceea 0822 ee0f 08df 939e f7cd c9dd a7d6  ..."............
0091d00: 0112 0350 5554 1a1e 2f31 2f72 6567 6973  ...PUT../1/regis
0091d10: 7472 792f 6d69 6e69 6f6e 732f 6365 7068  try/minions/ceph
0091d20: 2d32 2e69 7369 22d0 077b 226b 696e 6422  -2.isi"..{"kind"
0091d30: 3a22 4e6f 6465 222c 2261 7069 5665 7273  :"Node","apiVers
[... data continues and ends in the middle...]
0091f90: 6549 6e66 6f22 3a7b 226d 6163 6869 6e65  eInfo":{"machine
0091fa0: 4944 223a 2233 3062 6563 3465 3030 6365  ID":"30bec4e00ce
0091fb0: 3234 3561 6339 6330 3061 3861 3335 6564  245ac9c00a8a35ed
0091fc0: 3538 3065 3022 2c22 7379 7374 656d 5555  580e0","systemUU
0091fd0: 4944 223a 2230 3030 3030 3030 302d 3030  ID":"00000000-00
0091fe0: 3030 2d30 3030 302d 3030 3030 2d30 3032  00-0000-0000-002
0091ff0: 3539 3034 3430 3136 4122 2c22 626f 6f74  59044016A","boot
```

**Comment by xiang90** [comment]
@MikaelCluseau OK. I think your wal was generated by etcd 2.0.x. 

And you are out of luck, since you lost a committed entry. 2.0.x cannot recover from EOF and also it did not pay attention to the order of the entries. Thus a bad 2.0.x wal might not be recovered by 2.1.x.

This is fixed by https://github.com/coreos/etcd/commit/8b4eed29e5b0f808ea792e169ff5632bd95b962b.

If you really want to fix this. You can try to remove the last protobuf encoded entry in the wal file manually.

**Comment by MikaelCluseau** [comment]
Okay, I'll try that, I think it will be faster that redeploying all the services. Thanks for you help in concluding this. Will report here.

**Comment by MikaelCluseau** [comment]
FWIW, I fixed this by using xxd to "decode" the wal. Entries are starting by a varint, which is described as 0x08. Thus, I truncated the wal from the last 0x08 it has, and used xxd -r to re-encode the edited file, until etcd2 started. The data is ok after. A etcd specific tool could be faster, but it works quite fast this way :-)
