### ISSUE TITLE
panic: nodeToMember should never fail: raftAttributes key doesn't exist

### ISSUE THREAD

**Issue by spacejam** [coreos/etcd#3630]
Panic occurs after adding a new member to the cluster, and once it joins this occurs.  I am currently retracing my steps to see if I can reproduce it reliably.
```
015-10-01 17:22:52.532734 I | etcdmain: etcd Version: 2.2.0
2015-10-01 17:22:52.532802 I | etcdmain: Git SHA: e4561dd
2015-10-01 17:22:52.532812 I | etcdmain: Go Version: go1.4.2
2015-10-01 17:22:52.532819 I | etcdmain: Go OS/Arch: linux/amd64
2015-10-01 17:22:52.532827 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
2015-10-01 17:22:53.533696 I | etcdmain: listening for peers on http://ip-10-0-1-8.us-west-2.compute.internal:1025
2015-10-01 17:22:54.534580 I | etcdmain: listening for client requests on http://ip-10-0-1-8.us-west-2.compute.internal:1026
2015-10-01 17:22:55.535620 I | netutil: resolving ip-10-0-1-8.us-west-2.compute.internal:1025 to 10.0.1.8:1025
2015-10-01 17:22:56.536490 I | netutil: resolving ip-10-0-1-8.us-west-2.compute.internal:1025 to 10.0.1.8:1025
2015-10-01 17:22:56.536578 I | etcdserver: name = etcd-1443720152
2015-10-01 17:22:56.536589 I | etcdserver: data dir = etcd_data
2015-10-01 17:22:56.536598 I | etcdserver: member dir = etcd_data/member
2015-10-01 17:22:56.536606 I | etcdserver: heartbeat = 100ms
2015-10-01 17:22:56.536614 I | etcdserver: election = 1000ms
2015-10-01 17:22:56.536621 I | etcdserver: snapshot count = 10000
2015-10-01 17:22:56.536632 I | etcdserver: advertise client URLs = http://ip-10-0-1-8.us-west-2.compute.internal:1026
2015-10-01 17:22:56.536642 I | etcdserver: initial advertise peer URLs = http://ip-10-0-1-8.us-west-2.compute.internal:1025
2015-10-01 17:22:56.536655 I | etcdserver: initial cluster = etcd-1443720152=http://ip-10-0-1-8.us-west-2.compute.internal:1025
2015-10-01 17:22:56.538480 I | etcdserver: starting member 86cfcd96b62ad93e in cluster 692489ff14d6f969
2015-10-01 17:22:56.538534 I | raft: 86cfcd96b62ad93e became follower at term 0
2015-10-01 17:22:56.538552 I | raft: newRaft 86cfcd96b62ad93e [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015-10-01 17:22:56.538561 I | raft: 86cfcd96b62ad93e became follower at term 1
2015-10-01 17:22:56.538681 I | etcdserver: starting server... [version: 2.2.0, cluster version: to_be_decided]
2015-10-01 17:22:56.539799 N | etcdserver: added local member 86cfcd96b62ad93e [http://ip-10-0-1-8.us-west-2.compute.internal:1025] to cluster 692489ff14d6f969
2015-10-01 17:22:56.539867 E | etcdmain: failed to notify systemd for readiness
2015-10-01 17:22:57.038842 I | raft: 86cfcd96b62ad93e is starting a new election at term 1
2015-10-01 17:22:57.038900 I | raft: 86cfcd96b62ad93e became candidate at term 2
2015-10-01 17:22:57.038959 I | raft: 86cfcd96b62ad93e received vote from 86cfcd96b62ad93e at term 2
2015-10-01 17:22:57.038988 I | raft: 86cfcd96b62ad93e became leader at term 2
2015-10-01 17:22:57.039005 I | raft: raft.node: 86cfcd96b62ad93e elected leader 86cfcd96b62ad93e at term 2
2015-10-01 17:22:57.039642 I | etcdserver: published {Name:etcd-1443720152 ClientURLs:[http://ip-10-0-1-8.us-west-2.compute.internal:1026]} to cluster 692489ff14d6f969
2015-10-01 17:22:57.039682 I | etcdserver: setting up the initial cluster version to 2.2
2015-10-01 17:22:57.040170 N | etcdserver: set the initial cluster version to 2.2
2015-10-01 17:31:31.665333 N | etcdserver: added member 6f43f2add612b4f3 [http://ip-10-0-1-12.us-west-2.compute.internal:1025] to cluster 692489ff14d6f969
2015-10-01 17:31:32.668714 E | rafthttp: failed to write 6f43f2add612b4f3 on pipeline (dial tcp 10.0.1.12:1025: connection refused)
2015-10-01 17:31:32.669064 E | rafthttp: failed to dial 6f43f2add612b4f3 on stream Message (dial tcp 10.0.1.12:1025: connection refused)
2015-10-01 17:31:32.669101 E | rafthttp: failed to dial 6f43f2add612b4f3 on stream MsgApp v2 (dial tcp 10.0.1.12:1025: connection refused)
2015-10-01 17:31:32.669163 W | etcdserver: failed to reach the peerURL(http://ip-10-0-1-12.us-west-2.compute.internal:1025) of member 6f43f2add612b4f3 (Get http://ip-10-0-1-12.us-west-2.compute.internal:1025/version: dial tcp 10.0.1.12:1025: connection refused)
2015-10-01 17:31:32.669181 W | etcdserver: cannot get the version of member 6f43f2add612b4f3 (Get http://ip-10-0-1-12.us-west-2.compute.internal:1025/version: dial tcp 10.0.1.12:1025: connection refused)
2015-10-01 17:31:38.670475 E | rafthttp: failed to write 6f43f2add612b4f3 on pipeline (read tcp 10.0.1.12:1025: i/o timeout)
2015-10-01 17:31:38.670977 E | rafthttp: failed to dial 6f43f2add612b4f3 on stream MsgApp v2 (read tcp 10.0.1.12:1025: i/o timeout)
2015-10-01 17:31:38.671009 E | rafthttp: failed to dial 6f43f2add612b4f3 on stream Message (read tcp 10.0.1.12:1025: i/o timeout)
2015-10-01 17:31:39.766799 I | rafthttp: the connection with 6f43f2add612b4f3 became active
2015-10-01 17:31:40.039919 W | rafthttp: dropped MsgApp to 6f43f2add612b4f3 since pipeline's sending buffer is full
2015-10-01 17:31:40.138901 W | rafthttp: dropped MsgHeartbeat to 6f43f2add612b4f3 since pipeline's sending buffer is full
2015-10-01 17:31:40.238896 W | rafthttp: dropped MsgHeartbeat to 6f43f2add612b4f3 since pipeline's sending buffer is full
2015-10-01 17:31:40.338906 W | rafthttp: dropped MsgHeartbeat to 6f43f2add612b4f3 since pipeline's sending buffer is full
2015-10-01 17:31:40.438893 W | rafthttp: dropped MsgHeartbeat to 6f43f2add612b4f3 since pipeline's sending buffer is full
2015-10-01 17:31:40.539087 W | rafthttp: dropped MsgHeartbeat to 6f43f2add612b4f3 since pipeline's sending buffer is full
2015-10-01 17:31:40.539923 W | rafthttp: dropped MsgApp to 6f43f2add612b4f3 since pipeline's sending buffer is full
2015-10-01 17:31:40.638895 W | rafthttp: dropped MsgHeartbeat to 6f43f2add612b4f3 since pipeline's sending buffer is full
2015-10-01 17:31:40.738891 W | rafthttp: dropped MsgHeartbeat to 6f43f2add612b4f3 since pipeline's sending buffer is full
2015-10-01 17:31:40.781999 N | etcdserver: removed member 6f43f2add612b4f3 from cluster 692489ff14d6f969
2015-10-01 17:31:41.882063 W | rafthttp: rejected the stream from peer 6f43f2add612b4f3 since it was removed
2015-10-01 17:31:41.882260 W | rafthttp: rejected the stream from peer 6f43f2add612b4f3 since it was removed
2015-10-01 17:31:42.885295 C | etcdserver: nodeToMember should never fail: raftAttributes key doesn't exist
panic: nodeToMember should never fail: raftAttributes key doesn't exist

goroutine 48 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc20809fd20, 0xd9d8b0, 0x22, 0xc208321518, 0x1, 0x1)
	/go/src/github.com/mesosphere/etcd-mesos/_vendor/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x185
github.com/coreos/etcd/etcdserver.membersFromStore(0x7fa60f7b1b78, 0xc20816c9a0, 0xc208010000, 0xc20801f500)
	/go/src/github.com/mesosphere/etcd-mesos/_vendor/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:385 +0x3aa
github.com/coreos/etcd/etcdserver.(*cluster).ValidateConfigurationChange(0xc2080450e0, 0x3e50246da39a042a, 0x1, 0x6f43f2add612b4f3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/mesosphere/etcd-mesos/_vendor/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/cluster.go:231 +0x63
github.com/coreos/etcd/etcdserver.(*EtcdServer).applyConfChange(0xc20804c580, 0x3e50246da39a042a, 0x1, 0x6f43f2add612b4f3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/mesosphere/etcd-mesos/_vendor/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:851 +0x67
github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0xc20804c580, 0xc20831cf50, 0x1, 0x1, 0xc208321c78, 0x423, 0x0)
	/go/src/github.com/mesosphere/etcd-mesos/_vendor/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:778 +0x5a0
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc20804c580)
	/go/src/github.com/mesosphere/etcd-mesos/_vendor/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:480 +0xa97
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
	/go/src/github.com/mesosphere/etcd-mesos/_vendor/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:379 +0x44c
```

**Comment by yichengq** [comment]
Do you know all HTTP requests that it accepted?

**Comment by xiang90** [comment]
closed by https://github.com/coreos/etcd/pull/3657
