### ISSUE TITLE
etcd hang and doesn't fully stop when being removed when using v3

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3787]
```
2015-10-31 18:03:43.657761 E | etcdserver: the member has been permanently removed from the cluster
2015-10-31 18:03:43.657774 I | etcdserver: the data-dir used by this member must be removed.
^\SIGQUIT: quit
PC=0x45d551 m=0

goroutine 0 [idle]:
runtime.futex(0x11ec010, 0x0, 0x0, 0x0, 0x0, 0x11eb400, 0x0, 0x0, 0x40d934, 0x11ec010, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:288 +0x21
runtime.futexsleep(0x11ec010, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:39 +0x53
runtime.notesleep(0x11ec010)
	/usr/local/go/src/runtime/lock_futex.go:142 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc1.go:1128 +0x112
runtime.findrunnable(0xc820020000, 0x0)
	/usr/local/go/src/runtime/proc1.go:1530 +0x69e
runtime.schedule()
	/usr/local/go/src/runtime/proc1.go:1639 +0x267
runtime.park_m(0xc820119200)
	/usr/local/go/src/runtime/proc1.go:1698 +0x18b
runtime.mcall(0x7fff1b1d3160)
	/usr/local/go/src/runtime/asm_amd64.s:204 +0x5b

goroutine 1 [IO wait, 10 minutes]:
net.runtime_pollWait(0x7f52d437e0f0, 0x72, 0xc820012160)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201dd250, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201dd250, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201dd1f0, 0x0, 0x7f52d4385af8, 0xc8201e8580)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200d00d0, 0x44f9e0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200d00d0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.(*Server).Serve(0xc820018780, 0x7f52d4339c38, 0xc8200d00d0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/server.go:194 +0x187
github.com/coreos/etcd/etcdmain.startEtcd(0xc8200d2a00, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:323 +0x216d
github.com/coreos/etcd/etcdmain.Main()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:126 +0xc41
main.main()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/main.go:29 +0x14

goroutine 22 [chan receive]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0x11eb340)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.init.1
	/Users/unihorn/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 51 [syscall, 10 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 94 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f52d437e270, 0x72, 0xc820012160)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201dd090, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201dd090, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201dd030, 0x0, 0x7f52d4385af8, 0xc82ef9ba80)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200d00c0, 0x1000, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200d00c0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc8201f0140, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x70
net/http.(*Server).Serve(0xc82001e360, 0x7f52d4339ce0, 0xc8201f0140, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/coreos/etcd/etcdmain.serveHTTP(0x7f52d4339ce0, 0xc8201f0140, 0x7f52d4385938, 0xc82000fe30, 0x45d964b800, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x167
github.com/coreos/etcd/etcdmain.startEtcd.func3(0x7f52d4385938, 0xc82000fe30, 0x7f52d4339ce0, 0xc8201f0140)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:307 +0x61
created by github.com/coreos/etcd/etcdmain.startEtcd
	/Users/unihorn/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:308 +0x1ec0

goroutine 95 [IO wait, 10 minutes]:
net.runtime_pollWait(0x7f52d437e1b0, 0x72, 0xc820012160)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201dd170, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201dd170, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201dd110, 0x0, 0x7f52d4385af8, 0xc8201e85a0)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200d00c8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200d00c8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc8201eed20, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:52 +0x62
github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/netutil.(*limitListener).Accept(0xc8201f0200, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/netutil/listen.go:30 +0x8c
net/http.(*Server).Serve(0xc82001e300, 0x7f52d4339d50, 0xc8201f0200, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/coreos/etcd/etcdmain.serveHTTP(0x7f52d4339d50, 0xc8201f0200, 0x7f52d4385b20, 0xc8201e84c0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x167
github.com/coreos/etcd/etcdmain.startEtcd.func4(0xc8201e84c0, 0x7f52d4339d50, 0xc8201f0200)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:315 +0x7e
created by github.com/coreos/etcd/etcdmain.startEtcd
	/Users/unihorn/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:316 +0x1fa6

goroutine 119 [select]:
github.com/coreos/etcd/storage.(*watchableStore).syncWatchersLoop(0xc820bf3400)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/storage/watchable_store.go:203 +0x175
created by github.com/coreos/etcd/storage.newWatchableStore
	/Users/unihorn/gopath/src/github.com/coreos/etcd/storage/watchable_store.go:50 +0x1ab

goroutine 118 [select]:
github.com/coreos/etcd/storage/backend.(*backend).run(0xc820bf3340)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:138 +0x151
created by github.com/coreos/etcd/storage/backend.newBackend
	/Users/unihorn/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:79 +0x317

rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x11ec010
rsi    0x0
rbp    0x1
rsp    0x7fff1b1d2fb8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x7
r13    0xefce56
r14    0x7
r15    0x8
rip    0x45d551
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by xiang90** [comment]
@yichengq Can you please provide more information about how to reproduce this issue?

**Comment by yichengq** [comment]
I can reproduce it by
1. starting 3-member etcd cluster which enables v3demo
2. remove one member from the cluster
3. the removed member hangs
If you SIGQUIT the removed member, it will print the log as above.

**Comment by xiang90** [comment]
@yichengq Awesome. Thanks.
