### ISSUE TITLE
TestKVTxnBlockNonTnxOperations: panic: assertion failed: tx closed

### ISSUE THREAD

**Issue by AkihiroSuda** [coreos/etcd#4039]
TestKVTxnBlockNonTnxOperations can fail intermittently.

```
2015/12/16 08:19:59 store.index: compact 1
2015/12/16 08:19:59 store.index: compact 2
2015/12/16 08:19:59 store.index: compact 3
2015/12/16 08:19:59 store.index: compact 4
2015/12/16 08:19:59 store.index: compact 5
2015/12/16 08:19:59 store.index: compact 6
2015/12/16 08:19:59 store.index: compact 7
2015/12/16 08:19:59 store.index: compact 8
2015/12/16 08:19:59 store.index: compact 9
2015/12/16 08:19:59 store.index: compact 10
2015/12/16 08:19:59 store.index: compact 11
2015/12/16 08:19:59 store.index: compact 12
2015/12/16 08:19:59 store.index: compact 13
2015/12/16 08:19:59 store.index: compact 14
2015/12/16 08:19:59 store.index: compact 15
2015/12/16 08:19:59 store.index: compact 16
2015/12/16 08:19:59 store.index: compact 17
2015/12/16 08:19:59 store.index: compact 18
2015/12/16 08:19:59 store.index: compact 19
2015/12/16 08:19:59 store.index: compact 1
2015/12/16 08:19:59 store.index: compact 2
2015/12/16 08:19:59 store.index: compact 3
2015/12/16 08:19:59 store.index: compact 4
2015/12/16 08:19:59 store.index: compact 5
2015/12/16 08:19:59 store.index: compact 6
2015/12/16 08:19:59 store.index: compact 7
2015/12/16 08:19:59 store.index: compact 8
2015/12/16 08:19:59 store.index: compact 9
2015/12/16 08:19:59 store.index: compact 10
2015/12/16 08:19:59 store.index: compact 11
2015/12/16 08:19:59 store.index: compact 12
2015/12/16 08:19:59 store.index: compact 13
2015/12/16 08:19:59 store.index: compact 14
2015/12/16 08:19:59 store.index: compact 15
2015/12/16 08:19:59 store.index: compact 16
2015/12/16 08:19:59 store.index: compact 17
2015/12/16 08:19:59 store.index: compact 18
2015/12/16 08:19:59 store.index: compact 19
2015/12/16 08:20:00 store.index: compact 3
2015/12/16 08:20:00 store.index: compact 3
2015/12/16 08:20:05 store.index: compact 0
2015/12/16 08:20:05 store.index: compact 1
2015/12/16 08:20:05 store.index: compact 2
2015/12/16 08:20:05 store.index: compact 3
2015/12/16 08:20:05 store.index: compact 0
2015/12/16 08:20:06 store.index: compact 1
2015/12/16 08:20:06 store.index: compact 3
2015/12/16 08:20:07 store.index: compact 1
2015/12/16 08:20:07 storage: restore compact to 1
2015/12/16 08:20:08 storage: restore compact to 2
2015/12/16 08:20:09 store.index: compact 3
2015/12/16 08:20:09 storage: resume scheduled compaction at 2
2015/12/16 08:20:09 store.index: compact 2
2015/12/16 08:20:12 store.index: compact 1
2015/12/16 08:20:12 store.index: compact 2
2015/12/16 08:20:12 store.index: compact 3
2015/12/16 08:20:12 store.index: compact 4
2015/12/16 08:20:12 store.index: compact 5
2015/12/16 08:20:12 store.index: compact 6
2015/12/16 08:20:12 store.index: compact 7
2015/12/16 08:20:12 store.index: compact 8
2015/12/16 08:20:12 store.index: compact 9
2015/12/16 08:20:12 store.index: compact 10
2015/12/16 08:20:12 store.index: compact 11
2015/12/16 08:20:12 store.index: compact 12
2015/12/16 08:20:12 store.index: compact 13
2015/12/16 08:20:12 store.index: compact 14
2015/12/16 08:20:12 store.index: compact 15
2015/12/16 08:20:12 store.index: compact 16
2015/12/16 08:20:12 store.index: compact 17
2015/12/16 08:20:12 store.index: compact 18
2015/12/16 08:20:12 store.index: compact 19
2015/12/16 08:20:12 store.index: compact 1
2015/12/16 08:20:12 store.index: compact 2
2015/12/16 08:20:12 store.index: compact 3
2015/12/16 08:20:12 store.index: compact 4
2015/12/16 08:20:12 store.index: compact 5
2015/12/16 08:20:12 store.index: compact 6
2015/12/16 08:20:12 store.index: compact 7
2015/12/16 08:20:12 store.index: compact 8
2015/12/16 08:20:12 store.index: compact 9
2015/12/16 08:20:12 store.index: compact 10
2015/12/16 08:20:12 store.index: compact 11
2015/12/16 08:20:12 store.index: compact 12
2015/12/16 08:20:12 store.index: compact 13
2015/12/16 08:20:12 store.index: compact 14
2015/12/16 08:20:12 store.index: compact 15
2015/12/16 08:20:12 store.index: compact 16
2015/12/16 08:20:12 store.index: compact 17
2015/12/16 08:20:12 store.index: compact 18
2015/12/16 08:20:12 store.index: compact 19
2015/12/16 08:20:12 store.index: compact 3
2015/12/16 08:20:13 store.index: compact 3
2015/12/16 08:20:19 store.index: compact 0
2015/12/16 08:20:19 store.index: compact 1
2015/12/16 08:20:19 store.index: compact 2
2015/12/16 08:20:19 store.index: compact 3
2015/12/16 08:20:19 store.index: compact 0
2015/12/16 08:20:19 store.index: compact 1
2015/12/16 08:20:19 store.index: compact 3
2015/12/16 08:20:22 store.index: compact 1
2015/12/16 08:20:23 storage: restore compact to 1
2015/12/16 08:20:25 storage: restore compact to 2
2015/12/16 08:20:27 store.index: compact 3
2015/12/16 08:20:28 storage: resume scheduled compaction at 2
2015/12/16 08:20:28 store.index: compact 2
2015/12/16 08:20:34 store.index: compact 1
2015/12/16 08:20:34 store.index: compact 2
2015/12/16 08:20:34 store.index: compact 3
2015/12/16 08:20:34 store.index: compact 4
2015/12/16 08:20:34 store.index: compact 5
2015/12/16 08:20:34 store.index: compact 6
2015/12/16 08:20:34 store.index: compact 7
2015/12/16 08:20:34 store.index: compact 8
2015/12/16 08:20:34 store.index: compact 9
2015/12/16 08:20:34 store.index: compact 10
2015/12/16 08:20:34 store.index: compact 11
2015/12/16 08:20:34 store.index: compact 12
2015/12/16 08:20:34 store.index: compact 13
2015/12/16 08:20:34 store.index: compact 14
2015/12/16 08:20:34 store.index: compact 15
2015/12/16 08:20:34 store.index: compact 16
2015/12/16 08:20:34 store.index: compact 17
2015/12/16 08:20:34 store.index: compact 18
2015/12/16 08:20:34 store.index: compact 19
2015/12/16 08:20:34 store.index: compact 1
2015/12/16 08:20:34 store.index: compact 2
2015/12/16 08:20:34 store.index: compact 3
2015/12/16 08:20:34 store.index: compact 4
2015/12/16 08:20:34 store.index: compact 5
2015/12/16 08:20:34 store.index: compact 6
2015/12/16 08:20:34 store.index: compact 7
2015/12/16 08:20:34 store.index: compact 8
2015/12/16 08:20:34 store.index: compact 9
2015/12/16 08:20:34 store.index: compact 10
2015/12/16 08:20:34 store.index: compact 11
2015/12/16 08:20:34 store.index: compact 12
2015/12/16 08:20:34 store.index: compact 13
2015/12/16 08:20:34 store.index: compact 14
2015/12/16 08:20:34 store.index: compact 15
2015/12/16 08:20:34 store.index: compact 16
2015/12/16 08:20:34 store.index: compact 17
2015/12/16 08:20:34 store.index: compact 18
2015/12/16 08:20:34 store.index: compact 19
2015/12/16 08:20:36 store.index: compact 3
2015/12/16 08:20:37 store.index: compact 3
panic: assertion failed: tx closed

goroutine 393 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt._assert(0xc82037c600, 0xa71090, 0x9, 0x0, 0x0, 0x0)
        /etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:790 +0xfc
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*Cursor).seek(0xc82003ac40, 0xcdb2ea, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/cursor.go:155 +0xf7
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*Bucket).Bucket(0xc82037c638, 0xcdb2ea, 0x3, 0x3, 0x4629d4)
        /etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/bucket.go:112 +0x2ac
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*Tx).Bucket(0xc82037c620, 0xcdb2ea, 0x3, 0x3, 0x1)
        /etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/tx.go:100 +0x59
github.com/coreos/etcd/storage/backend.(*batchTx).UnsafePut(0xc8200e4be0, 0xcdb2ea, 0x3, 0x3, 0xc820329380, 0x11, 0x12, 0xc8203d7e80, 0xb, 0xb)
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/batch_tx.go:59 +0x8e
github.com/coreos/etcd/storage.(*store).put(0xc8202943f0, 0xc82026bc70, 0x3, 0x8, 0x0, 0x0, 0x0)
        github.com/coreos/etcd/storage/_test/_obj_test/kvstore.go:534 +0x538
github.com/coreos/etcd/storage.(*store).Put(0xc8202943f0, 0xc82026bc70, 0x3, 0x8, 0x0, 0x0, 0x0, 0x0)
        github.com/coreos/etcd/storage/_test/_obj_test/kvstore.go:102 +0xa3
github.com/coreos/etcd/storage.TestKVTxnBlockNonTnxOperations.func2()
        /etcd/gopath/src/github.com/coreos/etcd/storage/kv_test.go:428 +0x8f
github.com/coreos/etcd/storage.TestKVTxnBlockNonTnxOperations.func4(0xc82012a208, 0xc820484d80)
        /etcd/gopath/src/github.com/coreos/etcd/storage/kv_test.go:435 +0x3c
created by github.com/coreos/etcd/storage.TestKVTxnBlockNonTnxOperations
        /etcd/gopath/src/github.com/coreos/etcd/storage/kv_test.go:437 +0x437

goroutine 1 [runnable]:
testing.RunTests(0xb41c90, 0xcfa9c0, 0x3f, 0x3f, 0x9a1801)
        /usr/lib/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc820541f00, 0xcfdce0)
        /usr/lib/go/src/testing/testing.go:494 +0xe5
main.main()
        github.com/coreos/etcd/storage/_test/_testmain.go:252 +0x385

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 134 [select]:
github.com/coreos/etcd/storage/backend.(*backend).run(0xc8203e4900)
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:138 +0x1d5
created by github.com/coreos/etcd/storage/backend.newBackend
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:79 +0x436

goroutine 153 [select]:
github.com/coreos/etcd/storage/backend.(*backend).run(0xc820437800)
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:138 +0x1d5
created by github.com/coreos/etcd/storage/backend.newBackend
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:79 +0x436

goroutine 306 [select]:
github.com/coreos/etcd/storage/backend.(*backend).run(0xc820149480)
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:138 +0x1d5
created by github.com/coreos/etcd/storage/backend.newBackend
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:79 +0x436

goroutine 157 [select]:
github.com/coreos/etcd/storage/backend.(*backend).run(0xc820437e00)
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:138 +0x1d5
created by github.com/coreos/etcd/storage/backend.newBackend
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:79 +0x436

goroutine 162 [select]:
github.com/coreos/etcd/storage.(*watchableStore).syncWatchingsLoop(0xc820496600)
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:281 +0x21e
created by github.com/coreos/etcd/storage.newWatchableStore
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:66 +0x252

goroutine 167 [select]:
github.com/coreos/etcd/storage.(*watchableStore).syncWatchingsLoop(0xc820436480)
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:281 +0x21e
created by github.com/coreos/etcd/storage.newWatchableStore
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:66 +0x252

goroutine 170 [select]:
github.com/coreos/etcd/storage.(*watchableStore).syncWatchingsLoop(0xc820436c00)
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:281 +0x21e
created by github.com/coreos/etcd/storage.newWatchableStore
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:66 +0x252

goroutine 311 [select]:
github.com/coreos/etcd/storage.(*watchableStore).syncWatchingsLoop(0xc82019ab40)
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:281 +0x21e
created by github.com/coreos/etcd/storage.newWatchableStore
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:66 +0x252

goroutine 280 [select]:
github.com/coreos/etcd/storage/backend.(*backend).run(0xc8202ab000)
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:138 +0x1d5
created by github.com/coreos/etcd/storage/backend.newBackend
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:79 +0x436

goroutine 288 [select]:
github.com/coreos/etcd/storage/backend.(*backend).run(0xc8201b1540)
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:138 +0x1d5
created by github.com/coreos/etcd/storage/backend.newBackend
        /etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:79 +0x436

goroutine 324 [select]:
github.com/coreos/etcd/storage.(*watchableStore).syncWatchingsLoop(0xc82022aec0)
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:281 +0x21e
created by github.com/coreos/etcd/storage.newWatchableStore
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:66 +0x252

goroutine 327 [select]:
github.com/coreos/etcd/storage.(*watchableStore).syncWatchingsLoop(0xc820436ac0)
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:281 +0x21e
created by github.com/coreos/etcd/storage.newWatchableStore
        github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:66 +0x252
FAIL    github.com/coreos/etcd/storage  47.873s
```

**Comment by gyuho** [comment]
@AkihiroSuda **I cannot reproduce this error**. Can you provide your
testing environment or do you have a reliable way to reproduce this?

`tx closed` is from boltdb `ErrTxClosed`. Error message indicates that
your machine or test fails to initialize the database.

Did you run into this under slow hard-disk?

Thanks

**Comment by AkihiroSuda** [comment]
- Hardware: sorry I can't remember, but perhaps either of these ones:
 - 4-Core Xeon E3, 8GB RAM, HDD
 - AWS t2.medium, EBS magnestic store
- OS: Ubuntu 15.10 amd64
- etcd revision: 9b0b15c
- Workload: __Certainly, I was running another heavy workload (unrelated to etcd).
 And notably, I was able to reproduce the bug only when I was running the other workload.__

I'm trying to reproduce the bug again.

**Comment by gyuho** [comment]
I see. Even if it was running slow, this shouldn't happen. If you can find
a way to reproduce, please let me know. That would help me debug a lot.
Thanks!

On Mon, Jan 11, 2016, 22:53 Akihiro Suda <notifications@github.com> wrote:

>
>    - Hardware: sorry I can't remember, but perhaps either of these ones:
>       - 4-Core Xeon E3, 8GB RAM, HDD
>       - AWS t2.medium, EBS magnestic store
>    - OS: Ubuntu 15.10 amd64
>    - etcd revision: 9b0b15c
>    <https://github.com/coreos/etcd/commit/9b0b15c9be660695082d683bee6d0b5ea59904c4>
>    - Workload: *Certainly, I was running another heavy workload
>    (unrelated to etcd). And notably, I was able to reproduce the bug only when
>    I was running the other workload.*
>
> I'm trying to reproduce the bug again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coreos/etcd/issues/4039#issuecomment-170816612>.
>
-- 
Sincerely,
Gyu-Ho Lee

**Comment by AkihiroSuda** [comment]
For 9b0b15c, I can sometimes reproduce this panic using my fuzzing tool: https://github.com/AkihiroSuda/MicroEarthquake/tree/tag20160112

I'm currently testing latest 374b14e4 with my tool, but I'm not hitting the panic yet.
Perhaps the panic has been already fixed by some commits since 9b0b15c?

**Comment by gyuho** [comment]
@AkihiroSuda This is not related to https://github.com/coreos/etcd/commit/9b0b15c9be660695082d683bee6d0b5ea59904c4.

This happens when you have `nil` database inside transaction, therefore returning `tx closed`.
I am not sure what kind of fuzz testing you are running, but it might be: two routines share one
database and if the database got deleted or another routine closes the transaction by committing
data into the disk.

We can only debug when it can be reproducible in our side as well.

Please let me know whenever you find a way to get it.

I will keep investigating.

**Comment by AkihiroSuda** [comment]
@gyuho,

OK, could you please try this? https://github.com/AkihiroSuda/etcd/commit/6d9ac5a89e3f3de04c7f6655338f126b98f41840


This is based on latest b83c5288 (Jan 12), and I can reproduce the bug locally _without_ my fuzzing tool I mentioned above.
(you're quite right, the bug is not yet fixed.)

My environment is Ubuntu 15.10 amd64 (Go 1.5.1) on AWS t2.large, EBS magnetic store.

```
$ cd ~/WORK/etcd/storage
$ GOPATH=~/WORK/etcd/gopath go test -count 1000 -run TestKVTxnBlockNonTnxOperations
panic: assertion failed: tx closed

goroutine 1124 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt._assert(0x0, 0x916d30, 0x9, 0x0, 0x0, 0x0)
        /home/ubuntu/WORK/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:790 +0xee
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*Cursor).seek(0xc82003bac8, 0xb33274, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/WORK/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/cursor.go:155 +0x94
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*Bucket).Bucket(0xc82012eb78, 0xb33274, 0x3, 0x3, 0xc8204b7ba2)
        /home/ubuntu/WORK/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/bucket.go:112 +0x180
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*Tx).Bucket(0xc82012eb60, 0xb33274, 0x3, 0x3, 0x3)
        /home/ubuntu/WORK/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/tx.go:100 +0x4b
github.com/coreos/etcd/storage/backend.(*batchTx).UnsafePut(0xc8201f0f00, 0xb33274, 0x3, 0x3, 0xc8201f12a0, 0x12, 0x12, 0xc8204b7ba0, 0x5, 0x5)
        /home/ubuntu/WORK/etcd/gopath/src/github.com/coreos/etcd/storage/backend/batch_tx.go:60 +0x6d
_/home/ubuntu/WORK/etcd/storage.(*store).delete(0xc820407380, 0xc8203da650, 0x3, 0x8)
        /home/ubuntu/WORK/etcd/storage/kvstore.go:473 +0x546
_/home/ubuntu/WORK/etcd/storage.(*store).deleteRange(0xc820407380, 0xc8203da650, 0x3, 0x8, 0x0, 0x0, 0x0, 0x3)
        /home/ubuntu/WORK/etcd/storage/kvstore.go:452 +0x1aa
_/home/ubuntu/WORK/etcd/storage.(*store).DeleteRange(0xc820407380, 0xc8203da650, 0x3, 0x8, 0x0, 0x0, 0x0, 0xc820063b40, 0x7a6ec0)
        /home/ubuntu/WORK/etcd/storage/kvstore.go:131 +0x7c
_/home/ubuntu/WORK/etcd/storage.TestKVTxnBlockNonTnxOperations.func3()
        /home/ubuntu/WORK/etcd/storage/kv_test.go:433 +0x7d
_/home/ubuntu/WORK/etcd/storage.TestKVTxnBlockNonTnxOperations.func4(0xc82047e2b8, 0xc820135f20)
        /home/ubuntu/WORK/etcd/storage/kv_test.go:440 +0x4f
created by _/home/ubuntu/WORK/etcd/storage.TestKVTxnBlockNonTnxOperations
        /home/ubuntu/WORK/etcd/storage/kv_test.go:443 +0x3f9

goroutine 1 [chan receive]:
testing.RunTests(0x9ce518, 0xb4eb20, 0x3f, 0x3f, 0x1)
        /usr/lib/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc82004bef8, 0x0)
        /usr/lib/go/src/testing/testing.go:494 +0x70
main.main()
        _/home/ubuntu/WORK/etcd/storage/_test/_testmain.go:188 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 1105 [runnable]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0x3, 0x0, 0x0)
        /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:296 +0x4a
os.(*file).close(0xc8201fac00, 0x0, 0x0)
        /usr/lib/go/src/os/file_unix.go:126 +0x61
os.(*File).Close(0xc82047e2a8, 0x0, 0x0)
        /usr/lib/go/src/os/file_unix.go:118 +0x54
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*DB).close(0xc820228000, 0x0, 0x0)
        /home/ubuntu/WORK/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:394 +0xef
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*DB).Close(0xc820228000, 0x0, 0x0)
        /home/ubuntu/WORK/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:368 +0x14c
github.com/coreos/etcd/storage/backend.(*backend).Close(0xc820063740, 0x0, 0x0)
        /home/ubuntu/WORK/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:164 +0x69
_/home/ubuntu/WORK/etcd/storage.cleanup(0x7f725a8e8f48, 0xc820407380, 0x7f725a8e8d38, 0xc820063740, 0xc8201faba0, 0x28)
        /home/ubuntu/WORK/etcd/storage/kv_test.go:862 +0x3b
runtime.Goexit()
        /usr/lib/go/src/runtime/panic.go:320 +0xfb
testing.(*common).FailNow(0xc820212510)
        /usr/lib/go/src/testing/testing.go:336 +0x36
testing.(*common).Fatalf(0xc820212510, 0x969d00, 0x25, 0xc820049e48, 0x1, 0x1)
        /usr/lib/go/src/testing/testing.go:379 +0x83
_/home/ubuntu/WORK/etcd/storage.TestKVTxnBlockNonTnxOperations(0xc820212510)
        /home/ubuntu/WORK/etcd/storage/kv_test.go:454 +0x76a
testing.tRunner(0xc820212510, 0xb4ee68)
        /usr/lib/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
        /usr/lib/go/src/testing/testing.go:561 +0x86d
exit status 2
FAIL    _/home/ubuntu/WORK/etcd/storage 29.639s

```

**Comment by gyuho** [comment]
@AkihiroSuda Thanks a lot. Yes I had reproduced this panic in my machine as well.

The panic happens here:

https://github.com/coreos/etcd/blob/master/Godeps/_workspace/src/github.com/boltdb/bolt/cursor.go#L152-L169


```go
// seek moves the cursor to a given key and returns it.
// If the key does not exist then the next key is used.
func (c *Cursor) seek(seek []byte) (key []byte, value []byte, flags uint32) {
	_assert(c.bucket.tx.db != nil, "tx closed")
```

I will investigate more for better way to reproduce it, and file an issue to boltdb if necessary.


```
=== RUN   TestKVTxnBlockNonTnxOperations
panic: assertion failed: tx closed

exit status 2
FAIL	github.com/coreos/etcd/storage	18.063s
1: running [Created by storage.TestKVTxnBlockNonTnxOperations @ kv_test.go:441]
    bolt    db.go:790        _assert(0x40f700, 0x918d20, 0x9, 0, 0, 0)
    bolt    cursor.go:155    (*Cursor).seek(0xc82003bab0, 0xb37268, 0x3, 0x3, 0, 0, 0, 0, 0, 0, ...)
    bolt    bucket.go:112    (*Bucket).Bucket(0xc820112b78, 0xb37268, 0x3, 0x3, 0xc8200bfe42)
    bolt    tx.go:100        (*Tx).Bucket(0xc820112b60, 0xb37268, 0x3, 0x3, 0x3)
    backend batch_tx.go:60   (*batchTx).UnsafePut(0xc8204b74a0, 0xb37268, 0x3, 0x3, 0xc8204b77c0, 0x12, 0x12, 0xc8200bfe40, 0x5, 0x5)
    storage kvstore.go:473   (*store).delete(#1, #2, 0x3, 0x8)
    storage kvstore.go:452   (*store).deleteRange(#1, #2, 0x3, 0x8, 0, 0, 0, 0x3)
    storage kvstore.go:131   (*store).DeleteRange(#1, #2, 0x3, 0x8, 0, 0, 0, 0x5, 0x13)
    storage kv_test.go:432   TestKVTxnBlockNonTnxOperations.func3()
    storage kv_test.go:439   TestKVTxnBlockNonTnxOperations.func4(0xc820030170, 0xc8204dc3c0)
1: syscall [locked]
    runtime asm_amd64.s:1721 goexit()
1: runnable
    testing testing.go:562   RunTests(0x9d28b8, 0xb52b00, 0x3f, 0x3f, 0x1)
    testing testing.go:494   (*M).Run(#3, 0)
    main    _testmain.go:188 main()

```

**Comment by xiang90** [comment]
@AkihiroSuda @gyuho I think i know what happened. I am fixing this.
