### ISSUE TITLE
TestLessorGrant fails

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4156]
```
go test -run TestLessorGrant |&pp
fatal error: all goroutines are asleep - deadlock!

exit status 2
FAIL	github.com/coreos/etcd/lease	1.060s
1: chan receive
    testing testing.go:562    RunTests(0x6884c0, 0x742ae0, 0x4, 0x4, 0x1)
    testing testing.go:494    (*M).Run(0xc820041ef8, 0x745e60)
    main    _testmain.go:60   main()
1: semacquire [Created by testing.RunTests @ testing.go:561]
    sync    sema.go:43        runtime_Semacquire(#2)
    sync    mutex.go:82       (*Mutex).Lock(#1)
    backend batch_tx.go:112   (*batchTx).Commit(#1)
    backend backend.go:104    (*backend).ForceCommit(#4)
    lease   lessor.go:214     (*lessor).initAndRecover(#5)
    lease   lessor.go:78      NewLessor(0x5da501, #7, #4, #8, #3, 0)
    lease   lessor_test.go:36 TestLessorGrant(#6)
    testing testing.go:456    tRunner(#6, 0x742ae0)
1: semacquire [Created by backend.newBackend @ backend.go:91]
    sync    sema.go:43        runtime_Semacquire(#2)
    sync    mutex.go:82       (*Mutex).Lock(#1)
    backend batch_tx.go:112   (*batchTx).Commit(#1)
    backend backend.go:157    (*backend).run(#4)

```

```
model name	: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
go version go1.5.2 linux/amd64
Ubuntu 14.04.3 LTS
```

Only in my local machine... Will look into it.

**Comment by gyuho** [comment]
Here's full log:

```
go test -run TestLessorGrant
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.RunTests(0x6884c0, 0x742ae0, 0x4, 0x4, 0x1)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820041ef8, 0x745e60)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	github.com/coreos/etcd/lease/_test/_testmain.go:60 +0x116

goroutine 5 [semacquire]:
sync.runtime_Semacquire(0xc82000a4a4)
	/usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*Mutex).Lock(0xc82000a4a0)
	/usr/local/go/src/sync/mutex.go:82 +0x1c4
github.com/coreos/etcd/storage/backend.(*batchTx).Commit(0xc82000a4a0)
	/home/gyuho/go/src/github.com/coreos/etcd/storage/backend/batch_tx.go:112 +0x28
github.com/coreos/etcd/storage/backend.(*backend).ForceCommit(0xc8200128c0)
	/home/gyuho/go/src/github.com/coreos/etcd/storage/backend/backend.go:104 +0x25
github.com/coreos/etcd/lease.(*lessor).initAndRecover(0xc820012940)
	/home/gyuho/go/src/github.com/coreos/etcd/lease/lessor.go:214 +0x7f1
github.com/coreos/etcd/lease.NewLessor(0x5da501, 0x7fbef34545e8, 0xc8200128c0, 0x7fbef3454638, 0xc82000a4e0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/lease/lessor.go:78 +0x1ee
github.com/coreos/etcd/lease.TestLessorGrant(0xc82001a090)
	/home/gyuho/go/src/github.com/coreos/etcd/lease/lessor_test.go:36 +0x16f
testing.tRunner(0xc82001a090, 0x742ae0)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 6 [semacquire]:
sync.runtime_Semacquire(0xc82000a4a4)
	/usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*Mutex).Lock(0xc82000a4a0)
	/usr/local/go/src/sync/mutex.go:82 +0x1c4
github.com/coreos/etcd/storage/backend.(*batchTx).Commit(0xc82000a4a0)
	/home/gyuho/go/src/github.com/coreos/etcd/storage/backend/batch_tx.go:112 +0x28
github.com/coreos/etcd/storage/backend.(*backend).run(0xc8200128c0)
	/home/gyuho/go/src/github.com/coreos/etcd/storage/backend/backend.go:157 +0xf0
created by github.com/coreos/etcd/storage/backend.newBackend
	/home/gyuho/go/src/github.com/coreos/etcd/storage/backend/backend.go:91 +0x31a
exit status 2
FAIL	github.com/coreos/etcd/lease	1.056s
```

**Comment by gyuho** [comment]
`lease` package was not being tested in CI. Now test hangs https://travis-ci.org/coreos/etcd/jobs/100784027#L276.

We can investigate tomorrow.

**Comment by heyitsanthony** [comment]
I thought leases were still unstable?

**Comment by gyuho** [comment]
Right. Maybe we can add this once it's ready. Thanks
