### ISSUE TITLE
etcd crashed by a panic

### ISSUE THREAD

**Issue by jbking** [coreos/etcd#4171]
The problem is introduced by this.

https://github.com/coreos/etcd/commit/1f97f2dc36c9b5a9770886475e3af52b9d34fc8d#diff-8663bb0f53797ae80ef14f3e44668a55

We use a7287b6374b69f2db83e7eafc959dda703c02a22

How to reproduce

1. build etcd.
2. execute the etcd.
3. execute a command with etcdctl.

```
$ etcdctl --peers "http://127.0.0.1:4001" ls
panic: interface conversion: net.Conn is *netutil.limitListenerConn, not *net.TCPConn

goroutine 69 [running]:
github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc20810d0e0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:53 +0xe3
net/http.(*Server).Serve(0xc208043a40, 0x7f5f675ab788, 0xc20810d0e0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
github.com/coreos/etcd/etcdmain.serveHTTP(0x7f5f675ab788, 0xc20810d0e0, 0x7f5f675ac898, 0xc20812b920, 0x0, 0x0, 0x0)
        /go/src/github.com/coreos/etcd/etcdmain/http.go:39 +0x1be
github.com/coreos/etcd/etcdmain.func·006(0x7f5f675ab788, 0xc20810d0e0)
        /go/src/github.com/coreos/etcd/etcdmain/etcd.go:326 +0x80
created by github.com/coreos/etcd/etcdmain.startEtcd
        /go/src/github.com/coreos/etcd/etcdmain/etcd.go:327 +0x25a8

(snip)
```

**Comment by gyuho** [comment]
Yes, this is a bug. Confirmed that I see the same error message. Thanks for reporting. We will investigate.

**Comment by xiang90** [comment]
@jbking It should be fixed. Please give it a try.

**Comment by jbking** [comment]
It works. Thanks.l
