### ISSUE TITLE
TestWatchCancelRunning fails

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4388]
```
=== RUN   TestWatchCancelRunning
2016-02-02 22:51:31.459440 I | etcdserver: name = node7426964939554084645
2016-02-02 22:51:31.459459 I | etcdserver: data dir = /tmp/etcd011682120
2016-02-02 22:51:31.459465 I | etcdserver: member dir = /tmp/etcd011682120/member
2016-02-02 22:51:31.459471 I | etcdserver: heartbeat = 10ms
2016-02-02 22:51:31.459477 I | etcdserver: election = 100ms
2016-02-02 22:51:31.459482 I | etcdserver: snapshot count = 0
2016-02-02 22:51:31.459495 I | etcdserver: advertise client URLs = http://127.0.0.1:20306
2016-02-02 22:51:31.459502 I | etcdserver: name = node7922082315856329196
2016-02-02 22:51:31.459511 I | etcdserver: data dir = /tmp/etcd279984717
2016-02-02 22:51:31.459519 I | etcdserver: member dir = /tmp/etcd279984717/member
2016-02-02 22:51:31.459525 I | etcdserver: heartbeat = 10ms
2016-02-02 22:51:31.459531 I | etcdserver: election = 100ms
2016-02-02 22:51:31.459536 I | etcdserver: snapshot count = 0
2016-02-02 22:51:31.459560 I | etcdserver: advertise client URLs = http://127.0.0.1:20304
2016-02-02 22:51:31.459570 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:20303
2016-02-02 22:51:31.459592 I | etcdserver: initial cluster = node7426964939554084645=http://127.0.0.1:20305,node7544293796608738916=http://127.0.0.1:20301,node7922082315856329196=http://127.0.0.1:20303
2016-02-02 22:51:31.459714 I | etcdserver: name = node7544293796608738916
2016-02-02 22:51:31.459729 I | etcdserver: data dir = /tmp/etcd225993510
2016-02-02 22:51:31.459737 I | etcdserver: member dir = /tmp/etcd225993510/member
2016-02-02 22:51:31.459743 I | etcdserver: heartbeat = 10ms
2016-02-02 22:51:31.459749 I | etcdserver: election = 100ms
2016-02-02 22:51:31.459755 I | etcdserver: snapshot count = 0
2016-02-02 22:51:31.459765 I | etcdserver: advertise client URLs = http://127.0.0.1:20302
2016-02-02 22:51:31.459773 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:20301
2016-02-02 22:51:31.459791 I | etcdserver: initial cluster = node7426964939554084645=http://127.0.0.1:20305,node7544293796608738916=http://127.0.0.1:20301,node7922082315856329196=http://127.0.0.1:20303
2016-02-02 22:51:31.459845 I | etcdserver: starting member 7323412980a55600 in cluster afdcd60a10c157b0
2016-02-02 22:51:31.459873 I | raft: 7323412980a55600 became follower at term 0
2016-02-02 22:51:31.459882 I | raft: newRaft 7323412980a55600 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-02-02 22:51:31.459887 I | raft: 7323412980a55600 became follower at term 1
2016-02-02 22:51:31.459922 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:20305
2016-02-02 22:51:31.459950 I | etcdserver: initial cluster = node7426964939554084645=http://127.0.0.1:20305,node7544293796608738916=http://127.0.0.1:20301,node7922082315856329196=http://127.0.0.1:20303
2016-02-02 22:51:31.460059 I | etcdserver: starting member 39c04de534faac73 in cluster afdcd60a10c157b0
2016-02-02 22:51:31.460093 I | raft: 39c04de534faac73 became follower at term 0
2016-02-02 22:51:31.460105 I | raft: newRaft 39c04de534faac73 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-02-02 22:51:31.460113 I | raft: 39c04de534faac73 became follower at term 1
2016-02-02 22:51:31.460228 I | etcdserver: starting member 934d53795cc09315 in cluster afdcd60a10c157b0
2016-02-02 22:51:31.460260 I | raft: 934d53795cc09315 became follower at term 0
2016-02-02 22:51:31.460271 I | raft: newRaft 934d53795cc09315 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-02-02 22:51:31.460278 I | raft: 934d53795cc09315 became follower at term 1
2016-02-02 22:51:31.464190 I | etcdserver: set snapshot count to default 10000
2016-02-02 22:51:31.471271 I | etcdserver: starting server... [version: 2.3.0-alpha.0+git, cluster version: to_be_decided]
2016-02-02 22:51:31.476053 I | etcdserver: set snapshot count to default 10000
2016-02-02 22:51:31.476088 I | etcdserver: starting server... [version: 2.3.0-alpha.0+git, cluster version: to_be_decided]
2016-02-02 22:51:31.476395 N | etcdserver: added member 39c04de534faac73 [http://127.0.0.1:20301] to cluster afdcd60a10c157b0
2016-02-02 22:51:31.476509 I | etcdserver: set snapshot count to default 10000
2016-02-02 22:51:31.476527 I | etcdserver: starting server... [version: 2.3.0-alpha.0+git, cluster version: to_be_decided]
2016-02-02 22:51:31.476562 N | etcdserver: added local member 7323412980a55600 [http://127.0.0.1:20303] to cluster afdcd60a10c157b0
2016-02-02 22:51:31.476662 N | etcdserver: added member 934d53795cc09315 [http://127.0.0.1:20305] to cluster afdcd60a10c157b0
2016-02-02 22:51:31.476901 I | rafthttp: the connection with 39c04de534faac73 became active
2016-02-02 22:51:31.477078 N | etcdserver: added local member 39c04de534faac73 [http://127.0.0.1:20301] to cluster afdcd60a10c157b0
2016-02-02 22:51:31.477176 N | etcdserver: added member 7323412980a55600 [http://127.0.0.1:20303] to cluster afdcd60a10c157b0
2016-02-02 22:51:31.477299 N | etcdserver: added member 934d53795cc09315 [http://127.0.0.1:20305] to cluster afdcd60a10c157b0
2016-02-02 22:51:31.477380 I | rafthttp: the connection with 7323412980a55600 became active
2016-02-02 22:51:31.477468 I | rafthttp: the connection with 7323412980a55600 became active
2016-02-02 22:51:31.477528 N | etcdserver: added member 39c04de534faac73 [http://127.0.0.1:20301] to cluster afdcd60a10c157b0
2016-02-02 22:51:31.477702 N | etcdserver: added member 7323412980a55600 [http://127.0.0.1:20303] to cluster afdcd60a10c157b0
2016-02-02 22:51:31.477857 N | etcdserver: added local member 934d53795cc09315 [http://127.0.0.1:20305] to cluster afdcd60a10c157b0
2016-02-02 22:51:31.480118 I | rafthttp: the connection with 39c04de534faac73 became active
2016-02-02 22:51:31.480233 I | rafthttp: the connection with 934d53795cc09315 became active
2016-02-02 22:51:31.480342 I | rafthttp: the connection with 934d53795cc09315 became active
2016-02-02 22:51:31.500033 I | raft: 7323412980a55600 is starting a new election at term 1
2016-02-02 22:51:31.500085 I | raft: 7323412980a55600 became candidate at term 2
2016-02-02 22:51:31.500092 I | raft: 7323412980a55600 received vote from 7323412980a55600 at term 2
2016-02-02 22:51:31.500102 I | raft: 7323412980a55600 [logterm: 1, index: 3] sent vote request to 39c04de534faac73 at term 2
2016-02-02 22:51:31.500111 I | raft: 7323412980a55600 [logterm: 1, index: 3] sent vote request to 934d53795cc09315 at term 2
2016-02-02 22:51:31.500266 I | raft: 39c04de534faac73 [term: 1] received a MsgVote message with higher term from 7323412980a55600 [term: 2]
2016-02-02 22:51:31.500288 I | raft: 39c04de534faac73 became follower at term 2
2016-02-02 22:51:31.500316 I | raft: 39c04de534faac73 [logterm: 1, index: 3, vote: 0] voted for 7323412980a55600 [logterm: 1, index: 3] at term 2
2016-02-02 22:51:31.500351 I | raft: 934d53795cc09315 [term: 1] received a MsgVote message with higher term from 7323412980a55600 [term: 2]
2016-02-02 22:51:31.500366 I | raft: 934d53795cc09315 became follower at term 2
2016-02-02 22:51:31.500392 I | raft: 934d53795cc09315 [logterm: 1, index: 3, vote: 0] voted for 7323412980a55600 [logterm: 1, index: 3] at term 2
2016-02-02 22:51:31.500413 I | raft: 7323412980a55600 received vote from 39c04de534faac73 at term 2
2016-02-02 22:51:31.500420 I | raft: 7323412980a55600 [quorum:2] has received 2 votes and 0 vote rejections
2016-02-02 22:51:31.500431 I | raft: 7323412980a55600 became leader at term 2
2016-02-02 22:51:31.500439 I | raft: raft.node: 7323412980a55600 elected leader 7323412980a55600 at term 2
2016-02-02 22:51:31.500554 I | raft: raft.node: 39c04de534faac73 elected leader 7323412980a55600 at term 2
2016-02-02 22:51:31.500599 I | raft: raft.node: 934d53795cc09315 elected leader 7323412980a55600 at term 2
2016-02-02 22:51:31.501052 I | etcdserver: published {Name:node7922082315856329196 ClientURLs:[http://127.0.0.1:20304]} to cluster afdcd60a10c157b0
2016-02-02 22:51:31.501273 I | etcdserver: published {Name:node7544293796608738916 ClientURLs:[http://127.0.0.1:20302]} to cluster afdcd60a10c157b0
2016-02-02 22:51:31.501284 I | etcdserver: setting up the initial cluster version to 2.3
2016-02-02 22:51:31.501509 N | etcdserver: set the initial cluster version to 2.3
2016-02-02 22:51:31.501554 N | etcdserver: set the initial cluster version to 2.3
2016-02-02 22:51:31.501713 N | etcdserver: set the initial cluster version to 2.3
2016-02-02 22:51:31.501856 I | etcdserver: published {Name:node7426964939554084645 ClientURLs:[http://127.0.0.1:20306]} to cluster afdcd60a10c157b0
2016-02-02 22:51:31.512786 E | rafthttp: failed to read 7323412980a55600 on stream MsgApp v2 (net/http: request canceled)
2016-02-02 22:51:31.512815 I | rafthttp: the connection with 7323412980a55600 became inactive
2016-02-02 22:51:31.513317 E | rafthttp: failed to read 934d53795cc09315 on stream MsgApp v2 (net/http: request canceled)
2016-02-02 22:51:31.513336 I | rafthttp: the connection with 934d53795cc09315 became inactive
2016-02-02 22:51:31.514558 E | rafthttp: failed to read 934d53795cc09315 on stream Message (net/http: request canceled)
2016-02-02 22:51:31.514580 I | rafthttp: the connection with 934d53795cc09315 became inactive
panic: assertion failed: tx closed

goroutine 18485 [running]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt._assert(0x0, 0xedbcf0, 0x9, 0x0, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:790 +0xee
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*Cursor).seek(0xc821631170, 0x13a8294, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/cursor.go:155 +0x94
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*Bucket).Bucket(0xc823c8c478, 0x13a8294, 0x4, 0x4, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/bucket.go:112 +0x180
github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt.(*Tx).Bucket(0xc823c8c460, 0x13a8294, 0x4, 0x4, 0xc820050dc0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/boltdb/bolt/tx.go:100 +0x4b
github.com/coreos/etcd/storage/backend.(*batchTx).UnsafeRange(0xc821def2c0, 0x13a8294, 0x4, 0x4, 0x13a8a30, 0x10, 0x10, 0x0, 0x0, 0x0, ...)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/batch_tx.go:72 +0xa5
github.com/coreos/etcd/storage.(*consistentWatchableStore).consistentIndex(0xc821defba0, 0x9)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/consistent_watchable_store.go:136 +0xbc
github.com/coreos/etcd/storage.(*consistentWatchableStore).TxnBegin(0xc821defba0, 0x108796f)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/consistent_watchable_store.go:92 +0x86
github.com/coreos/etcd/storage.(*consistentWatchableStore).Put(0xc821defba0, 0xc820050d10, 0x1, 0x8, 0xc820050dc0, 0x1, 0x8, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/consistent_watchable_store.go:64 +0x42
github.com/coreos/etcd/etcdserver.applyPut(0xffffffffffffffff, 0x7f157ebdbf20, 0xc821defba0, 0x7f157ebc7b58, 0xc823186550, 0xc820221b40, 0x0, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/v3demo_server.go:233 +0x261
github.com/coreos/etcd/etcdserver.(*EtcdServer).applyV3Request(0xc820072000, 0xc821bc4320, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/v3demo_server.go:196 +0x2d2
github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0xc820072000, 0xc82017c288, 0x1, 0x7, 0xc822b6fb80, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:1025 +0x568
github.com/coreos/etcd/etcdserver.(*EtcdServer).applyEntries(0xc820072000, 0xc822b6fb80, 0xc821631ef8)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:674 +0x2cc
github.com/coreos/etcd/etcdserver.(*EtcdServer).applyAll(0xc820072000, 0xc822b6fb80, 0xc821631ef8)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:590 +0x5b
github.com/coreos/etcd/etcdserver.(*EtcdServer).startApplier.func1.1(0xc82017c288, 0x1, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:501 +0x61
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).startApplier.func1
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:517 +0x2bf

goroutine 1 [chan receive]:
testing.RunTests(0x108d610, 0x13c61c0, 0x12, 0x12, 0x1)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc821e91f08, 0x4)
	/usr/local/go/src/testing/testing.go:494 +0x70
github.com/coreos/etcd/clientv3/integration.TestMain(0xc821e91f08)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/integration/main_test.go:15 +0x21
main.main()
	github.com/coreos/etcd/clientv3/integration/_test/_testmain.go:86 +0x113

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 28 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc8201c4a40)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x7c
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc0

goroutine 68 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc8201c5ce0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x7c
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc0

goroutine 18333 [runnable]:
syscall.Syscall(0x3, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0xb, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:296 +0x4a
net.(*netFD).destroy(0xc821579a40)
	/usr/local/go/src/net/fd_unix.go:135 +0x46
net.(*netFD).readUnlock(0xc821579a40)
	/usr/local/go/src/net/fd_unix.go:169 +0x45
net.(*netFD).accept(0xc821579a40, 0x0, 0x7f157ebc1028, 0xc8200148a0)
	/usr/local/go/src/net/fd_unix.go:418 +0x2b5
net.(*TCPListener).AcceptTCP(0xc820030368, 0xc821605700, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820030368, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
net/http/httptest.(*historyListener).Accept(0xc822b0ebd0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/httptest/server.go:48 +0x63
net/http.(*Server).Serve(0xc8215f2f60, 0x7f157ebcb340, 0xc822b0ebd0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
created by net/http/httptest.(*Server).Start
	/usr/local/go/src/net/http/httptest/server.go:109 +0x380

goroutine 18161 [runnable]:
github.com/coreos/etcd/pkg/testutil.interestingGoroutines(0x0, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/testutil/leak.go:103 +0x5d
github.com/coreos/etcd/pkg/testutil.AfterTest(0xc82018e7e0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/testutil/leak.go:86 +0x1ca
github.com/coreos/etcd/clientv3/integration.runWatchTest(0xc82018e7e0, 0x108d238)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/integration/watch_test.go:60 +0x22f
github.com/coreos/etcd/clientv3/integration.TestWatchCancelRunning(0xc82018e7e0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/integration/watch_test.go:215 +0x2d
testing.tRunner(0xc82018e7e0, 0x13c6358)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 18267 [chan receive]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func1(0xc820072000, 0xc822b3f7a0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:562 +0x151
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc820072000)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:583 +0x5f4
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:433 +0x49a

goroutine 18297 [select]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).startApplier.func1(0xc822b3f7a0, 0xc820072000, 0xc822b6fb80)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:512 +0x495
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).startApplier
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:530 +0xa4

goroutine 18425 [runnable]:
net.runtime_pollWait(0x7f157ebcc240, 0x72, 0xc8200141d0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc826478ae0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc826478ae0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc826478a80, 0xc8215ca000, 0x1000, 0x1000, 0x0, 0x7f157ebc1050, 0xc8200141d0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200302f8, 0xc8215ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/coreos/etcd/pkg/transport.timeoutConn.Read(0x7f157ebc7188, 0xc8200302f8, 0x0, 0x0, 0xc8215ca000, 0x1000, 0x1000, 0x635246, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_conn.go:43 +0x1b8
github.com/coreos/etcd/pkg/transport.(*timeoutConn).Read(0xc822b1cb60, 0xc8215ca000, 0x1000, 0x1000, 0xc8215e0fb8, 0x0, 0x0)
	<autogenerated>:42 +0xc8
net/http.noteEOFReader.Read(0x7f157ebc7310, 0xc822b1cb60, 0xc8215f5b28, 0xc8215ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc822b1cb80, 0xc8215ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8215e0a80)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8215e0a80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8215f5ad0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 18426 [select]:
net/http.(*persistConn).writeLoop(0xc8215f5ad0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
exit status 2
FAIL	github.com/coreos/etcd/clientv3/integration	10.930s
```

**Comment by xiang90** [comment]
This issues seems to be fixed by https://github.com/coreos/etcd/commit/a89ba1e583f2847e3c74e579fdfd4a3665b73441.

Since we now stop the scheduler before we stop the backend.

Previously the panic is caused by the bad stop ordering https://github.com/coreos/etcd/blob/e2146e20809a9c81284da22deaa43443b9754c61/etcdserver/server.go#L559-L563. We should wait for the stop of the applier before we can stop the backend.

**Comment by heyitsanthony** [comment]
Agreed
