### ISSUE TITLE
etcd-tester: panics

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4463]
```
8 Feb 2016 23:48:11.320 2016/02/09 07:48:11 etcd-tester: [round#211 case#5] checking current storage hashes...
» 8 Feb 2016 23:48:19.428 panic: runtime error: invalid memory address or nil pointer dereference
» 8 Feb 2016 23:48:19.430 [signal 0xb code=0x1 addr=0x0 pc=0x40cc2a]
» 8 Feb 2016 23:48:19.430 goroutine 1 [running]:
» 8 Feb 2016 23:48:19.430 main.(*cluster).getKVHash(0xc82018e000, 0x42, 0x0, 0x0)
» 8 Feb 2016 23:48:19.430 /home/gyuho/go/src/github.com/coreos/etcd/tools/functional-tester/etcd-tester/tester.go:242 +0x44a
» 8 Feb 2016 23:48:19.430 main.(*tester).runLoop(0xc8201862d0)
» 8 Feb 2016 23:48:19.430 /home/gyuho/go/src/github.com/coreos/etcd/tools/functional-tester/etcd-tester/tester.go:124 +0x2db0
» 8 Feb 2016 23:48:19.430 main.main()
» 8 Feb 2016 23:48:19.430 /home/gyuho/go/src/github.com/coreos/etcd/tools/functional-tester/etcd-tester/main.go:57 +0x800
» 8 Feb 2016 23:48:19.430 goroutine 17 [syscall, 531 minutes, locked to thread]:
» 8 Feb 2016 23:48:19.430 runtime.goexit()
» 8 Feb 2016 23:48:19.430 /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
» 8 Feb 2016 23:48:19.435 goroutine 93975 [semacquire]:
» 8 Feb 2016 23:48:19.435 sync.runtime_Semacquire(0xc82011769c)
» 8 Feb 2016 23:48:19.435 /usr/local/go/src/runtime/sema.go:43 +0x26
» 8 Feb 2016 23:48:19.435 sync.(*Mutex).Lock(0xc820117698)
» 8 Feb 2016 23:48:19.435 /usr/local/go/src/sync/mutex.go:82 +0x1c4
» 8 Feb 2016 23:48:19.435 sync.(*RWMutex).Lock(0xc820117698)
» 8 Feb 2016 23:48:19.435 /usr/local/go/src/sync/rwmutex.go:82 +0x30
» 8 Feb 2016 23:48:19.436 github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/trace.(*trace).Finish(0xc83ee2bd40)
» 8 Feb 2016 23:48:19.436 /home/gyuho/go/src/github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/trace/trace.go:384 +0x365
» 8 Feb 2016 23:48:19.436 github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc.Invoke(0x7f1043181030, 0xc827963800, 0xcbb560, 0x14, 0xbbbb00, 0xc84dd99ec0, 0xbc4880, 0xc83ce901d8, 0xc8201723f0, 0x0, ...)
» 8 Feb 2016 23:48:19.443 /home/gyuho/go/src/github.com/coreos/etcd/Godeps/_workspace/src/google.golang.org/grpc/call.go:164 +0x7ec
» 8 Feb 2016 23:48:19.443 github.com/coreos/etcd/etcdserver/etcdserverpb.(*kVClient).Put(0xc82395f798, 0x7f1043181030, 0xc827963800, 0xc84dd99ec0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
» 8 Feb 2016 23:48:19.443 /home/gyuho/go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:1207 +0xec
» 8 Feb 2016 23:48:19.443 main.(*stresser).Stress.func1(0x7f10457dbab8, 0xc82163dc80, 0x7f10457dba38, 0xc82395f798, 0xc8200f2b90, 0x19)
» 8 Feb 2016 23:48:19.443 /home/gyuho/go/src/github.com/coreos/etcd/tools/functional-tester/etcd-tester/stresser.go:79 +0x31c
» 8 Feb 2016 23:48:19.443 created by main.(*stresser).Stress
» 8 Feb 2016 23:48:19.444 /home/gyuho/go/src/github.com/coreos/etcd/tools/functional-tester/etcd-tester/stresser.go:92 +0x464
» 8 Feb 2016 23:48:19.444 goroutine 7 [IO wait, 304 minutes]:
» 8 Feb 2016 23:48:19.444 net.runtime_pollWait(0x7f1043180c48, 0x72, 0xc82000e1a0)
» 8 Feb 2016 23:48:19.449 /usr/local/go/src/runtime/netpoll.go:157 +0x60
» 8 Feb 2016 23:48:19.449 net.(*pollDesc).Wait(0xc8201161b0, 0x72, 0x0, 0x0)
» 8 Feb 2016 23:48:19.449 /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
» 8 Feb 2016 23:48:19.449 net.(*pollDesc).WaitRead(0xc8201161b0, 0x0, 0x0)
» 8 Feb 2016 23:48:19.449 /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
» 8 Feb 2016 23:48:19.449 net.(*netFD).Read(0xc820116150, 0xc820195000, 0x1000, 0x1000, 0x0, 0x7f10457d3050, 0xc82000e1a0)
» 8 Feb 2016 23:48:19.449 /usr/local/go/src/net/fd_unix.go:232 +0x23a
» 8 Feb 2016 23:48:19.449 net.(*conn).Read(0xc8200ee128, 0xc820195000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
» 8 Feb 2016 23:48:19.449 /usr/local/go/src/net/net.go:172 +0xe4
» 8 Feb 2016 23:48:19.449 bufio.(*Reader).fill(0xc8200142a0)
» 8 Feb 2016 23:48:19.449 /usr/local/go/src/bufio/bufio.go:97 +0x1e9
» 8 Feb 2016 23:48:19.456 bufio.(*Reader).Read(0xc8200142a0, 0xc82000f790, 0x1, 0x9, 0x0, 0x0, 0x0)
» 8 Feb 2016 23:48:19.456 /usr/local/go/src/bufio/bufio.go:207 +0x260
» 8 Feb 2016 23:48:19.456 io.ReadAtLeast(0x7f10457d7828, 0xc8200142a0, 0xc82000f790, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
» 8 Feb 2016 23:48:19.456 /usr/local/go/src/io/io.go:298 +0xe6
» 8 Feb 2016 23:48:19.456 io.ReadFull(0x7f10457d7828, 0xc8200142a0, 0xc82000f790, 0x1, 0x9, 0xc8200e25f0, 0x0, 0x0)
» 8 Feb 2016 23:48:19.456 /usr/local/go/src/io/io.go:316 +0x62
» 8 Feb 2016 23:48:19.456 encoding/gob.decodeUintReader(0x7f10457d7828, 0xc8200142a0, 0xc82000f790, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
» 8 Feb 2016 23:48:19.456 /usr/local/go/src/encoding/gob/decode.go:121 +0x92
» 8 Feb 2016 23:48:19.456 encoding/gob.(*Decoder).recvMessage(0xc8200e2580, 0xc82033dbd0)
» 8 Feb 2016 23:48:19.456 /usr/local/go/src/encoding/gob/decoder.go:76 +0x5e
» 8 Feb 2016 23:48:19.456 encoding/gob.(*Decoder).decodeTypeSequence(0xc8200e2580, 0xdad400, 0xc8200e2580)
» 8 Feb 2016 23:48:19.461 /usr/local/go/src/encoding/gob/decoder.go:140 +0x47
» 8 Feb 2016 23:48:19.461 encoding/gob.(*Decoder).DecodeValue(0xc8200e2580, 0x99b3a0, 0xc820115620, 0x16, 0x0, 0x0)
» 8 Feb 2016 23:48:19.461 /usr/local/go/src/encoding/gob/decoder.go:208 +0x15d
» 8 Feb 2016 23:48:19.461 encoding/gob.(*Decoder).Decode(0xc8200e2580, 0x99b3a0, 0xc820115620, 0x0, 0x0)
» 8 Feb 2016 23:48:19.461 /usr/local/go/src/encoding/gob/decoder.go:185 +0x289
» 8 Feb 2016 23:48:19.461 net/rpc.(*gobClientCodec).ReadResponseHeader(0xc820115590, 0xc820115620, 0x0, 0x0)
» 8 Feb 2016 23:48:19.461 /usr/local/go/src/net/rpc/client.go:223 +0x51
» 8 Feb 2016 23:48:19.461 net/rpc.(*Client).input(0xc820014360)
» 8 Feb 2016 23:48:19.461 /usr/local/go/src/net/rpc/client.go:109 +0xbf
» 8 Feb 2016 23:48:19.461 created by net/rpc.NewClientWithCodec
» 8 Feb 2016 23:48:19.461 /usr/local/go/src/net/rpc/client.go:201 +0xd2
» 8 Feb 2016 23:48:19.465 goroutine 34 [IO wait, 304 minutes]:
» 8 Feb 2016 23:48:19.465 net.runtime_pollWait(0x7f1043180b88, 0x72, 0xc82000e1a0)
» 8 Feb 2016 23:48:19.465 /usr/local/go/src/runtime/netpoll.go:157 +0x60
» 8 Feb 2016 23:48:19.465 net.(*pollDesc).Wait(0xc8200540d0, 0x72, 0x0, 0x0)
» 8 Feb 2016 23:48:19.465 /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
» 8 Feb 2016 23:48:19.465 net.(*pollDesc).WaitRead(0xc8200540d0, 0x0, 0x0)
» 8 Feb 2016 23:48:19.465 /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
» 8 Feb 2016 23:48:19.465 net.(*netFD).Read(0xc820054070, 0xc820197000, 0x1000, 0x1000, 0x0, 0x7f10457d3050, 0xc82000e1a0)
» 8 Feb 2016 23:48:19.465 /usr/local/go/src/net/fd_unix.go:232 +0x23a
» 8 Feb 2016 23:48:19.465 net.(*conn).Read(0xc8200ee130, 0xc820197000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
» 8 Feb 2016 23:48:19.465 /usr/local/go/src/net/net.go:172 +0xe4
» 8 Feb 2016 23:48:19.467 bufio.(*Reader).fill(0xc82017c180)
» 8 Feb 2016 23:48:19.467 /usr/local/go/src/bufio/bufio.go:97 +0x1e9
» 8 Feb 2016 23:48:19.467 bufio.(*Reader).Read(0xc82017c180, 0xc8200ead10, 0x1, 0x9, 0x0, 0x0, 0x0)
» 8 Feb 2016 23:48:19.467 /usr/local/go/src/bufio/bufio.go:207 +0x260
» 8 Feb 2016 23:48:19.467 io.ReadAtLeast(0x7f10457d7828, 0xc82017c180, 0xc8200ead10, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
» 8 Feb 2016 23:48:19.467 /usr/local/go/src/io/io.go:298 +0xe6
» 8 Feb 2016 23:48:19.467 io.ReadFull(0x7f10457d7828, 0xc82017c180, 0xc8200ead10, 0x1, 0x9, 0xc8200f0570, 0x0, 0x0)
» 8 Feb 2016 23:48:19.467 /usr/local/go/src/io/io.go:316 +0x62
» 8 Feb 2016 23:48:19.467 encoding/gob.decodeUintReader(0x7f10457d7828, 0xc82017c180, 0xc8200ead10, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
» 8 Feb 2016 23:48:19.467 /usr/local/go/src/encoding/gob/decode.go:121 +0x92
» 8 Feb 2016 23:48:19.470 encoding/gob.(*Decoder).recvMessage(0xc8200f0500, 0xc82045fbd0)
» 8 Feb 2016 23:48:19.470 /usr/local/go/src/encoding/gob/decoder.go:76 +0x5e
» 8 Feb 2016 23:48:19.470 encoding/gob.(*Decoder).decodeTypeSequence(0xc8200f0500, 0xdad400, 0xc8200f0500)
» 8 Feb 2016 23:48:19.470 /usr/local/go/src/encoding/gob/decoder.go:140 +0x47
» 8 Feb 2016 23:48:19.470 encoding/gob.(*Decoder).DecodeValue(0xc8200f0500, 0x99b3a0, 0xc82017e990, 0x16, 0x0, 0x0)
» 8 Feb 2016 23:48:19.470 /usr/local/go/src/encoding/gob/decoder.go:208 +0x15d
» 8 Feb 2016 23:48:19.470 encoding/gob.(*Decoder).Decode(0xc8200f0500, 0x99b3a0, 0xc82017e990, 0x0, 0x0)
» 8 Feb 2016 23:48:19.470 /usr/local/go/src/encoding/gob/decoder.go:185 +0x289
» 8 Feb 2016 23:48:19.470 net/rpc.(*gobClientCodec).ReadResponseHeader(0xc82017e900, 0xc82017e990, 0x0, 0x0)
» 8 Feb 2016 23:48:19.470 /usr/local/go/src/net/rpc/client.go:223 +0x51
» 8 Feb 2016 23:48:19.470 net/rpc.(*Client).input(0xc82017c240)
» 8 Feb 2016 23:48:19.540 /usr/local/go/src/net/rpc/client.go:109 +0xbf
» 8 Feb 2016 23:48:19.540 created by net/rpc.NewClientWithCodec
» 8 Feb 2016 23:48:19.541 /usr/local/go/src/net/rpc/client.go:201 +0xd2
» 8 Feb 2016 23:48:19.541 goroutine 8 [IO wait, 304 minutes]:
» 8 Feb 2016 23:48:19.541 net.runtime_pollWait(0x7f1043180ac8, 0x72, 0xc82000e1a0)
» 8 Feb 2016 23:48:19.541 /usr/local/go/src/runtime/netpoll.go:157 +0x60
```

**Comment by gyuho** [comment]
Assume fixed by https://github.com/coreos/etcd/pull/4467. Will reopen when we have the same error again.
