### ISSUE TITLE
functional-tester: runtime: out of memory

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4641]
```
2016-02-28 14:35:29.551551 I | etcd-tester: [round#205 case#5] start injecting failure...
2016-02-28 14:35:29.553905 I | etcd-tester: Stopping 10.240.0.4:2378
2016-02-28 14:35:33.614126 I | etcd-tester: [round#205 case#5] injected failure
2016-02-28 14:35:33.614167 I | etcd-tester: [round#205 case#5] start recovering failure...
2016-02-28 14:35:34.655659 I | etcd-tester: [IMPORTANT] #0: WaitHealth error [2] rpc error: code = 4 desc = "context deadline exceeded" (10.240.0.4:2378) SHUTDOWN <nil> (took 1.00013115s)
2016-02-28 14:35:36.699561 I | etcd-tester: [IMPORTANT] #1: WaitHealth error [2] rpc error: code = 4 desc = "context deadline exceeded" (10.240.0.4:2378) SHUTDOWN <nil> (took 1.000194454s)
2016-02-28 14:35:38.739599 I | etcd-tester: [IMPORTANT] #2: WaitHealth error [2] rpc error: code = 4 desc = "context deadline exceeded" (10.240.0.4:2378) SHUTDOWN <nil> (took 1.000277694s)

2016-02-28 14:49:44.188115 I | etcd-tester: [IMPORTANT] #298: WaitHealth error [2] rpc error: code = 2 desc = "grpc: the client connection is closing" (10.240.0.4:2378) SHUTDOWN <nil> (took 2.587471347s)
2016-02-28 14:49:48.236009 I | etcd-tester: [IMPORTANT] #299: WaitHealth error [2] rpc error: code = 4 desc = "context deadline exceeded" (10.240.0.4:2378) SHUTDOWN <nil> (took 3.002097277s)
2016-02-28 14:49:49.236179 I | etcd-tester: [round#205 case#5] recovery error: [2] rpc error: code = 4 desc = "context deadline exceeded" (10.240.0.4:2378) SHUTDOWN <nil> (took 3.002097277s)
2016-02-28 14:49:49.237324 I | etcd-tester: [round#205 case#5] cleaning up...
```

`agent3` was down from memory issue.

**Comment by gyuho** [comment]
1. agent1: https://storage.googleapis.com/etcd-issue-4641-00/agent1/etcd.log
2. agent2: https://storage.googleapis.com/etcd-issue-4641-00/agent2/etcd.log
3. agent3: https://storage.googleapis.com/etcd-issue-4641-00/agent3/etcd.log
4. tester: https://storage.googleapis.com/etcd-issue-4641-00/tester_logs/tester.log

**Comment by xiang90** [comment]
@gyuho Can you check the log to see what happened?

**Comment by gyuho** [comment]
Yeah checking. All etcd servers were recovered as it requested but just the gRPC connection from agent3 to tester kept being closed. Not sure if it's gRPC issue or bad network.

I just redeployed testing cluster that pings additional v2 endpoint if there's any network issue.
And will try different timeouts as well.

**Comment by xiang90** [comment]
@gyuho I think one of the etcd member actually panics. And there are a few strange stuff in the log.

**Comment by gyuho** [comment]
@xiang90 Oh I missed that panic part. Will take a look. Thanks!

**Comment by gyuho** [comment]
In addition, agent3 panics at `2016/02/28 14:49:02`, while it is recovered at `2016-02-28 14:35:33` and since then having problem connecting to tester-client:

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf52450, 0x16)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc9f1d50000, 0x105e0000, 0x26f100, 0x13d0158)
	/usr/local/go/src/runtime/mem_linux.go:203 +0x9b
runtime.mHeap_SysAlloc(0x13b0260, 0x105e0000, 0xc835b47080)
	/usr/local/go/src/runtime/malloc.go:426 +0x160
runtime.mHeap_Grow(0x13b0260, 0x82f0, 0x0)
	/usr/local/go/src/runtime/mheap.go:628 +0x63
runtime.mHeap_AllocSpanLocked(0x13b0260, 0x82ed, 0x100)
	/usr/local/go/src/runtime/mheap.go:532 +0x5f1
runtime.mHeap_Alloc_m(0x13b0260, 0x82ed, 0x100000000, 0xc900000001)
	/usr/local/go/src/runtime/mheap.go:425 +0x1ac
runtime.mHeap_Alloc.func1()
	/usr/local/go/src/runtime/mheap.go:484 +0x41
runtime.systemstack(0x7fc79bffede8)
	/usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0x13b0260, 0x82ed, 0x10100000000, 0x20)
	/usr/local/go/src/runtime/mheap.go:485 +0x63
runtime.largeAlloc(0x105d9fc8, 0xc800000000, 0xc84c3ad7c0)
	/usr/local/go/src/runtime/malloc.go:748 +0xb3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:637 +0x33
runtime.systemstack(0xc82001b500)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:668

goroutine 47 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc84c3ad5e8 sp=0xc84c3ad5e0
runtime.mallocgc(0x105d9fc8, 0xda1b20, 0xc800000000, 0x42ac35)
	/usr/local/go/src/runtime/malloc.go:638 +0x9c4 fp=0xc84c3ad6b8 sp=0xc84c3ad5e8
runtime.newarray(0xda1b20, 0x3a3071, 0xc839a7c800)
	/usr/local/go/src/runtime/malloc.go:780 +0xc9 fp=0xc84c3ad6f8 sp=0xc84c3ad6b8
runtime.growslice(0xb51c80, 0xc9e45cc000, 0x2e8ca9, 0x2e8ce3, 0x2e8cef, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:97 +0x2c1 fp=0xc84c3ad768 sp=0xc84c3ad6f8
runtime.growslice_n(0xb51c80, 0xc9e45cc000, 0x2e8ca9, 0x2e8ce3, 0xc, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:44 +0xc7 fp=0xc84c3ad7c0 sp=0xc84c3ad768
github.com/coreos/etcd/raft.(*MemoryStorage).Append(0xc8201c60e0, 0xc9547ce708, 0x46, 0xa3, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/raft/storage.go:246 +0x665 fp=0xc84c3ad880 sp=0xc84c3ad7c0
github.com/coreos/etcd/etcdserver.(*raftNode).start.func1(0xc8201b0000)
	/home/gyuho/go/src/github.com/coreos/etcd/etcdserver/raft.go:199 +0x947 fp=0xc84c3adf98 sp=0xc84c3ad880
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc84c3adfa0 sp=0xc84c3adf98
created by github.com/coreos/etcd/etcdserver.(*raftNode).start
	/home/gyuho/go/src/github.com/coreos/etcd/etcdserver/raft.go:210 +0x116

```

`github.com/coreos/etcd/raft/storage.go:246` is:

```go
	switch {
	case uint64(len(ms.ents)) > offset:
		ms.ents = append([]pb.Entry{}, ms.ents[:offset]...)
		ms.ents = append(ms.ents, entries...)
	case uint64(len(ms.ents)) == offset:
		ms.ents = append(ms.ents, entries...)
	default:
		raftLogger.Panicf("missing log entry [last: %d, append at: %d]",
			ms.lastIndex(), entries[0].Index)
	}
```

**Comment by xiang90** [comment]
> since then having problem connecting to tester-client

I do not think this is correct. The test sent a lot of requests to it and it did receive them. There is no issues with the connection between agent3 and the tester. The requests timed out only because some issues at server side. Please check the log to verify this. Thanks!

**Comment by gyuho** [comment]
@xiang90  Right. I will look at server logs more closely. Thanks!

**Comment by gyuho** [comment]
Got one more panic (agent1 panic from `out of memory`):

1. agent1: https://storage.googleapis.com/etcd-issue-4641-01/agent1/etcd.log
2. agent2: https://storage.googleapis.com/etcd-issue-4641-01/agent2/etcd.log
3. agent3: https://storage.googleapis.com/etcd-issue-4641-01/agent3/etcd.log
4. tester: https://storage.googleapis.com/etcd-issue-4641-01/tester.log

**Comment by xiang90** [comment]
dropping the bug label. do not feel this is a "bug".

**Comment by gyuho** [comment]
Yeah, making stresser less intensive, there's no more panic. Current number of concurrent stresser goroutine is 200. When I set it up to 500, it ran out of memory very easily, like once every 10 round. When I set it up to 100, it runs with no problem. We can discuss more in office.

**Comment by gyuho** [comment]
@xiang90 has an idea of smarter rate limiter. This will be resolved once it is implemented in server side.

**Comment by xiang90** [comment]
I think we can close this for now after we start to do compaction+defrag.
