### ISSUE TITLE
Attaching an unknown lease panics etcd

### ISSUE THREAD

**Issue by barakmich** [coreos/etcd#4656]
Client takes a lease ID, stays alive. etcd dies and is wiped. Client reconnects and attempts to use the lease ID.

At the least, this should return an error -- it's a client error (unknown lease?) and shouldn't panic etcd.

```
panic: unexpected error from lease Attach

goroutine 726 [running]:
github.com/coreos/etcd/storage.(*store).put(0xc820073680, 0xc8203123c0, 0x4e, 0x50, 0xc8200ca180, 0x18, 0x20, 0x365334b6fc8e0005)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/kvstore.go:435 +0x8a9
github.com/coreos/etcd/storage.(*store).TxnPut(0xc820073680, 0x737f63844f8a65ee, 0xc8203123c0, 0x4e, 0x50, 0xc8200ca180, 0x18, 0x20, 0x365334b6fc8e0005, 0x6e9050, ...)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/kvstore.go:189 +0xc2
github.com/coreos/etcd/storage.(*watchableStore).TxnPut(0xc8201b2b00, 0x737f63844f8a65ee, 0xc8203123c0, 0x4e, 0x50, 0xc8200ca180, 0x18, 0x20, 0x365334b6fc8e0005, 0xc8200c9050, ...)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/watchable_store.go:123 +0xb0
github.com/coreos/etcd/storage.(*consistentWatchableStore).TxnPut(0xc8201babe0, 0x737f63844f8a65ee, 0xc8203123c0, 0x4e, 0x50, 0xc8200ca180, 0x18, 0x20, 0x365334b6fc8e0005, 0xc81fff9af1, ...)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/consistent_watchable_store.go:117 +0xca
github.com/coreos/etcd/storage.(*consistentWatchableStore).Put(0xc8201babe0, 0xc8203123c0, 0x4e, 0x50, 0xc8200ca180, 0x18, 0x20, 0x365334b6fc8e0005, 0x40d0ed)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/consistent_watchable_store.go:65 +0xbd
github.com/coreos/etcd/etcdserver.applyPut(0xffffffffffffffff, 0x7fab75eb4988, 0xc8201babe0, 0xc8201b3500, 0xc8201babe0, 0x0, 0x0)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/v3demo_server.go:189 +0x1e3
github.com/coreos/etcd/etcdserver.(*EtcdServer).applyV3Request(0xc82018c4e0, 0xc820312370, 0x0, 0x0)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/v3demo_server.go:158 +0x2b2
github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0xc82018c4e0, 0xc8203122d0, 0x1, 0x1, 0xc8201a00c0, 0x0, 0x0)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:1013 +0x568
github.com/coreos/etcd/etcdserver.(*EtcdServer).applyEntries(0xc82018c4e0, 0xc8201a00c0, 0xc8205a7ef8)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:665 +0x2be
github.com/coreos/etcd/etcdserver.(*EtcdServer).applyAll(0xc82018c4e0, 0xc8201a00c0, 0xc8205a7ef8)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:584 +0x5b
github.com/coreos/etcd/etcdserver.(*EtcdServer).startApplier.func1.1(0xc8203122d0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:495 +0x61
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).startApplier.func1
	/home/barak/src/agro/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:511 +0x2bf

```

**Comment by xiang90** [comment]
This is a bug I believe.

**Comment by heyitsanthony** [comment]
@barakmich are you using master? the line numbers seem out of sync

**Comment by xiang90** [comment]
@barakmich This is already fixed in master. See #4680.
