### ISSUE TITLE
Node can't join cluster after upgrade from 2.2.5 to 2.3.0

### ISSUE THREAD

**Issue by onorua** [coreos/etcd#4835]
## logs 
```
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: recognized and used environment variable ETCD_DATA_DIR=/srv/data/etcd/etcd27
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: recognized and used environment variable ETCD_NAME=etcd27
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: etcd Version: 2.3.0
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: Git SHA: 5e6eb7e
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: Go Version: go1.5.3
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: Go OS/Arch: linux/amd64
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: found invalid file/dir data under data dir /srv/data/etcd/etcd27 (Ignore this if you are upgrading etcd)
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-26.k8s.otlabs.fr:7001
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-25.k8s.otlabs.fr:7001
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-27.k8s.otlabs.fr:7001
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: listening for peers on http://172.16.236.27:7001
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: listening for client requests on http://172.16.236.27:4001
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: resolving ip-172-16-236-27.k8s.otlabs.fr:7001 to 172.16.236.27:7001
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: stopping listening for client requests on http://172.16.236.27:4001
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: stopping listening for peers on http://172.16.236.27:7001
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: member 499cd6aebfad0c5d has already been bootstrapped
```
## systemd service:
```
[Unit]
Description=etcd key-value store
Documentation=https://github.com/coreos/etcd

[Service]
User=etcd
Type=notify
Environment=ETCD_DATA_DIR=/srv/data/etcd/etcd27
Environment=ETCD_NAME=etcd27
ExecStart=/usr/local/bin/etcd \
    --addr 172.16.236.27:4001 \
    --bind-addr 172.16.236.27:4001 \
    --initial-cluster-state new \
    --initial-cluster-token mycluster \
    --listen-peer-urls  http://172.16.236.27:7001 \
    --initial-advertise-peer-urls http://172.16.236.27:7001 \
    --snapshot-count=5000 \
    --discovery-srv 'k8s.otlabs.fr'
Restart=always
RestartSec=10s
LimitNOFILE=40000

[Install]
WantedBy=multi-user.target
```

Did I miss something?

**Comment by xiang90** [comment]
@onorua 

```
Mar 22 07:33:33 ip-172-16-236-27 etcd[11332]: found invalid file/dir data under data dir /srv/data/etcd/etcd27 (Ignore this if you are upgrading etcd)
```

This does not seem right (even you are upgrading etcd). etcd complaints about the bootstrapping since the member dir is not configured correctly. Or etcd should just restart instead of doing a bootstrap.

**Comment by xiang90** [comment]
@onorua Can you do a ls under dir `/srv/data/etcd/etcd27`?

**Comment by onorua** [comment]
Unfortunately I've removed the dir, instead of `mv` to it. Will try to reproduce it again, if I'll be "lucky".

**Comment by onorua** [comment]
I've got the same error message, but I've got another one this time as well, don't know if it is valid reproduce or not. 
What I did, I'm moving from etcd inside docker container, to etcd as a systemd service. In order to do this, I stop the container, create user etcd under which it is running, and make
```
chown -R etcd /srv/data/etcd/etcd27
```
Then my etcd server tries to start, but fail with following errors:
```
Mar 22 18:55:31 ip-172-16-236-27 systemd[1]: Starting etcd key-value store...
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: recognized and used environment variable ETCD_DATA_DIR=/srv/data/etcd/etcd27
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: recognized and used environment variable ETCD_NAME=etcd27
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: etcd Version: 2.3.0
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: Git SHA: 5e6eb7e
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: Go Version: go1.5.3
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: Go OS/Arch: linux/amd64
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: found invalid file/dir data under data dir /srv/data/etcd/etcd27 (Ignore this if you are upgrading etcd)
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: the server is already initialized as member before, starting as etcd member...
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-27.k8s.otlabs.fr:7001
Mar 22 18:55:31 ip-172-16-236-27 etcd[30816]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-25.k8s.otlabs.fr:7001
Mar 22 18:55:31 ip-172-16-236-27 systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 18:55:31 ip-172-16-236-27 systemd[1]: Failed to start etcd key-value store.
Mar 22 18:55:31 ip-172-16-236-27 systemd[1]: etcd.service: Unit entered failed state.
Mar 22 18:55:31 ip-172-16-236-27 systemd[1]: etcd.service: Failed with result 'exit-code'.
Mar 22 18:55:31 ip-172-16-236-27 systemd[1]: Stopped etcd key-value store.
Mar 22 18:55:32 ip-172-16-236-27 systemd[1]: Starting etcd key-value store...
Mar 22 18:55:32 ip-172-16-236-27 etcd[30961]: recognized and used environment variable ETCD_DATA_DIR=/srv/data/etcd/etcd27
Mar 22 18:55:32 ip-172-16-236-27 etcd[30961]: recognized and used environment variable ETCD_NAME=etcd27
Mar 22 18:55:32 ip-172-16-236-27 etcd[30961]: etcd Version: 2.3.0
Mar 22 18:55:32 ip-172-16-236-27 etcd[30961]: Git SHA: 5e6eb7e
Mar 22 18:55:32 ip-172-16-236-27 etcd[30961]: Go Version: go1.5.3
Mar 22 18:55:32 ip-172-16-236-27 etcd[30961]: Go OS/Arch: linux/amd64
Mar 22 18:55:32 ip-172-16-236-27 etcd[30961]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Mar 22 18:55:32 ip-172-16-236-27 etcd[30961]: found invalid file/dir data under data dir /srv/data/etcd/etcd27 (Ignore this if you are upgrading etcd)
Mar 22 18:55:32 ip-172-16-236-27 etcd[30961]: the server is already initialized as member before, starting as etcd member...
Mar 22 18:55:32 ip-172-16-236-27 etcd[30961]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-27.k8s.otlabs.fr:7001
Mar 22 18:55:32 ip-172-16-236-27 systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 18:55:32 ip-172-16-236-27 systemd[1]: Failed to start etcd key-value store.
Mar 22 18:55:32 ip-172-16-236-27 systemd[1]: etcd.service: Unit entered failed state.
Mar 22 18:55:32 ip-172-16-236-27 systemd[1]: etcd.service: Failed with result 'exit-code'.
```
then couple of times it can't start up, and then, it shows this:
```
Mar 22 19:16:20 ip-172-16-236-27 systemd[1]: Starting etcd key-value store...
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: recognized and used environment variable ETCD_DATA_DIR=/srv/data/etcd/etcd27
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: recognized and used environment variable ETCD_NAME=etcd27
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: etcd Version: 2.3.0
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: Git SHA: 5e6eb7e
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: Go Version: go1.5.3
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: Go OS/Arch: linux/amd64
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: found invalid file/dir data under data dir /srv/data/etcd/etcd27 (Ignore this if you are upgrading etcd)
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: the server is already initialized as member before, starting as etcd member...
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-25.k8s.otlabs.fr:7001
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-26.k8s.otlabs.fr:7001
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-27.k8s.otlabs.fr:7001
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: listening for peers on http://172.16.236.27:7001
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: listening for client requests on http://172.16.236.27:4001
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: recovered store from snapshot at index 275055
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: name = etcd27
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: data dir = /srv/data/etcd/etcd27
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: member dir = /srv/data/etcd/etcd27/member
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: heartbeat = 100ms
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: election = 1000ms
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: snapshot count = 5000
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: advertise client URLs = http://172.16.236.27:4001
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: restarting member 499cd6aebfad0c5d in cluster 67812c605c43d31c at commit index 277055
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: 499cd6aebfad0c5d became follower at term 2018
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: newRaft 499cd6aebfad0c5d [peers: [499cd6aebfad0c5d,65b064a223e15a04,c095da2c1856e37e], term: 2018, commit: 277055, applied: 275055, lastindex: 277055, lastterm: 2018]
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: added member 499cd6aebfad0c5d [http://ip-172-16-236-27.k8s.otlabs.fr:7001] to cluster 67812c605c43d31c from store
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: added member 65b064a223e15a04 [http://ip-172-16-236-26.k8s.otlabs.fr:7001] to cluster 67812c605c43d31c from store
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: added member c095da2c1856e37e [http://ip-172-16-236-25.k8s.otlabs.fr:7001] to cluster 67812c605c43d31c from store
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: set the cluster version to 2.3 from store
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: starting server... [version: 2.3.0, cluster version: 2.3]
Mar 22 19:16:20 ip-172-16-236-27 systemd[1]: Started etcd key-value store.
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: the connection with 65b064a223e15a04 became active
Mar 22 19:16:20 ip-172-16-236-27 etcd[28116]: the connection with c095da2c1856e37e became active
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: 499cd6aebfad0c5d [term: 2018] received a MsgHeartbeat message with higher term from c095da2c1856e37e [term: 2019]
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: 499cd6aebfad0c5d became follower at term 2019
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: tocommit(285191) is out of range [lastIndex(277055)]. Was the raft log corrupted, truncated, or lost?
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: panic: tocommit(285191) is out of range [lastIndex(277055)]. Was the raft log corrupted, truncated, or lost?
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: goroutine 23 [running]:
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc8201c5600, 0x1055340, 0x5d, 0xc822472340, 0x2, 0x2)
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x191
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc82021a850, 0x45a07)
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/log.go:194 +0x1a6
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc82111c000, 0x8, 0x499cd6aebfad0c5d, 0xc095da2c1856e37e, 0x7e3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:771 +0x44
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: github.com/coreos/etcd/raft.stepFollower(0xc82111c000, 0x8, 0x499cd6aebfad0c5d, 0xc095da2c1856e37e, 0x7e3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:736 +0x119a
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: github.com/coreos/etcd/raft.(*raft).Step(0xc82111c000, 0x8, 0x499cd6aebfad0c5d, 0xc095da2c1856e37e, 0x7e3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: github.com/coreos/etcd/raft.(*node).run(0xc821389400, 0xc82111c000)
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:310 +0x8fd
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: created by github.com/coreos/etcd/raft.RestartNode
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:215 +0x2e3
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: goroutine 1 [chan receive]:
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: github.com/coreos/etcd/etcdmain.Main()
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:195 +0x195b
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: main.main()
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x14
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: goroutine 42 [chan receive]:
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc8201c41a0)
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x7c
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc0
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: goroutine 63 [chan receive]:
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc8201c5980)
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x7c
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]:         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc0
Mar 22 19:16:21 ip-172-16-236-27 etcd[28116]: goroutine 83 [syscall]:
Mar 22 19:16:21 ip-172-16-236-27 systemd[1]: etcd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 22 19:16:21 ip-172-16-236-27 systemd[1]: etcd.service: Unit entered failed state.
Mar 22 19:16:21 ip-172-16-236-27 systemd[1]: etcd.service: Failed with result 'exit-code'.
Mar 22 19:16:31 ip-172-16-236-27 systemd[1]: etcd.service: Service hold-off time over, scheduling restart.
Mar 22 19:16:31 ip-172-16-236-27 systemd[1]: Stopped etcd key-value store.
Mar 22 19:16:31 ip-172-16-236-27 systemd[1]: Starting etcd key-value store...
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: recognized and used environment variable ETCD_DATA_DIR=/srv/data/etcd/etcd27
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: recognized and used environment variable ETCD_NAME=etcd27
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: etcd Version: 2.3.0
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: Git SHA: 5e6eb7e
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: Go Version: go1.5.3
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: Go OS/Arch: linux/amd64
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: found invalid file/dir data under data dir /srv/data/etcd/etcd27 (Ignore this if you are upgrading etcd)
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: the server is already initialized as member before, starting as etcd member...
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-25.k8s.otlabs.fr:7001
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-27.k8s.otlabs.fr:7001
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: got bootstrap from DNS for etcd-server at http://ip-172-16-236-26.k8s.otlabs.fr:7001
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: listening for peers on http://172.16.236.27:7001
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: listening for client requests on http://172.16.236.27:4001
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: recovered store from snapshot at index 275055
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: name = etcd27
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: data dir = /srv/data/etcd/etcd27
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: member dir = /srv/data/etcd/etcd27/member
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: heartbeat = 100ms
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: election = 1000ms
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: snapshot count = 5000
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: advertise client URLs = http://172.16.236.27:4001
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: restarting member 499cd6aebfad0c5d in cluster 67812c605c43d31c at commit index 277055
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: 499cd6aebfad0c5d became follower at term 2018
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: newRaft 499cd6aebfad0c5d [peers: [499cd6aebfad0c5d,65b064a223e15a04,c095da2c1856e37e], term: 2018, commit: 277055, applied: 275055, lastindex: 277055, lastterm: 2018]
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: added member 499cd6aebfad0c5d [http://ip-172-16-236-27.k8s.otlabs.fr:7001] to cluster 67812c605c43d31c from store
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: added member 65b064a223e15a04 [http://ip-172-16-236-26.k8s.otlabs.fr:7001] to cluster 67812c605c43d31c from store
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: added member c095da2c1856e37e [http://ip-172-16-236-25.k8s.otlabs.fr:7001] to cluster 67812c605c43d31c from store
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: set the cluster version to 2.3 from store
Mar 22 19:16:31 ip-172-16-236-27 etcd[29103]: the connection with 65b064a223e15a04 became active
```
folder looks like this:
```
/srv/data/etcd/etcd27# ls -la
total 16
drwx------ 4 etcd root 4096 Mar 22 19:18 .
drwxr-xr-x 3 root root 4096 Mar 22 07:51 ..
drwx------ 3 etcd root 4096 Mar 22 18:55 data
drwx------ 4 etcd root 4096 Mar 22 19:18 member
/srv/data/etcd/etcd27# find . 
.
./data
./data/member
./data/member/wal
./data/member/wal/0000000000000001-00000000000449d4.wal
./data/member/wal/0000000000000000-0000000000000000.wal
./data/member/snap
./data/member/snap/000000000000004b-00000000000061ad.snap
./data/member/snap/00000000000007e2-000000000004326f.snap
./data/member/snap/00000000000007e3-00000000000445f8.snap
./data/member/snap/00000000000006ce-00000000000088bf.snap
./data/member/snap/00000000000007e3-0000000000045981.snap
./member
./member/wal
./member/wal/0000000000000006-000000000003c492.wal
./member/wal/0000000000000002-0000000000015243.wal
./member/wal/0000000000000004-0000000000028a41.wal
./member/wal/0000000000000005-0000000000032711.wal
./member/wal/0000000000000003-000000000001ee7a.wal
./member/snap
./member/snap/00000000000007e2-0000000000041ee6.snap
./member/snap/00000000000007e2-0000000000040b5d.snap
./member/snap/00000000000007e2-000000000003e44b.snap
./member/snap/00000000000007e2-000000000004326f.snap
./member/snap/00000000000007e2-000000000003f7d4.snap
```
Let me know if I can help more?

**Comment by onorua** [comment]
One more I forgot to add, systemd status shows this:
```
# systemctl status etcd
● etcd.service - etcd key-value store
   Loaded: loaded (/lib/systemd/system/etcd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2016-03-22 19:22:01 UTC; 250ms ago
     Docs: https://github.com/coreos/etcd
  Process: 4934 ExecStart=/usr/local/bin/etcd --addr 172.16.236.27:4001 --bind-addr 172.16.236.27:4001 --initial-cluster-state new --initial-cluster-token mycluster --listen-peer-urls http://172.16.236.27:7001 --initial-advertise-peer-urls http://172.16.236.27:7001 --snapshot-count=5000 --discovery-srv k8s.otlabs.fr (code=exited, status=2)
 Main PID: 4934 (code=exited, status=2)

Mar 22 19:22:01 ip-172-16-236-27 systemd[1]: etcd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 22 19:22:01 ip-172-16-236-27 systemd[1]: Failed to start etcd key-value store.
Mar 22 19:22:01 ip-172-16-236-27 systemd[1]: etcd.service: Unit entered failed state.
Mar 22 19:22:01 ip-172-16-236-27 systemd[1]: etcd.service: Failed with result 'exit-code'.
```

**Comment by xiang90** [comment]
@onorua I am not exactly sure what happened. But it does not look like this is caused by the upgrade. It seems like there are missing WAL files for something. Did you move your WAL dir around? Is this a fresh cluster? How did you reproduce the issue?

**Comment by xiang90** [comment]
The layout of your datadir looks strange. etcd should not create a dir called `data`.

**Comment by onorua** [comment]
oh... my gosh! As I've said, we are moving from etcd inside docker continer to systemd service, etcd inside docker had wrong mountpoint inside the container, I've just confirmed that. That is why container was not able to find `member` dir with all the files, because it was actually in `data/member`. 
I'm closing this now, sorry for your time, that was my fault :( 
I was just confused by that message of upgrade

**Comment by xiang90** [comment]
@onorua No problem at all.
