### ISSUE TITLE
TestWatchableKVWatch fails

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#5104]
https://travis-ci.org/coreos/etcd/jobs/123408460#L602

```
--- FAIL: TestWatchableKVWatch (28.91s)
	testutil.go:55: goroutine 583 [running]:
		github.com/coreos/etcd/pkg/testutil.FatalStack(0xc8204adc20, 0xae53e0, 0x19)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/testutil/testutil.go:54 +0x88
		github.com/coreos/etcd/storage.TestWatchableKVWatch(0xc8204adc20)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/kv_test.go:806 +0x2806
		testing.tRunner(0xc8204adc20, 0xd29378)
			/tmp/workdir/go/src/testing/testing.go:456 +0xdd
		created by testing.RunTests
			/tmp/workdir/go/src/testing/testing.go:561 +0xaa4
		
		goroutine 1 [chan receive]:
		testing.RunTests(0xb72550, 0xd28fa0, 0x41, 0x41, 0x9c5401)
			/tmp/workdir/go/src/testing/testing.go:562 +0xafa
		testing.(*M).Run(0xc820361f00, 0xd2c3c0)
			/tmp/workdir/go/src/testing/testing.go:494 +0xe5
		main.main()
			github.com/coreos/etcd/storage/_test/_testmain.go:258 +0x385
		
		goroutine 17 [syscall, locked to thread]:
		runtime.goexit()
			/tmp/workdir/go/src/runtime/asm_amd64.s:1696 +0x1
		
		goroutine 369 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc8203f7140)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:117 +0x437
		
		goroutine 159 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc8203c3320)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:117 +0x437
		
		goroutine 169 [select]:
		github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc8203f6cc0)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/schedule/schedule.go:146 +0x459
		created by github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x366
		
		goroutine 170 [select]:
		github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc8203f7080)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/schedule/schedule.go:146 +0x459
		created by github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x366
		
		goroutine 174 [select]:
		github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc8203f7920)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/schedule/schedule.go:146 +0x459
		created by github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x366
		
		goroutine 176 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc8203f7b60)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:117 +0x437
		
		goroutine 178 [select]:
		github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc8203f7f20)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/schedule/schedule.go:146 +0x459
		created by github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x366
		
		goroutine 183 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc82040a960)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:117 +0x437
		
		goroutine 184 [select]:
		github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc82040aa80)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/schedule/schedule.go:146 +0x459
		created by github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x366
		
		goroutine 188 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc82040b020)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:117 +0x437
		
		goroutine 192 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc82040b560)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:117 +0x437
		
		goroutine 190 [select]:
		github.com/coreos/etcd/storage.(*watchableStore).syncWatchersLoop(0xc82036bdc0)
			github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:279 +0x21e
		created by github.com/coreos/etcd/storage.newWatchableStore
			github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:83 +0x3ec
		
		goroutine 196 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc82040baa0)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:117 +0x437
		
		goroutine 194 [select]:
		github.com/coreos/etcd/storage.(*watchableStore).syncWatchersLoop(0xc820476000)
			github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:279 +0x21e
		created by github.com/coreos/etcd/storage.newWatchableStore
			github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:83 +0x3ec
		
		goroutine 201 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc82040a120)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:117 +0x437
		
		goroutine 204 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc82040a660)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:117 +0x437
		
		goroutine 208 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc82040bc80)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:117 +0x437
		
		goroutine 206 [select]:
		github.com/coreos/etcd/storage.(*watchableStore).syncWatchersLoop(0xc8204764d0)
			github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:279 +0x21e
		created by github.com/coreos/etcd/storage.newWatchableStore
			github.com/coreos/etcd/storage/_test/_obj_test/watchable_store.go:83 +0x3ec
		
		goroutine 212 [select]:
		github.com/coreos/etcd/storage/backend.(*backend).run(0xc8203f6360)
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.go:182 +0x1d5
		created by github.com/coreos/etcd/storage/backend.newBackend
			/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/storage/backend/backend.g
	testutil.go:56: failed to watch the event
2016/04/15 18:19:12 storage: restore compact to 3
2016/04/15 18:19:12 store.index: compact 2
2016/04/15 18:19:12 storage: resume scheduled compaction at 2
2016/04/15 18:19:12 store.index: compact 5
FAIL
```

[log.txt](https://github.com/coreos/etcd/files/221516/log.txt)

**Comment by heyitsanthony** [comment]
I ran more than a thousand rounds of `TestWatchableKVWatch` with and without `-race` on a slow atom (in addition to a faster machine). I can't seem to reproduce this bug.
/cc @mitake @gyuho

**Comment by gyuho** [comment]
Yeah we haven't seen this again in CI either. Think we can close it for now?

**Comment by xiang90** [comment]
Let's close this for now. Reopen if this comes up again. Thanks!
