### ISSUE TITLE
Etcd out of memory

### ISSUE THREAD

**Issue by coozy** [coreos/etcd#5274]
Etcd OOMs
I have the stack traces not sure if that is useful. 

Version:
```
[root@]# etcd -version
etcd Version: 2.3.1
Git SHA: 2b67f52
Go Version: go1.5.3
Go OS/Arch: linux/amd64
```

```
[root@]# du -sh /var/lib/etcd/
1.9G	/var/lib/etcd/
[root@]# ls -ltrh /var/lib/etcd/default.etcd/member/snap/
total 1.4G
-rw-r--r-- 1 etcd etcd 260M May  4 17:35 000000000000000b-000000000077cf46.snap
-rw-r--r-- 1 etcd etcd 262M May  4 18:04 000000000000000b-000000000077f688.snap
-rw-r--r-- 1 etcd etcd 270M May  4 18:36 000000000000000c-0000000000781d99.snap
-rw-r--r-- 1 etcd etcd 271M May  4 19:38 000000000000000c-00000000007844aa.snap
-rw-r--r-- 1 etcd etcd 271M May  4 20:39 000000000000000c-0000000000786bbb.snap

[root@]# ls -ltrh /var/lib/etcd/default.etcd/member/wal/
total 562M
-rw------- 1 etcd etcd  62M May  4 14:02 0000000000000073-00000000006de02c.wal
-rw------- 1 etcd etcd  62M May  4 16:27 0000000000000074-00000000006f350a.wal
-rw------- 1 etcd etcd  62M May  4 17:10 0000000000000075-0000000000719c0a.wal
-rw------- 1 etcd etcd  62M May  4 20:34 0000000000000076-000000000075806c.wal
-rw------- 1 etcd etcd 8.1M May  4 21:25 0000000000000077-00000000007868e7.wal

[root@]# free
              total        used        free      shared  buff/cache   available
Mem:        4045732     2058800     1273660         348      713272     1779244
Swap:             0           0           0

```

```
 purged file /var/lib/etcd/default.etcd/member/snap/0000000000000007-0000000000738547.snap successfully
 start to snapshot (applied: 7630765, lastsnap: 7620764)
 purged file /var/lib/etcd/default.etcd/member/snap/0000000000000007-000000000073ac58.snap successfully
 saved snapshot at index 7630765
 compacted raft log at 7625765
 start to snapshot (applied: 7640766, lastsnap: 7630765)
 fatal error: runtime: out of memory
 runtime stack:
 runtime.throw(0xf80d20, 0x16)
 /usr/local/go/src/runtime/panic.go:527 +0x90
 runtime.sysMap(0xc8af040000, 0xeba0000, 0x431800, 0x14181f8)
 /usr/local/go/src/runtime/mem_linux.go:203 +0x9b
 runtime.mHeap_SysAlloc(0x13f8240, 0xeba0000, 0x0)
 /usr/local/go/src/runtime/malloc.go:426 +0x160
 runtime.mHeap_Grow(0x13f8240, 0x75d0, 0x0)
 /usr/local/go/src/runtime/mheap.go:628 +0x63
 runtime.mHeap_AllocSpanLocked(0x13f8240, 0x75ca, 0x7fa068104d20)
 /usr/local/go/src/runtime/mheap.go:532 +0x5f1
 runtime.mHeap_Alloc_m(0x13f8240, 0x75ca, 0xffffff0100000000, 0xc82035bec8)
 /usr/local/go/src/runtime/mheap.go:425 +0x1ac
 runtime.mHeap_Alloc.func1()
 /usr/local/go/src/runtime/mheap.go:484 +0x41
 runtime.systemstack(0xc82035bee0)
 /usr/local/go/src/runtime/asm_amd64.s:278 +0xab
 runtime.mHeap_Alloc(0x13f8240, 0x75ca, 0x10100000000, 0x7fa068104d80)
 /usr/local/go/src/runtime/mheap.go:485 +0x63
 runtime.largeAlloc(0xeb92a7d, 0x1, 0x0)
 /usr/local/go/src/runtime/malloc.go:748 +0xb3
 runtime.mallocgc.func3()
 /usr/local/go/src/runtime/malloc.go:637 +0x33
 runtime.systemstack(0xc820018000)
 /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
 runtime.mstart()
 /usr/local/go/src/runtime/proc1.go:668
 goroutine 2885511 [running]:
```

**Comment by xiang90** [comment]
@coozy It seems you put too much data into etcd. For etcd2.0, normally you should not put more than 200MB. https://github.com/coreos/etcd/blob/master/Documentation/v2/benchmarks/etcd-2-2-0-rc-memory-benchmarks.md#data-size-threshold.

We are not going to fix this for etcd2 since it has been addressed by the new storage engine for etcd3. etcd3 supports xGB of data.
