### ISSUE TITLE
clientv3: panic in session

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5437]
While I was testing v3 capability stuff, the client panicked. I understand that we need to make rpc available before start testing. However, I do not expect the client to panic.

```
--- FAIL: TestDoubleBarrier (0.23s)
	v3_double_barrier_test.go:38: could not enter on barrier (etcdserver: not capable)
	v3_double_barrier_test.go:38: could not enter on barrier (etcdserver: not capable)
	v3_double_barrier_test.go:38: could not enter on barrier (etcdserver: not capable)
	v3_double_barrier_test.go:38: could not enter on barrier (etcdserver: not capable)
	v3_double_barrier_test.go:38: could not enter on barrier (etcdserver: not capable)
	v3_double_barrier_test.go:38: could not enter on barrier (etcdserver: not capable)
	v3_double_barrier_test.go:38: could not enter on barrier (etcdserver: not capable)
	v3_double_barrier_test.go:38: could not enter on barrier (etcdserver: not capable)
	v3_double_barrier_test.go:38: could not enter on barrier (etcdserver: not capable)
	v3_double_barrier_test.go:56: could not enter last barrier (etcdserver: not capable)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x7efac8]

goroutine 20453 [running]:
panic(0xedcf60, 0xc820014110)
	/usr/local/golang/1.6.1/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8201962d0)
	/usr/local/golang/1.6.1/go/src/testing/testing.go:467 +0x192
panic(0xedcf60, 0xc820014110)
	/usr/local/golang/1.6.1/go/src/runtime/panic.go:426 +0x4e9
github.com/coreos/etcd/clientv3/concurrency.(*Session).Orphan(0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/concurrency/session.go:95 +0x18
github.com/coreos/etcd/integration.dropSessionLease(0xc8264c7ee0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/integration/v3_double_barrier_test.go:144 +0x75
runtime.Goexit()
	/usr/local/golang/1.6.1/go/src/runtime/panic.go:323 +0xfb
testing.(*common).FailNow(0xc8201962d0)
	/usr/local/golang/1.6.1/go/src/testing/testing.go:346 +0x36
testing.(*common).Fatalf(0xc8201962d0, 0x1174b60, 0x21, 0xc831cdde40, 0x1, 0x1)
	/usr/local/golang/1.6.1/go/src/testing/testing.go:389 +0x83
github.com/coreos/etcd/integration.TestDoubleBarrier(0xc8201962d0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/integration/v3_double_barrier_test.go:56 +0x422
testing.tRunner(0xc8201962d0, 0x1620418)
	/usr/local/golang/1.6.1/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/golang/1.6.1/go/src/testing/testing.go:582 +0x892
exit status 2
```

**Comment by xiang90** [comment]
Double checked. It is actually a bad assumption we made in the test code that assuming the session can be created... So closing this issue and going to fix the test.
