### ISSUE TITLE
test: panic in TestWatchReconnRequest

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5511]
```
=== RUN   TestWatchReconnRequest
2016-05-31 19:51:33.088199 I | integration: launching node8320214757319120064 (unix://localhost:node8320214757319120064.sock)
2016-05-31 19:51:33.093657 I | integration: launching node6066662195674198309 (unix://localhost:node6066662195674198309.sock)
2016-05-31 19:51:33.095106 I | integration: launching node7536830495703928964 (unix://localhost:node7536830495703928964.sock)
2016-05-31 19:51:33.110037 I | etcdserver: name = node8320214757319120064
2016-05-31 19:51:33.110126 I | etcdserver: data dir = /tmp/etcd359232793
2016-05-31 19:51:33.110192 I | etcdserver: member dir = /tmp/etcd359232793/member
2016-05-31 19:51:33.110257 I | etcdserver: heartbeat = 10ms
2016-05-31 19:51:33.110307 I | etcdserver: election = 100ms
2016-05-31 19:51:33.110353 I | etcdserver: snapshot count = 0
2016-05-31 19:51:33.110411 I | etcdserver: advertise client URLs = http://127.0.0.1:21152
2016-05-31 19:51:33.110468 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:21151
2016-05-31 19:51:33.110570 I | etcdserver: initial cluster = node6066662195674198309=http://127.0.0.1:21147,node7536830495703928964=http://127.0.0.1:21149,node8320214757319120064=http://127.0.0.1:21151
2016-05-31 19:51:33.128670 I | etcdserver: name = node7536830495703928964
2016-05-31 19:51:33.128795 I | etcdserver: data dir = /tmp/etcd409487906
2016-05-31 19:51:33.128887 I | etcdserver: member dir = /tmp/etcd409487906/member
2016-05-31 19:51:33.128969 I | etcdserver: heartbeat = 10ms
2016-05-31 19:51:33.129034 I | etcdserver: election = 100ms
2016-05-31 19:51:33.129095 I | etcdserver: snapshot count = 0
2016-05-31 19:51:33.129179 I | etcdserver: advertise client URLs = http://127.0.0.1:21150
2016-05-31 19:51:33.129255 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:21149
2016-05-31 19:51:33.129405 I | etcdserver: initial cluster = node6066662195674198309=http://127.0.0.1:21147,node7536830495703928964=http://127.0.0.1:21149,node8320214757319120064=http://127.0.0.1:21151
2016-05-31 19:51:33.130623 I | etcdserver: name = node6066662195674198309
2016-05-31 19:51:33.130777 I | etcdserver: data dir = /tmp/etcd690668559
2016-05-31 19:51:33.130923 I | etcdserver: member dir = /tmp/etcd690668559/member
2016-05-31 19:51:33.131045 I | etcdserver: heartbeat = 10ms
2016-05-31 19:51:33.131153 I | etcdserver: election = 100ms
2016-05-31 19:51:33.131256 I | etcdserver: snapshot count = 0
2016-05-31 19:51:33.131386 I | etcdserver: advertise client URLs = http://127.0.0.1:21148
2016-05-31 19:51:33.131513 I | etcdserver: initial advertise peer URLs = http://127.0.0.1:21147
2016-05-31 19:51:33.131762 I | etcdserver: initial cluster = node6066662195674198309=http://127.0.0.1:21147,node7536830495703928964=http://127.0.0.1:21149,node8320214757319120064=http://127.0.0.1:21151
2016-05-31 19:51:33.148285 I | etcdserver: starting member dc3cde9072b18b64 in cluster 2137d20c0d9bc798
2016-05-31 19:51:33.148658 I | raft: dc3cde9072b18b64 became follower at term 0
2016-05-31 19:51:33.148821 I | raft: newRaft dc3cde9072b18b64 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-05-31 19:51:33.149012 I | raft: dc3cde9072b18b64 became follower at term 1
2016-05-31 19:51:33.171492 I | etcdserver: set snapshot count to default 10000
2016-05-31 19:51:33.171565 I | etcdserver: starting server... [version: 3.0.0-beta.0+git, cluster version: to_be_decided]
2016-05-31 19:51:33.175420 N | etcdserver: added member 3689d64eec4a9d11 [http://127.0.0.1:21147] to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.175876 N | etcdserver: added member 61c8b1a6fb4577e2 [http://127.0.0.1:21149] to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.176331 N | etcdserver: added local member dc3cde9072b18b64 [http://127.0.0.1:21151] to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.183568 I | etcdserver: starting member 61c8b1a6fb4577e2 in cluster 2137d20c0d9bc798
2016-05-31 19:51:33.183760 I | raft: 61c8b1a6fb4577e2 became follower at term 0
2016-05-31 19:51:33.183830 I | raft: newRaft 61c8b1a6fb4577e2 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-05-31 19:51:33.183876 I | raft: 61c8b1a6fb4577e2 became follower at term 1
2016-05-31 19:51:33.184896 I | etcdserver: starting member 3689d64eec4a9d11 in cluster 2137d20c0d9bc798
2016-05-31 19:51:33.185066 I | raft: 3689d64eec4a9d11 became follower at term 0
2016-05-31 19:51:33.185134 I | raft: newRaft 3689d64eec4a9d11 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2016-05-31 19:51:33.185177 I | raft: 3689d64eec4a9d11 became follower at term 1
2016-05-31 19:51:33.230461 I | etcdserver: set snapshot count to default 10000
2016-05-31 19:51:33.230532 I | etcdserver: starting server... [version: 3.0.0-beta.0+git, cluster version: to_be_decided]
2016-05-31 19:51:33.263164 I | etcdserver: set snapshot count to default 10000
2016-05-31 19:51:33.263232 I | etcdserver: starting server... [version: 3.0.0-beta.0+git, cluster version: to_be_decided]
2016-05-31 19:51:33.270241 I | rafthttp: the connection with dc3cde9072b18b64 became active
2016-05-31 19:51:33.272204 I | integration: launched node8320214757319120064 (unix://localhost:node8320214757319120064.sock)
2016-05-31 19:51:33.273181 I | rafthttp: the connection with dc3cde9072b18b64 became active
2016-05-31 19:51:33.274908 N | etcdserver: added local member 3689d64eec4a9d11 [http://127.0.0.1:21147] to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.275648 N | etcdserver: added member 61c8b1a6fb4577e2 [http://127.0.0.1:21149] to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.276759 I | integration: launched node7536830495703928964 (unix://localhost:node7536830495703928964.sock)
2016-05-31 19:51:33.277104 N | etcdserver: added member 3689d64eec4a9d11 [http://127.0.0.1:21147] to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.277705 N | etcdserver: added member dc3cde9072b18b64 [http://127.0.0.1:21151] to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.279585 N | etcdserver: added local member 61c8b1a6fb4577e2 [http://127.0.0.1:21149] to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.280673 I | integration: launched node6066662195674198309 (unix://localhost:node6066662195674198309.sock)
2016-05-31 19:51:33.283283 N | etcdserver: added member dc3cde9072b18b64 [http://127.0.0.1:21151] to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.284174 I | raft: dc3cde9072b18b64 is starting a new election at term 1
2016-05-31 19:51:33.284250 I | raft: dc3cde9072b18b64 became candidate at term 2
2016-05-31 19:51:33.284287 I | raft: dc3cde9072b18b64 received vote from dc3cde9072b18b64 at term 2
2016-05-31 19:51:33.284327 I | raft: dc3cde9072b18b64 [logterm: 1, index: 3] sent vote request to 3689d64eec4a9d11 at term 2
2016-05-31 19:51:33.284366 I | raft: dc3cde9072b18b64 [logterm: 1, index: 3] sent vote request to 61c8b1a6fb4577e2 at term 2
2016-05-31 19:51:33.285188 I | rafthttp: the connection with 3689d64eec4a9d11 became active
2016-05-31 19:51:33.289560 I | rafthttp: the connection with 61c8b1a6fb4577e2 became active
2016-05-31 19:51:33.290431 I | rafthttp: the connection with 3689d64eec4a9d11 became active
2016-05-31 19:51:33.291379 I | rafthttp: the connection with 61c8b1a6fb4577e2 became active
2016-05-31 19:51:33.293046 I | raft: 61c8b1a6fb4577e2 is starting a new election at term 1
2016-05-31 19:51:33.293144 I | raft: 61c8b1a6fb4577e2 became candidate at term 2
2016-05-31 19:51:33.293173 I | raft: 61c8b1a6fb4577e2 received vote from 61c8b1a6fb4577e2 at term 2
2016-05-31 19:51:33.293207 I | raft: 61c8b1a6fb4577e2 [logterm: 1, index: 3] sent vote request to 3689d64eec4a9d11 at term 2
2016-05-31 19:51:33.293240 I | raft: 61c8b1a6fb4577e2 [logterm: 1, index: 3] sent vote request to dc3cde9072b18b64 at term 2
2016-05-31 19:51:33.299344 I | raft: dc3cde9072b18b64 [logterm: 1, index: 3, vote: dc3cde9072b18b64] rejected vote from 61c8b1a6fb4577e2 [logterm: 1, index: 3] at term 2
2016-05-31 19:51:33.302183 I | raft: 3689d64eec4a9d11 [term: 1] received a MsgVote message with higher term from 61c8b1a6fb4577e2 [term: 2]
2016-05-31 19:51:33.302306 I | raft: 3689d64eec4a9d11 became follower at term 2
2016-05-31 19:51:33.302365 I | raft: 3689d64eec4a9d11 [logterm: 1, index: 3, vote: 0] voted for 61c8b1a6fb4577e2 [logterm: 1, index: 3] at term 2
2016-05-31 19:51:33.302494 I | raft: 61c8b1a6fb4577e2 [logterm: 1, index: 3, vote: 61c8b1a6fb4577e2] rejected vote from dc3cde9072b18b64 [logterm: 1, index: 3] at term 2
2016-05-31 19:51:33.304144 I | raft: 61c8b1a6fb4577e2 received vote rejection from dc3cde9072b18b64 at term 2
2016-05-31 19:51:33.304209 I | raft: 61c8b1a6fb4577e2 [quorum:2] has received 1 votes and 1 vote rejections
2016-05-31 19:51:33.304352 I | raft: 61c8b1a6fb4577e2 received vote from 3689d64eec4a9d11 at term 2
2016-05-31 19:51:33.304401 I | raft: 61c8b1a6fb4577e2 [quorum:2] has received 2 votes and 1 vote rejections
2016-05-31 19:51:33.304468 I | raft: 61c8b1a6fb4577e2 became leader at term 2
2016-05-31 19:51:33.304524 I | raft: raft.node: 61c8b1a6fb4577e2 elected leader 61c8b1a6fb4577e2 at term 2
2016-05-31 19:51:33.306833 I | raft: 3689d64eec4a9d11 [logterm: 1, index: 3, vote: 61c8b1a6fb4577e2] rejected vote from dc3cde9072b18b64 [logterm: 1, index: 3] at term 2
2016-05-31 19:51:33.308275 I | raft: dc3cde9072b18b64 received vote rejection from 61c8b1a6fb4577e2 at term 2
2016-05-31 19:51:33.308343 I | raft: dc3cde9072b18b64 [quorum:2] has received 1 votes and 1 vote rejections
2016-05-31 19:51:33.308631 I | raft: dc3cde9072b18b64 received vote rejection from 3689d64eec4a9d11 at term 2
2016-05-31 19:51:33.308696 I | raft: dc3cde9072b18b64 [quorum:2] has received 1 votes and 2 vote rejections
2016-05-31 19:51:33.308765 I | raft: dc3cde9072b18b64 became follower at term 2
2016-05-31 19:51:33.309372 I | raft: raft.node: dc3cde9072b18b64 elected leader 61c8b1a6fb4577e2 at term 2
2016-05-31 19:51:33.309474 I | raft: raft.node: 3689d64eec4a9d11 elected leader 61c8b1a6fb4577e2 at term 2
2016-05-31 19:51:33.317842 I | etcdserver: published {Name:node7536830495703928964 ClientURLs:[http://127.0.0.1:21150]} to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.320579 I | etcdserver: published {Name:node8320214757319120064 ClientURLs:[http://127.0.0.1:21152]} to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.323330 I | etcdserver: published {Name:node6066662195674198309 ClientURLs:[http://127.0.0.1:21148]} to cluster 2137d20c0d9bc798
2016-05-31 19:51:33.325846 I | etcdserver: setting up the initial cluster version to 3.0
2016-05-31 19:51:33.327474 N | membership: set the initial cluster version to 3.0
2016-05-31 19:51:33.328295 N | membership: set the initial cluster version to 3.0
2016-05-31 19:51:33.328837 N | membership: set the initial cluster version to 3.0
==================
WARNING: DATA RACE
Read by goroutine 238:
  runtime.chansend()
      /usr/local/golang/1.6.2/go/src/runtime/chan.go:115 +0x0
  github.com/coreos/etcd/etcdserver/api/v3rpc.(*serverWatchStream).recvLoop()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:180 +0xb69
  github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch.func2()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:126 +0x2e

Previous write by goroutine 62:
  runtime.closechan()
      /usr/local/golang/1.6.2/go/src/runtime/chan.go:292 +0x0
  github.com/coreos/etcd/etcdserver/api/v3rpc.(*serverWatchStream).close()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:304 +0xac
  github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:137 +0x3dc
  github.com/coreos/etcd/etcdserver/etcdserverpb._Watch_Watch_Handler()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2261 +0xfe
  github.com/coreos/etcd/etcdserver/api/v3rpc.metricsStreamInterceptor()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:113 +0x21c
  github.com/coreos/etcd/etcdserver/api/v3rpc.newStreamInterceptor.func1()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:91 +0x57e
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/server.go:609 +0xf6a
  google.golang.org/grpc.(*Server).handleStream()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/server.go:686 +0x150a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/server.go:348 +0xad

Goroutine 238 (running) created at:
  github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:126 +0x2fb
  github.com/coreos/etcd/etcdserver/etcdserverpb._Watch_Watch_Handler()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2261 +0xfe
  github.com/coreos/etcd/etcdserver/api/v3rpc.metricsStreamInterceptor()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:113 +0x21c
  github.com/coreos/etcd/etcdserver/api/v3rpc.newStreamInterceptor.func1()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:91 +0x57e
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/server.go:609 +0xf6a
  google.golang.org/grpc.(*Server).handleStream()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/server.go:686 +0x150a
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/server.go:348 +0xad

Goroutine 62 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/server.go:349 +0xa7
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/transport/http2_server.go:209 +0x1961
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/transport/http2_server.go:268 +0xf56
  google.golang.org/grpc.(*Server).serveStreams()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/server.go:350 +0x1dc
  google.golang.org/grpc.(*Server).serveNewHTTP2Transport()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/server.go:337 +0x54d
  google.golang.org/grpc.(*Server).handleRawConn()
      /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/server.go:314 +0x5b1
==================
panic: send on closed channel

goroutine 10227 [running]:
panic(0xf8b3c0, 0xc826284b90)
	/usr/local/golang/1.6.2/go/src/runtime/panic.go:481 +0x3ff
github.com/coreos/etcd/etcdserver/api/v3rpc.(*serverWatchStream).recvLoop(0xc822e4fea0, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:180 +0xb6a
github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch.func2(0xc8262964e0, 0xc822e4fea0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:126 +0x2f
created by github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:126 +0x2fc
exit status 2
```

**Comment by xiang90** [comment]
@heyitsanthony Have you seen this before?

**Comment by heyitsanthony** [comment]
@xiang90 #5505
