### ISSUE TITLE
test: TestGRPCStreamRequireLeader panics

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5512]
```
=== RUN   TestGRPCStreamRequireLeader
panic: send on closed channel

goroutine 142932 [running]:
panic(0xce5540, 0xc82126b4f0)
	/usr/local/golang/1.6.2/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/etcdserver/api/v3rpc.(*serverWatchStream).recvLoop(0xc821841570, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:180 +0x748
github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch.func2(0xc823bb5320, 0xc821841570)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:126 +0x21
created by github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:126 +0x26d
```

**Comment by heyitsanthony** [comment]
Duplicates #5511
