### ISSUE TITLE
TestElectionWait fails

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#5529]
```
=== RUN   TestElectionWait
panic: watcher not victim but not in watch groups

goroutine 235946 [running]:
panic(0xce8620, 0xc820e20330)
	/usr/local/golang/1.6.2/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/mvcc.(*watchableStore).cancelWatcher(0xc8200e34d0, 0xc823b00dc0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/mvcc/watchable_store.go:235 +0x174
github.com/coreos/etcd/mvcc.(*watchableStore).watch.func1()
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/mvcc/watchable_store.go:217 +0x29
github.com/coreos/etcd/mvcc.(*watchStream).Cancel(0xc83219b300, 0x0, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/mvcc/watcher.go:124 +0x83
github.com/coreos/etcd/etcdserver/api/v3rpc.(*serverWatchStream).recvLoop(0xc8235f9030, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:190 +0x22d
github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch.func2(0xc82a170d80, 0xc8235f9030)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:126 +0x21
created by github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:126 +0x26d
exit status 2
FAIL	github.com/coreos/etcd/integration	856.644s
```

**Comment by xiang90** [comment]
this should also be closed by #5557
