### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference during IsRangePermitted

### ISSUE THREAD

**Issue by nekto0n** [coreos/etcd#5569]
Hi!
If I build etcd from master and give it a spin I quickly run into this panic trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x71172f]

goroutine 220 [running]:
panic(0xece7e0, 0xc820014090)
        /home/nekto0n/.local/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/auth.(*authStore).IsRangePermitted(0xc823d1a930, 0x0, 0xc824205500, 0x5b, 0xc824205500)
        /home/nekto0n/workspace/etcd/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/auth/store.go:634 +0x6f
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applyV3Request(0xc820194400, 0xc8227daea0, 0xc820962bd0)
        /home/nekto0n/workspace/etcd/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/apply.go:81 +0x112
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applyEntryNormal(0xc820194400, 0xc823e0f790)
        /home/nekto0n/workspace/etcd/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:1066 +0x47f
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0xc820194400, 0xc821016048, 0x4685, 0x46a9, 0xc820aa2e40, 0x0, 0x0)
        /home/nekto0n/workspace/etcd/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:1012 +0xc2
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applyEntries(0xc820194400, 0xc820aa2e40, 0xc823d20000)
        /home/nekto0n/workspace/etcd/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:727 +0x2bd
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applyAll(0xc820194400, 0xc820aa2e40, 0xc823d20000)
        /home/nekto0n/workspace/etcd/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:597 +0x78
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func2(0x7f01a0189c58, 0xc820aa2e00)
        /home/nekto0n/workspace/etcd/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:577 +0x32
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc820a9f1a0)
        /home/nekto0n/workspace/etcd/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:160 +0x323
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
        /home/nekto0n/workspace/etcd/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x27d
```

I have an older (perhaps two weeks old) version which runs okay. Maybe this report will be helpful.

**Comment by xiang90** [comment]
@nekto0n We are working on the auth features. So master might not be stable at the moment. Thanks for reporting!

**Comment by mitake** [comment]
@nekto0n thanks for your report. As @xiang90 says, the auth feature for v3 API is still under construction. I'll fix it ASAP.

**Comment by nekto0n** [comment]
Thank you for such swift replies!

**Comment by mitake** [comment]
@nekto0n could you share how to reproduce the panic? e.g. how did you launch the cluster, how did you invoked etcdctl, etc

**Comment by nekto0n** [comment]
Sorry for taking so long to respond. I'm sure @xiang90 got it right :)
