### ISSUE TITLE
etcd 3.0.1 startup failure on Windows 7 64-bit

### ISSUE THREAD

**Issue by MartyMacGyver** [coreos/etcd#5852]
The following error is seen when trying to start etcd 3.0.1 on Windows 7 64-bit if the `default.etcd` directory tree is not already present:

```
2016-07-02 01:12:50.368813 I | etcdmain: etcd Version: 3.0.1
2016-07-02 01:12:50.368813 I | etcdmain: Git SHA: a4a52cb
2016-07-02 01:12:50.368813 I | etcdmain: Go Version: go1.6.2
2016-07-02 01:12:50.368813 I | etcdmain: Go OS/Arch: windows/amd64
2016-07-02 01:12:50.368813 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2016-07-02 01:12:50.368813 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2016-07-02 01:12:50.368813 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-07-02 01:12:50.368813 I | etcdmain: listening for peers on http://localhost:2380
2016-07-02 01:12:50.368813 I | etcdmain: listening for client requests on localhost:2379
2016-07-02 01:12:50.368813 I | etcdserver: name = default
2016-07-02 01:12:50.368813 I | etcdserver: data dir = default.etcd
2016-07-02 01:12:50.368813 I | etcdserver: member dir = default.etcd/member
2016-07-02 01:12:50.368813 I | etcdserver: heartbeat = 100ms
2016-07-02 01:12:50.368813 I | etcdserver: election = 1000ms
2016-07-02 01:12:50.368813 I | etcdserver: snapshot count = 10000
2016-07-02 01:12:50.368813 I | etcdserver: advertise client URLs = http://localhost:2379
2016-07-02 01:12:50.368813 I | etcdserver: initial advertise peer URLs = http://localhost:2380
2016-07-02 01:12:50.368813 I | etcdserver: initial cluster = default=http://localhost:2380
2016-07-02 01:12:50.378813 C | etcdserver: create wal error: rename default.etcd/member/wal.tmp default.etcd/member/wa: Access is denied.
```

This will repeatedly fail until you manually rename `default.etcd/member/wal.tmp` to `default.etcd/member/wal`. Then etcd will start normally.

Notably, this problem is **not** seen in etcd 2.3.7 under the same initial conditions.

**Comment by MartyMacGyver** [comment]
I will add that I'm wondering if this is related to this old Go bug (at least as it related to os.rename() behavior on Windows):

https://github.com/golang/go/issues/8914

If there is an open file handle in `.../wal.tmp/`, that would block an OS-level rename from working.

**Comment by xiang90** [comment]
@MartyMacGyver Maybe you can give a try to fix?

**Comment by MartyMacGyver** [comment]
I'm limited in what I can contribute to a project like this employer-wise.

But to discuss it...

First, while the other bug I mentioned above may be useful to refer to, this isn't quite the same problem.

Second, if there was a test that executes the "new install" case without a default.etcd folder, that would reproduce and flag this error.

In wal.go:105 (Create()), the WAL file gets locked (from fileutil/lock_windows.go, we see this uses LOCKFILE_EXCLUSIVE_LOCK). Then later in the function, the folder containing this locked file gets renamed. That fails as a contained file is locked.

This (new in v3) attempt to make Create() appear atomic goes a bit too far, at least for operability on Windows. Specifically, creating a temp folder, exclusively locking a file within it, and then trying to rename that folder, isn't going to work on Windows. I'm not sure what the architectural imperative is for this enhanced atomicity in v3. Perhaps some junction manipulation would work (at least in NTFS), but exclusively locking the file and renaming its containing folder isn't going to work - perhaps one must simply abstract a relaxed requirement for Windows, much like multiple lock_* abstractions exist for lock functionality, or accept deprecated functionality by effectively disallowing the initialization without manual intervention.

I prefer to see the former, even if it means accepting that Windows can't mimic atomicity for this use case, or at best using some other mechanism (e.g., MoveFileEx) to better handle this case. However, it might mean some re-architecture of this: I'm not sure why the temp folder is getting renamed, versus a temp file (via MoveFileEx if in Windows, to preserve posix-style behavior - see the above-referenced bug for more on that topic).

**Comment by MartyMacGyver** [comment]
One additional note: this use of os.Rename() as part of the atomic WAL folder init is part of a relatively recent change via commit e6add51, fixing bug #5270.

**Comment by heyitsanthony** [comment]
@MartyMacGyver there are multiple files in the directory; if etcd is killed in the middle of init without atomic rename of the directory then it could have a partially initialized wal directory (which came up in stress testing). I believe the fix is to hold off on locking until after the rename. I'll see if I can get it working again.

**Comment by tangduoling** [comment]
I installed etcd on Windows,and I find the same problem happened "create wal error: rename default.etcd\member\wal.tmp default.etcd\member\wal: Access is denied.".Does anyone know how to solve the problem,thanks.

**Comment by tangduoling** [comment]
the output is like this:

[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2019-11-04 16:33:57.195194 I | etcdmain: etcd Version: 3.4.3
2019-11-04 16:33:57.259993 I | etcdmain: Git SHA: 3cf2f69b5
2019-11-04 16:33:57.260990 I | etcdmain: Go Version: go1.12.12
2019-11-04 16:33:57.260990 I | etcdmain: Go OS/Arch: windows/amd64
2019-11-04 16:33:57.260990 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2019-11-04 16:33:57.261988 N | etcdmain: failed to detect default host (default host not supported on windows_amd64)
2019-11-04 16:33:57.261988 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2019-11-04 16:33:57.270965 N | etcdmain: the server is already initialized as member before, starting as etcd member...
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2019-11-04 16:33:57.570164 I | embed: name = default
2019-11-04 16:33:57.572159 I | embed: data dir = default.etcd
2019-11-04 16:33:57.576148 I | embed: member dir = default.etcd\member
2019-11-04 16:33:57.582132 I | embed: heartbeat = 100ms
2019-11-04 16:33:57.583130 I | embed: election = 1000ms
2019-11-04 16:33:57.584127 I | embed: snapshot count = 100000
2019-11-04 16:33:57.585124 I | embed: advertise client URLs = http://localhost:2379
2019-11-04 16:33:57.690842 I | wal: releasing file lock to rename "default.etcd\\member\\wal.tmp" to "default.etcd\\member\\wal"
2019-11-04 16:33:57.719765 C | etcdserver: create wal error: rename default.etcd\member\wal.tmp default.etcd\member\wal: Access is denied.
panic: create wal error: rename default.etcd\member\wal.tmp default.etcd\member\wal: Access is denied.

goroutine 1 [running]:
github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc0002093c0, 0x1088e73, 0x14, 0xc0002aa508, 0x1, 0x1)
        /home/ec2-user/go/pkg/mod/github.com/coreos/pkg@v0.0.0-20160727233714-3ac0863d7acf/capnslog/pkg_logger.go:75 +0x13c
go.etcd.io/etcd/etcdserver.startNode(0x107c5ec, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc00024ec00, 0x1, 0x1, 0xc00024ea80, ...)
        /tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/raft.go:438 +0xf23
go.etcd.io/etcd/etcdserver.NewServer(0x107c5ec, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc00024ec00, 0x1, 0x1, 0xc00024ea80, ...)
        /tmp/etcd-release-3.4.3/etcd/release/etcd/etcdserver/server.go:407 +0x4956
go.etcd.io/etcd/embed.StartEtcd(0xc0000e0580, 0xc0000e0b00, 0x0, 0x0)
        /tmp/etcd-release-3.4.3/etcd/release/etcd/embed/etcd.go:211 +0x9d7
go.etcd.io/etcd/etcdmain.startEtcd(0xc0000e0580, 0x107b73f, 0x6, 0x1, 0xc00009f1d0)
        /tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/etcd.go:302 +0x47
go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2()
        /tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/etcd.go:144 +0x2f69
go.etcd.io/etcd/etcdmain.Main()
        /tmp/etcd-release-3.4.3/etcd/release/etcd/etcdmain/main.go:46 +0x3f
main.main()
        /tmp/etcd-release-3.4.3/etcd/release/etcd/main.go:28 +0x27
