### ISSUE TITLE
Etcd 3.0 crash on start as new member

### ISSUE THREAD

**Issue by meyskens** [coreos/etcd#5904]
When I let a fresh etcd 3 instance join a 2.3 cluster it gives the following error when opening a raft connection.
```
2016-07-08 19:21:29.293805 I | raft: newRaft 40df24e2b0cfec80 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x3966a0]

goroutine 1 [running]:
panic(0x96bd90, 0x1110a038)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x330
sync/atomic.storeUint64(0x11414104, 0x0, 0x0)
	/usr/lib/go-1.6/src/sync/atomic/64bit_arm.go:20 +0x40
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*consistentIndex).setConsistentIndex(0x11414104, 0x0, 0x0)
	/usr/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/consistent_index.go:28 +0x2c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0x11244420, 0x11414000, 0xb6f0b018, 0x1110ad40)
	/usr/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:414 +0x1d28
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0x112e6000, 0x0, 0x0, 0x0)
	/usr/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:366 +0x25cc
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
	/usr/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:116 +0x1b8c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
	/usr/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:36 +0x1c8
main.main()
	/usr/src/github.com/coreos/etcd/cmd/main.go:28 +0x14
```

I run this on ARM, not sure if that causes it.

**Comment by heyitsanthony** [comment]
@meyskens should be fixed with #5890, try building from master?

**Comment by meyskens** [comment]
Thanks! that fixed this

**Comment by jaredeh** [comment]
@meyskens I see from your github page you are doing etcd on scaleways.  Do you know if they might host arm architecture CI for etcd?

**Comment by meyskens** [comment]
Probably, they are very happy to help open source projects. Drop them a mail at opensource@scaleway.com
If you can't come to a deal mail me and I will ask if our company can't sponsor some.
