### ISSUE TITLE
invalid argument when trying to open database

### ISSUE THREAD

**Issue by mihok** [coreos/etcd#5923]
When trying to run a basic custom etcd vagrant setup, with the data-dir volumes shared with the host machine for preservation of state we run into a `panic: cannot open database at /var/lib/etcd/member/snap/db (invalid argument)`

Ubuntu 14.04 64x
etcd 3.0.1

etcd log:
```
2016-07-12 13:11:08.437589 I | flags: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
2016-07-12 13:11:08.437668 I | flags: recognized and used environment variable ETCD_NAME=queue
2016-07-12 13:11:08.437696 W | flags: unrecognized environment variable ETCD_HOME=/opt/etcd-3.0.1
2016-07-12 13:11:08.437709 I | etcdmain: etcd Version: 3.0.1
2016-07-12 13:11:08.437713 I | etcdmain: Git SHA: a4a52cb
2016-07-12 13:11:08.437717 I | etcdmain: Go Version: go1.6.2
2016-07-12 13:11:08.437721 I | etcdmain: Go OS/Arch: linux/amd64
2016-07-12 13:11:08.437726 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2016-07-12 13:11:08.438113 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-07-12 13:11:08.438298 I | etcdmain: listening for peers on http://localhost:2380
2016-07-12 13:11:08.438329 I | etcdmain: listening for client requests on localhost:2379
2016-07-12 13:11:08.441254 C | backend: cannot open database at /var/lib/etcd/member/snap/db (invalid argument)
panic: cannot open database at /var/lib/etcd/member/snap/db (invalid argument)

goroutine 1 [running]:
panic(0xd44e00, 0xc82019d600)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc82016c0c0, 0x11debc0, 0x1f, 0xc820127aa0, 0x2, 0x2)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x191
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.newBackend(0xc8201a1ee0, 0x1c, 0x5f5e100, 0x2710, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:106 +0x1ee
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.NewDefaultBackend(0xc8201a1ee0, 0x1c, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:100 +0x53
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc8200737c0, 0x0, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:253 +0x696
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc820021c00, 0x0, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:366 +0x23ea
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:116 +0x213d
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:36 +0x21e
main.main()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/main.go:28 +0x14
```

Basic Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

$instances = 1
$instance_name_prefix = "app"

$app_cpus = 1
$app_memory = 2048

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_agent = true

  (1..$instances).each do |i|
    config.vm.define vm_name = "%s-%02d" % [$instance_name_prefix, i] do |config|
      config.vm.hostname = vm_name

      config.vm.provider :virtualbox do |vb|
        vb.memory = $app_memory
        vb.cpus = $app_cpus
      end

      ip = "44.0.0.#{i+100}"
      config.vm.network :private_network, ip: ip
      config.vm.network "public_network"

      config.vm.synced_folder "./.etcd/#{vm_name}",  "/var/lib/etcd"

      config.vm.provision "shell", path: "etcd.sh", name: "etcd", env: {"IP" => ip}
    end
  end

end
```

etcd install script:
```
#!/bin/bash

set -x;


apt-get update -y
apt-get upgrade -y
apt-get autoremove -y

# ETCd

cd /opt/
curl -L https://github.com/coreos/etcd/releases/download/v3.0.1/etcd-v3.0.1-linux-amd64.tar.gz -o etcd-3.0.1.tar.gz
mkdir /opt/etcd-3.0.1
tar -zxvf etcd-3.0.1.tar.gz  -C etcd-3.0.1 --strip-components=1
ln -s /opt/etcd-3.0.1/etcd /usr/local/bin/etcd
ln -s /opt/etcd-3.0.1/etcdctl /usr/local/bin/etcdctl
cp /vagrant/.etcd/etcd.service /etc/init/etcd.conf
sed s/MY_IP/$IP/ </vagrant/.etcd/etcd.override >/etc/init/etcd.override
mkdir /var/log/etcd
chown vagrant:vagrant /var/log/etcd
start etcd
```

etcd upstart script:
```
description "etcd Service"
author "Matthew Mihok"

env ETCD_HOME=/opt/etcd-3.0.1
env ETCD_DATA_DIR=/var/lib/etcd
env LOG_HOME=/var/log/etcd

# Run as etcd
setuid vagrant
setgid vagrant

# Make sure network and fs is up, and start in runlevels 2-5
start on (net-device-up
          and local-filesystems
          and runlevel [2345])
# Stop in runlevels 0,1 and 6
stop on runlevel [016]

# automatically respawn, but if its respwaning too fast (5 times in 60 seconds, don't do that)
respawn
respawn limit 5 60

# make sure node is there, the code directory is there
pre-start script
    test -d $ETCD_DATA_DIR || { stop; exit 0; }
    test -x $ETCD_HOME/etcd || { stop; exit 0; }
end script

# cd to code path and run node, with the right switches
script

    export ETCD_NAME=`cat /etc/hostname`
    exec etcd >> $LOG_HOME/etcd.log 2>&1

end script
```

etcd upstart override:
```
    env ETCD_DATA_DIR=/var/lib/etcd
    env ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
    env ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    env ETCD_INITIAL_ADVERTISE_PEER_URLS=http://MY_IP:2380
    env ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    env ETCD_INITIAL_CLUSTER="app-01=http://44.0.0.101:2380"
```

**Comment by mihok** [comment]
Updated to include all configuration files necessary (I believe), let me know if there is more you need

**Comment by xiang90** [comment]
@mihok Check https://github.com/boltdb/bolt/issues/459. etcd now does not work for shared volume among vm and its host due to mmap issue.

**Comment by xiang90** [comment]
etcd does not work for shared volumes between vm and its host. This is a mmap issue (restriction), see https://github.com/boltdb/bolt/issues/459 for more details.
