### ISSUE TITLE
testing: etcd_release_upgrade_test.go time out

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5929]
```
panic: test timed out after 10m0s

goroutine 1121 [running]:
panic(0xb2c0c0, 0xc82015a090)
	/usr/local/golang/1.6.2/go/src/runtime/panic.go:481 +0x3e6
testing.startAlarm.func1()
	/usr/local/golang/1.6.2/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/golang/1.6.2/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 7 minutes]:
testing.RunTests(0xf41ca8, 0x121ac20, 0x70, 0x70, 0x1)
	/usr/local/golang/1.6.2/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820044f08, 0xecd060)
	/usr/local/golang/1.6.2/go/src/testing/testing.go:515 +0x81
github.com/coreos/etcd/e2e.TestMain(0xc820044f08)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/e2e/main_test.go:15 +0x21
main.main()
	github.com/coreos/etcd/e2e/_test/_testmain.go:274 +0x114

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/golang/1.6.2/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 44 [chan receive]:
github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc8201f21c0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x7c
created by github.com/coreos/etcd/pkg/logutil.NewMergeLogger
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc0

goroutine 1102 [chan receive, 7 minutes]:
github.com/coreos/etcd/e2e.(*etcdProcessCluster).StopAll(0xc8201c85a0, 0x7f15b1833f70, 0xc820164560)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/e2e/etcd_test.go:416 +0x257
github.com/coreos/etcd/e2e.(*etcdProcessCluster).Close(0xc8201c85a0, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/e2e/etcd_test.go:435 +0x31
github.com/coreos/etcd/e2e.TestReleaseUpgrade.func1(0xc8201c85a0, 0xc8201e4000)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/e2e/etcd_release_upgrade_test.go:46 +0x28
runtime.Goexit()
	/usr/local/golang/1.6.2/go/src/runtime/panic.go:340 +0xfb
testing.(*common).FailNow(0xc8201e4000)
	/usr/local/golang/1.6.2/go/src/testing/testing.go:346 +0x36
testing.(*common).Fatalf(0xc8201e4000, 0xe89c60, 0x22, 0xc820191cf8, 0x1, 0x1)
	/usr/local/golang/1.6.2/go/src/testing/testing.go:389 +0x83
github.com/coreos/etcd/e2e.TestReleaseUpgrade(0xc8201e4000)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/e2e/:78 +0xc9f
testing.tRunner(0xc8201e4000, 0x121b520)
	/usr/local/golang/1.6.2/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/golang/1.6.2/go/src/testing/testing.go:582 +0x892

goroutine 1105 [syscall]:
syscall.Syscall(0x0, 0x5, 0xc82010f000, 0x1000, 0x2, 0xf81, 0x0)
	/usr/local/golang/1.6.2/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x5, 0xc82010f000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/golang/1.6.2/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x5, 0xc82010f000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/golang/1.6.2/go/src/syscall/syscall_unix.go:161 +0x4d
os.(*File).read(0xc820032208, 0xc82010f000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/golang/1.6.2/go/src/os/file_unix.go:228 +0x53
os.(*File).Read(0xc820032208, 0xc82010f000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
	/usr/local/golang/1.6.2/go/src/os/file.go:95 +0x8a
bufio.(*Reader).fill(0xc820045ef0)
	/usr/local/golang/1.6.2/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820045ef0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/golang/1.6.2/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadBytes(0xc820045ef0, 0xc82001cc0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/golang/1.6.2/go/src/bufio/bufio.go:406 +0xa9
bufio.(*Reader).ReadString(0xc820045ef0, 0xc82020a00a, 0x0, 0x0, 0x0, 0x0)
	/usr/local/golang/1.6.2/go/src/bufio/bufio.go:446 +0x4d
github.com/coreos/etcd/pkg/expect.(*ExpectProcess).read(0xc82001ccb0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/expect/expect.go:63 +0x148
created by github.com/coreos/etcd/pkg/expect.NewExpect
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/expect/expect.go:54 +0x298
exit status 2
```

**Comment by gyuho** [comment]
I haven't been able to reproduce, but based on the log...

We can tell [defer epc.Close()](https://github.com/coreos/etcd/blob/master/e2e/etcd_release_upgrade_test.go#L46-L50) is hanging forever waiting to receive from `ep.donec` https://github.com/coreos/etcd/blob/master/e2e/etcd_test.go#L433.

Because `ep.donec` should have been closed by [`waitReady`](https://github.com/coreos/etcd/blob/master/e2e/etcd_test.go#L441), but it didn't get closed.

Maybe, `waitReady` didn't get to close `ep.donec` because it was hanging from some OS errors... but for lack of logs, I can't tell what it is.

@heyitsanthony And do we still need to wait from `donec`? I don't see any line that uses `Interact` with  `donec`. Can we move `donec` like something below, so we don't block on waiting on `donec`?

```diff
diff --git a/e2e/etcd_test.go b/e2e/etcd_test.go
index 42b7a35..0217c95 100644
--- a/e2e/etcd_test.go
+++ b/e2e/etcd_test.go
@@ -121,7 +121,7 @@ type etcdProcessCluster struct {
 type etcdProcess struct {
        cfg   *etcdProcessConfig
        proc  *expect.ExpectProcess
-       donec chan struct{} // closed when Interact() terminates
+       donec chan struct{}
 }
 
 type etcdProcessConfig struct {
@@ -364,11 +364,12 @@ func (epc *etcdProcessCluster) Start() (err error) {
        for i := range epc.procs {
                go func(n int) { readyC <- epc.procs[n].waitReady() }(i)
        }
-       for range epc.procs {
+       for _, p := range epc.procs {
                if err := <-readyC; err != nil {
                        epc.Close()
                        return err
                }
+               <-p.donec
        }
        return nil
 }
@@ -430,8 +431,6 @@ func (ep *etcdProcess) Stop() error {
        if err := ep.proc.Stop(); err != nil {
                return err
        }
-       <-ep.donec
-
        if ep.cfg.purl.Scheme == "unix" || ep.cfg.purl.Scheme == "unixs" {
                os.RemoveAll(ep.cfg.purl.Host)
        }
```

**Comment by heyitsanthony** [comment]
@gyuho I don't think that will make a difference, otherwise more e2e tests would be failing. I suspect this is why `donec` wasn't closing: https://github.com/coreos/etcd/commit/6b487fb1991b73d3da626e9afc8b535790131f00#diff-05b1f8b1c4ac72beaf21242730b7e33cL395 -- if `Expect` fails, `donec` will never close. If `epr.proc.Stop()` fails, `Restart` will exit without waiting on `donec`. The test will then exit, calling `epc.Close()` which will then wait on `donec`. Has this error happened since that commit?

**Comment by gyuho** [comment]
@heyitsanthony Right, makes sense.

This failure never happened since that commit you mentioned.

**Comment by xiang90** [comment]
@heyitsanthony @gyuho OK. So probably the root cause is the stuff we fixed yesterday.Let's close this for now. Reopen if this happens again.

**Comment by gyuho** [comment]
Yeah this should be fixed. Ran over 10K rounds on this test with no failure. Will reopen if that happens again.
