### ISSUE TITLE
embed: panic for duplicate enum registered

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#5986]
Hi
I embed etcd and it works ok until I update the newest etcd. 
The program panics when starts, error:

```
2016-07-19 16:02:34.713623 I | proto: duplicate proto type registered: raftpb.Entry
2016-07-19 16:02:34.713712 I | proto: duplicate proto type registered: raftpb.SnapshotMetadata
2016-07-19 16:02:34.713717 I | proto: duplicate proto type registered: raftpb.Snapshot
2016-07-19 16:02:34.713720 I | proto: duplicate proto type registered: raftpb.Message
2016-07-19 16:02:34.713723 I | proto: duplicate proto type registered: raftpb.HardState
2016-07-19 16:02:34.713726 I | proto: duplicate proto type registered: raftpb.ConfState
2016-07-19 16:02:34.713729 I | proto: duplicate proto type registered: raftpb.ConfChange
panic: proto: duplicate enum registered: raftpb.EntryType

goroutine 1 [running]:
panic(0x9904e0, 0xc8201f5610)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/golang/protobuf/proto.RegisterEnum(0xe84150, 0x10, 0xc8201f7bf0, 0xc8201f7c20)
	/Users/tangliu/program/go/src/github.com/golang/protobuf/proto/properties.go:815 +0xe2
github.com/coreos/etcd/raft/raftpb.init.1()
	/Users/tangliu/program/go/src/github.com/coreos/etcd/raft/raftpb/raft.pb.go:291 +0x263
github.com/coreos/etcd/raft/raftpb.init()
	/Users/tangliu/program/go/src/github.com/coreos/etcd/raft/raftpb/raft.pb.go:1889 +0x4ff
github.com/coreos/etcd/raft.init()
	/Users/tangliu/program/go/src/github.com/coreos/etcd/raft/util.go:117 +0x51
github.com/coreos/etcd/etcdserver/membership.init()
	/Users/tangliu/program/go/src/github.com/coreos/etcd/etcdserver/membership/store.go:193 +0x7e
github.com/coreos/etcd/etcdserver.init()
	/Users/tangliu/program/go/src/github.com/coreos/etcd/etcdserver/v3_server.go:566 +0x9b
github.com/coreos/etcd/embed.init()
	/Users/tangliu/program/go/src/github.com/coreos/etcd/embed/util.go:30 +0x60
github.com/pingcap/pd/server.init()
```

I find that this panic is introduces in this commit.  https://github.com/coreos/etcd/commit/50be793f098541528d214d49154459c0de297ce7

How to solve it?

**Comment by gyuho** [comment]
@siddontang Here's how I reproduced even without embedding etcd:

```go
package main

import (
	"fmt"

	"github.com/coreos/etcd/raft/raftpb"
	raftpb2 "github.com/pingcap/kvproto/pkg/raftpb"
)

func main() {
	fmt.Println(raftpb.EntryNormal)
	fmt.Println(raftpb2.ConfChangeType_AddNode)

	// cfg := embed.NewConfig()
	// cfg.Dir = "default.etcd"
	// e, err := embed.StartEtcd(cfg)
	// if err != nil {
	// 	log.Fatal(err)
	// }
	// defer e.Close()
	// log.Fatal(<-e.Err())
}
```

```
2016/07/19 09:48:36 proto: duplicate proto type registered: raftpb.Entry
2016/07/19 09:48:36 proto: duplicate proto type registered: raftpb.SnapshotMetadata
2016/07/19 09:48:36 proto: duplicate proto type registered: raftpb.Snapshot
2016/07/19 09:48:36 proto: duplicate proto type registered: raftpb.Message
2016/07/19 09:48:36 proto: duplicate proto type registered: raftpb.HardState
2016/07/19 09:48:36 proto: duplicate proto type registered: raftpb.ConfState
2016/07/19 09:48:36 proto: duplicate proto type registered: raftpb.ConfChange
panic: proto: duplicate enum registered: raftpb.EntryType

goroutine 1 [running]:
panic(0x4dd2e0, 0xc42000a5f0)
	/home/gyuho/go-master/src/runtime/panic.go:500 +0x1a1
github.com/golang/protobuf/proto.RegisterEnum(0x50694f, 0x10, 0xc420010660, 0xc420010690)
	/home/gyuho/go/src/github.com/golang/protobuf/proto/properties.go:815 +0x13a
github.com/pingcap/kvproto/pkg/raftpb.init.1()
	/home/gyuho/go/src/github.com/pingcap/kvproto/pkg/raftpb/raftpb.pb.go:471 +0x194
github.com/pingcap/kvproto/pkg/raftpb.init()
	/home/gyuho/go/src/github.com/pingcap/kvproto/pkg/raftpb/raftpb.pb.go:517 +0x414
main.init()
	/home/gyuho/a.go:23 +0x38
exit status 2
```

The problem is `github.com/pingcap/pd` imports the same `raftpb` package here https://github.com/pingcap/pd/blob/master/server/event.go#L19.

And the `raftpb` package in pingcap https://github.com/pingcap/kvproto/blob/master/pkg/raftpb/raftpb.pb.go#L35 has the duplicate name in proto as `etcd/raftpb`.

Since etcd switched to `golang/protobuf`, same as pingcap, so it complains about duplicate name registration.

Workaround would be either project changes its name or package name?

Can you try giving `pingcap/kvproto` different `raftpb` names?

Thanks.

**Comment by siddontang** [comment]
Hi @gyuho 

I change our kvproto to another name, and it doesn't panic with your above example. I will do more test in our project.
