### ISSUE TITLE
rafttest TestRestart timeouts

### ISSUE THREAD

**Issue by AkihiroSuda** [coreos/etcd#6290]
TestRestart almost always timeouts on my machine 

```
$ git log | head -n 10
commit e53b99588a05d1f4ef172c178d4ed8e8106b8be4
Merge: f73258a 5e96360
Author: Anthony Romano <anthony.romano@coreos.com>
Date:   Sun Aug 28 20:41:19 2016 -0700

    Merge pull request #6288 from heyitsanthony/fix-retryread

    clientv3: retry non-mutable rpcs on Internal codes

commit 5e963608b72dbc815eb5bb96414d869cf6fd63c9

$ go version
go version go1.6.3 linux/amd64

$ ./build

$ GOPATH=$(pwd)/gopath go test -v -race -run TestRestart ./raft/rafttest
=== RUN   TestRestart
raft2016/08/29 07:08:44 INFO: 1 became follower at term 0
raft2016/08/29 07:08:44 INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2016/08/29 07:08:44 INFO: 1 became follower at term 1
raft2016/08/29 07:08:44 INFO: 2 became follower at term 0
raft2016/08/29 07:08:44 INFO: newRaft 2 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2016/08/29 07:08:44 INFO: 2 became follower at term 1
raft2016/08/29 07:08:44 INFO: 3 became follower at term 0
raft2016/08/29 07:08:44 INFO: newRaft 3 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2016/08/29 07:08:44 INFO: 3 became follower at term 1
raft2016/08/29 07:08:44 INFO: 4 became follower at term 0
raft2016/08/29 07:08:44 INFO: newRaft 4 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2016/08/29 07:08:44 INFO: 4 became follower at term 1
raft2016/08/29 07:08:44 INFO: 5 became follower at term 0
raft2016/08/29 07:08:44 INFO: newRaft 5 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2016/08/29 07:08:44 INFO: 5 became follower at term 1
raft2016/08/29 07:08:44 INFO: 2 is starting a new election at term 1
raft2016/08/29 07:08:44 INFO: 2 became candidate at term 2
raft2016/08/29 07:08:44 INFO: 2 received vote from 2 at term 2
raft2016/08/29 07:08:44 INFO: 2 [logterm: 1, index: 5] sent vote request to 5 at term 2
raft2016/08/29 07:08:44 INFO: 2 [logterm: 1, index: 5] sent vote request to 1 at term 2
raft2016/08/29 07:08:44 INFO: 2 [logterm: 1, index: 5] sent vote request to 3 at term 2
raft2016/08/29 07:08:44 INFO: 2 [logterm: 1, index: 5] sent vote request to 4 at term 2
raft2016/08/29 07:08:44 INFO: 4 is starting a new election at term 1
raft2016/08/29 07:08:44 INFO: 4 became candidate at term 2
raft2016/08/29 07:08:44 INFO: 4 received vote from 4 at term 2
raft2016/08/29 07:08:44 INFO: 4 [logterm: 1, index: 5] sent vote request to 1 at term 2
raft2016/08/29 07:08:44 INFO: 4 [logterm: 1, index: 5] sent vote request to 2 at term 2
raft2016/08/29 07:08:44 INFO: 4 [logterm: 1, index: 5] sent vote request to 3 at term 2
raft2016/08/29 07:08:44 INFO: 4 [logterm: 1, index: 5] sent vote request to 5 at term 2
raft2016/08/29 07:08:44 INFO: 1 [term: 1] received a MsgVote message with higher term from 2 [term: 2]
raft2016/08/29 07:08:44 INFO: 5 is starting a new election at term 1
raft2016/08/29 07:08:44 INFO: 5 became candidate at term 2
raft2016/08/29 07:08:44 INFO: 5 received vote from 5 at term 2
raft2016/08/29 07:08:44 INFO: 5 [logterm: 1, index: 5] sent vote request to 1 at term 2
raft2016/08/29 07:08:44 INFO: 5 [logterm: 1, index: 5] sent vote request to 2 at term 2
raft2016/08/29 07:08:44 INFO: 5 [logterm: 1, index: 5] sent vote request to 3 at term 2
raft2016/08/29 07:08:44 INFO: 1 became follower at term 2
raft2016/08/29 07:08:44 INFO: 1 [logterm: 1, index: 5, vote: 0] voted for 2 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 3 [term: 1] received a MsgVote message with higher term from 2 [term: 2]
raft2016/08/29 07:08:44 INFO: 5 [logterm: 1, index: 5] sent vote request to 4 at term 2
raft2016/08/29 07:08:44 INFO: 3 became follower at term 2
raft2016/08/29 07:08:44 INFO: 5 [logterm: 1, index: 5, vote: 5] rejected vote from 2 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 3 [logterm: 1, index: 5, vote: 0] voted for 2 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 2 [logterm: 1, index: 5, vote: 2] rejected vote from 4 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 4 [logterm: 1, index: 5, vote: 4] rejected vote from 2 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 1 [logterm: 1, index: 5, vote: 2] rejected vote from 4 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 5 [logterm: 1, index: 5, vote: 5] rejected vote from 4 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 3 [logterm: 1, index: 5, vote: 2] rejected vote from 4 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 3 [logterm: 1, index: 5, vote: 2] rejected vote from 5 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 2 received vote from 1 at term 2
raft2016/08/29 07:08:44 INFO: 2 [quorum:3] has received 2 votes and 0 vote rejections
raft2016/08/29 07:08:44 INFO: 2 received vote from 3 at term 2
raft2016/08/29 07:08:44 INFO: 2 [quorum:3] has received 3 votes and 0 vote rejections
raft2016/08/29 07:08:44 INFO: 2 became leader at term 2
raft2016/08/29 07:08:44 INFO: 4 [logterm: 1, index: 5, vote: 4] rejected vote from 5 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 1 [logterm: 1, index: 5, vote: 2] rejected vote from 5 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 4 received vote rejection from 2 at term 2
raft2016/08/29 07:08:44 INFO: 4 [quorum:3] has received 1 votes and 1 vote rejections
raft2016/08/29 07:08:44 INFO: 4 received vote rejection from 1 at term 2
raft2016/08/29 07:08:44 INFO: 4 [quorum:3] has received 1 votes and 2 vote rejections
raft2016/08/29 07:08:44 INFO: 5 received vote rejection from 3 at term 2
raft2016/08/29 07:08:44 INFO: 5 [quorum:3] has received 1 votes and 1 vote rejections
raft2016/08/29 07:08:44 INFO: 4 received vote rejection from 5 at term 2
raft2016/08/29 07:08:44 INFO: 4 [quorum:3] has received 1 votes and 3 vote rejections
raft2016/08/29 07:08:44 INFO: 4 became follower at term 2
raft2016/08/29 07:08:44 INFO: raft.node: 2 elected leader 2 at term 2
raft2016/08/29 07:08:44 INFO: 2 [logterm: 2, index: 6, vote: 2] rejected vote from 5 [logterm: 1, index: 5] at term 2
raft2016/08/29 07:08:44 INFO: 5 received vote rejection from 1 at term 2
raft2016/08/29 07:08:44 INFO: 5 [quorum:3] has received 1 votes and 2 vote rejections
raft2016/08/29 07:08:44 INFO: 5 received vote rejection from 4 at term 2
raft2016/08/29 07:08:44 INFO: 5 [quorum:3] has received 1 votes and 3 vote rejections
raft2016/08/29 07:08:44 INFO: 5 became follower at term 2
raft2016/08/29 07:08:44 INFO: raft.node: 1 elected leader 2 at term 2
raft2016/08/29 07:08:44 INFO: raft.node: 3 elected leader 2 at term 2
raft2016/08/29 07:08:44 INFO: raft.node: 4 elected leader 2 at term 2
raft2016/08/29 07:08:44 INFO: raft.node: 5 elected leader 2 at term 2
2016/08/29 07:08:44 raft.2: stop
2016/08/29 07:08:44 raft.3: stop
raft2016/08/29 07:08:44 INFO: 3 became follower at term 2
raft2016/08/29 07:08:44 INFO: newRaft 3 [peers: [], term: 2, commit: 6, applied: 0, lastindex: 6, lastterm: 2]
raft2016/08/29 07:08:44 INFO: 2 became follower at term 2
raft2016/08/29 07:08:44 INFO: newRaft 2 [peers: [], term: 2, commit: 6, applied: 0, lastindex: 6, lastterm: 2]
raft2016/08/29 07:08:44 INFO: 5 is starting a new election at term 2
raft2016/08/29 07:08:44 INFO: 5 became candidate at term 3
raft2016/08/29 07:08:44 INFO: 5 received vote from 5 at term 3
raft2016/08/29 07:08:44 INFO: 5 [logterm: 2, index: 6] sent vote request to 3 at term 3
raft2016/08/29 07:08:44 INFO: 5 [logterm: 2, index: 6] sent vote request to 4 at term 3
raft2016/08/29 07:08:44 INFO: 5 [logterm: 2, index: 6] sent vote request to 1 at term 3
raft2016/08/29 07:08:44 INFO: 5 [logterm: 2, index: 6] sent vote request to 2 at term 3
raft2016/08/29 07:08:44 INFO: raft.node: 5 lost leader 2 at term 3
raft2016/08/29 07:08:44 INFO: 1 [term: 2] received a MsgVote message with higher term from 5 [term: 3]
raft2016/08/29 07:08:44 INFO: 4 [term: 2] received a MsgVote message with higher term from 5 [term: 3]
raft2016/08/29 07:08:44 INFO: 4 became follower at term 3
raft2016/08/29 07:08:44 INFO: 1 became follower at term 3
raft2016/08/29 07:08:44 INFO: 1 [logterm: 2, index: 6, vote: 0] voted for 5 [logterm: 2, index: 6] at term 3
raft2016/08/29 07:08:44 INFO: raft.node: 1 lost leader 2 at term 3
raft2016/08/29 07:08:44 INFO: 3 [term: 2] received a MsgVote message with higher term from 5 [term: 3]
raft2016/08/29 07:08:44 INFO: 3 became follower at term 3
raft2016/08/29 07:08:44 INFO: 3 [logterm: 2, index: 6, vote: 0] voted for 5 [logterm: 2, index: 6] at term 3
raft2016/08/29 07:08:44 INFO: 4 [logterm: 2, index: 6, vote: 0] voted for 5 [logterm: 2, index: 6] at term 3
raft2016/08/29 07:08:44 INFO: raft.node: 4 lost leader 2 at term 3
raft2016/08/29 07:08:44 INFO: 5 received vote from 1 at term 3
raft2016/08/29 07:08:44 INFO: 5 [quorum:3] has received 2 votes and 0 vote rejections
raft2016/08/29 07:08:44 INFO: 5 received vote from 3 at term 3
raft2016/08/29 07:08:44 INFO: 5 [quorum:3] has received 3 votes and 0 vote rejections
raft2016/08/29 07:08:44 INFO: 5 became leader at term 3
raft2016/08/29 07:08:44 INFO: raft.node: 5 elected leader 5 at term 3
raft2016/08/29 07:08:44 INFO: raft.node: 1 elected leader 5 at term 3
raft2016/08/29 07:08:44 INFO: raft.node: 4 elected leader 5 at term 3
raft2016/08/29 07:08:44 INFO: raft.node: 3 elected leader 5 at term 3
2016/08/29 07:08:45 raft.1: stop
SIGQUIT: quit
PC=0x4611b1 m=0

goroutine 0 [idle]:
runtime.futex(0x831f88, 0x0, 0x0, 0x0, 0x0, 0x8318d0, 0x0, 0x0, 0x40faaa, 0x831f88, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:306 +0x21
runtime.futexsleep(0x831f88, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x831f88)
        /usr/local/go/src/runtime/lock_futex.go:145 +0xca
runtime.stopm()
        /usr/local/go/src/runtime/proc.go:1538 +0x10b
runtime.findrunnable(0xc820016000, 0x0)
        /usr/local/go/src/runtime/proc.go:1976 +0x808
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:2075 +0x2a6
runtime.park_m(0xc82021e480)
        /usr/local/go/src/runtime/proc.go:2140 +0x157
runtime.mcall(0x454b40)
        /usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0x74a0a0, 0x82ed20, 0x5, 0x5, 0x7fe0b5abf201)
        /usr/local/go/src/testing/testing.go:583 +0xb39
testing.(*M).Run(0xc820039f10, 0x7)
        /usr/local/go/src/testing/testing.go:515 +0x11e
main.main()
        _/go/src/github.com/coreos/etcd/raft/rafttest/_test/_testmain.go:64 +0x211

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan send, 9 minutes]:
_/go/src/github.com/coreos/etcd/raft/rafttest.(*node).stop(0xc8200544d0)
        /go/src/github.com/coreos/etcd/raft/rafttest/node.go:112 +0xa0
_/go/src/github.com/coreos/etcd/raft/rafttest.TestRestart(0xc82009e000)
        /go/src/github.com/coreos/etcd/raft/rafttest/node_test.go:83 +0xd29
testing.tRunner(0xc82009e000, 0x82ed68)
        /usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:582 +0xae3

goroutine 13 [select]:
github.com/coreos/etcd/raft.(*node).run(0xc820013800, 0xc8202002d0)
        /go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:314 +0x15d2
created by github.com/coreos/etcd/raft.StartNode
        /go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:211 +0x890

goroutine 14 [runnable]:
time.Sleep(0xf4240)
        /usr/local/go/src/runtime/time.go:59 +0xf9
_/go/src/github.com/coreos/etcd/raft/rafttest.(*node).start.func1(0xc820013ce0, 0xc820054770)
        /go/src/github.com/coreos/etcd/raft/rafttest/node.go:75 +0x60c
created by _/go/src/github.com/coreos/etcd/raft/rafttest.(*node).start
        /go/src/github.com/coreos/etcd/raft/rafttest/node.go:104 +0xb1

goroutine 15 [select]:
github.com/coreos/etcd/raft.(*node).run(0xc820013e00, 0xc8202003c0)
        /go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:314 +0x15d2
created by github.com/coreos/etcd/raft.StartNode
        /go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:211 +0x890

goroutine 16 [select]:
_/go/src/github.com/coreos/etcd/raft/rafttest.(*node).start.func1(0xc820258300, 0xc8200548c0)
        /go/src/github.com/coreos/etcd/raft/rafttest/node.go:66 +0x1096
created by _/go/src/github.com/coreos/etcd/raft/rafttest.(*node).start
        /go/src/github.com/coreos/etcd/raft/rafttest/node.go:104 +0xb1

goroutine 18 [select]:
github.com/coreos/etcd/raft.(*node).run(0xc8202ba1e0, 0xc8203fa000)
        /go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:314 +0x15d2
created by github.com/coreos/etcd/raft.RestartNode
        /go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:224 +0x36e

goroutine 19 [runnable]:
time.Sleep(0xf4240)
        /usr/local/go/src/runtime/time.go:59 +0xf9
_/go/src/github.com/coreos/etcd/raft/rafttest.(*node).start.func1(0xc8202ba660, 0xc820054620)
        /go/src/github.com/coreos/etcd/raft/rafttest/node.go:75 +0x60c
created by _/go/src/github.com/coreos/etcd/raft/rafttest.(*node).start
        /go/src/github.com/coreos/etcd/raft/rafttest/node.go:104 +0xb1

goroutine 34 [select, 9 minutes]:
github.com/coreos/etcd/raft.(*node).run(0xc8202ac420, 0xc82043c000)
        /go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:314 +0x15d2
created by github.com/coreos/etcd/raft.RestartNode
        /go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:224 +0x36e

goroutine 35 [select, 9 minutes]:
github.com/coreos/etcd/raft.(*node).step(0xc8202ac420, 0x7fe0b59df958, 0xc820010658, 0x2, 0x2, 0x1, 0x0, 0x0, 0x0, 0xc820014f00, ...)
        /go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:437 +0x256
github.com/coreos/etcd/raft.(*node).Step(0xc8202ac420, 0x7fe0b59df958, 0xc820010658, 0x2, 0x2, 0x1, 0x0, 0x0, 0x0, 0xc820014f00, ...)
        /go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:418 +0xd8
_/go/src/github.com/coreos/etcd/raft/rafttest.(*node).start.func1(0xc8202ac8a0, 0xc8200544d0)
        /go/src/github.com/coreos/etcd/raft/rafttest/node.go:82 +0x8f1
created by _/go/src/github.com/coreos/etcd/raft/rafttest.(*node).start
        /go/src/github.com/coreos/etcd/raft/rafttest/node.go:104 +0xb1

rax    0xca
rbx    0x0
rcx    0x4611b3
rdx    0x0
rdi    0x831f88
rsi    0x0
rbp    0x1
rsp    0x7ffcf4338d88
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc82025edd8
r13    0x831e80
r14    0xc82021e480
r15    0x0
rip    0x4611b1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL    _/go/src/github.com/coreos/etcd/raft/rafttest   600.010s
```

**Comment by AkihiroSuda** [comment]
Question: why `rafttest` has been disabled in Travis?
```
IGNORE_PKGS="(cmd|vendor|etcdserverpb|rafttest)"
```
https://github.com/coreos/etcd/pull/5707

**Comment by gyuho** [comment]
@AkihiroSuda Yeah other tests in rafttest are broken as well. We need to fix them.
