### ISSUE TITLE
Cannot restore backup to new cluster

### ISSUE THREAD

**Issue by tschuy** [coreos/etcd#6322]
I'm trying to back up an existing cluster and restore it to a single node on a virtual machine so I can have a copy of the data to work with.

Both machines I'm running `etcd` on are on alpha channel with etcd 2.3.2. 

```
$ # node of existing cluster
$ sudo etcdctl backup --data-dir /var/lib/etcd2 --backup-dir /tmp/etcd2
$ sudo tar -czf discovery-etcd2-backup.tar.gz /tmp/etcd2

$ # my laptop
$ scp core@ip:~/discovery-etcd2-backup.tar.gz ~/
$ scp ~/discovery-etcd2-backup.tar.gz core@192.168.122.2:~/bkp.tar.gz

$ # 192.168.122.2
$ tar xzf bkp.tar.gz
$ cd tmp/etcd2
$ etcd2 --data-dir=`pwd` --force-new-cluster
2016-08-31 21:32:57.293015 I | etcdmain: etcd Version: 2.3.2
2016-08-31 21:32:57.293666 I | etcdmain: Git SHA: ce63f10
2016-08-31 21:32:57.294199 I | etcdmain: Go Version: go1.6.3
2016-08-31 21:32:57.294452 I | etcdmain: Go OS/Arch: linux/amd64
2016-08-31 21:32:57.294672 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2016-08-31 21:32:57.295176 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-08-31 21:32:57.297886 I | etcdmain: listening for peers on http://localhost:2380
2016-08-31 21:32:57.299014 I | etcdmain: listening for peers on http://localhost:7001
2016-08-31 21:32:57.299849 I | etcdmain: listening for client requests on http://localhost:2379
2016-08-31 21:32:57.300861 I | etcdmain: listening for client requests on http://localhost:4001
```

It'll look good for a few seconds, and then suddenly:

```
2016-08-31 21:33:06.890096 I | etcdserver: recovered store from snapshot at index 2619106666
2016-08-31 21:33:06.890235 I | etcdserver: name = default
2016-08-31 21:33:06.890287 I | etcdserver: force new cluster
2016-08-31 21:33:06.890331 I | etcdserver: data dir = /home/core/tmp/etcdbkp
2016-08-31 21:33:06.890374 I | etcdserver: member dir = /home/core/tmp/etcdbkp/member
2016-08-31 21:33:06.890413 I | etcdserver: heartbeat = 100ms
2016-08-31 21:33:06.890504 I | etcdserver: election = 1000ms
2016-08-31 21:33:06.890565 I | etcdserver: snapshot count = 10000
2016-08-31 21:33:06.890628 I | etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2016-08-31 21:33:06.899946 I | etcdserver: forcing restart of member 56e1f00b6b01 in cluster 56e1f00b6b02 at commit index 2619112460
2016-08-31 21:33:06.900389 I | raft: 56e1f00b6b01 became follower at term 1517828
2016-08-31 21:33:06.900454 I | raft: newRaft 56e1f00b6b01 [peers: [86c13032f1cdc0,31c5cfd1106f9608,3547ec1bd35d0a84,d23f70f817a2d5b6,e1ddce3b6ae591ff], term: 1517828, commit: 2619112460, applied: 2619106666, lastindex: 2619112460, lastterm: 1517828]
2016-08-31 21:33:06.900648 I | etcdserver: added member 3547ec1bd35d0a84 [http://10.16.9.115:2380] to cluster 56e1f00b6b02 from store
2016-08-31 21:33:06.900706 I | etcdserver: added member 86c13032f1cdc0 [http://10.16.9.113:2380] to cluster 56e1f00b6b02 from store
2016-08-31 21:33:06.900742 I | etcdserver: added member d23f70f817a2d5b6 [http://10.16.9.111:2380] to cluster 56e1f00b6b02 from store
2016-08-31 21:33:06.900777 I | etcdserver: added member e1ddce3b6ae591ff [http://10.16.9.87:2380] to cluster 56e1f00b6b02 from store
2016-08-31 21:33:06.900812 I | etcdserver: added member 31c5cfd1106f9608 [http://10.16.9.23:2380] to cluster 56e1f00b6b02 from store
2016-08-31 21:33:06.900849 I | etcdserver: set the cluster version to 2.3 from store
2016-08-31 21:33:06.902824 I | etcdserver: starting server... [version: 2.3.2, cluster version: 2.3]
2016-08-31 21:33:06.903181 E | etcdmain: failed to notify systemd for readiness: No socket
2016-08-31 21:33:06.903236 E | etcdmain: forgot to set Type=notify in systemd service file?
2016-08-31 21:33:06.969403 N | etcdserver: removed member 86c13032f1cdc0 from cluster 56e1f00b6b02
2016-08-31 21:33:06.969718 N | etcdserver: removed member 31c5cfd1106f9608 from cluster 56e1f00b6b02
2016-08-31 21:33:06.969918 N | etcdserver: removed member 3547ec1bd35d0a84 from cluster 56e1f00b6b02
2016-08-31 21:33:06.970125 N | etcdserver: removed member d23f70f817a2d5b6 from cluster 56e1f00b6b02
panic: runtime error: index out of range

goroutine 54 [running]:
panic(0xdc82a0, 0xc820010070)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/raft.(*raft).maybeCommit(0xc8481eacc0, 0xc8482f40c0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.2/work/gopath/src/github.com/coreos/etcd/raft/raft.go:382 +0x302
github.com/coreos/etcd/raft.(*raft).removeNode(0xc8481eacc0, 0xe1ddce3b6ae591ff)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.2/work/gopath/src/github.com/coreos/etcd/raft/raft.go:842 +0x59
github.com/coreos/etcd/raft.(*node).run(0xc8481f06e0, 0xc8481eacc0)
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.2/work/gopath/src/github.com/coreos/etcd/raft/node.go:330 +0xca4
created by github.com/coreos/etcd/raft.RestartNode
	/build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.2/work/gopath/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4
```

I''ve tried `ETCD_INITIAL_ADVERTISE_PEER_URLS=http://127.0.0.1:2380` to no avail.

**Comment by xiang90** [comment]
@tschuy Can you try with 2.3.7? I believe there was a bug in early version of 2.3 release.

**Comment by tschuy** [comment]
ah, looks like that solves it. thanks!
