### ISSUE TITLE
auth: docs sadly out of date / segfault on --user

### ISSUE THREAD

**Issue by glycerine** [coreos/etcd#6343]
The authentication docs, found here:

https://coreos.com/etcd/docs/latest/authentication.html

are woefully out of date. Moreover nobody must be using --user, because it segfaults instantly.

details:

```
On OSX 10.11.6, at etcd tip (as of this writing: 0d07154926ab68d1d05abc2600234c6b4021550e)
ETCDCTL_API=3 in the environment
go1.7 dawmin/amd64

$ etcd --version
etcd Version: 3.0.0+git
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.7
Go OS/Arch: darwin/amd64
```

```
$ etcdctl user grant root -roles root
Error: unknown shorthand flag: 'r' in -roles

docs should be updated to suggest: etcdctl user grant root root
```

```
$ etcdctl auth enable
Authentication Enabled

$ etcdctl role get guest
Error:  etcdserver: user name not found

# invalidating the claim: "This [role guest] will be created on security activation (if it doesn’t already exist) to have full access to all keys, as was true in etcd 2.0." from https://coreos.com/etcd/docs/latest/authentication.html
# also, seems to be looking for a user rather than a role, according to the error message.
```

```
$ etcdctl -u root get a z
Error: unknown shorthand flag: 'u' in -u

# docs give -u as an example, but it no longer works.

# trying --user results in a segfault:

$ etcdctl --user root get a z
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x7be600, 0xc420016100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/etcd/etcdctl/ctlv3/command.authCfgFromCmd(0xc42023e000, 0xc4201707c0)
	/Users/me/go/src/github.com/coreos/etcd/etcdctl/ctlv3/command/global.go:254 +0x27a
github.com/coreos/etcd/etcdctl/ctlv3/command.mustClientFromCmd(0xc42023e000, 0xe8e068)
	/Users/me/go/src/github.com/coreos/etcd/etcdctl/ctlv3/command/global.go:88 +0x101
github.com/coreos/etcd/etcdctl/ctlv3/command.getCommandFunc(0xc42023e000, 0xc420170700, 0x2, 0x4)
	/Users/me/go/src/github.com/coreos/etcd/etcdctl/ctlv3/command/get_command.go:61 +0xe5
github.com/spf13/cobra.(*Command).execute(0xc42023e000, 0xc4201706c0, 0x4, 0x4, 0xc42023e000, 0xc4201706c0)
	/Users/me/go/src/github.com/spf13/cobra/command.go:603 +0x439
github.com/spf13/cobra.(*Command).ExecuteC(0xc86a40, 0x8c53c6, 0xb, 0xc42017de78)
	/Users/me/go/src/github.com/spf13/cobra/command.go:689 +0x367
github.com/spf13/cobra.(*Command).Execute(0xc86a40, 0x0, 0x0)
	/Users/me/go/src/github.com/spf13/cobra/command.go:648 +0x2b
github.com/coreos/etcd/etcdctl/ctlv3.Start()
	/Users/me/go/src/github.com/coreos/etcd/etcdctl/ctlv3/ctl.go:96 +0x8e
main.main()
	/Users/me/go/src/github.com/coreos/etcd/etcdctl/main.go:40 +0x1fb
$
```

**Comment by glycerine** [comment]
https://github.com/coreos/etcd/pull/6344 addresses the panic.

**Comment by xiang90** [comment]
The doc you looked at is for v2. CoreOS doc is not on v3 yet. Check https://github.com/coreos/etcd/blob/master/etcdctl/README.md#auth-enable-or-disable instead.

**Comment by glycerine** [comment]
okay. would be polite if the docs actually said that they are for version 2 at the top of the page -- I found it directly from Google, and the url includes the word 'latest'. So I was mislead.

**Comment by glycerine** [comment]
the doc portion is a dup of #6342, so I'm closing this out now that #6344 merged.
