### ISSUE TITLE
TestWatchWithRequireLeader: Timed out

### ISSUE THREAD

**Issue by fanminshi** [coreos/etcd#6386]
Via semaphore https://semaphoreci.com/coreos/etcd/branches/master/builds/892

```
goroutine 55316 [chan receive, 6 minutes]:
github.com/coreos/etcd/clientv3/integration.TestWatchWithRequireLeader(0xc822e87320)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/integration/watch_test.go:672 +0x1285
testing.tRunner(0xc822e87320, 0x19ed6f8)
	/usr/local/golang/1.6.3/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/golang/1.6.3/go/src/testing/testing.go:582 +0xae3
```

**Comment by gyuho** [comment]
Logs show that it's hanging waiting from `<-chNoLeader`. 

https://github.com/coreos/etcd/blob/master/clientv3/integration/watch_test.go#L715

I've running this test over 5k rounds but cannot reproduce yet...
