### ISSUE TITLE
Unable to restore ETCD2 data 

### ISSUE THREAD

**Issue by muralibandi** [coreos/etcd#6477]
Hi ,

I lost data on one of my etcd node and trying to restore data from other node in etcd2 cluster. But facing issues.. 

kube-master01 backup # etcd2 --data-dir=/home/core/new/backup/ -force-new-cluster
2016-09-20 02:57:35.855033 I | etcdmain: etcd Version: 2.3.2
2016-09-20 02:57:35.855117 I | etcdmain: Git SHA: ce63f10
2016-09-20 02:57:35.855124 I | etcdmain: Go Version: go1.6.3
2016-09-20 02:57:35.855141 I | etcdmain: Go OS/Arch: linux/amd64
2016-09-20 02:57:35.855159 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2016-09-20 02:57:35.855283 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-09-20 02:57:35.855974 I | etcdmain: listening for peers on http://localhost:2380
2016-09-20 02:57:35.856107 I | etcdmain: listening for peers on http://localhost:7001
2016-09-20 02:57:35.856198 I | etcdmain: listening for client requests on http://localhost:2379
2016-09-20 02:57:35.856296 I | etcdmain: listening for client requests on http://localhost:4001
2016-09-20 02:57:35.961404 I | etcdserver: recovered store from snapshot at index 1160117
2016-09-20 02:57:35.961446 I | etcdserver: name = default
2016-09-20 02:57:35.961453 I | etcdserver: force new cluster
2016-09-20 02:57:35.961459 I | etcdserver: data dir = /home/core/new/backup/
2016-09-20 02:57:35.961468 I | etcdserver: member dir = /home/core/new/backup/member
2016-09-20 02:57:35.961478 I | etcdserver: heartbeat = 100ms
2016-09-20 02:57:35.961488 I | etcdserver: election = 1000ms
2016-09-20 02:57:35.961499 I | etcdserver: snapshot count = 10000
2016-09-20 02:57:35.961513 I | etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2016-09-20 02:57:35.988090 I | etcdserver: discarding 1 uncommitted WAL entries 
2016-09-20 02:57:35.999740 I | etcdserver: forcing restart of member 574584e3ae01 in cluster 574584e3ae02 at commit index 1161865
2016-09-20 02:57:36.000128 I | raft: 574584e3ae01 became follower at term 2101
2016-09-20 02:57:36.000161 I | raft: newRaft 574584e3ae01 [peers: [115eb6d719f91346,32c45f331a7bdfad,3beeedb5112cef4c,3f17b387edc5ba53,5eb961e4ea824fa2], term: 2101, commit: 1161865, applied: 1160117, lastindex: 1161865, lastterm: 2101]
2016-09-20 02:57:36.000391 I | etcdserver: added member 115eb6d719f91346 [http://x.x.x.136:2380] to cluster 574584e3ae02 from store
2016-09-20 02:57:36.000416 I | etcdserver: added member 32c45f331a7bdfad [http://x.x.x.165:2380] to cluster 574584e3ae02 from store
2016-09-20 02:57:36.000429 I | etcdserver: added member 3beeedb5112cef4c [http://x.x.x.132:2380] to cluster 574584e3ae02 from store
2016-09-20 02:57:36.000440 I | etcdserver: added member 3f17b387edc5ba53 [http://x.x.x.122:2380] to cluster 574584e3ae02 from store
2016-09-20 02:57:36.000451 I | etcdserver: added member 5eb961e4ea824fa2 [http://x.x.x.142:2380] to cluster 574584e3ae02 from store
2016-09-20 02:57:36.000464 I | etcdserver: set the cluster version to 2.3 from store
2016-09-20 02:57:36.005477 E | rafthttp: request sent was ignored (cluster ID mismatch: remote[115eb6d719f91346]=de80bbe64a1c04d1, local=574584e3ae02)
2016-09-20 02:57:36.005516 E | rafthttp: request sent was ignored (cluster ID mismatch: remote[115eb6d719f91346]=de80bbe64a1c04d1, local=574584e3ae02)
2016-09-20 02:57:36.011380 E | rafthttp: request sent was ignored (cluster ID mismatch: remote[3beeedb5112cef4c]=de80bbe64a1c04d1, local=574584e3ae02)
2016-09-20 02:57:36.012880 I | etcdserver: starting server... [version: 2.3.2, cluster version: 2.3]
2016-09-20 02:57:36.013610 E | etcdmain: failed to notify systemd for readiness: No socket
2016-09-20 02:57:36.013627 E | etcdmain: forgot to set Type=notify in systemd service file?
2016-09-20 02:57:36.013899 E | rafthttp: request sent was ignored (cluster ID mismatch: remote[3beeedb5112cef4c]=de80bbe64a1c04d1, local=574584e3ae02)
2016-09-20 02:57:36.014245 E | rafthttp: request sent was ignored (cluster ID mismatch: remote[3f17b387edc5ba53]=de80bbe64a1c04d1, local=574584e3ae02)
2016-09-20 02:57:36.014563 E | rafthttp: request sent was ignored (cluster ID mismatch: remote[3f17b387edc5ba53]=de80bbe64a1c04d1, local=574584e3ae02)
2016-09-20 02:57:36.015834 N | etcdserver: removed member 32c45f331a7bdfad from cluster 574584e3ae02
2016-09-20 02:57:36.017487 N | etcdserver: removed member 115eb6d719f91346 from cluster 574584e3ae02
2016-09-20 02:57:36.017684 N | etcdserver: removed member 3beeedb5112cef4c from cluster 574584e3ae02
2016-09-20 02:57:36.017899 N | etcdserver: removed member 3f17b387edc5ba53 from cluster 574584e3ae02
panic: runtime error: index out of range

goroutine 76 [running]:
panic(0xdc82a0, 0xc82000e070)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/raft.(*raft).maybeCommit(0xc8200e20c0, 0xc8202e0d20)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.2/work/gopath/src/github.com/coreos/etcd/raft/raft.go:382 +0x302
github.com/coreos/etcd/raft.(*raft).removeNode(0xc8200e20c0, 0x5eb961e4ea824fa2)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.2/work/gopath/src/github.com/coreos/etcd/raft/raft.go:842 +0x59
github.com/coreos/etcd/raft.(*node).run(0xc82037e460, 0xc8200e20c0)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.2/work/gopath/src/github.com/coreos/etcd/raft/node.go:330 +0xca4
created by github.com/coreos/etcd/raft.RestartNode
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.2/work/gopath/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4
-kube-master01 backup #

**Comment by muralibandi** [comment]
Below is the command used to take backup from the a node in the cluster.


etcdctl backup --data-dir /var/lib/etcd2 --backup-dir /root/backup/

**Comment by muralibandi** [comment]
Can some one help me on this, do i have any option other than rebuilding etcd cluster?

**Comment by heyitsanthony** [comment]
@muralibandi I created a backup with a two member cluster in 2.3.2 and got the same error when restoring with `-force-new-cluster`. Restoring from the same backup with 2.3.7 and `-force-new-cluster` works for me. So, try 2.3.7?

**Comment by muralibandi** [comment]
I am able to restore my cluster using steps mentioned in below url..

https://coreos.com/etcd/docs/latest/etcd-live-cluster-reconfiguration.html

**Comment by xiang90** [comment]
2.3.2 has known issue with --force-new-cluster flag. it is fixed since 2.3.3. As you already got it working, I close this issue. Thanks!
