### ISSUE TITLE
wal: can't repair with subsequent zero entries in sector

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#6515]
- Happened in functional-tester with failpoints with master branch (2 days ago, there was no change in `wal` package)
- Data can be found here https://console.cloud.google.com/storage/browser/etcd-functional-tester/wal-crc-20160923

To summarize,

```
panic: failpoint panic: etcd-tester

goroutine 55 [running]:
panic(0xc9a720, 0xc42ab36090)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/gofail/runtime.actPanic(0xc425204240, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/gofail/runtime/terms.go:318 +0x164
github.com/coreos/gofail/runtime.(*term).do(0xc425204240, 0xe98901, 0xc4252042b8)
	/home/gyuho/go/src/github.com/coreos/gofail/runtime/terms.go:290 +0x2f
github.com/coreos/gofail/runtime.(*terms).eval(0xc425204280, 0x0, 0x0, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/gofail/runtime/terms.go:105 +0x13a
github.com/coreos/gofail/runtime.(*Failpoint).Acquire(0xc4201eab40, 0x0, 0x0, 0x1295260, 0xc42011b630)
	/home/gyuho/go/src/github.com/coreos/gofail/runtime/failpoint.go:41 +0x4c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).commit(0xc420268f00, 0xe95c00)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:171 +0xfc
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).Commit(0xc420268f00)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:140 +0x66
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*backend).run(0xc4202b7680)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:199 +0x13b
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.newBackend
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:119 +0x1c4
2016-09-22 19:28:21.002754 I | etcdmain: etcd Version: 3.1.0-alpha.0+git
2016-09-22 19:28:21.002817 I | etcdmain: Git SHA: 095cff4-FAILPOINTS
2016-09-22 19:28:21.002824 I | etcdmain: Go Version: go1.7.1
2016-09-22 19:28:21.002832 I | etcdmain: Go OS/Arch: linux/amd64
2016-09-22 19:28:21.002842 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2016-09-22 19:28:21.002884 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-09-22 19:28:21.002895 I | etcdmain: advertising using detected default host "10.240.0.19"
2016-09-22 19:28:21.002945 I | embed: listening for peers on http://10.240.0.19:2380
2016-09-22 19:28:21.002972 I | embed: listening for client requests on 10.240.0.19:2379
2016-09-22 19:28:21.012801 W | snap: skipped unexpected non snapshot file 0000000000002129-000000000732d31f.snap.broken
2016-09-22 19:28:21.025515 I | etcdserver: recovered store from snapshot at index 269745050
2016-09-22 19:28:21.025556 I | etcdserver: name = etcd-0
2016-09-22 19:28:21.025562 I | etcdserver: data dir = agent.etcd
2016-09-22 19:28:21.025570 I | etcdserver: member dir = agent.etcd/member
2016-09-22 19:28:21.025576 I | etcdserver: heartbeat = 100ms
2016-09-22 19:28:21.025581 I | etcdserver: election = 1000ms
2016-09-22 19:28:21.025586 I | etcdserver: snapshot count = 10000
2016-09-22 19:28:21.025601 I | etcdserver: advertise client URLs = http://10.240.0.19:2379
2016-09-22 19:28:21.289585 C | etcdserver: read wal error (walpb: crc mismatch) and cannot be repaired
```

And if I run the `wal.Repair` function on this WAL file

```go
wal.Repair("./agent09/agent.etcd/member/wal")
```

```
sector: [8 2 16 137 170 155 150 12 26 153 1 8 0 16 153 150 1 24 131 196 208 128 1 34 138 1 34 123 10 19 102 111 111 48 48 48 48 48 48 48 48 48 48 48 48 99 98 55 49 18 100 116 121 104 104 101 112 109 115 116 105 113 112 114 109 97 100 121 107 111 100 117 109 114 105 108 107 100 111 104]
sector: [117 112 110 117 114 109 113 121 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2016-09-23 16:33:00.188711 E | wal: could not repair error (walpb: crc mismatch)
```

First sector is 80 bytes, second is 88 bytes, where the first 8 bytes aren't zero.
So `d.isTornEntry(data)` returns `false`.

@heyitsanthony Should we return `true` when subsequent entries after non-zero bytes are all zero in sector?

I tried running `Repair` bypassing this error, and the repair worked.

**Comment by heyitsanthony** [comment]
@gyuho `isTornEntry` should only look a single entry; subsequent entries don't matter. It is supposed to check that if a single record is corrupted, then the bytes for that one entry should be all 0's on at least one of the sectors it spans. The disk model is that if a record is corrupted, then at least one of its sectors wasn't written down with the entry data. If the sector wasn't written with the entry data, then the bytes on that sector covering that entry should still be 0.

I'm not surprised removing the check was able to repair the problem; repair will truncate away the bad entry and the wal will be valid. This isn't necessary correct since by removing that check there's no telling whether the record was synced as committed (repair should reject the wal) or not (repair should fix the wal).

The way to debug the sort of corruption that's happening is to find the broken entry (starting with the length header) and look its contents (are there any gaps if 0's? does it look like there's another record/record length header inside this record?) and maybe the following entry (is the next length corrupted?).

**Comment by gyuho** [comment]
@heyitsanthony Right. I will first reproduce more, and then look more closely at the WAL files. Thanks.

**Comment by gyuho** [comment]
@heyitsanthony Some progress...


> find the broken entry

The broken WAL file is `agent09/agent.etcd/member/wal/000000000000039b-0000000010115210.wal`, where `wal.Repair("./agent09/agent.etcd/member/wal")` returns `wal: could not repair error (walpb: crc mismatch)` error.

<br>

> and look its contents

`od` command shows

```
tail -2 agent09/agent.etcd/member/wal/000000000000039b-0000000010115210.wal | od -tx1 -Ax
000000 08 cc aa 8c f5 b5 ea 95 f6 24 00 00 00 00 a4 00
000010 00 00 00 00 00 84 08 02 10 89 aa 9b 96 0c 1a 99
000020 01 08 00 10 99 96 01 18 83 c4 d0 80 01 22 8a 01
000030 22 7b 0a 13 66 6f 6f 30 30 30 30 30 30 30 30 30
000040 30 30 30 63 62 37 31 12 64 74 79 68 68 65 70 6d
000050 73 74 69 71 70 72 6d 61 64 79 6b 6f 64 75 6d 72
000060 69 6c 6b 64 6f 68 75 70 6e 75 72 6d 71 79 00 00
000070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
13d9660 00 00 00 00 00 00
13d9666
```

If we look at raw bytes of that file with some print statement inside `(d *decoder) decodeRecord(rec *walpb.Record)`

```go
fmt.Println("iteration", i, ":", rec.Crc)
fmt.Println("===data===")
fmt.Println(string(data))
```

Last entries are shown as below

```
iteration 235723 : 1072436981
===data===
��������Ѐ"9**
foo000000000000e50ffoo000000000000e703�
˪������$

iteration 235724 : 3744476934
===data===
����Ѐ"$*
foo0000000000024471�
������$

iteration 235725 : 3267810569
===data===
����
      �����Ѐ"�"{
foo000000000000cb71dtyhhepmstiqprmadykodumrilkdohupnurmqy

2016-09-27 07:32:55.794725 E | wal: could not repair error (walpb: crc mismatch)
```

`3267810569` is the mismatched hash, and the corrupted entry has bytes of `foo000000000000cb71` and `tyhhepmstiqprmadykodumrilkdohupnurmqy`. So I tried to find the corresponding entry in other WAL directory that's not corrupted.

```go
wal.Repair("./agent10/agent.etcd/member/wal")

if strings.Contains(string(data), "oo000000000000cb71") && strings.Contains(string(data), "tyhhepmstiqprmadykodumrilkdohupnurmqy") {
	fmt.Println()
	fmt.Println("iteration", i, ":", rec.Crc)
	fmt.Println("===data===")
	fmt.Println(string(data))
}
```

And there is a corresponding entry that's not corrupted

```
iteration 93491 : 1101555404
===data===
�͡������Ѐ"�"{
foo000000000000cb71dtyhhepmstiqprmadykodumrilkdohupnurmqynhmohxwlodocrguwgnbjxsfbtgbooefvyrqpeuqdjqzctpinpmpcbmqngojftkb�
```

<br>
If we compare those two entries

```
# corrupted
CRC: 3267810569
data:
����
      �����Ѐ"�"{
foo000000000000cb71dtyhhepmstiqprmadykodumrilkdohupnurmqy

# non-corrupted
CRC: 1101555404
data:
�͡������Ѐ"�"{
foo000000000000cb71dtyhhepmstiqprmadykodumrilkdohupnurmqynhmohxwlodocrguwgnbjxsfbtgbooefvyrqpeuqdjqzctpinpmpcbmqngojftkb�
������$
```

We can see corrupted entry was partial-write.

Does this make sense?

I will debug further today.

**Comment by gyuho** [comment]
@heyitsanthony pointed out our page writer doesn't consider the file offsets, where it should. I will try to make page writer aware of file offsets with test cases.
