### ISSUE TITLE
TestWatchEventType: WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6534]
via semaphore (https://semaphoreci.com/coreos/etcd/branches/master/builds/995)

```
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 57085 [running]:
panic(0xf5aa20, 0xc420937640)
	/usr/local/golang/1.7/go/src/runtime/panic.go:500 +0x1ae
sync.(*WaitGroup).Wait(0xc4281f9ae8)
	/usr/local/golang/1.7/go/src/sync/waitgroup.go:133 +0x13e
github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func1(0xc4281f98c0, 0x1568880, 0xc42214e8a0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:580 +0x82
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc4281f98c0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:645 +0xad7
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:503 +0x5aa
```

**Comment by gyuho** [comment]
@heyitsanthony @xiang90 Go doc says

```
	// This goroutine has set counter to 0 when waiters > 0.
	// Now there can't be concurrent mutations of state:
	// - Adds must not happen concurrently with Wait,
	// - Wait does not increment waiters if it sees counter == 0.
```

We are calling `Wait` in defer statement, while concurrent `Add` call (from `goAttach`) happens.
