### ISSUE TITLE
Lease: Retrieving lease info using lease client LeaseTimeToLive() causes etcd node panic and die

### ISSUE THREAD

**Issue by fanminshi** [coreos/etcd#6537]
I observe that when lease client is retrieving a lease using LeaseTimeToLive() at the moment after the lease just has expired causes one of three etcd nodes to panic and die.

Setup:
OS: OS X El Captitan 10.11.6
etcd Version: 3.1.0-alpha.0+gi
Go Version: go1.7
Go OS/Arch: darwin/amd64

Recreating the issue:
1. Download ectd code in your working directory.
2. CD into `../github.com/coreos/etcd`, start a three node etcd quorum via `goreman start` 
3. In a different terminal, run following script 
```go
package main
import (
	"fmt"
	pb "github.com/coreos/etcd/etcdserver/etcdserverpb"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
)

func main() {
	p := fmt.Println
	conn, err := grpc.Dial("localhost:2379", grpc.WithInsecure())
	if err != nil {
		p(err)
	}
	lc := pb.NewLeaseClient(conn)
	ctx, _ := context.WithCancel(context.Background())

	resp, err := lc.LeaseGrant(ctx, &pb.LeaseGrantRequest{
		TTL: 2,
	}, grpc.FailFast(false))

	LTL := &pb.LeaseTimeToLiveRequest{
		ID:   resp.ID,
		Keys: true,
	}

	for {
		leaseTTLResp, err := lc.LeaseTimeToLive(ctx, LTL)
		if err != nil {
			p(err)
		}
		p(leaseTTLResp)
	}
}
```

4. Observe that output from etcd quorum shows a panic message around 2 second after script execution of  step 3,  
```
12:32:54 etcd1 | panic: 
12:32:54 etcd1 | runtime error: invalid memory address or nil pointer dereference
12:32:54 etcd1 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3820a3]
12:32:54 etcd1 | goroutine 17968 [running]:
12:32:54 etcd1 | panic(0x8ec6a0, 0xc420010080)
12:32:54 etcd1 | 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
12:32:54 etcd1 | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*LeaseServer).LeaseTimeToLive(0xc420369040, 0xe961c0, 0xc4215e6690, 0xc4216b5a50, 0xe994a0, 0xc4202a58c0, 0x0)
12:32:54 etcd1 | 	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/lease.go:62 +0x73
12:32:54 etcd1 | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*quotaLeaseServer).LeaseTimeToLive(0xc4203690c0, 0xe961c0, 0xc4215e6690, 0xc4216b5a50, 0xc4200fc8e0, 0x5e215, 0x1bd3a2)
12:32:54 etcd1 | 	<autogenerated>:26 +0x6b
12:32:54 etcd1 | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb._Lease_LeaseTimeToLive_Handler.func1(0xe961c0, 0xc4215e6690, 0x973040, 0xc4216b5a50, 0xe994a0, 0xc4202a58c0, 0xc, 0x0)
12:32:54 etcd1 | 	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2672 +0xa2
12:32:54 etcd1 | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.metricsUnaryInterceptor(0xe961c0, 0xc4215e6690, 0x973040, 0xc4216b5a50, 0xc421719340, 0xc421719360, 0x108c8, 0x20, 0x91d420, 0x1)
12:32:54 etcd1 | 	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:100 +0x186
12:32:54 etcd1 | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1(0xe961c0, 0xc4215e6690, 0x973040, 0xc4216b5a50, 0xc421719340, 0xc421719360, 0xc, 0x0, 0x0, 0xc4200fcaf8)
12:32:54 etcd1 | 	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:56 +0xc3
12:32:54 etcd1 | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb._Lease_LeaseTimeToLive_Handler(0x920800, 0xc4203690c0, 0xe961c0, 0xc4215e6690, 0xc4217167d0, 0xc420077ea0, 0x0, 0x0, 0xc42001f500, 0xc420e25520)
12:32:54 etcd1 | 	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2674 +0x166
12:32:54 etcd1 | github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420dee000, 0xe99620, 0xc420212900, 0xc4215e43c0, 
12:32:54 etcd1 | 0xc420e50570, 0xeb6a10, 0x0, 0x0, 0x0)
12:32:54 etcd1 | 	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:608 +0xc50
12:32:54 etcd1 | github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420dee000, 0xe99620, 0xc420212900, 0xc4215e43c0, 0x0)
12:32:54 etcd1 | 	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:766 +0x6b0
12:32:54 etcd1 | github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420e53690, 0xc420dee000, 0xe99620, 0xc420212900, 0xc4215e43c0)
12:32:54 etcd1 | 	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:419 +
12:32:54 etcd1 | 0xab
12:32:54 etcd1 | created by 
12:32:54 etcd1 | github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
12:32:54 etcd1 | 	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:420 +0xa3
```

**Comment by gyuho** [comment]
Just to add

This starts happening when lease gets expired.

I will look at the code path sometime today as well.
