### ISSUE TITLE
TestReleaseUpgrade fails on arm64

### ISSUE THREAD

**Issue by glevand** [coreos/etcd#6561]
On arm64, when running the test script I get a failure of TestReleaseUpgrade, but when I run the test individually it passes:

```GOPATH=$(pwd) PASSES="build unit release integration" ./test```

```GOPATH=$(pwd)/gopath:$(pwd) go test -v -run 'TestReleaseUpgrade' github.com/coreos/etcd/e2e```

Here's the failure:

```
=== RUN   TestReleaseUpgrade
--- FAIL: TestReleaseUpgrade (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b3010]

goroutine 1209 [running]:
panic(0xc52f40, 0x48200121b0)
        /usr/local/lib/go-1.6.3/src/runtime/panic.go:481 +0x384
testing.tRunner.func1(0x4820200990)
        /usr/local/lib/go-1.6.3/src/testing/testing.go:467 +0x168
panic(0xc52f40, 0x48200121b0)
        /usr/local/lib/go-1.6.3/src/runtime/panic.go:443 +0x4b4
github.com/coreos/etcd/e2e.(*etcdProcessCluster).Close(0x48200e12e0, 0x0, 0x0)
        /home/geoff/projects/coreos/git/coreos--etcd/gopath/src/github.com/coreos/etcd/e2e/etcd_test.go:427 +0x80
github.com/coreos/etcd/e2e.newEtcdProcessCluster(0x4820200ab0, 0x4820200ab0, 0x0, 0x0)
        /home/geoff/projects/coreos/git/coreos--etcd/gopath/src/github.com/coreos/etcd/e2e/etcd_test.go:189 +0x16c
exit status 2
FAIL    github.com/coreos/etcd/e2e      172.002s
github.com/coreos/etcd/e2e.TestReleaseUpgrade(0x4820200990)
        /home/geoff/projects/coreos/git/coreos--etcd/gopath/src/github.com/coreos/etcd/e2e/etcd_release_upgrade_test.go:43 +0x23c
testing.tRunner(0x4820200990, 0x11fdee0)
        /usr/local/lib/go-1.6.3/src/testing/testing.go:473 +0xbc
created by testing.RunTests
        /usr/local/lib/go-1.6.3/src/testing/testing.go:582 +0x65c
```

**Comment by glevand** [comment]
I'll close this issue.  https://github.com/coreos/etcd/pull/6564 fixed the null pointer deference.  I'll look into fixing the test failure and either open a PR if I can find a fix, or open another issue if I can't.
