### ISSUE TITLE
TestWatchReconnRequest: index out of range

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6606]
via semaphore (https://semaphoreci.com/coreos/etcd/branches/master/builds/1057)

Probably due to receiving an error when an event is expected.

```
--- FAIL: TestWatchReconnRequest (0.33s)
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 58239 [running]:
panic(0xfb3b20, 0xc420016140)
        /usr/local/golang/1.7.1/go/src/runtime/panic.go:500 +0x1ae
testing.tRunner.func1(0xc4233ac9c0)
        /usr/local/golang/1.7.1/go/src/testing/testing.go:579 +0x474
panic(0xfb3b20, 0xc420016140)
        /usr/local/golang/1.7.1/go/src/runtime/panic.go:458 +0x271
github.com/coreos/etcd/clientv3/integration.putAndWatch(0xc4233ac9c0, 0xc4219c59a0, 0x10c6328, 0x1, 0x10c6328, 0x1)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/integration/watch_test.go:344 +0x5d2
github.com/coreos/etcd/clientv3/integration.testWatchReconnRequest(0xc4233ac9c0, 0xc4219c59a0)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/integration/watch_test.go:223 +0x348
github.com/coreos/etcd/clientv3/integration.runWatchTest(0xc4233ac9c0, 0x1182f60)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/integration/watch_test.go:67 +0x697
github.com/coreos/etcd/clientv3/integration.TestWatchReconnRequest(0xc4233ac9c0)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/integration/watch_test.go:184 +0x45
testing.tRunner(0xc4233ac9c0, 0x1182ec8)
        /usr/local/golang/1.7.1/go/src/testing/testing.go:610 +0xca
created by testing.(*T).Run
        /usr/local/golang/1.7.1/go/src/testing/testing.go:646 +0x530
exit status 2
```

**Comment by xiang90** [comment]
@gyuho Can you take a look?

**Comment by gyuho** [comment]
Sure

**Comment by gyuho** [comment]
@heyitsanthony Haven't been able to reproduce this, with over 1,500 rounds...

Only possibility that I can think of is that the popping the created event here https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L589

```go
if len(ws.buf) > 0 && ws.buf[0].Created {
	select {
	case ws.initReq.retc <- ws.outc:
		// send first creation event and only if requested
		if !ws.initReq.createdNotify {
			ws.buf = ws.buf[1:]
		}
	default:
	}
}
```

`ws.initReq.retc <- ws.outc` could block, and `select` falls through `default` case.

And the created event gets sent out, with 0 event in its response.

Why do we have `default:` here? Does it ever get blocked?

Thanks.

**Comment by heyitsanthony** [comment]
Yeah, this code sending too many create events.
