### ISSUE TITLE
data race: TestSnapshot

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#6728]
```
WARNING: DATA RACE
Write at 0x00c42049a343 by goroutine 103:
  testing.(*common).FailNow()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:452 +0x4a
  testing.(*common).Fatalf()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:496 +0x94
  github.com/coreos/etcd/etcdserver.TestSnapshot.func2()
      /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server_test.go:866 +0x33e
Previous write at 0x00c42049a343 by goroutine 81:
  testing.(*common).FailNow()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:452 +0x4a
  testing.(*common).Fatalf()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:496 +0x94
  github.com/coreos/etcd/etcdserver.TestSnapshot.func3()
      /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server_test.go:877 +0x523
Goroutine 103 (running) created at:
  github.com/coreos/etcd/etcdserver.TestSnapshot()
      /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server_test.go:872 +0x857
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:610 +0xc9
Goroutine 81 (finished) created at:
  github.com/coreos/etcd/etcdserver.TestSnapshot()
      /home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server_test.go:886 +0x893
  testing.tRunner()
      /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/testing/testing.go:610 +0xc9
```

**Comment by heyitsanthony** [comment]
This is a data race from concurrent calls to `Fatalf`, not an actual race in the etcd code. What was the `Fatal` logging output?

**Comment by gyuho** [comment]
@heyitsanthony  https://travis-ci.org/coreos/etcd/jobs/170575410#L4032

Think we have two goroutines `Fatal`ing https://github.com/coreos/etcd/blob/master/etcdserver/server_test.go#L877?

**Comment by heyitsanthony** [comment]
I suspect it's taking too long in `s.KV().Commit()` since the `Wait`s fail before `SaveNoCopy` runs causing recording the `SaveNoCopy` event to block forever:
```
goroutine 468 [chan send, 2 minutes]:
github.com/coreos/etcd/pkg/testutil.(*recorderStream).Record(0xc42012c4c8, 0xf810f2, 0xa, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/testutil/recorder.go:91 +0x8e
github.com/coreos/etcd/pkg/mock/mockstore.(*storeRecorder).SaveNoCopy(0xc42026dd80, 0x1, 0x3, 0xc42014be60, 0x1, 0x1)
	/home/travis/gopath/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/mock/mockstore/store_recorder.go:113 +0x83
github.com/coreos/etcd/etcdserver.(*EtcdServer).snapshot.func1()
	github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:1741 +0xdf
github.com/coreos/etcd/etcdserver.(*EtcdServer).goAttach.func1(0xc4203fa500, 0xc42038a090)
	github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:2037 +0x80
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).goAttach
	github.com/coreos/etcd/etcdserver/_test/_obj_test/server.go:2038 +0x271
```

**Comment by xiang90** [comment]
@heyitsanthony 

If that is the case, the waiter should timeout and print out the logging? (I am convinced commit takes longer than 5 seconds, just do not know why it does not fail fast)

**Comment by xiang90** [comment]
Oh... I see why... since both of the fatals are in go routines. It makes sense now. I guess we should just close this one... CI was too slow.

**Comment by heyitsanthony** [comment]
@xiang90 it can be made to fail fast by deferring the `ch <- struct{}{}`'s so it'll close even on fatal. Worth fixing?

**Comment by xiang90** [comment]
@heyitsanthony 

Ha. Yes. See #6801
