### ISSUE TITLE
raft: panic term should not be set when sending MsgReadIndex

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#6744]
- Found in our functional-tester cluster
    - All logs and data can be found at https://console.cloud.google.com/storage/browser/etcd-functional-tester/prevote-term-panic-20161027
- Related to recent PreVote change in raft https://github.com/coreos/etcd/pull/6624

```
2016-10-27 06:42:15.180509 I | etcdmain: etcd Version: 3.1.0-rc.0+git
2016-10-27 06:42:15.180550 I | etcdmain: Git SHA: d7c21e6
2016-10-27 06:42:15.180554 I | etcdmain: Go Version: go1.7.1
2016-10-27 06:42:15.180558 I | etcdmain: Go OS/Arch: linux/amd64
2016-10-27 06:42:15.180562 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2016-10-27 06:42:15.180593 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-10-27 06:42:15.180600 I | etcdmain: advertising using detected default host "10.240.0.3"
2016-10-27 06:42:15.180631 I | embed: listening for peers on http://10.240.0.3:2380
2016-10-27 06:42:15.180652 I | embed: listening for client requests on 10.240.0.3:2379
2016-10-27 06:42:15.197845 W | snap: skipped unexpected non snapshot file 000000000354d96a.snap.db
2016-10-27 06:42:15.208967 I | etcdserver: recovered store from snapshot at index 129848120
2016-10-27 06:42:15.208999 I | etcdserver: name = etcd-1
2016-10-27 06:42:15.209004 I | etcdserver: data dir = agent.etcd
2016-10-27 06:42:15.209009 I | etcdserver: member dir = agent.etcd/member
2016-10-27 06:42:15.209013 I | etcdserver: heartbeat = 100ms
2016-10-27 06:42:15.209016 I | etcdserver: election = 1000ms
2016-10-27 06:42:15.209020 I | etcdserver: snapshot count = 10000
2016-10-27 06:42:15.209031 I | etcdserver: advertise client URLs = http://10.240.0.3:2379
2016-10-27 06:42:15.316363 I | etcdserver: restarting member 42411cb09b560f1f in cluster fdbf2ff13dcd2db8 at commit index 129856865
2016-10-27 06:42:15.316647 I | raft: 42411cb09b560f1f became follower at term 2420
2016-10-27 06:42:15.316663 I | raft: newRaft 42411cb09b560f1f [peers: [42411cb09b560f1f,4cfcd26ad3dae2b4,a44e36e45f9e8271], term: 2420, commit: 129856865, applied: 129848120, lastindex: 129856948, lastterm: 2420]
2016-10-27 06:42:15.316854 I | etcdserver/api: enabled capabilities for version 3.1
2016-10-27 06:42:15.316873 I | etcdserver/membership: added member 42411cb09b560f1f [http://10.240.0.3:2380] to cluster fdbf2ff13dcd2db8 from store
2016-10-27 06:42:15.316879 I | etcdserver/membership: added member 4cfcd26ad3dae2b4 [http://10.240.0.4:2380] to cluster fdbf2ff13dcd2db8 from store
2016-10-27 06:42:15.316884 I | etcdserver/membership: added member a44e36e45f9e8271 [http://10.240.0.2:2380] to cluster fdbf2ff13dcd2db8 from store
2016-10-27 06:42:15.316890 I | etcdserver/membership: set the cluster version to 3.1 from store
2016-10-27 06:42:15.331245 I | mvcc: restore compact to 118621511
2016-10-27 06:42:15.609089 I | rafthttp: starting peer 4cfcd26ad3dae2b4...
2016-10-27 06:42:15.609141 I | rafthttp: started HTTP pipelining with peer 4cfcd26ad3dae2b4
2016-10-27 06:42:15.609547 I | rafthttp: started streaming with peer 4cfcd26ad3dae2b4 (writer)
2016-10-27 06:42:15.609817 I | rafthttp: started streaming with peer 4cfcd26ad3dae2b4 (writer)
2016-10-27 06:42:15.610058 I | rafthttp: started peer 4cfcd26ad3dae2b4
2016-10-27 06:42:15.610077 I | rafthttp: added peer 4cfcd26ad3dae2b4
2016-10-27 06:42:15.610094 I | rafthttp: starting peer a44e36e45f9e8271...
2016-10-27 06:42:15.610115 I | rafthttp: started HTTP pipelining with peer a44e36e45f9e8271
2016-10-27 06:42:15.610141 I | rafthttp: started streaming with peer 4cfcd26ad3dae2b4 (stream MsgApp v2 reader)
2016-10-27 06:42:15.610158 I | rafthttp: started streaming with peer 4cfcd26ad3dae2b4 (stream Message reader)
2016-10-27 06:42:15.610394 I | rafthttp: started streaming with peer a44e36e45f9e8271 (writer)
2016-10-27 06:42:15.610487 I | rafthttp: started streaming with peer a44e36e45f9e8271 (writer)
2016-10-27 06:42:15.610689 I | rafthttp: started peer a44e36e45f9e8271
2016-10-27 06:42:15.610707 I | rafthttp: added peer a44e36e45f9e8271
2016-10-27 06:42:15.610711 I | rafthttp: started streaming with peer a44e36e45f9e8271 (stream MsgApp v2 reader)
2016-10-27 06:42:15.610726 I | etcdserver: starting server... [version: 3.1.0-rc.0+git, cluster version: 3.1]
2016-10-27 06:42:15.610779 I | rafthttp: started streaming with peer a44e36e45f9e8271 (stream Message reader)
2016-10-27 06:42:15.611206 I | rafthttp: peer 4cfcd26ad3dae2b4 became active
2016-10-27 06:42:15.611220 I | rafthttp: established a TCP streaming connection with peer 4cfcd26ad3dae2b4 (stream Message writer)
2016-10-27 06:42:15.611226 I | raft: raft.node: 42411cb09b560f1f elected leader a44e36e45f9e8271 at term 2420
2016-10-27 06:42:15.611250 I | rafthttp: established a TCP streaming connection with peer 4cfcd26ad3dae2b4 (stream Message reader)
2016-10-27 06:42:15.611312 I | rafthttp: established a TCP streaming connection with peer 4cfcd26ad3dae2b4 (stream MsgApp v2 reader)
2016-10-27 06:42:15.611486 I | rafthttp: peer a44e36e45f9e8271 became active
2016-10-27 06:42:15.611499 I | rafthttp: established a TCP streaming connection with peer a44e36e45f9e8271 (stream Message writer)
2016-10-27 06:42:15.611722 I | rafthttp: established a TCP streaming connection with peer 4cfcd26ad3dae2b4 (stream MsgApp v2 writer)
2016-10-27 06:42:15.611749 I | rafthttp: established a TCP streaming connection with peer a44e36e45f9e8271 (stream MsgApp v2 writer)
2016-10-27 06:42:15.612632 I | rafthttp: established a TCP streaming connection with peer a44e36e45f9e8271 (stream Message reader)
2016-10-27 06:42:15.612855 I | rafthttp: established a TCP streaming connection with peer a44e36e45f9e8271 (stream MsgApp v2 reader)
2016-10-27 06:42:15.761640 I | etcdserver: start to snapshot (applied: 129862044, lastsnap: 129848120)
2016-10-27 06:42:15.769047 I | etcdserver: published {Name:etcd-1 ClientURLs:[http://10.240.0.3:2379]} to cluster fdbf2ff13dcd2db8
2016-10-27 06:42:15.769118 E | etcdmain: forgot to set Type=notify in systemd service file?
2016-10-27 06:42:15.769128 I | embed: ready to serve client requests
2016-10-27 06:42:15.769419 N | embed: serving insecure client requests on 10.240.0.3:2379, this is strongly discouraged!
2016-10-27 06:42:15.777887 I | etcdserver: saved snapshot at index 129862044
2016-10-27 06:42:15.778115 I | etcdserver: compacted raft log at 129857044
2016-10-27 06:42:22.774518 I | raft: 42411cb09b560f1f [term: 2420] received a MsgVote message with higher term from 4cfcd26ad3dae2b4 [term: 2421]
2016-10-27 06:42:22.774555 I | raft: 42411cb09b560f1f became follower at term 2421
2016-10-27 06:42:22.774566 I | raft: 42411cb09b560f1f [logterm: 2420, index: 129869965, vote: 0] cast MsgVote for 4cfcd26ad3dae2b4 [logterm: 2420, index: 129869965] at term 2421
2016-10-27 06:42:22.774572 I | raft: raft.node: 42411cb09b560f1f lost leader a44e36e45f9e8271 at term 2421
2016-10-27 06:42:22.777152 I | raft: raft.node: 42411cb09b560f1f elected leader 4cfcd26ad3dae2b4 at term 2421
panic: term should not be set when sending MsgReadIndex (was 2421)

goroutine 88 [running]:
panic(0xc8ba00, 0xc42201a320)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
etcd/raft.(*raft).send(0xc4201420f0, 0xf, 0x4cfcd26ad3dae2b4, 0x42411cb09b560f1f, 0x975, 0x0, 0x0, 0xc420722dc0, 0x1, 0x1, ...)
	etcd/raft/raft.go:354 +0x3cb
etcd/raft.stepFollower(0xc4201420f0, 0xf, 0x4cfcd26ad3dae2b4, 0xa44e36e45f9e8271, 0x975, 0x0, 0x0, 0xc420722dc0, 0x1, 0x1, ...)
	etcd/raft/raft.go:1063 +0x86e
etcd/raft.(*raft).Step(0xc4201420f0, 0xf, 0x42411cb09b560f1f, 0xa44e36e45f9e8271, 0x975, 0x0, 0x0, 0xc420722dc0, 0x1, 0x1, ...)
	etcd/raft/raft.go:778 +0x11ef
etcd/raft.(*node).run(0xc420591560, 0xc4201420f0)
	etcd/raft/node.go:319 +0x657
created by etcd/raft.RestartNode
	etcd/raft/node.go:219 +0x33c
```

**Comment by gyuho** [comment]
Here's what happened:

```
agent01 == a44e36e45f9e8271
agent02 == 42411cb09b560f1f
agent03 == 4cfcd26ad3dae2b4
```

```
[term 2419] 42411cb09b560f1f was leader
[term 2420] a44e36e45f9e8271 was leader
[term 2421] 4cfcd26ad3dae2b4 was leader
```

<br>
`2016-10-27` was the date in timestamps:

```
# tester
06:42:22.764434 I | etcd-tester: [round#349 case#3] injecting failure "kill leader member"
# kills agent1, which was leader right now

# agent01
06:42:22.774472 N | pkg/osutil: received terminated signal, shutting down...
06:42:22.774557 I | raft: a44e36e45f9e8271 [term 2420] starts to transfer leadership to 4cfcd26ad3dae2b4
06:42:22.874761 I | etcdserver: a44e36e45f9e8271 finished leadership transfer from a44e36e45f9e8271 to 4cfcd26ad3dae2b4 (took 100.23349ms)

# agent03
06:42:22.907463 I | raft: 4cfcd26ad3dae2b4 became leader at term 2421
06:42:22.907481 I | raft: raft.node: 4cfcd26ad3dae2b4 elected leader 4cfcd26ad3dae2b4 at term 2421
```

<br>
But at term 2421, agent02 panic:

```
# agent02
06:42:22.774518 I | raft: 42411cb09b560f1f [term: 2420] received a MsgVote message with higher term from 4cfcd26ad3dae2b4 [term: 2421]
06:42:22.774555 I | raft: 42411cb09b560f1f became follower at term 2421
06:42:22.774566 I | raft: 42411cb09b560f1f [logterm: 2420, index: 129869965, vote: 0] cast MsgVote for 4cfcd26ad3dae2b4 [logterm: 2420, index: 129869965] at term 2421
06:42:22.774572 I | raft: raft.node: 42411cb09b560f1f lost leader a44e36e45f9e8271 at term 2421
06:42:22.777152 I | raft: raft.node: 42411cb09b560f1f elected leader 4cfcd26ad3dae2b4 at term 2421

panic: term should not be set when sending MsgReadIndex (was 2421)
```


So `r.send(msg pb.MsgReadIndex)` was called with `msg.Term != 0`. I am trying to find out how this happened when we only send `MsgReadIndex` through `(n *node) ReadIndex`, and agent02 was not even the old leader at term 2421.
