### ISSUE TITLE
Abnormal exit

### ISSUE THREAD

**Issue by quan2005** [coreos/etcd#6775]
# Bug reporting

2016-11-01 15:10:47.115699 I | etcdmain: etcd Version: 3.0.6
2016-11-01 15:10:47.115709 I | etcdmain: Git SHA: 9efa00d
2016-11-01 15:10:47.115716 I | etcdmain: Go Version: go1.6.3
2016-11-01 15:10:47.115725 I | etcdmain: Go OS/Arch: linux/amd64
2016-11-01 15:10:47.115735 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2016-11-01 15:10:47.115745 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2016-11-01 15:10:47.115814 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2016-11-01 15:10:47.116441 I | etcdmain: listening for peers on http://localhost:2380
2016-11-01 15:10:47.116514 I | etcdmain: listening for client requests on 0.0.0.0:2379
2016-11-01 15:10:47.122025 I | etcdserver: recovered store from snapshot at index 19401949
2016-11-01 15:10:47.122048 I | etcdserver: name = default
2016-11-01 15:10:47.122056 I | etcdserver: data dir = default.etcd
2016-11-01 15:10:47.122064 I | etcdserver: member dir = default.etcd/member
2016-11-01 15:10:47.122071 I | etcdserver: heartbeat = 100ms
2016-11-01 15:10:47.122077 I | etcdserver: election = 1000ms
2016-11-01 15:10:47.122084 I | etcdserver: snapshot count = 10000
2016-11-01 15:10:47.122100 I | etcdserver: advertise client URLs = http://0.0.0.0:2380
2016-11-01 15:10:48.714138 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 19403895
2016-11-01 15:10:48.715256 I | raft: 8e9e05c52164694d became follower at term 23
2016-11-01 15:10:48.717741 I | raft: newRaft 8e9e05c52164694d [peers: [8e9e05c52164694d], term: 23, commit: 19403895, applied: 19401949, lastindex: 19403895, lastterm: 23]
2016-11-01 15:10:48.718039 I | api: enabled capabilities for version 3.0
2016-11-01 15:10:48.718071 I | membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32 from store
2016-11-01 15:10:48.718085 I | membership: set the cluster version to 3.0 from store
2016-11-01 15:10:48.767840 I | etcdserver: starting server... [version: 3.0.6, cluster version: 3.0]
2016-11-01 15:10:49.518996 I | raft: 8e9e05c52164694d is starting a new election at term 23
2016-11-01 15:10:49.519058 I | raft: 8e9e05c52164694d became candidate at term 24
2016-11-01 15:10:49.519073 I | raft: 8e9e05c52164694d received vote from 8e9e05c52164694d at term 24
2016-11-01 15:10:49.519099 I | raft: 8e9e05c52164694d became leader at term 24
2016-11-01 15:10:49.519115 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 24
2016-11-01 15:10:49.519772 I | etcdserver: published {Name:default ClientURLs:[http://0.0.0.0:2380]} to cluster cdf818194e3a8c32
2016-11-01 15:10:49.519797 I | etcdmain: ready to serve client requests
2016-11-01 15:10:49.520386 N | etcdmain: serving insecure client requests on 0.0.0.0:2379, this is strongly discouraged!
2016-11-01 15:11:17.734047 I | v3rpc/grpc: transport: http2Server.HandleStreams failed to read frame: read tcp 192.168.23.133:2379->192.168.100.88:6089: read: connection reset by peer
panic: watcher not victim but not in watch groups

goroutine 880 [running]:
panic(0xd420a0, 0xc820340350)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*watchableStore).cancelWatcher(0xc820213290, 0xc82036e5a0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:235 +0x174
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*watchableStore).watch.func1()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:217 +0x29
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*watchStream).Close(0xc8204ec5c0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watcher.go:140 +0xd8
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*serverWatchStream).close(0xc821389030)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:319 +0x3a
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch(0xc82031ed50, 0x7fee3000f4f0, 0xc820346a20, 0x7fee2ffc9ac0, 0xc820241fc0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:137 +0x348
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb._Watch_Watch_Handler(0xee1140, 0xc82031ed50, 0x7fee3000f4a8, 0xc8213a6b40, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2348 +0xd8
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.metricsStreamInterceptor(0xee1140, 0xc82031ed50, 0x7fee3000f4a8, 0xc8213a6b40, 0xc82145e620, 0x1325940, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:113 +0x196
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.newStreamInterceptor.func1(0xee1140, 0xc82031ed50, 0x7fee3000f4a8, 0xc8213a6b40, 0xc82145e620, 0x1325940, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:91 +0x471
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc8201fa000, 0x7fee301f10d8, 0xc8206eb560, 0xc821384690, 0xc82031ee10, 0x172f460, 0xc821425f50, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:693 +0xa97
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc8201fa000, 0x7fee301f10d8, 0xc8206eb560, 0xc821384690, 0xc821425f50)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:770 +0x1151
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc82145a360, 0xc8201fa000, 0x7fee301f10d8, 0xc8206eb560, 0xc821384690)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:419 +0xa0
created by github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:420 +0x9a

**Comment by quan2005** [comment]
WatchCreateRequest request = WatchCreateRequest
                .newBuilder()
                .setKey(“aaa”)
                .setRangeEnd("bbb/ccc/2/z")
                .build();

**Comment by xiang90** [comment]
Can you try with etcd 3.0.13? I think this bug is already fixed.

**Comment by xiang90** [comment]
this pr(https://github.com/coreos/etcd/pull/5557) fixed this issue.
