### ISSUE TITLE
panic: watcher not victim but not in watch groups

### ISSUE THREAD

**Issue by vimalk78** [coreos/etcd#6819]
Steps to reproduce:

1. start a single node etcd
`vimal (master) bin $ ./etcd --debug=true`

2. start watch, and then press Ctrl-C
```
vimal (master) bin $ ./etcdctl watch key key --rev=1  -w=simple
^C
vimal (master) bin $ 
```

results in below panic :

```
panic: watcher not victim but not in watch groups

goroutine 172 [running]:
panic(0xc8b540, 0xc42000fac0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*watchableStore).cancelWatcher(0xc4201f83f0, 0xc4201dc620)
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:236 +0x231
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*watchableStore).watch.func1()
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:218 +0x33
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*watchStream).Close(0xc4203af1c0)
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watcher.go:143 +0xd6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*serverWatchStream).close(0xc420088240)
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:346 +0x34
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch(0xc4203ee240, 0x128c000, 0xc42000f5b0, 0xc420571b28, 0xc420571b38)
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:145 +0x3a2
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb._Watch_Watch_Handler(0xcc8bc0, 0xc4203ee240, 0x128a380, 0xc4200881b0, 0x128c0c0, 0xc4203af180)
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2455 +0xbb
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.metricsStreamInterceptor(0xcc8bc0, 0xc4203ee240, 0x128a380, 0xc4200881b0, 0xc420122600, 0xe830d0, 0xc42002f800, 0x0)
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:113 +0x12c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.newStreamInterceptor.func1(0xcc8bc0, 0xc4203ee240, 0x128a380, 0xc4200881b0, 0xc420122600, 0xe830d0, 0x0, 0x0)
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:91 +0x115
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc420460000, 0x128c240, 0xc420088120, 0xc4203c43c0, 0xc4203ee2d0, 0x12a5420, 0x0, 0x0, 0x0)
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:693 +0x2b6
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420460000, 0x128c240, 0xc420088120, 0xc4203c43c0, 0x0)
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:770 +0xc36
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42000f460, 0xc420460000, 0x128c240, 0xc420088120, 0xc4203c43c0)
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:419 +0xab
created by github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/vimal/gowork/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:420 +0xa3


```

Environment : 
Ubuntu 14.04 LTE, with HDD

**Comment by xiang90** [comment]
What is the version of etcd?

**Comment by gyuho** [comment]
@xiang90 @heyitsanthony I can reproduce with current master branch?

**Comment by xiang90** [comment]
@gyuho Can you try to fix this?

**Comment by gyuho** [comment]
Sure

**Comment by vimalk78** [comment]
​vimal (master) bin $ ./etcd --version
etcd Version: 3.1.0-alpha.1+git
Git SHA: 57e2b15
Go Version: go1.7
Go OS/Arch: linux/amd64

**Comment by gyuho** [comment]
@vimalk78 Pleas try with master branch. That watch request will be canceled right away; `key key` is wrong range since range end is not greater than range start.

Thanks for reporting!
