### ISSUE TITLE
TestV3MaintenanceHashInflight: unexpected fault address

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6989]
via https://jenkins-etcd.prod.coreos.systems/job/etcd-proxy/274/console

```
=== RUN   TestV3MaintenanceHashInflight
unexpected fault address 0x7f24d796014f
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f24d796014f pc=0xf03373]

goroutine 98024 [running]:
runtime.throw(0x11d3dd1, 0x5)
	/usr/lib/go-1.7/src/runtime/panic.go:566 +0x95 fp=0xc434f971e0 sp=0xc434f971c0
runtime.sigpanic()
	/usr/lib/go-1.7/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc434f97238 sp=0xc434f971e0
github.com/boltdb/bolt.(*Bucket).openBucket(0xc420354c58, 0x7f24d796014f, 0x20, 0x20, 0x9)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/boltdb/bolt/bucket.go:143 +0x303 fp=0xc434f97340 sp=0xc434f97238
github.com/boltdb/bolt.(*Bucket).Bucket(0xc420354c58, 0x7f24d7960146, 0x9, 0x9, 0x7f24d796014f)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/boltdb/bolt/bucket.go:120 +0x2c7 fp=0xc434f97450 sp=0xc434f97340
github.com/boltdb/bolt.(*Tx).Bucket(0xc420354c40, 0x7f24d7960146, 0x9, 0x9, 0x0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/boltdb/bolt/tx.go:101 +0x5d fp=0xc434f97490 sp=0xc434f97450
github.com/coreos/etcd/mvcc/backend.(*backend).Hash.func1(0xc420354c40, 0x12ac848, 0xc420354c40)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/mvcc/backend/backend.go:160 +0x259 fp=0xc434f975b8 sp=0xc434f97490
github.com/boltdb/bolt.(*DB).View(0xc422372f00, 0xc434f97650, 0x0, 0x0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/boltdb/bolt/db.go:626 +0xe2 fp=0xc434f97610 sp=0xc434f975b8
github.com/coreos/etcd/mvcc/backend.(*backend).Hash(0xc42647fc80, 0xc42019f7d0, 0xc400000000, 0x0, 0x0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/mvcc/backend/backend.go:175 +0x1b5 fp=0xc434f97680 sp=0xc434f97610
github.com/coreos/etcd/mvcc.(*store).Hash(0xc421f8d930, 0xc400000000, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/mvcc/kvstore.go:341 +0xfe fp=0xc434f976d8 sp=0xc434f97680
github.com/coreos/etcd/mvcc.(*watchableStore).Hash(0xc426470480, 0x16dfee0, 0xc426470480, 0x1729888, 0x10e7860)
	<autogenerated>:67 +0x69 fp=0xc434f97730 sp=0xc434f976d8
github.com/coreos/etcd/etcdserver/api/v3rpc.(*maintenanceServer).Hash(0xc42623d340, 0x16da940, 0xc42d1d1dd0, 0x1729888, 0x3, 0x16dddc0, 0xc42a83b080)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/maintenance.go:117 +0x6c fp=0xc434f97798 sp=0xc434f97730
github.com/coreos/etcd/etcdserver/etcdserverpb._Maintenance_Hash_Handler.func1(0x16da940, 0xc42d1d1dd0, 0x1136fc0, 0x1729888, 0xc4205c71d0, 0x8, 0x10e88a0, 0x10e88a0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3061 +0xe9 fp=0xc434f97810 sp=0xc434f97798
github.com/grpc-ecosystem/go-grpc-prometheus.UnaryServerInterceptor(0x16da940, 0xc42d1d1dd0, 0x1136fc0, 0x1729888, 0xc422d12760, 0xc422d12820, 0xc420e90c00, 0x7f29f12ff000, 0x0, 0xc422d12740)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/grpc-ecosystem/go-grpc-prometheus/server.go:29 +0xd0 fp=0xc434f97898 sp=0xc434f97810
github.com/coreos/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1(0x16da940, 0xc42d1d1dd0, 0x1136fc0, 0x1729888, 0xc422d12760, 0xc422d12820, 0x7f29df7053b0, 0x0, 0xd14a3a, 0xc420e90c00)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:58 +0x106 fp=0xc434f97940 sp=0xc434f97898
github.com/coreos/etcd/etcdserver/etcdserverpb._Maintenance_Hash_Handler(0x10f90c0, 0xc42623d340, 0x16da940, 0xc42d1d1dd0, 0xc4205c7180, 0xc427983de0, 0x0, 0x0, 0xc42917dae8, 0x74dc41)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3063 +0x1db fp=0xc434f97a00 sp=0xc434f97940
google.golang.org/grpc.(*Server).processUnaryRPC(0xc42b0d63c0, 0x16ddf40, 0xc4204c9b00, 0xc42253a870, 0xc42586de00, 0x16fe2e8, 0xc42d1d1da0, 0x0, 0x0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/server.go:638 +0x10c8 fp=0xc434f97d18 sp=0xc434f97a00
google.golang.org/grpc.(*Server).handleStream(0xc42b0d63c0, 0x16ddf40, 0xc4204c9b00, 0xc42253a870, 0xc42d1d1da0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/server.go:796 +0xf9d fp=0xc434f97f40 sp=0xc434f97d18
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42cd1bf80, 0xc42b0d63c0, 0x16ddf40, 0xc4204c9b00, 0xc42253a870)
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/server.go:449 +0xb9 fp=0xc434f97f78 sp=0xc434f97f40
runtime.goexit()
	/usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc434f97f80 sp=0xc434f97f78
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/server.go:450 +0xbb
```

**Comment by gyuho** [comment]
Reported upstream https://github.com/boltdb/bolt/issues/644.

**Comment by gyuho** [comment]
Got again https://jenkins-etcd-public.prod.coreos.systems/job/etcd-proxy/785/console

**Comment by heyitsanthony** [comment]
@gyuho  #7743 / e771c6042bda7e026279032b1b03848c37da805f fixes this?

**Comment by gyuho** [comment]
@heyitsanthony Yes, closing.
