### ISSUE TITLE
etcd-runner: election causes panic

### ISSUE THREAD

**Issue by fanminshi** [coreos/etcd#7091]
Setup:
macOS 10.11.6
Go Version: go1.7.3
Go OS/Arch: darwin/amd64
etcd version: 24601ca24b46f5d700746c5902ee62aca6b1b805 from master

Reproduce:
```
# screen 1
fanmins-MacBook-Pro:etcd fanminshi$ ./bin/etcd
...
# screen 2
fanmins-MacBook-Pro: pwd <ETCDPATH>/tools/functional-tester/etcd-runner
fanmins-MacBook-Pro:etcd-runner fanminshi$ go build
fanmins-MacBook-Pro:etcd-runner fanminshi$ ./etcd-runner -mode election
panic: Unexpected error from context packet: context canceled

goroutine 246 [running]:
panic(0x46f480, 0xc420130b90)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
google.golang.org/grpc/transport.ContextErr(0x763e80, 0xc4200122b0, 0xc4200122b0, 0x1, 0x0)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/transport/transport.go:566 +0x213
google.golang.org/grpc/transport.wait(0x76c800, 0xc420286570, 0x0, 0x0, 0xc42037d4a0, 0xc4201cd180, 0x0, 0x0, 0x0)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/transport/transport.go:579 +0xf4
google.golang.org/grpc/transport.(*http2Client).NewStream(0xc4201eafc0, 0xc94028, 0xc42028b0c0, 0xc42054d360, 0x0, 0xc420347430, 0xaeaca)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/transport/http2_client.go:328 +0x758
google.golang.org/grpc.sendRequest(0xc94028, 0xc42028b0c0, 0x76bd40, 0x7ae408, 0x0, 0x0, 0xc42054d360, 0x76ece0, 0xc4201eafc0, 0x4e53e0, ...)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/call.go:80 +0x95
google.golang.org/grpc.invoke(0xc94028, 0xc42028b0c0, 0x532234, 0x16, 0x4e53e0, 0xc42024c620, 0x4f0f80, 0xc420286540, 0xc420302900, 0xc420130b70, ...)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/call.go:191 +0x622
github.com/grpc-ecosystem/go-grpc-prometheus.UnaryClientInterceptor(0xc94028, 0xc42028b0c0, 0x532234, 0x16, 0x4e53e0, 0xc42024c620, 0x4f0f80, 0xc420286540, 0xc420302900, 0x56dfd8, ...)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/grpc-ecosystem/go-grpc-prometheus/client.go:20 +0x11d
google.golang.org/grpc.Invoke(0xc94028, 0xc42028b0c0, 0x532234, 0x16, 0x4e53e0, 0xc42024c620, 0x4f0f80, 0xc420286540, 0xc420302900, 0xc420130b70, ...)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/call.go:116 +0xdd
github.com/coreos/etcd/etcdserver/etcdserverpb.(*kVClient).Range(0xc420132240, 0xc94028, 0xc42028b0c0, 0xc42024c620, 0xc420130b70, 0x1, 0x1, 0x474320, 0x4b3f01, 0xc420130b70)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2203 +0xd2
github.com/coreos/etcd/clientv3.(*retryKVClient).Range(0xc420137740, 0xc94028, 0xc42028b0c0, 0xc42024c620, 0xc420130b70, 0x1, 0x1, 0x1, 0xc420130b20, 0x0)
	<autogenerated>:174 +0x92
github.com/coreos/etcd/clientv3.(*kv).do(0xc420131be0, 0xc94028, 0xc42028b0c0, 0x1, 0xc420130ae0, 0x9, 0x10, 0xc420130b10, 0x9, 0x9, ...)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/kv.go:145 +0x4ee
github.com/coreos/etcd/clientv3.(*kv).Do(0xc420131be0, 0xc94028, 0xc42028b0c0, 0x1, 0xc420130ae0, 0x9, 0x10, 0xc420130b10, 0x9, 0x9, ...)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/kv.go:124 +0x7d
github.com/coreos/etcd/clientv3.(*kv).Get(0xc420131be0, 0xc94028, 0xc42028b0c0, 0xc420131cd0, 0x9, 0xc4201e0fc0, 0x3, 0x3, 0xc42042fa40, 0x0, ...)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/kv.go:98 +0xe2
github.com/coreos/etcd/clientv3/concurrency.(*Election).observe(0xc420398640, 0xc94028, 0xc42028b0c0, 0xc42042e6c0)
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/concurrency/election.go:146 +0x107
created by github.com/coreos/etcd/clientv3/concurrency.(*Election).Observe
	/Users/fanminshi/work/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/concurrency/election.go:137 +0x7f
```

**Comment by heyitsanthony** [comment]
Fixed by 85e14a841a3f8472940867a9792594ff62556774. (Cf.  #7604)
