### ISSUE TITLE
pkg/report: panic when a lot of error happens

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#7178]
When a bunch of `zk: node already exists` error happens

```
2017-01-17 23:56:11.799714 I | control: sending message [index: 2 | operation: "Heartbeat" | database: "ZooKeeper" | endpoint: "10.240.0.28:3500"]
2017-01-17 23:56:11.802353 I | control: got response [index: 2 | endpoint: "10.240.0.28:3500" | response: success:true ]
fatal error: concurrent map read and map write

goroutine 1713 [running]:
runtime.throw(0xee0111, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc437066510 sp=0xc4370664f0
runtime.mapaccess1_faststr(0xd85d40, 0xc427d3a5a0, 0xed7177, 0x17, 0xc4331c4d00)
	/usr/local/go/src/runtime/hashmap_fast.go:201 +0x4f3 fp=0xc437066570 sp=0xc437066510
github.com/coreos/dbtester/vendor/github.com/coreos/etcd/pkg/report.(*report).processResult(0xc42014d000, 0xc437066640)
	/home/gyuho/go/src/github.com/coreos/dbtester/vendor/github.com/coreos/etcd/pkg/report/report.go:180 +0xa0 fp=0xc437066600 sp=0xc437066570
github.com/coreos/dbtester/vendor/github.com/coreos/etcd/pkg/report.(*report).processResults(0xc42014d000)
	/home/gyuho/go/src/github.com/coreos/dbtester/vendor/github.com/coreos/etcd/pkg/report/report.go:194 +0x118 fp=0xc4370666d0 sp=0xc437066600
github.com/coreos/dbtester/vendor/github.com/coreos/etcd/pkg/report.(*report).Stats.func1(0xc4331c6000, 0xc42014d000)
	/home/gyuho/go/src/github.com/coreos/dbtester/vendor/github.com/coreos/etcd/pkg/report/report.go:114 +0x6d fp=0xc4370667b0 sp=0xc4370666d0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4370667b8 sp=0xc4370667b0
created by github.com/coreos/dbtester/vendor/github.com/coreos/etcd/pkg/report.(*report).Stats
	/home/gyuho/go/src/github.com/coreos/dbtester/vendor/github.com/coreos/etcd/pkg/report/report.go:127 +0x67

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc420250814)
```

Might be Go bug...

**Comment by heyitsanthony** [comment]
I think the bug is from here: https://github.com/coreos/dbtester/blob/e438ad3cc2964fce640ba0deab54c505ecd5a49a/control/step2_stress_database.go#L403

`b.report` is being reused and `Stats` is getting called repeatedly without collecting the result; it's launching multiple goroutines concurrently on the same data from `report`. Might want to run the race detector on it.

**Comment by gyuho** [comment]
Yeah think this is on my side, since it changes the client number 100, 200, 300, and collect all the data at the end... Close for now. Will investigate more. Thanks.
