### ISSUE TITLE
Restore issue with Kubernetes-1.5.1

### ISSUE THREAD

**Issue by r007m4n** [coreos/etcd#7192]
I'm running Kubernetes-1.5.1 and Etcd-3.0.15.
I took a snapshot on a Etcd server and tried to restore using the snapshot.db file. 
However, I encountered following error that said "panic: no lessor to attach lease"
I tested restore command using etcd-3.0.15, etcd-3.0.16 and 3.0.1 and got same errors. 

```
-bash-4.2$ ETCDCTL_API=3 etcdctl snapshot restore snapshot.db --name m1 --initial-cluster m1=http://localhost:2380 --initial-advertise-peer-urls http://localhost:2380

2017-01-19 22:59:32.671013 I | mvcc: restore compact to 3616080
**panic: no lessor to attach lease**

goroutine 1 [running]:
panic(0xc60aa0, 0xc820223fa0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*store).restore(0xc82025c000, 0x0, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:420 +0x1335
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.NewStore(0x7f70f9e49100, 0xc82025a6c0, 0x0, 0x0, 0x7f70f9e49158, 0xc820223048, 0x20)
        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:120 +0x39e
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.makeDB(0xc820234280, 0x18, 0x7ffe20e9570f, 0x1b, 0x1)
        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/snapshot_command.go:374 +0xaef
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.snapshotRestoreCommandFunc(0xc820229e00, 0xc820222fa0, 0x1, 0x1)
        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/snapshot_command.go:194 +0x66a
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).execute(0xc820229e00, 0xc820222f60, 0x1, 0x1, 0x0, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:572 +0x85a
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1592160, 0xc820229e00, 0x0, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:662 +0x53f
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).Execute(0x1592160, 0x0, 0x0)
        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:618 +0x2d
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3.Start()
        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/ctl.go:96 +0x8f
main.main()
        /home/gyuho/go/src/github.com/coreos/etcd/cmd/etcdctl/main.go:40 +0x111
```

**Comment by xiang90** [comment]
@r007m4n I can confirm this is a bug. We are going to fix it soonish.

**Comment by xiang90** [comment]
@r007m4n Already fixed. We are doing a release today to include this fix. Sorry for the inconvenience.

**Comment by r007m4n** [comment]
@xiang90 Thanks you very much for your quick response and fixes. 
I will test new release once it comes
