### ISSUE TITLE
TestLaunchDuplicateMemberShouldFail: raft log corruption?

### ISSUE THREAD

**Issue by mitake** [coreos/etcd#7239]
From https://github.com/coreos/etcd/pull/7234

```
=== RUN   TestLaunchDuplicateMemberShouldFail
2017-01-26 03:41:04.797180 C | raft: tocommit(8) is out of range [lastIndex(3)]. Was the raft log corrupted, truncated, or lost?
panic: tocommit(8) is out of range [lastIndex(3)]. Was the raft log corrupted, truncated, or lost?

goroutine 17008 [running]:
panic(0x1077e80, 0xc42adec340)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1ae
github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc4201a57a0, 0x122a732, 0x5d, 0xc42e94f2e0, 0x2, 0x2)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x1ae
github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc424482af0, 0x8)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/raft/log.go:191 +0x208
github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc4200c6ff0, 0x8, 0xe52a448599cfeaf4, 0x2672a310b242e497, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/raft/raft.go:1095 +0x7a
github.com/coreos/etcd/raft.stepCandidate(0xc4200c6ff0, 0x8, 0xe52a448599cfeaf4, 0x2672a310b242e497, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/raft/raft.go:1002 +0xd4e
github.com/coreos/etcd/raft.(*raft).Step(0xc4200c6ff0, 0x8, 0xe52a448599cfeaf4, 0x2672a310b242e497, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/raft/raft.go:778 +0x1187
github.com/coreos/etcd/raft.(*node).run(0xc42c04a4e0, 0xc4200c6ff0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/raft/node.go:319 +0x61d
created by github.com/coreos/etcd/raft.StartNode
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/raft/node.go:206 +0x800
exit status 2
FAIL	github.com/coreos/etcd/integration	73.372s
Build step 'Execute shell' marked build as failure
Setting status of fa1cbd5890659e361c71b5979f4ed6a4408f82c9 to FAILURE with url https://jenkins-etcd-public.prod.coreos.systems/job/etcd-proxy/566 and message: 'Build finished. '
Using context: jenkins-proxy-ci
Finished: FAILURE
```

The detailed log can be found here: https://jenkins-etcd-public.prod.coreos.systems/job/etcd-proxy/566/console

**Comment by xiang90** [comment]
@gyuho can you take a look at this one?

**Comment by gyuho** [comment]
Yeah let me try to reproduce this.

**Comment by mitake** [comment]
It happened in the CI of my recent PR: https://github.com/coreos/etcd/pull/7260

https://jenkins-etcd-public.prod.coreos.systems/job/etcd-proxy/641/console

It seems that the failures are identical, though.

**Comment by gyuho** [comment]
Haven't seen it for 6 months. Will revisit if it happens again.
