### ISSUE TITLE
TestKVGetResetLoneEndpoint: endless election cycle

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#7283]
via https://jenkins-etcd-public.prod.coreos.systems/job/etcd-proxy/646/console

Appears to be hanging/deadlocking on `simpleBalancer.Close`:
```
goroutine 70428 [semacquire, 10 minutes]:
sync.runtime_Semacquire(0xc4214f7940)
	/usr/lib/go-1.7/src/runtime/sema.go:47 +0x30
sync.(*RWMutex).RLock(0xc4214f7934)
	/usr/lib/go-1.7/src/sync/rwmutex.go:43 +0x95
github.com/coreos/etcd/clientv3.(*simpleBalancer).Get(0xc4214f7900, 0x7fc8fffb82e0, 0xc4220d1f80, 0x1, 0x7, 0x2, 0x0, 0x43e257, 0x0, 0x0, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/balancer.go:190 +0x6f
google.golang.org/grpc.(*ClientConn).getTransport(0xc42215c360, 0x7fc8fffb82e0, 0xc4220d1f80, 0xc4210e2601, 0x6715354, 0x161fc60, 0x129fea181, 0x0, 0x0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/clientconn.go:536 +0xd9
google.golang.org/grpc.invoke(0x7fc8fffb82e0, 0xc4220d1f80, 0x113adda, 0x16, 0x1090880, 0xc4223f2460, 0x10a14c0, 0xc420945110, 0xc42215c360, 0xc422074810, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/call.go:173 +0x409
google.golang.org/grpc.Invoke(0x7fc8fffb82e0, 0xc4220d1f80, 0x113adda, 0x16, 0x1090880, 0xc4223f2460, 0x10a14c0, 0xc420945110, 0xc42215c360, 0xc422074810, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/call.go:118 +0x217
github.com/coreos/etcd/etcdserver/etcdserverpb.(*kVClient).Range(0xc420c723c0, 0x7fc8fffb82e0, 0xc4220d1f80, 0xc4223f2460, 0xc422074810, 0x1, 0x1, 0x0, 0x0, 0x3)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2209 +0x107
github.com/coreos/etcd/clientv3.(*retryWriteKVClient).Range(0xc421f8bd60, 0x7fc8fffb82e0, 0xc4220d1f80, 0xc4223f2460, 0xc422074810, 0x1, 0x1, 0x40, 0x109fc60, 0x0)
	<autogenerated>:174 +0xb7
github.com/coreos/etcd/clientv3.(*retryKVClient).Range.func1(0x7fc8fffb82e0, 0xc4220d1f80, 0x4122b8, 0xc42018b000)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/retry.go:92 +0x115
github.com/coreos/etcd/clientv3.(*Client).newAuthRetryWrapper.func1(0x7fc8fffb82e0, 0xc4220d1f80, 0xc422058fc0, 0xc42018b000, 0x7fc9000c3960)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/retry.go:61 +0x5f
github.com/coreos/etcd/clientv3.(*retryKVClient).Range(0xc420c723e0, 0x7fc8fffb82e0, 0xc4220d1f80, 0xc4223f2460, 0xc422074810, 0x1, 0x1, 0x0, 0x0, 0x1)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/retry.go:94 +0x25f
github.com/coreos/etcd/clientv3.(*kv).do(0xc421e05770, 0x7fc8fffb82e0, 0xc4220d1f80, 0x1, 0xc4220747d8, 0x3, 0x8, 0x0, 0x0, 0x0, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/kv.go:145 +0x6d9
github.com/coreos/etcd/clientv3.(*kv).Do(0xc421e05770, 0x7fc8fffb82e0, 0xc4220d1f80, 0x1, 0xc4220747d8, 0x3, 0x8, 0x0, 0x0, 0x0, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/kv.go:124 +0x8e
github.com/coreos/etcd/clientv3.(*kv).Get(0xc421e05770, 0x7fc8fffb82e0, 0xc4220d1f80, 0x112931e, 0x3, 0xc425bac668, 0x1, 0x1, 0xc421fd7ac0, 0xc421fd7ac0, ...)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/kv.go:98 +0xf3
github.com/coreos/etcd/clientv3/integration.TestKVGetResetLoneEndpoint.func1(0xc420baedc0, 0xc420351080, 0xc4220d1ec0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/integration/kv_test.go:860 +0x19c
created by github.com/coreos/etcd/clientv3/integration.TestKVGetResetLoneEndpoint
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/integration/kv_test.go:865 +0x53c
```

```
goroutine 70203 [semacquire, 10 minutes]:
sync.runtime_Semacquire(0xc4214f7938)
	/usr/lib/go-1.7/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc4214f7934)
	/usr/lib/go-1.7/src/sync/mutex.go:85 +0xde
sync.(*RWMutex).Lock(0xc4214f7934)
	/usr/lib/go-1.7/src/sync/rwmutex.go:86 +0x49
github.com/coreos/etcd/clientv3.(*simpleBalancer).Close(0xc4214f7900, 0x0, 0x0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/balancer.go:216 +0x5a
google.golang.org/grpc.(*ClientConn).Close(0xc42215c360, 0x0, 0x0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/clientconn.go:577 +0x281
github.com/coreos/etcd/clientv3.(*Client).Close(0xc420baedc0, 0x0, 0x1dcd6500)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/client.go:86 +0xcb
runtime.Goexit()
	/usr/lib/go-1.7/src/runtime/panic.go:340 +0xfb
testing.(*common).FailNow(0xc420351080)
	/usr/lib/go-1.7/src/testing/testing.go:453 +0x59
testing.(*common).Fatalf(0xc420351080, 0x113de87, 0x19, 0x0, 0x0, 0x0)
	/usr/lib/go-1.7/src/testing/testing.go:496 +0x95
github.com/coreos/etcd/clientv3/integration.TestKVGetResetLoneEndpoint(0xc420351080)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/integration/kv_test.go:870 +0x6a2
testing.tRunner(0xc420351080, 0x11ebae0)
	/usr/lib/go-1.7/src/testing/testing.go:610 +0xca
created by testing.(*T).Run
	/usr/lib/go-1.7/src/testing/testing.go:646 +0x530
```

**Comment by fanminshi** [comment]
lbWatcher listens on `b.notifyCh` via `balancer.Notify()` and it is blocked on `tearDown()`.
```
sync.runtime_Semacquire(0xc4240b59c4)
	/usr/lib/go-1.7/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc4240b59c0)
	/usr/lib/go-1.7/src/sync/mutex.go:85 +0xde
google.golang.org/grpc.(*addrConn).tearDown(0xc4240b58c0, 0x15e6420, 0xc4200117e0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/clientconn.go:857 +0x91
google.golang.org/grpc.(*ClientConn).lbWatcher(0xc42215c360)
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/clientconn.go:420 +0x9dc
created by google.golang.org/grpc.DialContext
	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/clientconn.go:339 +0x778
```
  
`balancer.Up()` acquires lock and is blocked sending addrs to `b.notifyCh`.
```
  goroutine 70415 [chan send, 10 minutes]:
  github.com/coreos/etcd/clientv3.(*simpleBalancer).Up(0xc4214f7900, 0xc425197ef7, 0x1e, 0x0, 0x0, 0x0)
  	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/clientv3/balancer.go:153 +0x389
  google.golang.org/grpc.(*addrConn).resetTransport(0xc4240b58c0, 0xc4220c0500, 0xc422ada2c0, 0xc4220e23f0)
  	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/clientconn.go:737 +0xe7b
  google.golang.org/grpc.(*ClientConn).resetAddrConn.func1(0xc4240b58c0)
  	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/clientconn.go:498 +0x42
  created by google.golang.org/grpc.(*ClientConn).resetAddrConn
  	/home/jenkins/workspace/etcd-proxy/gopath/src/google.golang.org/grpc/clientconn.go:507 +0x643
```
  
Since `balancer.Up()` hasn't released lock due to blocked by `tearDown()` from `lbWatcher()`, I suspect this causes `balancer.Close()` to hang.
