### ISSUE TITLE
functional-tester: concurrent map iteration and map write

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#7448]
Was deployed with master branch (right after https://github.com/coreos/etcd/commit/fb81fb44fa86af51e0d65f30bd9be9f51d4b6d64)

etcd-tester

```
2017-03-07 23:37:42.787234 I | etcd-tester: [round#744 case#25] injected failure
2017-03-07 23:37:42.787293 I | etcd-tester: [round#744 case#25] recovering failure "failpoint github.com/coreos/etcd/etcdserver/raftBeforeFollowerSend panic majority"
2017-03-07 23:37:42.809425 I | etcd-tester: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.240.0.14:2379: getsockopt: connection refused"; Reconnecting to {10.240.0.14:2379 <nil>}
2017-03-07 23:37:42.880225 I | etcd-tester: [round#744 case#25] recovered failure
2017-03-07 23:37:42.880270 I | etcd-tester: [round#744 case#25] canceling the stressers...
2017-03-07 23:37:42.896610 I | etcd-tester: lease stresser "10.240.0.15:2379" is canceled
2017-03-07 23:37:42.899873 I | etcd-tester: grpc: addrConn.transportMonitor exits due to: context canceled
2017-03-07 23:37:42.900145 I | etcd-tester: lease stresser "10.240.0.16:2379" is canceled
2017-03-07 23:37:42.902808 I | etcd-tester: keyStresser "10.240.0.14:2379" is canceled
2017-03-07 23:37:42.902844 I | etcd-tester: keyStresser "10.240.0.15:2379" is canceled
2017-03-07 23:37:42.902874 I | etcd-tester: keyStresser "10.240.0.16:2379" is canceled
2017-03-07 23:37:42.902901 I | etcd-tester: grpc: addrConn.transportMonitor exits due to: context canceled
2017-03-07 23:37:42.902941 I | etcd-tester: lease stresser "10.240.0.14:2379" is canceled
2017-03-07 23:37:42.902981 I | etcd-tester: lease stresser "10.240.0.13:2379" is canceled
2017-03-07 23:37:42.902994 I | etcd-tester: grpc: addrConn.transportMonitor exits due to: context canceled
2017-03-07 23:37:42.903003 I | etcd-tester: grpc: addrConn.transportMonitor exits due to: context canceled
2017-03-07 23:37:42.903016 I | etcd-tester: grpc: addrConn.transportMonitor exits due to: context canceled
2017-03-07 23:37:42.903036 I | etcd-tester: lease stresser "10.240.0.11:2379" is canceled
2017-03-07 23:37:42.903593 I | etcd-tester: keyStresser "10.240.0.11:2379" is canceled
2017-03-07 23:37:42.903730 I | etcd-tester: keyStresser "10.240.0.13:2379" is canceled
2017-03-07 23:37:42.903744 I | etcd-tester: [round#744 case#25] canceled stressers
2017-03-07 23:37:42.903752 I | etcd-tester: [round#744 case#25] wait until cluster is healthy
2017-03-07 23:37:44.608382 I | etcd-tester: [round#744 case#25] cluster is healthy
2017-03-07 23:37:44.608427 I | etcd-tester: [round#744 case#25] checking consistency and invariant of cluster
2017-03-07 23:37:47.900540 I | etcd-tester: transport: http2Client.notifyError got notified that the client transport was broken read tcp 10.240.0.17:57590->10.240.0.15:2379: read: connection reset by peer.
```

server side panic

```
2017-03-07 23:37:44.553853 I | rafthttp: established a TCP streaming connection with peer 7f98004f25324e68 (stream MsgApp v2 reader)
2017-03-07 23:37:44.554004 I | rafthttp: established a TCP streaming connection with peer 7f98004f25324e68 (stream Message reader)
2017-03-07 23:37:46.839670 W | etcdserver: timed out waiting for read index response
fatal error: concurrent map iteration and map write

goroutine 1492 [running]:
runtime.throw(0xecb57d, 0x26)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4242146a8 sp=0xc424214688
runtime.mapiternext(0xc4242147c0)
	/usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc424214758 sp=0xc4242146a8
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease.(*Lease).Keys(0xc420d09e00, 0xc4223cf600, 0xc420d09e00, 0xc4241817c0)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:548 +0x143 fp=0xc424214830 sp=0xc424214758
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).LeaseTimeToLive(0xc420197080, 0x7f9d63efdbe0, 0xc424b2fd70, 0xc424b52f50, 0x0, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/v3_server.go:343 +0x214 fp=0xc424214938 sp=0xc424214830
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*LeaseServer).LeaseTimeToLive(0xc427153540, 0x7f9d63efdbe0, 0xc424b2fd70, 0xc424b52f50, 0xc4241817c0, 0xc4242149e8, 0x3)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/lease.go:55 +0x56 fp=0xc424214998 sp=0xc424214938
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*quotaLeaseServer).LeaseTimeToLive(0xc427153580, 0x7f9d63efdbe0, 0xc424b2fd70, 0xc424b52f50, 0xc427153580, 0xec8c4d, 0xf)
	<autogenerated>:32 +0x6b fp=0xc4242149e0 sp=0xc424214998
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb._Lease_LeaseTimeToLive_Handler.func1(0x7f9d63efdbe0, 0xc424b2fd70, 0xdfbe20, 0xc424b52f50, 0xc4254500a0, 0xc424214a90, 0x956c9d, 0xc424b2fd70)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2683 +0x86 fp=0xc424214a28 sp=0xc4242149e0
github.com/coreos/etcd/cmd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.UnaryServerInterceptor(0x7f9d63efdbe0, 0xc424b2fd70, 0xdfbe20, 0xc424b52f50, 0xc4223cf580, 0xc4223cf5c0, 0x40fef8, 0x20, 0xda0980, 0x1)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go:29 +0xa4 fp=0xc424214aa0 sp=0xc424214a28
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1(0x7f9d63efdbe0, 0xc424b2fd70, 0xdfbe20, 0xc424b52f50, 0xc4223cf580, 0xc4223cf5c0, 0x0, 0xc424214b70, 0x40fef8, 0x50)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:57 +0xc3 fp=0xc424214b08 sp=0xc424214aa0
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb._Lease_LeaseTimeToLive_Handler(0xda5b00, 0xc427153580, 0x7f9d63efdbe0, 0xc424b2fd70, 0xc425450050, 0xc42671e360, 0x0, 0x0, 0x91425aab22976ad4, 0xc422258940)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2685 +0x177 fp=0xc424214b80 sp=0xc424214b08
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc428517bc0, 0x13740a0, 0xc427b2db00, 0xc4244704b0, 0xc426a82ed0, 0x13a19f0, 0x0, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:638 +0xb5c fp=0xc424214dd8 sp=0xc424214b80
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc428517bc0, 0x13740a0, 0xc427b2db00, 0xc4244704b0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:796 +0x1261 fp=0xc424214f80 sp=0xc424214dd8
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4275aff80, 0xc428517bc0, 0x13740a0, 0xc427b2db00, 0xc4244704b0)
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:449 +0xa9 fp=0xc424214fb8 sp=0xc424214f80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc424214fc0 sp=0xc424214fb8
created by github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:450 +0xa1

goroutine 1 [select]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:175 +0xc3b
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:36 +0x61
main.main()
	/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x20

goroutine 6 [IO wait]:
net.runtime_pollWait(0x7f9fe3f9eeb0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420044998, 0x72, 0x0, 0xc42010a020)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420044998, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc420044930, 0x0, 0x1365ae0, 0xc42010a020)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42000c0d0, 0xc420104240, 0xd54740, 0x139abb0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000c0d0, 0xc420104210, 0xd54740, 0x139abb0, 0xdf0720)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
net/http.(*Server).Serve(0xc420166000, 0x136eda0, 0xc42000c0d0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x228
net/http.Serve(0x136eda0, 0xc42000c0d0, 0x1364de0, 0x13ce108, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2307 +0x78
created by github.com/coreos/gofail/runtime.serve
	/home/gyuho/go/src/github.com/coreos/gofail/runtime/http.go:32 +0xd7

```

**Comment by gyuho** [comment]
@heyitsanthony

The problem is that all methods to `lease.Lessor` is guarded by the mutex inside `lease.lease` (https://github.com/coreos/etcd/blob/master/lease/lessor.go#L116-L117), but the invidual `lease.Lease` items are not. So the racey `lease.Lease.Keys()` calls could trigger such panic (this is the new panic introduced in Go 1.8).

To reproduce in `lease`

```go
func TestLessorGrantConcurrentKeys(t *testing.T) {
	dir, be := NewTestBackend(t)
	defer os.RemoveAll(dir)
	defer be.Close()

	fd := &fakeDeleter{}

	le := newLessor(be, minLeaseTTL)
	le.SetRangeDeleter(fd)

	// grant a lease with long term (100 seconds) to
	// avoid early termination during the test.
	l, err := le.Grant(1, 100)
	if err != nil {
		t.Fatalf("could not grant lease for 100s ttl (%v)", err)
	}

	itemn := 10
	items := make([]LeaseItem, itemn)
	for i := 0; i < itemn; i++ {
		items[i] = LeaseItem{Key: fmt.Sprintf("foo%d", i)}
	}
	if err = le.Attach(l.ID, items); err != nil {
		t.Fatalf("failed to attach items to the lease: %v", err)
	}

	donec := make(chan struct{})
	go func() {
		le.Detach(l.ID, items)
		close(donec)
	}()

	var wg sync.WaitGroup
	wg.Add(itemn)
	for i := 0; i < itemn; i++ {
		go func() {
			defer wg.Done()
			l.Keys()
		}()
	}

	<-donec
}
```

Should we introduce a new mutex field inside `lease.Lease` or expose `lease.lessor.mu` field and guard whenever we call `Keys` on individual leas item?

**Comment by heyitsanthony** [comment]
@gyuho adding a rwmutex to `Lease` seems OK
