### ISSUE TITLE
Panic renaming snap.db on windows when starting with  initial-cluster-state existing

### ISSUE THREAD

**Issue by maximecaron** [coreos/etcd#7489]
# Setup
etcd Version: 3.1.2"
etcdmain: Git SHA: 714e7ec
etcdmain: Go Version: go1.7.5"
etcdmain: Go OS/Arch: windows/amd64"

# Bug detail

After starting ETCD with the following parameter, the ETCD process crash shortly after on trying to rename a snap.db file.

etcd.exe --name BN2SCH030331562 --initial-advertise-peer-urls http://BN2SCH030331562:2380 --listen-peer-urls http://BN2SCH030331562:2380 --listen-client-urls http://127.0.0.1:2379,http://BN2SCH030331562:2379 --advertise-client-urls http://BN2SCH030331562:2379 --initial-cluster-token epoch_636247512080469477 --initial-cluster BN2SCH030331562=http://BN2SCH030331562:2380,BN2SCH030331564=http://BN2SCH030331564:2380,BN2SCH030341530=http://BN2SCH030341530:2380 --initial-cluster-state existing --data-dir k:\etcddata\epoch_636247512080469477 --max-snapshots 5 --max-wals 5 --auto-compaction-retention 1 --heartbeat-interval 200 --election-timeout 1000"

2017-03-13 11:06:40.330996 I | snap: saved database snapshot to disk [total bytes: 364855296]
2017-03-13 11:06:40.330996 I | rafthttp: received and saved database snapshot [index: 14152306, from: 2a2f93bdf8960ab0] successfully"
...
2017-03-13 11:06:40.331985 I | etcdserver: applying snapshot at index 0..."
2017-03-13 11:06:40.331985 I  panic: rename snapshot file error: rename k:\etcddata\epoch_636247512080469477/member/snap/0000000000d7f272.snap.db k:\etcddata\epoch_636247512080469477/member/snap/db: Access is denied."

# Stack trace

goroutine 258 [running]:"
panic(0xccf340, 0xc043414460)"
	/usr/local/go/src/runtime/panic.go:500 +0x1af"
github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc042171380, 0xe6c016, 0x1e, 0xc043425610, 0x1, 0x1)"
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x171"
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applySnapshot(0xc0422482c0, 0xc0421fe140, 0xc043400fd0)"
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:794 +0x16c4"
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applyAll(0xc0422482c0, 0xc0421fe140, 0xc043400fd0)"
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:748 +0x77"
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func6(0x21c55e8, 0xc0421fe100)"
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:714 +0x47"
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc042200480)"
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:160 +0xe4"
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler"
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x1ef"

**Comment by heyitsanthony** [comment]
Possibly from holding the file lock on the db file while doing the rename.

**Comment by maximecaron** [comment]
Could it be because of the PurgeFile go routine (/pkg/fileutil/purge.go) still holding the lock from TryLockFile() call

**Comment by heyitsanthony** [comment]
@maximecaron no, that will only lock files with names ending in `snap` or `wal`.

**Comment by maximecaron** [comment]
on windows there is a custom rename to WAL https://github.com/coreos/etcd/blob/2724c3946eb2f3def5ed38a127be982b62c81779/wal/wal_windows.go
But something similar is needed at https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L801

**Comment by heyitsanthony** [comment]
@maximecaron that's because it's renaming a directory. This case only renames a file.

**Comment by maximecaron** [comment]
Does this mean that running Etcd on Windows is not a supported scenario ?

**Comment by gyuho** [comment]
@maximecaron etcd on Windows is considered experimental https://github.com/coreos/etcd/blob/master/Documentation/op-guide/supported-platform.md.
