### ISSUE TITLE
3.1.3 - panic:  runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by davissp14** [coreos/etcd#7554]
**Boot Options**
etcdmain: etcd Version: 3.1.3
etcdmain: Git SHA: 21fdcc6
etcdmain: Go Version: go1.7.5
etcdmain: Go OS/Arch: linux/amd64
etcdmain: setting maximum number of CPUs to 16, total number of available CPUs is 16
etcdmain: the server is already initialized as member before, starting as etcd member...
etcdserver: recovered store from snapshot at index 1889755
etcdserver: data dir = /data/etcd
etcdserver: member dir = /data/etcd/member
etcdserver: heartbeat = 500ms
etcdserver: election = 5000ms
etcdserver: snapshot count = 1000
etcdserver: advertise client URLs = http://10.29.2.2:2379
etcdserver: restarting member b4209ca7294e5168 in cluster b62a0c975a8fe910 at commit index 1890456
raft: b4209ca7294e5168 became follower at term 17
raft: newRaft b4209ca7294e5168 [peers: [1178374633b90656,39d29160b3d5fd78,b4209ca7294e5168], term: 17, commit: 1890456, applied: 1889755, lastindex: 1890457, lastterm: 17]
etcdserver/api: enabled capabilities for version 3.1

```
etcd.19  | panic: runtime error: invalid memory address or nil pointer dereference
etcd.19  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8bdca8]
etcd.19  |
etcd.19  | goroutine 376 [running]:
etcd.19  | panic(0xd159e0, 0xc42000a0e0)
etcd.19  |        /usr/local/go/src/runtime/panic.go:500 +0x1a1
etcd.19  | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/auth.(*authStore).IsAdminPermitted(0xc42d621810, 0x0, 0x0, 0x0)
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/auth/store.go:772 +0xc8
etcd.19  | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*authMaintenanceServer).isAuthenticated(0xc42e010b60, 0x7f6cebe2c800, 0xc42c4a86f0, 0x12e0ec0, 0xc42041c9c0)
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/maintenance.go:160 +0xae
etcd.19  | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*authMaintenanceServer).Status(0xc42e010b60, 0x7f6cebe2c800, 0xc42c4a86f0, 0x132c528, 0x5, 0xe589d5, 0x18)
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/maintenance.go:188 +0x43
etcd.19  | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb._Maintenance_Status_Handler.func1(0x7f6cebe2c800, 0xc42c4a86f0, 0xd9f520, 0x132c528, 0xc42cfd8640, 0xc42041ca38, 0x9bc0a6, 0xc42c4a86f0)
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3025 +0xa2
etcd.19  | github.com/coreos/etcd/cmd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.UnaryServerInterceptor(0x7f6cebe2c800, 0xc42c4a86f0, 0xd9f520, 0x132c528, 0xc429c49da0, 0xc429c49dc0, 0x40f9e8, 0x20, 0xd47a00, 0x1)
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go:29 +0xa4
etcd.19  | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1(0x7f6cebe2c800, 0xc42c4a86f0, 0xd9f520, 0x132c528, 0xc429c49da0, 0xc429c49dc0, 0xde92c0, 0x40daac, 0xc420138478, 0xc42041cb28)
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:57 +0xc3
etcd.19  | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb._Maintenance_Status_Handler(0xd6a8a0, 0xc42e010b60, 0x7f6cebe2c800, 0xc42c4a86f0, 0xc42cfd85f0, 0xc4205346e0, 0x0, 0x0, 0x2, 0xc42df377a0)
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3027 +0x166
etcd.19  | github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc42015c000, 0x12e3500, 0xc4201e06c0, 0xc4201493b0, 0xc42020d5c0, 0x1301378, 0x0, 0x0, 0x0)
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:638 +0xc14
etcd.19  | github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42015c000, 0x12e3500, 0xc4201e06c0, 0xc4201493b0, 0x0)
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:796 +0x6b0
etcd.19  | github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc423d457c0, 0xc42015c000, 0x12e3500, 0xc4201e06c0, 0xc4201493b0)
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:449 +0xab
etcd.19  | created by github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
etcd.19  |        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:450 +0xa3
```

**Comment by xiang90** [comment]
@heyitsanthony I remember this is fixed at some point?
