### ISSUE TITLE
etcdctl crash with panic on getting role

### ISSUE THREAD

**Issue by idonin** [coreos/etcd#7691]
with --write-output=fields
```
root@example:~# etcdctl --insecure-transport=false --insecure-skip-tls-verify=true --user=root:$ROOT_PASSWORD  role get some_role -w fields
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x508294]

goroutine 1 [running]:
panic(0xbf91e0, 0xc42000e0b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.(*fieldsPrinter).hdr(0xc42020df90, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/printer_fields.go:37 +0xc4
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.(*fieldsPrinter).RoleGet(0xc42020df90, 0x7ffd945dc933, 0xb, 0x0, 0xc4201f40b8, 0x1, 0x1)
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/printer_fields.go:150 +0x35
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.roleGetCommandFunc(0xc420254c00, 0xc420093ec0, 0x1, 0x6)
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/role_command.go:138 +0x13c
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).execute(0xc420254c00, 0xc420093c20, 0x6, 0x6, 0xc420254c00, 0xc420093c20)
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:572 +0x411
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x113d040, 0xd071fe, 0xb, 0xc420237e78)
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:662 +0x412
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).Execute(0x113d040, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:618 +0x2b
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3.Start()
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/ctl.go:96 +0x8e
main.main()
	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcdctl/main.go:40 +0x1fb
root@example:~# etcdctl version
etcdctl version: 3.1.5
API version: 3.1
```

**Comment by idonin** [comment]
Also, ```-w json``` gives strange hash instead of human-readable text. This is feature of bug?

**Comment by heyitsanthony** [comment]
@idonin `-w json` will base64 encode for fields that are binary strings (e.g., key, range_end, value), so that's expected behavior. etcdctl shouldn't be crashing, though...

**Comment by heyitsanthony** [comment]
ugh, tests aren't covering `RoleGet` either: https://codecov.io/gh/coreos/etcd/src/39e32e953e9b8774f96bd4cc03eeb42c0849fc7d/etcdserver/api/v3rpc/auth.go#L71

**Comment by mitake** [comment]
@idonin @heyitsanthony sorry for the problem and missing this issue, I'll fix it soon.
