### ISSUE TITLE
TestAuthInfoFromCtx: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#7887]
My Mac machine fails on this test (master branch).

Just `go test -v -run TestAuthInfoFromCtx` in `auth` package.

```
=== RUN   TestAuthInfoFromCtx
2017-05-05 09:10:46.369645 W | auth: simple token is not cryptographically signed
2017-05-05 09:10:46.371440 N | auth: added a new user: root
2017-05-05 09:10:46.371463 N | auth: Role root is created
2017-05-05 09:10:46.371486 N | auth: granted role root to user root
2017-05-05 09:10:46.371498 N | auth: Authentication enabled
2017-05-05 09:10:46.371857 N | auth: Role role-test is created
2017-05-05 09:10:46.373317 N | auth: added a new user: foo
--- FAIL: TestAuthInfoFromCtx (0.02s)
	store_test.go:471: expected auth: invalid auth token, got <nil>
	store_test.go:477: expected auth: invalid auth token, got <nil>
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x149b5a8]

goroutine 71 [running]:
testing.tRunner.func1(0xc42013b520)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x151fa60, 0x185a650)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/coreos/etcd/auth.TestAuthInfoFromCtx(0xc42013b520)
	/Users/gyuho/go/src/github.com/coreos/etcd/auth/store_test.go:485 +0xc78
testing.tRunner(0xc42013b520, 0x15de128)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/coreos/etcd/auth	0.292s
```

```
go version
go version go1.8.1 darwin/amd64
```

**Comment by gyuho** [comment]
Confirmed that this only happens in MacOS.

**Comment by gyuho** [comment]
Nvm, my grpc-go local branch was somehow even with its master branch (git sha [844f573616520565fdc6fb4db242321b5456fd6d](https://github.com/grpc/grpc-go/pull/1221/commits)). Breaks from https://github.com/grpc/grpc-go/commit/0c1d39df28cc4e0369b185df2b33b1094cd543fb.
