### ISSUE TITLE
TestRestartRemoved: failed to remove member in time

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#7921]
via https://semaphoreci.com/coreos/etcd/branches/master/builds/1920

```
--- FAIL: TestRestartRemoved (33.98s)
        cluster.go:315: failed to remove member 4068fe73a08ddfc8 in time
```

Potentially relevant snippet (30s jump):
```
2017-05-12 16:41:19.132189 W | etcdserver: reject message from removed member 4068fe73a08ddfc8
2017-05-12 16:41:19.132210 W | rafthttp: failed to process raft message (cannot process message from removed member)
2017-05-12 16:41:19.132284 I | 16:41:19.132278 server.go:2753: http: panic serving @: cannot process message from removed member
goroutine 283897 [running]:
net/http.(*conn).serve.func1(0x1c5e9d40)
        /usr/local/golang/1.8/go/src/net/http/server.go:1721 +0x9f
panic(0x8854960, 0x2181b320)
        /usr/local/golang/1.8/go/src/runtime/panic.go:489 +0x22a
github.com/coreos/etcd/rafthttp.(*pipelineHandler).ServeHTTP(0x1abf9660, 0x8d160c0, 0x1910eab0, 0x19839500)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/rafthttp/http.go:130 +0x764
net/http.(*ServeMux).ServeHTTP(0x1abf96a0, 0x8d160c0, 0x1910eab0, 0x19839500)
        /usr/local/golang/1.8/go/src/net/http/server.go:2238 +0xf0
net/http.(*ServeMux).ServeHTTP(0x1abf9720, 0x8d160c0, 0x1910eab0, 0x19839500)
        /usr/local/golang/1.8/go/src/net/http/server.go:2238 +0xf0
github.com/coreos/etcd/pkg/testutil.(*PauseableHandler).ServeHTTP(0x1abf9760, 0x8d160c0, 0x1910eab0, 0x19839500)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/testutil/pauseable_handler.go:33 +0x78
net/http.serverHandler.ServeHTTP(0x19122380, 0x8d160c0, 0x1910eab0, 0x19839500)
        /usr/local/golang/1.8/go/src/net/http/server.go:2568 +0x70
net/http.(*conn).serve(0x1c5e9d40, 0x8d16e00, 0x21398900)
        /usr/local/golang/1.8/go/src/net/http/server.go:1825 +0x578
created by net/http.(*Server).Serve
        /usr/local/golang/1.8/go/src/net/http/server.go:2668 +0x225
2017-05-12 16:41:19.142329 W | etcdserver: reject message from removed member 4068fe73a08ddfc8
2017-05-12 16:41:19.142346 W | rafthttp: failed to process raft message (cannot process message from removed member)
2017-05-12 16:41:19.142419 I | 16:41:19.142414 server.go:2753: http: panic serving @: cannot process message from removed member
goroutine 283903 [running]:
net/http.(*conn).serve.func1(0x1c5e9f20)
        /usr/local/golang/1.8/go/src/net/http/server.go:1721 +0x9f
panic(0x8854960, 0x2181b650)
        /usr/local/golang/1.8/go/src/runtime/panic.go:489 +0x22a
github.com/coreos/etcd/rafthttp.(*pipelineHandler).ServeHTTP(0x1abf9660, 0x8d160c0, 0x1910eb40, 0x19839900)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/rafthttp/http.go:130 +0x764
net/http.(*ServeMux).ServeHTTP(0x1abf96a0, 0x8d160c0, 0x1910eb40, 0x19839900)
        /usr/local/golang/1.8/go/src/net/http/server.go:2238 +0xf0
net/http.(*ServeMux).ServeHTTP(0x1abf9720, 0x8d160c0, 0x1910eb40, 0x19839900)
        /usr/local/golang/1.8/go/src/net/http/server.go:2238 +0xf0
github.com/coreos/etcd/pkg/testutil.(*PauseableHandler).ServeHTTP(0x1abf9760, 0x8d160c0, 0x1910eb40, 0x19839900)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/testutil/pauseable_handler.go:33 +0x78
net/http.serverHandler.ServeHTTP(0x19122380, 0x8d160c0, 0x1910eb40, 0x19839900)
        /usr/local/golang/1.8/go/src/net/http/server.go:2568 +0x70
net/http.(*conn).serve(0x1c5e9f20, 0x8d16e00, 0x213994a0)
        /usr/local/golang/1.8/go/src/net/http/server.go:1825 +0x578
created by net/http.(*Server).Serve
        /usr/local/golang/1.8/go/src/net/http/server.go:2668 +0x225
2017-05-12 16:41:19.152216 W | etcdserver: reject message from removed member 4068fe73a08ddfc8
2017-05-12 16:41:19.152233 W | rafthttp: failed to process raft message (cannot process message from removed member)
2017-05-12 16:41:19.152307 I | 16:41:19.152302 server.go:2753: http: panic serving @: cannot process message from removed member
goroutine 283907 [running]:
net/http.(*conn).serve.func1(0x1d1a6300)
        /usr/local/golang/1.8/go/src/net/http/server.go:1721 +0x9f
panic(0x8854960, 0x2181b980)
        /usr/local/golang/1.8/go/src/runtime/panic.go:489 +0x22a
github.com/coreos/etcd/rafthttp.(*pipelineHandler).ServeHTTP(0x1abf9660, 0x8d160c0, 0x1910ebd0, 0x1d218680)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/rafthttp/http.go:130 +0x764
net/http.(*ServeMux).ServeHTTP(0x1abf96a0, 0x8d160c0, 0x1910ebd0, 0x1d218680)
        /usr/local/golang/1.8/go/src/net/http/server.go:2238 +0xf0
net/http.(*ServeMux).ServeHTTP(0x1abf9720, 0x8d160c0, 0x1910ebd0, 0x1d218680)
        /usr/local/golang/1.8/go/src/net/http/server.go:2238 +0xf0
github.com/coreos/etcd/pkg/testutil.(*PauseableHandler).ServeHTTP(0x1abf9760, 0x8d160c0, 0x1910ebd0, 0x1d218680)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/testutil/pauseable_handler.go:33 +0x78
net/http.serverHandler.ServeHTTP(0x19122380, 0x8d160c0, 0x1910ebd0, 0x1d218680)
        /usr/local/golang/1.8/go/src/net/http/server.go:2568 +0x70
net/http.(*conn).serve(0x1d1a6300, 0x8d16e00, 0x1cdc8560)
        /usr/local/golang/1.8/go/src/net/http/server.go:1825 +0x578
created by net/http.(*Server).Serve
        /usr/local/golang/1.8/go/src/net/http/server.go:2668 +0x225
2017-05-12 16:41:19.162250 W | etcdserver: reject message from removed member 4068fe73a08ddfc8
2017-05-12 16:41:19.162264 W | rafthttp: failed to process raft message (cannot process message from removed member)
2017-05-12 16:41:19.162327 I | 16:41:19.162323 server.go:2753: http: panic serving @: cannot process message from removed member
goroutine 283912 [running]:
net/http.(*conn).serve.func1(0x1d1a64e0)
        /usr/local/golang/1.8/go/src/net/http/server.go:1721 +0x9f
panic(0x8854960, 0x20982810)
        /usr/local/golang/1.8/go/src/runtime/panic.go:489 +0x22a
github.com/coreos/etcd/rafthttp.(*pipelineHandler).ServeHTTP(0x1abf9660, 0x8d160c0, 0x19012240, 0x1d218a80)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/rafthttp/http.go:130 +0x764
net/http.(*ServeMux).ServeHTTP(0x1abf96a0, 0x8d160c0, 0x19012240, 0x1d218a80)
        /usr/local/golang/1.8/go/src/net/http/server.go:2238 +0xf0
net/http.(*ServeMux).ServeHTTP(0x1abf9720, 0x8d160c0, 0x19012240, 0x1d218a80)
        /usr/local/golang/1.8/go/src/net/http/server.go:2238 +0xf0
github.com/coreos/etcd/pkg/testutil.(*PauseableHandler).ServeHTTP(0x1abf9760, 0x8d160c0, 0x19012240, 0x1d218a80)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/testutil/pauseable_handler.go:33 +0x78
net/http.serverHandler.ServeHTTP(0x19122380, 0x8d160c0, 0x19012240, 0x1d218a80)
        /usr/local/golang/1.8/go/src/net/http/server.go:2568 +0x70
net/http.(*conn).serve(0x1d1a64e0, 0x8d16e00, 0x1cdc88c0)
        /usr/local/golang/1.8/go/src/net/http/server.go:1825 +0x578
created by net/http.(*Server).Serve
        /usr/local/golang/1.8/go/src/net/http/server.go:2668 +0x225
2017-05-12 16:41:19.172365 W | etcdserver: reject message from removed member 4068fe73a08ddfc8
2017-05-12 16:41:19.172382 W | rafthttp: failed to process raft message (cannot process message from removed member)
2017-05-12 16:41:19.172472 I | 16:41:19.172466 server.go:2753: http: panic serving @: cannot process message from removed member
goroutine 283930 [running]:
net/http.(*conn).serve.func1(0x1dddc300)
        /usr/local/golang/1.8/go/src/net/http/server.go:1721 +0x9f
panic(0x8854960, 0x2181bd60)
        /usr/local/golang/1.8/go/src/runtime/panic.go:489 +0x22a
github.com/coreos/etcd/rafthttp.(*pipelineHandler).ServeHTTP(0x1abf9660, 0x8d160c0, 0x1910ec60, 0x1a5f8000)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/rafthttp/http.go:130 +0x764
net/http.(*ServeMux).ServeHTTP(0x1abf96a0, 0x8d160c0, 0x1910ec60, 0x1a5f8000)
        /usr/local/golang/1.8/go/src/net/http/server.go:2238 +0xf0
net/http.(*ServeMux).ServeHTTP(0x1abf9720, 0x8d160c0, 0x1910ec60, 0x1a5f8000)
        /usr/local/golang/1.8/go/src/net/http/server.go:2238 +0xf0
github.com/coreos/etcd/pkg/testutil.(*PauseableHandler).ServeHTTP(0x1abf9760, 0x8d160c0, 0x1910ec60, 0x1a5f8000)
        /home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/pkg/testutil/pauseable_handler.go:33 +0x78
net/http.serverHandler.ServeHTTP(0x19122380, 0x8d160c0, 0x1910ec60, 0x1a5f8000)
        /usr/local/golang/1.8/go/src/net/http/server.go:2568 +0x70
net/http.(*conn).serve(0x1dddc300, 0x8d16e00, 0x19eae700)
        /usr/local/golang/1.8/go/src/net/http/server.go:1825 +0x578
created by net/http.(*Server).Serve
        /usr/local/golang/1.8/go/src/net/http/server.go:2668 +0x225
2017-05-12 16:41:52.667067 W | rafthttp: rejected the stream from peer 4068fe73a08ddfc8 since it was removed
2017-05-12 16:41:52.667135 W | rafthttp: rejected the stream from peer 4068fe73a08ddfc8 since it was removed
2017-05-12 16:41:52.667166 W | etcdserver: reject message from removed member 4068fe73a08ddfc8
2017-05-12 16:41:52.667176 W | rafthttp: failed to process raft message (cannot process message from removed member)
2017-05-12 16:41:52.667256 I | 16:41:52.667251 server.go:2753: http: panic serving @: cannot process message from removed member
```

**Comment by gyuho** [comment]
Will reopen when it happens again.
