### ISSUE TITLE
[report_bugs] benchmark tool test for watch can cause a panic

### ISSUE THREAD

**Issue by arthurkiller** [coreos/etcd#8171]
Benchmark tool for etcd watch benchmark can be panic

based on release 3.2

```
panic: send on closed channel

goroutine 16843 [running]:
github.com/coreos/etcd/tools/benchmark/cmd.recvWatchChan(0xc420ab5320, 0xc42006de60)
        /Users/arthur/golang/src/github.com/coreos/etcd/tools/benchmark/cmd/watch.go:201 +0x1bc
created by github.com/coreos/etcd/tools/benchmark/cmd.doWatch
        /Users/arthur/golang/src/github.com/coreos/etcd/tools/benchmark/cmd/watch.go:189 +0x234
```

Cause the result channel was closed before any watcher goroutine done.
I have fixed this with a PR and tested for it.

**Comment by arthurkiller** [comment]
@xiang90

**Comment by arthurkiller** [comment]
the test command
```
./benchmark watch --total 1000
```

my go version
```
go version go1.8.3 darwin/amd64
```

**Comment by heyitsanthony** [comment]
@arthurkiller this is fixed in master but wasn't backported to 3.2, but it can be backported into 3.2.2 /cc @gyuho

**Comment by xiang90** [comment]
closing

**Comment by gyuho** [comment]
https://github.com/coreos/etcd/pull/8069 is backported to release-3.2 branch.
