### ISSUE TITLE
etcd backup function is not complete

### ISSUE THREAD

**Issue by yfoelling** [coreos/etcd#8195]
Hey, 

i tested the desaster recovery of the ETCD Cluster in our environment.
I used the `etcdctl backup` functionality, after trying to recover from that backup i got the following error:
```
/ # etcd --data-dir=/tmp --force-new-cluster
2017-06-29 13:54:23.064483 I | etcdmain: etcd Version: 3.0.4
2017-06-29 13:54:23.064559 I | etcdmain: Git SHA: d53923c
2017-06-29 13:54:23.064566 I | etcdmain: Go Version: go1.6.3
2017-06-29 13:54:23.064573 I | etcdmain: Go OS/Arch: linux/amd64
2017-06-29 13:54:23.064579 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2017-06-29 13:54:23.065415 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2017-06-29 13:54:23.066876 I | etcdmain: listening for peers on http://localhost:2380
2017-06-29 13:54:23.066960 I | etcdmain: listening for client requests on localhost:2379
2017-06-29 13:54:25.969977 I | etcdserver: recovered store from snapshot at index 187022420
2017-06-29 13:54:25.970031 I | etcdserver: name = default
2017-06-29 13:54:25.970037 I | etcdserver: force new cluster
2017-06-29 13:54:25.970043 I | etcdserver: data dir = /tmp
2017-06-29 13:54:25.970051 I | etcdserver: member dir = /tmp/member
2017-06-29 13:54:25.970056 I | etcdserver: heartbeat = 100ms
2017-06-29 13:54:25.970060 I | etcdserver: election = 1000ms
2017-06-29 13:54:25.970066 I | etcdserver: snapshot count = 10000
2017-06-29 13:54:25.970078 I | etcdserver: advertise client URLs = http://localhost:2379
2017-06-29 13:54:25.993294 I | etcdserver: discarding 1 uncommitted WAL entries
2017-06-29 13:54:25.993817 I | etcdserver: forcing restart of member XXXXX in cluster XXXXXX at commit index 187023516
2017-06-29 13:54:25.993898 I | raft: XXXXXXXX became follower at term 55519
2017-06-29 13:54:25.993924 I | raft: newRaft XXXXXXX [peers: [XXXXXXXX], term: 55519, commit: 187023516, applied: 187022420, lastindex: 187023516, lastterm: 55519]
2017-06-29 13:54:25.994144 I | api: enabled capabilities for version 3.0
2017-06-29 13:54:25.994172 I | membership: added member XXXXXX [http://X.X.X.X:2380] to cluster XXXXX from store
2017-06-29 13:54:25.994182 I | membership: added member XXXXXX [http://X.X.X.X:2380] to cluster XXXXX from store
2017-06-29 13:54:25.994202 I | membership: added member XXXXXX [http://X.X.X.X:2380] to cluster XXXXX from store
2017-06-29 13:54:25.994215 I | membership: set the cluster version to 3.0 from store
2017-06-29 13:54:25.996338 I | etcdmain: stopping listening for client requests on localhost:2379
2017-06-29 13:54:25.996380 I | etcdmain: stopping listening for peers on http://localhost:2380
2017-06-29 13:54:25.996409 C | etcdmain: database file (/tmp/member/snap/db) of the backend is missing
```

When copying and adding the mentioned "DB" file manually the restore works fine.

In the documentation the db file isn´t mentioned either https://coreos.com/etcd/docs/latest/v2/admin_guide.html#disaster-recovery

Please add the db file to the backup function, or clarify this in the documentation!

ETCD Version: 3.0.4
Docker Image used for testing the recovery:  quay.io/coreos/etcd:v3.0.4

**Comment by xiang90** [comment]
try 3.2.1. The bug should already be fixed.

**Comment by wenqingxing** [comment]
CentOS Linux release 7.4.1708 (Core)
etcd Version: 3.3.10

hello,Etcd start error: snapshot file does not exist.Three nodes of the etcd cluster, all three reported the same error,No data backup.

error logs

Mar 05 11:01:05 k8s01.test systemd[1]: Starting Etcd Server...
Mar 05 11:01:05 k8s01.test etcd[902]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=https://192.168.88.101:2380
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_CLIENT_CERT_AUTH, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_KEY_FILE, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_CERT_FILE, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_INITIAL_CLUSTER_STATE, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_PEER_TRUSTED_CA_FILE, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_INITIAL_CLUSTER, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_PEER_KEY_FILE, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_INITIAL_CLUSTER_TOKEN, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_TRUSTED_CA_FILE, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_LISTEN_PEER_URLS, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_PEER_CERT_FILE, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_ADVERTISE_CLIENT_URLS, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_DATA_DIR, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_LISTEN_CLIENT_URLS, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: recognized environment variable ETCD_PEER_CLIENT_CERT_AUTH, but unused: shadowed by corresponding flag
Mar 05 11:01:05 k8s01.test etcd[902]: etcd Version: 3.3.10
Mar 05 11:01:05 k8s01.test etcd[902]: Git SHA: 27fc7e2
Mar 05 11:01:05 k8s01.test etcd[902]: Go Version: go1.10.4
Mar 05 11:01:05 k8s01.test etcd[902]: Go OS/Arch: linux/amd64
Mar 05 11:01:05 k8s01.test etcd[902]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Mar 05 11:01:05 k8s01.test etcd[902]: the server is already initialized as member before, starting as etcd member...
Mar 05 11:01:05 k8s01.test etcd[902]: peerTLS: cert = /k8s/etcd/ssl/server.pem, key = /k8s/etcd/ssl/server-key.pem, ca = , trusted-ca = /k8s/etcd/ssl/ca.pem, client-cert-auth = true, crl-fi
Mar 05 11:01:05 k8s01.test etcd[902]: listening for peers on https://192.168.88.101:2380
Mar 05 11:01:05 k8s01.test etcd[902]: listening for client requests on 192.168.88.101:2379
Mar 05 11:01:05 k8s01.test etcd[902]: recovered store from snapshot at index 400004
Mar 05 11:01:05 k8s01.test etcd[902]: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
Mar 05 11:01:05 k8s01.test bash[902]: panic: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
Mar 05 11:01:05 k8s01.test bash[902]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 05 11:01:05 k8s01.test bash[902]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb8cb90]
Mar 05 11:01:05 k8s01.test bash[902]: goroutine 1 [running]:
Mar 05 11:01:05 k8s01.test bash[902]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer.func1(0xc4201dfca0, 0xc4201df758)
Mar 05 11:01:05 k8s01.test bash[902]: /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:291 +0x40
Mar 05 11:01:05 k8s01.test bash[902]: panic(0xde0ce0, 0xc420237a40)
Mar 05 11:01:05 k8s01.test bash[902]: /usr/local/go/src/runtime/panic.go:502 +0x229
Mar 05 11:01:05 k8s01.test bash[902]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc4201b29c0, 0xfe8789, 0x2a, 0xc4201df7f8, 0x1, 0x1)
Mar 05 11:01:05 k8s01.test bash[902]: /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x162
Mar 05 11:01:05 k8s01.test bash[902]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0x7ffc28794999, 0x6, 0x0, 0x0, 0x0, 0x0, 0xc420111400, 0x1, 0x1, 0xc42011
Mar 05 11:01:05 k8s01.test bash[902]: /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:386 +0x26bb
Mar 05 11:01:05 k8s01.test bash[902]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc42021e000, 0xc42021e480, 0x0, 0x0)
Mar 05 11:01:05 k8s01.test bash[902]: /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:179 +0x811
Mar 05 11:01:05 k8s01.test bash[902]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc42021e000, 0xfc62b7, 0x6, 0xc4201e0d01, 0x2)
Mar 05 11:01:05 k8s01.test bash[902]: /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:181 +0x40
...skipping...

What should I do?

**Comment by kaliExist** [comment]
i meet this question too.........any solution??
