### ISSUE TITLE
How to run etcd inside a docker image 

### ISSUE THREAD

**Issue by bhaveshj21** [coreos/etcd#8647]
I wanted to run the etcd inside a docker image, I am able to create the docker image.
I have referenced these https://github.com/coreos/etcd/blob/master/Dockerfile
https://github.com/coreos/etcd/blob/master/scripts/build-docker

for creating the image, but when I run the image I get "docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"etcd\": executable file not found in $PATH"." 
I also tried specifying  "ENTRYPOINT command etcd" in the docker image and I get "etcd not found"
error.  
How can I run it inside the docker image ?

**Comment by gyuho** [comment]
Please see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md.
And https://github.com/coreos/etcd/releases -- you don't need to build docker image, instead download from our release images.

**Comment by bhaveshj21** [comment]
my use case is ti build a docker image for etcd and deploy it to the server and access it from there can this be achieved via this ?

**Comment by gyuho** [comment]
@bhaveshj21 If you need to build Docker image yourself, try `make docker-release-master-build` https://github.com/coreos/etcd/blob/master/Makefile#L71. But why you need to build manually, when you can just docker pull released images?

**Comment by bhaveshj21** [comment]
@gyuho sorry if I sound stupid , I am very new to this. But just to clarify 
docker pull released images means I have to pull images from the docker hub ?
do I need any login credentials for it ?
and also I can deploy this image to aws right ?

**Comment by fanminshi** [comment]
`docker pull released images means I have to pull images from the docker hub ?`
not necessarily. you can pull image from other registry as well such as gcr.

`do I need any login credentials for it ?`
not, it is public

`and also I can deploy this image to aws right ?`
if you have docker, then u can run it. it is not specific to cloud provider.

**Comment by bhaveshj21** [comment]
@fanminshi thanks , how can I pull etcd docker image, the above links provide information to run the docker image , how to pull it to my local ?

**Comment by fanminshi** [comment]
```sh
docker run \
  -p 2379:2379 \
  -p 2380:2380 \
  --name etcd-v3.2.8 \
  --volume=/tmp/etcd-data.tmp:/etcd-data \
  gcr.io/etcd-development/etcd:v3.2.8 \
  /usr/local/bin/etcd \
  --name s1 \
  --data-dir /etcd-data \
  --listen-client-urls http://0.0.0.0:2379 \
  --advertise-client-urls http://0.0.0.0:2379 \
  --listen-peer-urls http://0.0.0.0:2380 \
  --initial-advertise-peer-urls http://0.0.0.0:2380 \
  --initial-cluster s1=http://0.0.0.0:2380 \
  --initial-cluster-token tkn \
```
docker run automatically pulls the image. so you don't have to pull it yourself.

**Comment by bhaveshj21** [comment]
thanks @fanminshi  I ran this command and I am able to get the docker image, but I am seeing some issues, when I am connecting to etcd through my api, I ran the docker image but I am getting this error when I try to connect through my api 

Error: connect ECONNREFUSED 127.0.0.1:2379
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)  

I ran the following command to get my docker image 

docker run \
  -p 2379:2379 \
  -p 2380:2380 \
  --name etcd-v3.2.8 \
  --volume=/tmp/etcd-data.tmp:/etcd-data \
  gcr.io/etcd-development/etcd:v3.2.8 \
  /usr/local/bin/etcd \
  --name s1 \
  --data-dir /etcd-data \
  --listen-client-urls http://127.0.0.1:2379 \
  --advertise-client-urls http://127.0.0.1:2379 \
  --listen-peer-urls http://127.0.0.1:2380 \
  --initial-advertise-peer-urls http://127.0.0.1:2380 \
  --initial-cluster s1=http://127.0.0.1:2380 \
  --initial-cluster-token tkn \

and these are the logs after running the docker image 

2017-10-06 04:28:27.570492 I | etcdmain: etcd Version: 3.2.8
2017-10-06 04:28:27.570560 I | etcdmain: Git SHA: e211fb6
2017-10-06 04:28:27.570568 I | etcdmain: Go Version: go1.8.3
2017-10-06 04:28:27.570580 I | etcdmain: Go OS/Arch: linux/amd64
2017-10-06 04:28:27.570598 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2017-10-06 04:28:27.570609 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2017-10-06 04:28:27.571086 I | embed: listening for peers on http://localhost:2380
2017-10-06 04:28:27.571281 I | embed: listening for client requests on localhost:2379
2017-10-06 04:28:27.613991 I | etcdserver: name = default
2017-10-06 04:28:27.614036 I | etcdserver: data dir = default.etcd
2017-10-06 04:28:27.614047 I | etcdserver: member dir = default.etcd/member
2017-10-06 04:28:27.614053 I | etcdserver: heartbeat = 100ms
2017-10-06 04:28:27.614058 I | etcdserver: election = 1000ms
2017-10-06 04:28:27.614062 I | etcdserver: snapshot count = 100000
2017-10-06 04:28:27.614076 I | etcdserver: advertise client URLs = http://localhost:2379
2017-10-06 04:28:27.614139 I | etcdserver: initial advertise peer URLs = http://localhost:2380
2017-10-06 04:28:27.614175 I | etcdserver: initial cluster = default=http://localhost:2380
2017-10-06 04:28:27.684159 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
2017-10-06 04:28:27.684230 I | raft: 8e9e05c52164694d became follower at term 0
2017-10-06 04:28:27.684247 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017-10-06 04:28:27.684282 I | raft: 8e9e05c52164694d became follower at term 1
2017-10-06 04:28:27.764147 W | auth: simple token is not cryptographically signed
2017-10-06 04:28:27.814022 I | etcdserver: starting server... [version: 3.2.8, cluster version: to_be_decided]
2017-10-06 04:28:27.814756 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2017-10-06 04:28:28.489531 I | raft: 8e9e05c52164694d is starting a new election at term 1
2017-10-06 04:28:28.489603 I | raft: 8e9e05c52164694d became candidate at term 2
2017-10-06 04:28:28.489730 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
2017-10-06 04:28:28.489779 I | raft: 8e9e05c52164694d became leader at term 2
2017-10-06 04:28:28.489794 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
2017-10-06 04:28:28.490992 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
2017-10-06 04:28:28.491216 I | embed: ready to serve client requests
2017-10-06 04:28:28.491552 I | etcdserver: setting up the initial cluster version to 3.2
2017-10-06 04:28:28.491750 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
2017-10-06 04:28:28.502117 N | etcdserver/membership: set the initial cluster version to 3.2
2017-10-06 04:28:28.502573 I | etcdserver/api: enabled capabilities for version 3.2

I am able to connect to etcd if I run it directly without docker.
