### ISSUE TITLE
clientv3/ordering TestUnresolvableOrderViolation fails (after 'unhealthy' patch)

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#8694]
Creating a new issue since it was only partially fixed via https://github.com/coreos/etcd/pull/8674.

Originally https://github.com/coreos/etcd/issues/8624.
Still failing https://semaphoreci.com/coreos/etcd/branches/master/builds/2450.
Health balancer is broken.

```
goroutine 1968 [select, 2 minutes]:
github.com/coreos/etcd/clientv3.(*Client).newRetryWrapper.func1(0x182da40, 0xc420078058, 0xc4226a0c00, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/retry.go:54 +0x21d
github.com/coreos/etcd/clientv3.(*retryWriteKVClient).Put(0xc4230ffd40, 0x182da40, 0xc420078058, 0xc4226a0b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/retry.go:144 +0x208
github.com/coreos/etcd/clientv3.(*retryKVClient).Put(0xc424bc6330, 0x182da40, 0xc420078058, 0xc4226a0b80, 0x0, 0x0, 0x0, 0x12be958, 0xc422f1917c, 0xc422f1917c)
	<autogenerated>:1 +0xa9
github.com/coreos/etcd/clientv3.(*retryWriteKVClient).Put.func1(0x182da40, 0xc420078058, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/retry.go:145 +0xe9
github.com/coreos/etcd/clientv3.(*Client).newAuthRetryWrapper.func1(0x182da40, 0xc420078058, 0xc4226a0bc0, 0x40, 0xc4207ff638)
	/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/retry.go:93 +0xc4
github.com/coreos/etcd/clientv3.(*retryWriteKVClient).Put(0xc4230ffd60, 0x182da40, 0xc420078058, 0xc4226a0b80, 0x0, 0x0, 0x0, 0xc4207ff668, 0x439338, 0x40)
	/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/retry.go:144 +0x208
github.com/coreos/etcd/clientv3.(*retryKVClient).Put(0xc424bc6350, 0x182da40, 0xc420078058, 0xc4226a0b80, 0x0, 0x0, 0x0, 0x1b, 0x4656b4, 0x4159b0)
	<autogenerated>:1 +0xa9
github.com/coreos/etcd/clientv3.(*kv).do(0xc424bc6360, 0x182da40, 0xc420078058, 0x2, 0xc42053da60, 0x3, 0x8, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/kv.go:163 +0x20d
github.com/coreos/etcd/clientv3.(*kv).Do(0xc424bc6360, 0x182da40, 0xc420078058, 0x2, 0xc42053da60, 0x3, 0x8, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/kv.go:136 +0x9b
github.com/coreos/etcd/clientv3.(*kv).Put(0xc424bc6360, 0x182da40, 0xc420078058, 0x1284939, 0x3, 0x1284903, 0x3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/kv.go:105 +0x127
github.com/coreos/etcd/clientv3/ordering.TestUnresolvableOrderViolation(0xc4201900f0)
	/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/ordering/util_test.go:105 +0xa27
testing.tRunner(0xc4201900f0, 0x12bb850)
	/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x569

...

	/go/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/clientconn.go:808 +0xa7f
FAIL	github.com/coreos/etcd/clientv3/ordering	180.236s
```

Now at least we know, later PRs on balancer aren't directly breaking these...

**Comment by xiang90** [comment]
this is fixed by https://github.com/coreos/etcd/pull/8742
