### ISSUE TITLE
test: TestV3KVInflightRangeRequests with -tags cluster_proxy

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#8761]
https://jenkins-etcd.prod.coreos.systems/job/etcd-proxy/3171/console

```
=== RUN   TestV3KVInflightRangeRequests
WARNING: 2017/10/25 21:47:13 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:29696456701519652550: connect: no such file or directory"; Reconnecting to {localhost:29696456701519652550 <nil>}
WARNING: 2017/10/25 21:47:13 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:29696456701519652550: connect: no such file or directory"; Reconnecting to {localhost:29696456701519652550 <nil>}
INFO: 2017/10/25 21:47:13 get error from resetTransport context canceled, transportMonitor returning
WARNING: 2017/10/25 21:47:13 grpc: addrConn.transportMonitor exits due to: context canceled
WARNING: 2017/10/25 21:47:13 grpc: addrConn.transportMonitor exits due to: context canceled
WARNING: 2017/10/25 21:47:13 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:29696456701519652550: connect: no such file or directory"; Reconnecting to {localhost:29696456701519652550 <nil>}
WARNING: 2017/10/25 21:47:13 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:29696456701519652550: connect: no such file or directory"; Reconnecting to {localhost:29696456701519652550 <nil>}
WARNING: 2017/10/25 21:47:13 Failed to dial localhost:29696456701519652550: context canceled; please retry.
WARNING: 2017/10/25 21:47:13 Failed to dial localhost:29696456701519652550: context canceled; please retry.
WARNING: 2017/10/25 21:47:13 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:29696456701519652550: connect: no such file or directory"; Reconnecting to {localhost:29696456701519652550 <nil>}
WARNING: 2017/10/25 21:47:13 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:29696456701519652550: connect: no such file or directory"; Reconnecting to {localhost:29696456701519652550 <nil>}
WARNING: 2017/10/25 21:47:13 Failed to dial localhost:29696456701519652550: context canceled; please retry.
WARNING: 2017/10/25 21:47:13 Failed to dial localhost:29696456701519652550: context canceled; please retry.
WARNING: 2017/10/25 21:47:13 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:29696456701519652550: connect: no such file or directory"; Reconnecting to {localhost:29696456701519652550 <nil>}
WARNING: 2017/10/25 21:47:13 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:29696456701519652550: connect: no such file or directory"; Reconnecting to {localhost:29696456701519652550 <nil>}
WARNING: 2017/10/25 21:47:13 Failed to dial localhost:29696456701519652550: context canceled; please retry.
WARNING: 2017/10/25 21:47:13 Failed to dial localhost:29696456701519652550: context canceled; please retry.
--- FAIL: TestV3KVInflightRangeRequests (0.14s)
	v3_grpc_inflight_test.go:85: inflight request should be canceld with context canceled, got rpc error: code = Internal desc = grpc: the connection is drained
```

**Comment by gyuho** [comment]
This is from `nil` pointer reference to bbolt

`tx` was `nil`

https://github.com/coreos/bbolt/blob/60725ac8b25b78805aa8e2eaee714c62c55b1527/tx.go#L100-L102

```
panic: nil tx

goroutine 145 [running]:
github.com/coreos/bbolt.(*Tx).Bucket(0x0, 0x1a9c358, 0x3, 0x3, 0x1b23ac0)
	/home/gyuho/go/src/github.com/coreos/bbolt/tx.go:102 +0xe0
github.com/coreos/etcd/mvcc/backend.(*readTx).UnsafeRange(0xc4201339f0, 0x1a9c358, 0x3, 0x3, 0xc420015d20, 0x11, 0x12, 0x0, 0x0, 0x0, ...)
	/home/gyuho/go/src/github.com/coreos/etcd/mvcc/backend/read_tx.go:75 +0x81a
github.com/coreos/etcd/mvcc.(*storeTxnRead).rangeKeys(0xc42061fe90, 0xc420624450, 0x3, 0x8, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, ...)
	/home/gyuho/go/src/github.com/coreos/etcd/mvcc/kvstore_txn.go:140 +0x859
github.com/coreos/etcd/mvcc.(*storeTxnRead).Range(0xc42061fe90, 0xc420624450, 0x3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4a9000, ...)
	/home/gyuho/go/src/github.com/coreos/etcd/mvcc/kvstore_txn.go:45 +0xe3
github.com/coreos/etcd/mvcc.(*txnReadWrite).Range(0xc420620950, 0xc420624450, 0x3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x454300, ...)
	<autogenerated>:1 +0xeb
github.com/coreos/etcd/mvcc.(*metricsTxnWrite).Range(0xc42061fec0, 0xc420624450, 0x3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42007e100, ...)
	/home/gyuho/go/src/github.com/coreos/etcd/mvcc/metrics_txn.go:38 +0x12f
github.com/coreos/etcd/etcdserver.(*applierV3backend).Range(0xc420238280, 0x1aac8c0, 0xc42061fec0, 0xc4201f2d20, 0x0, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/etcdserver/apply.go:264 +0x31d
github.com/coreos/etcd/etcdserver.(*EtcdServer).Range.func2()
	/home/gyuho/go/src/github.com/coreos/etcd/etcdserver/v3_server.go:98 +0xa6
github.com/coreos/etcd/etcdserver.(*EtcdServer).doSerialize(0xc4200b1b00, 0x1aac440, 0xc42061f710, 0xc420197980, 0xc420053570, 0x5, 0x5bb819bddda23564)
	/home/gyuho/go/src/github.com/coreos/etcd/etcdserver/v3_server.go:530 +0x143
github.com/coreos/etcd/etcdserver.(*EtcdServer).Range(0xc4200b1b00, 0x1aac440, 0xc42061f710, 0xc4201f2d20, 0x436988, 0x1342140, 0x2c5)
	/home/gyuho/go/src/github.com/coreos/etcd/etcdserver/v3_server.go:99 +0x258
github.com/coreos/etcd/etcdserver/api/v3rpc.(*kvServer).Range(0xc420206900, 0x1aac440, 0xc42061f710, 0xc4201f2d20, 0x133d3c0, 0xc420053600, 0x1aadca0)
	/home/gyuho/go/src/github.com/coreos/etcd/etcdserver/api/v3rpc/key.go:52 +0xb2
github.com/coreos/etcd/etcdserver/api/v3rpc.(*quotaKVServer).Range(0xc420206940, 0x1aac440, 0xc42061f710, 0xc4201f2d20, 0xc420206940, 0x5, 0x14493fb)
	<autogenerated>:1 +0x7e
github.com/coreos/etcd/etcdserver/etcdserverpb._KV_Range_Handler.func1(0x1aac440, 0xc42061f710, 0x140e3e0, 0xc4201f2d20, 0xc42062e460, 0x7, 0xc4205b6f27, 0xc42061f6e0)
	/home/gyuho/go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3312 +0xa2
github.com/grpc-ecosystem/go-grpc-prometheus.UnaryServerInterceptor(0x1aac440, 0xc42061f710, 0x140e3e0, 0xc4201f2d20, 0xc420197940, 0xc420197960, 0x7, 0x7f6fba40d000, 0x0, 0x465304)
	/home/gyuho/go/src/github.com/grpc-ecosystem/go-grpc-prometheus/server.go:29 +0xfb
github.com/coreos/etcd/etcdserver/api/v3rpc.newUnaryInterceptor.func1(0x1aac440, 0xc42061f710, 0x140e3e0, 0xc4201f2d20, 0xc420197940, 0xc420197960, 0x0, 0xc420032a80, 0xc420594c40, 0x7f6fba40d000)
	/home/gyuho/go/src/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:57 +0x101
github.com/coreos/etcd/etcdserver/etcdserverpb._KV_Range_Handler(0x133d3c0, 0xc420206940, 0x1aac440, 0xc42061f710, 0xc42062e410, 0xc4201e43f0, 0x0, 0x0, 0xc42057d958, 0x4659bf)
	/home/gyuho/go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3314 +0x1ed
google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200c0000, 0x1ab09a0, 0xc4200c9680, 0xc42013da00, 0xc4203649f0, 0x1af2600, 0xc42061fb60, 0x0, 0x0)
	/home/gyuho/go/src/google.golang.org/grpc/server.go:806 +0x1096
google.golang.org/grpc.(*Server).handleStream(0xc4200c0000, 0x1ab09a0, 0xc4200c9680, 0xc42013da00, 0xc42061fb60)
	/home/gyuho/go/src/google.golang.org/grpc/server.go:1006 +0x14a7
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420078e10, 0xc4200c0000, 0x1ab09a0, 0xc4200c9680, 0xc42013da00)
	/home/gyuho/go/src/google.golang.org/grpc/server.go:552 +0xad
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/gyuho/go/src/google.golang.org/grpc/server.go:550 +0xb9
exit status 2
FAIL	github.com/coreos/etcd/integration	0.158s
```

Will investigate where those inflight requests went through when we do the graceful shutdown in etcdserver.
