### ISSUE TITLE
Panic when stopping etcd process

### ISSUE THREAD

**Issue by hectorj2f** [coreos/etcd#8916]
etcd v3.2.9

When stopping etcd, we always get the following panic error. Is there a way of gracefully stopping etcd ?

```
panic: Drain() is not implemented

goroutine 101105 [running]:
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*serverHandlerTransport).Drain(0xc4217b18c0)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/handler_server.go:374 +0x64
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*Server).GracefulStop(0xc420464620)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/server.go:1006 +0x2e6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.(*Etcd).Close.func2(0xc424b04300, 0xc4202f5cc0)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:201 +0x54
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.(*Etcd).Close
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:202 +0x20a
```

**Comment by gyuho** [comment]
Suggestion from gRPC team https://github.com/grpc/grpc-go/issues/1384#issuecomment-317124531

**Comment by gyuho** [comment]
Easy to repro: start a single node etcd cluster with TLS. Spawn a watcher. Stop etcd.
