### ISSUE TITLE
coverage: test panic at the end, on gocovmerge

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#8924]
https://jenkins-etcd-public.prod.coreos.systems/job/etcd-coverage/2991/console

```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x4d6840, 0xc42000e0d0)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
main.mergeProfileBlock.func1(0x0, 0x3)
	/home/anthony_romano/gp/src/github.com/wadey/gocovmerge/gocovmerge.go:30 +0xa3
main.mergeProfileBlock(0xc4200104c0, 0x5e, 0x27, 0x61, 0x2, 0x2, 0x1, 0x12, 0x12)
	/home/anthony_romano/gp/src/github.com/wadey/gocovmerge/gocovmerge.go:35 +0xe6
main.mergeProfiles(0xc4200104c0, 0xc420263880)
	/home/anthony_romano/gp/src/github.com/wadey/gocovmerge/gocovmerge.go:24 +0x138
main.addProfile(0xc42009c000, 0xb8, 0x100, 0xc420263880, 0xc42009c000, 0xb8, 0x100)
	/home/anthony_romano/gp/src/github.com/wadey/gocovmerge/gocovmerge.go:74 +0x310
main.main()
	/home/anthony_romano/gp/src/github.com/wadey/gocovmerge/gocovmerge.go:106 +0xf7
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x4d6840, 0xc42000e0d0)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
```

https://github.com/wadey/gocovmerge

**Comment by gyuho** [comment]
```
gocovmerge covdir/e2e.1512417469546420125.coverprofile
gocovmerge covdir/e2e.1512417469561389968.coverprofile
gocovmerge covdir/e2e.1512417469616324760.coverprofile
gocovmerge covdir/e2e.1512417469669966860.coverprofile
panic: runtime error: index out of range

goroutine 1 [running]:
main.mergeProfileBlock.func1(0x0, 0xc42032ae01)
	/go/src/github.com/wadey/gocovmerge/gocovmerge.go:30 +0x8a
main.mergeProfileBlock(0xc42004e780, 0xda, 0x20, 0xdc, 0x2, 0x1, 0x1, 0x24, 0x24)
	/go/src/github.com/wadey/gocovmerge/gocovmerge.go:35 +0xc8
main.mergeProfiles(0xc42004e780, 0xc42004f600)
	/go/src/github.com/wadey/gocovmerge/gocovmerge.go:24 +0x136
main.addProfile(0xc4203d0000, 0x4b, 0x80, 0xc42004f600, 0xc4203d0000, 0x4b, 0x80)
	/go/src/github.com/wadey/gocovmerge/gocovmerge.go:74 +0x2bc
main.main()
	/go/src/github.com/wadey/gocovmerge/gocovmerge.go:106 +0x79
gocovmerge covdir/e2e.1512417469690753018.coverprofile
gocovmerge covdir/e2e.1512417469870523089.coverprofile
gocovmerge covdir/e2e.1512417470349367693.coverprofile
gocovmerge covdir/e2e.1512417470464032343.coverprofile
gocovmerge covdir/e2e.1512417470480532759.coverprofile
gocovmerge covdir/e2e.1512417470542127692.coverprofile
```

**Comment by xiang90** [comment]
can we get fixed soon? or can we go back to a older version of gocovmerge which does not have this issue?

**Comment by gyuho** [comment]
@xiang90 Yeah, I am forking `gocovmerge` to debug this panic in a separate branch https://github.com/coreos/etcd/pull/8970.
