### ISSUE TITLE
health interface returns 503 Service Unavailable probabilistic

### ISSUE THREAD

**Issue by wangjianlin13** [coreos/etcd#9113]
# Bug reporting

I use etcd-v3.1.0-linux-amd64 as a etcd cluster witch has 4 etcd server. When call the health interface through resttemplate and curl, the etcd returns 503  Service Unavailable 3 times in about 10 hours.  Through analysis etcd log, snapshot not happened when etcd server returns 503. In addition, when etcd server returns 503, the function of reading and writing is normal. Etcd-3.2.7 has the same problem.
  The log is:
exception when check link status：url = https://127.0.0.1:11007/health
org.springframework.web.client.HttpServerErrorException: 503 Service Unavailable
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94) ~[spring-web-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700) ~[spring-web-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653) ~[spring-web-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613) ~[spring-web-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:531) ~[spring-web-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at com.huawei.csp.grmanager.scheduled.ManageLinkCheckTimer.checkLinkStatusByIp(ManageLinkCheckTimer.java:268) [cspgrmanager-service-1.2.0.B014.jar:?]
	at com.huawei.csp.grmanager.scheduled.ManageLinkCheckTimer.etcdCheckTimer(ManageLinkCheckTimer.java:132) [cspgrmanager-service-1.2.0.B014.jar:?]
	at sun.reflect.GeneratedMethodAccessor206.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by gyuho** [comment]
I think it's just transient error? Did you try retrying on that 503 error code? Was there any leader election at the moment you got 503?

**Comment by wangjianlin13** [comment]
How can I know when leader election happens? I don't find relative log in etcd log.

**Comment by wangjianlin13** [comment]
How can I know when leader election happens? I don't find relative log in etcd log.

**Comment by gyuho** [comment]
Other temporary network errors can also trigger 503. I think you should implement your own retry logic, as our clientv3 does for transient network errors.
