### ISSUE TITLE
panic in concurrency.NewSession(cli, concurrency.WithTTL(lockTTL))  without etcd running

### ISSUE THREAD

**Issue by jiaxuanzhou** [coreos/etcd#9493]
# Bug reporting
my code is ：
`func main() {

	ClientV3, _ := clientv3.New(clientv3.Config{
		Endpoints:   []string{"http://127.0.0.1:2379"},
		DialTimeout: 5 * time.Second,
	})

	GainLock(ClientV3)
}

func GainLock(cli *clientv3.Client) error {
	s, err := concurrency.NewSession(cli, concurrency.WithTTL(lockTTL))
	if err != nil {
		return err
	}
}
`
panic in clientv3, here is the logs:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x148ad17]

goroutine 1 [running]:
github.com/coreos/etcd/clientv3.(*Client).Ctx(...)
	/Users/chuhe/code/src/github.com/coreos/etcd/clientv3/client.go:116
github.com/coreos/etcd/clientv3/concurrency.NewSession(0x0, 0xc420199df8, 0x1, 0x1, 0x0, 0x0, 0xc42005c540)
	/Users/chuhe/code/src/github.com/coreos/etcd/clientv3/concurrency/session.go:39 +0x37
main.GainLock(0x0, 0x0, 0x0)
	/Users/chuhe/code/src/lock/lock.go:36 +0xd4
main.main()
	/Users/chuhe/code/src/lock/lock.go:31 +0xf0

**Comment by jiaxuanzhou** [comment]
but when set up the etcd to serve on 127.0.0.1:2379,  it runs happy!
